### ISSUE TITLE
[Bug]: 苹果浏览器下缩小左侧菜单和展开左侧菜单，导航联动效果失效

### ISSUE THREAD

**Issue by muyangsx** [flipped-aurora/gin-vue-admin#1000]
### gin-vue-admin 版本

2.4.6

### Node 版本

v14.19.0

### Golang 版本

go version go1.17.5 darwin/arm64

### 是否依旧存在

不可以

### bug描述

苹果浏览器下缩小左侧菜单和展开左侧菜单，导航联动效果失效

### 修改建议

能否将修改步骤做个介绍，代码升级不太容易，同时又想解决这个问题。期待回复，感谢～

**Comment by bypanghu** [comment]
经测试，最新版本的前端代码在我的电脑上并不会出现这样的错误，请运行最新版本的代码，再看看
