### ISSUE TITLE
[Bug]: Security Issues-20220402-luckyt0mat0

### ISSUE THREAD

**Issue by LuckyT0mat0** [flipped-aurora/gin-vue-admin#1002]
### gin-vue-admin 版本

V2.5.0b

### Node 版本

v16.3.0

### Golang 版本

go1.16.6 

### 是否依旧存在

可以

### bug描述

发现了一个任意文件读取/下载安全漏洞，wx联系~

### 修改建议

参数校验下即可。

**Comment by piexlmax** [comment]
已收到详细复现过程，将会尽快修复。
