### ISSUE TITLE
[Bug]: 新增菜单时弹出的对话框

### ISSUE THREAD

**Issue by xiaomaguoguo** [flipped-aurora/gin-vue-admin#1005]
### gin-vue-admin 版本

main

### Node 版本

v16.5.0

### Golang 版本

go 1.17.5

### 是否依旧存在

可以

### bug描述

1.登录系统后，查看菜单管理界面
2.在菜单管理界面中点击新增菜单
3.在弹出的新增菜单中选择图标那一栏里，点击打开下拉选择框时，下拉菜单里面的icon+文字不对齐，导致选择任意一个icon后显示在选项也是icon+文字不对齐

### 修改建议

希望icon+文字水平对齐并垂直居中

**Comment by bypanghu** [comment]
请看我最新的pr
