### ISSUE TITLE
无法进入登录页面

### ISSUE THREAD

**Issue by lucky-yangyi** [flipped-aurora/gin-vue-admin#1010]
### gin-vue-admin 版本

V2.5.0 beta.22022/04/06

### Node 版本

v14.16.0

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

首先进入登陆页的时候 死循环 无法跳转到登录页 审查元素也无法审查  解决办法只能清除缓存 才能进入登陆页

**Comment by piexlmax** [comment]
提供一下详细复现过程
