### ISSUE TITLE
[Bug]: 用户管理修改角色失败

### ISSUE THREAD

**Issue by ssj66** [flipped-aurora/gin-vue-admin#1011]
### gin-vue-admin 版本

main

### Node 版本

v14

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

![image](https://user-images.githubusercontent.com/84908733/161905398-8ad08f82-7b55-4eda-979c-62fcc56e36b5.png)

确定后角色新增不进去，并且角色表多出一条没有角色IID的相同角色数据

![image](https://user-images.githubusercontent.com/84908733/161905559-5299b31e-1b18-49c2-b49e-60ad5212a8df.png)

**Comment by piexlmax** [comment]
使用main版本 已修复

**Comment by bypanghu** [comment]
最新的main分支已经修复，请使用最新main分支代码
