### ISSUE TITLE
[Bug]: 代码生成错误

### ISSUE THREAD

**Issue by wuyushuai** [flipped-aurora/gin-vue-admin#1012]
### gin-vue-admin 版本

V2.5.1 beta

### Node 版本

V2.5.1 beta

### Golang 版本

1.7

### 是否依旧存在

可以

### int 类型 link会生成错误

使用int 类型生成的代码 ，在 GetTestPorxyInfoList 里边 db = db.Where("type LIKE ?","%"+info.Type+"%") 生成错误

 `func (testPorxyService *TestPorxyService) GetTestPorxyInfoList(info pkgtestReq.TestPorxySearch) (err error, list interface{}, total int64) {
	limit := info.PageSize
	offset := info.PageSize * (info.Page - 1)
	// 创建db
	db := global.GVA_DB.Model(&pkgtest.TestPorxy{})
	var testPorxys []pkgtest.TestPorxy
	// 如果有条件搜索 下方会自动创建搜索语句
	if info.Addr != "" {
		db = db.Where("addr = ?", info.Addr)
	}
	if info.Type != nil {
		db = db.Where("type LIKE ?","%"+info.Type+"%") //这里报 cannot convert "%" (untyped string constant) to *intcompiler[InvalidUntypedConversion](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#InvalidUntypedConversion)

		//db = db.Where("type LIKE ?", &info.Type)
	}
	err = db.Count(&total).Error
	if err != nil {
		return
	}
	err = db.Limit(limit).Offset(offset).Find(&testPorxys).Error
	return err, testPorxys, total
}
`

**Comment by piexlmax** [comment]
int 不能拼接字符串的

**Comment by wuyushuai** [comment]
> int 不能创作的作品

很奇怪的问题啊，本来代码生成出来就是错误的，我测试几遍都有问题，我重新拉了一份重新安装后又没有这个问题了
