### ISSUE TITLE
[Feature]: Makefile一键式打包

### ISSUE THREAD

**Issue by songzhibin97** [flipped-aurora/gin-vue-admin#1014]
### 功能描述以及必要性描述

1. local版本打包，包括前端&后端，建议打包完成后生成独立文件夹
2. linux生成版本打包，一键拖到服务直接使用

### 建议和方案

Makefile不同指令

**Comment by songzhibin97** [comment]
目前版本号需要手动更新，在打包的时候可以做到自动化

**Comment by piexlmax** [comment]
做

**Comment by SliverHorn** [comment]
@songzhibin97 windows 用户能用？？

**Comment by tscuite** [comment]
萌新运维这周完成
