### ISSUE TITLE
[Bug]: 部署到阿里云后台，登录时弹出404错误

### ISSUE THREAD

**Issue by h98458** [flipped-aurora/gin-vue-admin#1015]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16

### Golang 版本

go 1.16

### 是否依旧存在

不可以

### bug描述

地址：http://120.24.204.232:3308/#/login

接口报错

检测到接口错误Error: Request failed with status code 404

错误码 404 ：此类错误多为接口未注册（或未重启）或者请求路径（方法）与api路径（方法）不符--如果为自动化代码请检查是否存在空格

### 修改建议

初学者，不知道哪里出问题了，请大神们指教

**Comment by sytlw** [comment]
http://120.24.204.232:3308/api/base/captcha   你的API服务要么没启动，要么就是你的API地址错误，这个无法访问。

**Comment by piexlmax** [comment]
请参考官网部署文档和bilibili部署教学视频，猜测nginx未设置代理导致。

**Comment by h98458** [comment]
谢谢，确实是nginx代理设置有问题，现在登录时又发现500错误：
接口报错

检测到接口错误Error: Request failed with status code 500

错误码 500 ：此类错误内容常见于后台panic，请先查看后台日志，如果影响您正常使用可强制登出清理缓存

正在排错，初学者让大家见笑了

**Comment by piexlmax** [comment]
F:/GitHub/gin-vue-admin/server/service/system/sys_casbin.go:97 (0xdcdb96)
请看文档，部署文档，未携带静态文件导致。

**Comment by h98458** [comment]
非常感谢，传错文件夹，把source当成resoure了
