### ISSUE TITLE
[Bug]: go generate 不应该修改全局配置

### ISSUE THREAD

**Issue by jeffguorg** [flipped-aurora/gin-vue-admin#1026]
### gin-vue-admin 版本

master/954859bd5bed5e5e0d69634c0ce2800089828a3e

### Node 版本

v17.8.0

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

go generate 会修改全局 go env

### 修改建议

使用 direnv 或类似的工具

**Comment by piexlmax** [comment]
您好，感谢您提的issue，请问您那边有什么好的解决方案吗，如果可以，您可以尝试修复它。

**Comment by SliverHorn** [comment]
你不想用不执行不就好了么？这也不是bug，只能说这个使用方式和你的使用场景不匹配，自行修改自己所需要的命令即可
