### ISSUE TITLE
[Feature]: 密码加salt

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1034]
### 功能描述以及必要性描述

安全性考虑

### 建议和方案

sys_users表，password，加个salt

**Comment by pnck** [comment]
可以直接用UUID作为salt @piexlmax

**Comment by tesun** [comment]
直接更换md5就是
import  "golang.org/x/crypto/bcrypt"

// PasswordHash 密码hash
func PasswordHash(password string) (string, error) {
	bytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	return string(bytes), err
}

// PasswordVerify 密码校验
func PasswordVerify(password, hash string) bool {
	err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(password))
	return err == nil
}

**Comment by pnck** [comment]
> 直接更换md5就是 import "golang.org/x/crypto/bcrypt"
> 
> // PasswordHash 密码hash func PasswordHash(password string) (string, error) { bytes, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost) return string(bytes), err }
> 
> // PasswordVerify 密码校验 func PasswordVerify(password, hash string) bool { err := bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) return err == nil }

确实  不如直接bcrypt

**Comment by hedeqiang** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1045
