### ISSUE TITLE
[Bug]:  数据库view的问题

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1035]
### gin-vue-admin 版本

V2.5.0b

### Node 版本

v14

### Golang 版本

go 1.17

### 是否依旧存在

未测试

### bug描述

![image](https://user-images.githubusercontent.com/83160341/163547407-54895803-e9c9-4643-b8d0-f47d65e109d3.png)

![d3014745217163769f7425a053e3f17](https://user-images.githubusercontent.com/83160341/163547428-364e73ea-1616-4df6-aa35-e889397083ed.png)
这个view会导致导出sql再导入到别的mysql里时，数据库账号连接不一致，会报错。

当然这个也可能是数据库的问题。我用的是mysql 5.7。

### 修改建议

建议：避免使用视图？

**Comment by pnck** [comment]
创建视图的时候是没有显式指定 definer 的，所以你导进去之后报错应该是导出时自动加上的 `DEFINER=xxx` 定义导致的。尝试手动去掉导出sql的这个clause再试试？

**Comment by ilylx** [comment]
去掉这行肯定是没问题的。。

有没有方法不导出这一行？

**Comment by ilylx** [comment]
刚看到，有类似的问题
https://github.com/flipped-aurora/gin-vue-admin/issues/410
