### ISSUE TITLE
[Bug]: 多个详情页切换时，只会展示最后一个页面的内容

### ISSUE THREAD

**Issue by spring-jtw** [flipped-aurora/gin-vue-admin#1040]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

![cb5b179de78683d6b86a958cc087c9c](https://user-images.githubusercontent.com/34936466/163948850-59883ef0-7773-4401-a169-313f6dc4f4a8.png)
存在两个详情页面的时候  切换tab只会展示最后一个页面的内容 

### 修改建议

根据页面路由动态展示页面内容

**Comment by bypanghu** [comment]
你好，请将`router`数组中的`name`设成不同的字符串，现在是以`name`作为字段判断的，所以你只需要将`name`改变即可

**Comment by ilylx** [comment]
@bypanghu 这个name没法改吧，就是同一个页面

**Comment by Eastboat** [comment]
> @spring-jtw 可以页面onUpdated的时候重新init

我不能执行onUpdated这些钩子，切换只是单纯页面(keepAlive)展示，不请求任何数据
