### ISSUE TITLE
[Feature]: 可定制表单页面是弹窗还是打开新标签

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1043]
### 功能描述以及必要性描述

1. 现在表单添加和修改都是弹窗的形式，我想改为可以选择是弹窗或者新页面(tab)里打开编辑。
2. 同类型的页面不创建新标签，比如系统内置的字典详情页，现在是每点一个字典详情就打开一个标签。
3. 可能产生的问题：在编辑页面，url为xxx/edit?id=11，点保存，有可能需要回到列表，就是关闭当前标签。也可能会进入create页面，目前我是route.push到xxx/add，但是这时候是打开了新标签，edit页面标签还没有关闭。
4. 还有个场景是: 一个select， onchange的时候变更url参数，目前的情况也是打开很多同名标签。
5. 

### 建议和方案

rt

**Comment by ilylx** [comment]
其实能有个关闭tab的方法，也就好处理了。

现在有吗？

**Comment by ilylx** [comment]
我的表单和列表是在一个页面上，左边表单右边列表，点击列表的编辑按钮就进入edit模式同时url里的id变化，这种情况就打开新标签实在是不科学。。。

**Comment by piexlmax** [comment]
emitter.emit('closeThisPage') 即可关闭当前页
当前的打开不同参数的url开启新的标签页是为了考虑更多用户的使用习惯，且提供了closeTab配置保证离开页面时标签自动关闭。请多查阅文档和看教学视频详细了解使用方法。

**Comment by piexlmax** [comment]
你所描述的场景，均可以修改menu配置 closeTab 解决

**Comment by ilylx** [comment]
closeThisPage() 很赞，完美 ！
