### ISSUE TITLE
[Bug]: PostgreSQL初始化，报错内容指引有误

### ISSUE THREAD

**Issue by AuroraTea** [flipped-aurora/gin-vue-admin#1054]
### gin-vue-admin 版本

2.5.1Beta

### Node 版本

v16.14.0

### Golang 版本

go 1.17.6

### 是否依旧存在

可以

### bug描述

1，初始化时正确填写，但是点击初始化按钮报错“自动创建数据库失败”，而且报错很奇怪
2，无该数据库则报错 FATAL: database \"pcbhub\" does not exist (SQLSTATE 3D000))
3，有该数据库则报错 ERROR: database \"pcbhub\" already exists (SQLSTATE 42P04)

### 修改建议

实测问题应该和报错不符合（换了postgres用户就可以了），实际上是用户少了一个权限的问题才对（能确定不是Create DB权限）
报错的内容确实令人迷惑了

**Comment by pnck** [comment]
link: #910 

pg有个坑点是数据库启动往往不是默认参数，而非默认参数会影响库名用户之类的配置项……
无论开发环境有没有使用 docker compose，启动pg都推荐使用docker：

（推荐启动参数）
` docker run -d --name gva-db -ePOSTGRES_USER=<USERNAME> -ePOSTGRES_PASSWORD=<USER_PWD> -p5432:5432 postgres:14`

expose 5432以防你不知道navicat或者data grid该连什么地址。 **生产环境部署不需要暴露它**

要注意的点：

1. 如果指定 `-ePOSTGRES_DB=<DBNAME>` ，那么建库操作会失败，因为这个时候pg启动即有 `DBNMAE` 库存在，而pg `CREATE DATABASE` 语句是不支持 `IF NOT EXISTS`条件的。
2. 如果指定了 `-ePOSTGRES_USER` 则必须配合使用 `-ePOSTGRES_PASSWORD` 并且 `postgres` 用户将不再可用（实际上[根据文档](https://hub.docker.com/_/postgres)， `-ePOSTGRES_PASSWORD`  是必填变量）
3. pg会创建 _与用户同名的库_ 用来存储一些 schema.  所以**不要让库跟用户名同名**   &nbsp;  <- 猜测你遇到的是这个问题

推荐的启动参数就是只指定用户名和密码不指定初始库，让server能执行那条 `CREATE DATABASE` 以及之后的东西

其实实现 `CREATE DATABASE IF NOT EXISTS` 也是可行的，不过反馈少就一直没改

**Comment by AuroraTea** [comment]
> 
我跑到#910下也问了一嘴哈哈，因为感觉那个issue没解决就close了。
pg生产环境下也部署在docker里吗，我只有开发和测试的时候会在docker里部署数据库哎，不是有IO和状态方面的讲究吗。

3是我了，我的用户和库是同名的，后来成功我以为是因为把用户换成超级管理员了，这么说可能是因为这个操作让库和用户名不同名了~~

我看到2.5.0b的时候有这个问题，但是到2.5.1b还是有~猜到是反馈少的原因所以来加一个反馈~~

**Comment by pnck** [comment]
> @pnck 我跑到 #910 下也问了一嘴哈哈，因为感觉那个issue没解决就close了。 pg生产环境下也部署在docker里吗，我只有开发和测试的时候会在docker里部署数据库哎，不是有IO和状态方面的讲究吗。
> 
> 3是我了，我的用户和库是同名的，后来成功我以为是因为把用户换成超级管理员了，这么说可能是因为这个操作让库和用户名不同名了~~
> 
> 我看到2.5.0b的时候有这个问题，但是到2.5.1b还是有~猜到是反馈少的原因所以来加一个反馈~~

有些文章会告诉你 数据库放容器里不是个好主意，因为
1.  数据并不能随之「容器化」，你经常需要挂载外面的volume。要么使用自动创建的volume，但那样数据可能随时会丢
2.  数据需要水平扩容时容器化没有任何帮助

请注意这些建议描述的场景，基本上都是在负载量大到单服务器撑不住的时候。
如果我已经需要一个集群级的数据库服务了，那么我不应该用docker来host数据库，这是正确的，也是你看到的类似表述的核心场景。
但如果我的业务规模还是维持在需要单机集成的水平，比如你做的是个硬件产品，需要在一台机子上跑齐所有服务，那么docker提供的基础性隔离还是有用的，最起码不同服务的日志不会混在一起。


如果你不知道「是否需要」用docker来跑db服务，那么你总是可以用docker的。
否则你会知道「不应该」用它

**Comment by AuroraTea** [comment]
> > @pnck 我跑到 #910 下也问了一嘴哈哈，因为感觉那个issue没解决就close了。 pg生产环境下也部署在docker里吗，我只有开发和测试的时候会在docker里部署数据库哎，不是有IO和状态方面的讲究吗。
> > 3是我了，我的用户和库是同名的，后来成功我以为是因为把用户换成超级管理员了，这么说可能是因为这个操作让库和用户名不同名了~~
> > 我看到2.5.0b的时候有这个问题，但是到2.5.1b还是有~猜到是反馈少的原因所以来加一个反馈~~
> 
> 有些文章会告诉你 数据库放容器里不是个好主意，因为
> 
> 1. 数据并不能随之「容器化」，你经常需要挂载外面的volume。要么使用自动创建的volume，但那样数据可能随时会丢
> 2. 数据需要水平扩容时容器化没有任何帮助
> 
> 请注意这些建议描述的场景，基本上都是在负载量大到单服务器撑不住的时候。 如果我已经需要一个集群级的数据库服务了，那么我不应该用docker来host数据库，这是正确的，也是你看到的类似表述的核心场景。 但如果我的业务规模还是维持在需要单机集成的水平，比如你做的是个硬件产品，需要在一台机子上跑齐所有服务，那么docker提供的基础性隔离还是有用的，最起码不同服务的日志不会混在一起。
> 
> 如果你不知道「是否需要」用docker来跑db服务，那么你总是可以用docker的。 否则你会知道「不应该」用它

吼吼，谢谢大佬，你这番话很有参考价值
