### ISSUE TITLE
[Bug]: 用户管理->编辑用户信息后会在角色列表增加一条角色ID为空的记录

### ISSUE THREAD

**Issue by chzhewl** [flipped-aurora/gin-vue-admin#1060]
### gin-vue-admin 版本

main

### Node 版本

v14

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

用户管理->编辑某个用户确认后会在角色列表增加一条角色ID为空的记录,在线体验版也存在同样问题。

### 修改建议

无

**Comment by piexlmax** [comment]
main 无法复现此问题 体验版目前暂未更新到最新版本

**Comment by piexlmax** [comment]
#967 已在此经修复
