### ISSUE TITLE
[Feature]: 增加管理自定义配置项功能

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1063]
### 功能描述以及必要性描述

基本上每个系统都需要很多配置吧，类似自带的系统配置，可以做成内置的一项功能。

key/value的形式，添加key中文，key英文，value，备注。

当然，能自定义表单更好，就是麻烦点。

再来个全局的根据key获取value的方法。

**Comment by ilylx** [comment]
配置有变更的话来个事件触发

**Comment by piexlmax** [comment]
系统拥有配置管理功能只是体验版防止用户篡改系统数据所以屏蔽了，clone main代码本地查看即可

**Comment by ilylx** [comment]
> 系统拥有配置管理功能只是体验版防止用户篡改系统数据所以屏蔽了，clone main代码本地查看即可

你是说"系统工具-系统配置"么，这是已有的可以配置的选项。

我的意思是可以让用户自己增加其他配置项。

**Comment by SliverHorn** [comment]
> > 系统拥有配置管理功能只是体验版防止用户篡改系统数据所以屏蔽了，clone main代码本地查看即可
> 
> 你是说"系统工具-系统配置"么，这是已有的可以配置的选项。
> 
> 我的意思是可以让用户自己增加其他配置项。

不行的，go的配置文件不允许自定义

**Comment by pnck** [comment]
厄我补充一下，配置项会有很多种实现方式，也有不同的…… 「作用级别」？

打个比方，业务上的配置项往往是动态的，比如「线程/runner数量」、「文件大小限制」之类的，这些都可以放在某个「配置数据库」里，而且增删修改他们，业务系统本身是不用重启的。

但有些配置影响的是业务系统本身，比如「jvm内存限制」（当然了这里没有，只是这个例子好懂），数据库连接池大小、监听地址等等。这些配置项通常不会在界面上提供配置，就算提供了，改完之后也是要重启的，代价比较大。

gva目前已经有大量这种静态配置项了，你在系统配置中能看到一部分但不全。他们都是用viper管理的。viper这个项目本身也是配合cobra那个命令行parser开发的，用作者的话来说这个项目的初衷就是管理那些 ini、yml 这种程序启动后一直保持不变的环境配置文件，并不是用来处理动态、自定义的配置项的。所以它的使用方式也非常静态，要么绑定到一个 golang struct，要么绑定到 cobra 的某个 flag。虽然可以动态读写新值，但本意上不是那样用的。


我理解主题里说的「基本上每个系统都需要很多配置」指的其实是业务上的配置项，或者说干脆就是想要一个自带的kv数据库crud feature，跟静态配置项得区分开来。把静态配置写成动态的我不觉得会是个正确的做法。。

**Comment by ilylx** [comment]
@pnck 是的，主要是指业务上的配置项。
我加了个config表，id,key,value,note 4个字段，然后自动生成代码，基本也能满足需求，只是触发变更时间麻烦点。

**Comment by piexlmax** [comment]
业务类型配置建议用户自行根据业务开发，此feature将不进行主体适配，可纳入插件功能，欢迎pr。
