### ISSUE TITLE
[Bug]: 未知条件下发生upstream timed out

### ISSUE THREAD

**Issue by dtlalala** [flipped-aurora/gin-vue-admin#1064]
### gin-vue-admin 版本

2.5.0

### Node 版本

非开发环境，用nginx

### Golang 版本

go 1.17.8

### 是否依旧存在

未测试

### bug描述

场景：nginx部署前端，后端直接启动包文件的方式运行，运行一段时间后（这个时间不确定，有时会突然出现，不好复现），前端刷新进入不了，查看nginx日志，发现是（ upstream timed out (110: Connection timed out) while reading response header from upstream, client:xx.xx, server: xx.xx.xx.xx, request: "POST /api/menu/getMenu HTTP/1.1", upstream: "[http://1xx.xx.xx.xx:8888/menu/getMenu](https://support.qq.com/products/371961/link-jump?jump=http%3A%2F%2F1xx.xx.xx.xx%3A8888%2Fmenu%2FgetMenu)", host: "xx.xx.xx.xx:18080", referrer: "[http://xx.xx.xx.xx:18080/](https://support.qq.com/products/371961/link-jump?jump=http%3A%2F%2Fxx.xx.xx.xx%3A18080%2F)"）
但是将nginx超时时间设长仍然无效，后通过postman调用后端接口PrivateGroup中的那些接口后端日志不刷新，但调用健康检查和其他无效的接口后有日志打印。
不太清楚是否是PrivateGroup这个组里面的接口的问题，当时未去尝试调用login这些

**Comment by songzhibin97** [comment]
@tscuite

**Comment by dtlalala** [comment]
````
http {
    #include      /app/appopt/app/xxxx-doc/xxxxdoc_deploy/mrdoc_nginx.conf;
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    #client_max_body_size 50m;
    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       8080;
        server_name  xxxx;

        root /app/appopt/app/frontend/dist;            

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            #proxy_read_timeout 3600;
            #proxy_http_version 1.1;
            #proxy_set_header Connection "";
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }

        location  /api {
            proxy_set_header Host $http_host;
            proxy_set_header  X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass  http://xxxx:xxxx;
        }
    }
}
````
上面是nginx的配置，但是直接用工具请求接口也没有返回，但请求health能够看到`"ok"`，也尝试加长过proxy_read_timeout的时间，但是并没有用，每次都需要重启后端服务才能够解决。

**Comment by dtlalala** [comment]
今天又出现这个问题了，然后检查发现那些需要认证的接口加上X-token去尝试调用就会一直pending，但是不加上X-token就会拦截返回“非法登录”，/base/login这类不需要认证的公共接口都能够正常返回。请问是我JWT哪里配置出了问题嘛？
![image](https://user-images.githubusercontent.com/53786616/168591677-c14b8f12-7aef-4905-9e5f-40f2b341e8ef.png)
没有用redis，没开启单点登录。

**Comment by dtlalala** [comment]
![image](https://user-images.githubusercontent.com/53786616/169735761-76cdac5f-3ff9-46d8-bd76-cd23ca05e831.png)
![image](https://user-images.githubusercontent.com/53786616/169737619-efe55743-b8bb-4c46-9641-fb2085d9f4ca.png)
又复现了该问题，通过日志埋点定位到是casbin_rbac.go中的`e := casbinService.Casbin() success, _ := e.Enforce(sub, obj, act)`这两段代码，走到这里后面的日志都没打印

本人go语言刚刚学习，不太理解图二中红框中这两句代码的作用，上面的问题有点怀疑是 sync.once.Do 这个函数阻塞了。

**Comment by pnck** [comment]
另外once是个用于单例或实现类似C那种 local static变量效果的东西，实际上就是一个加锁的全局变量。
once.Do只会执行一次，你红框标的作用是从文件加载 casbin model。由于这文件几乎不会改，甚至可以

```go
func (casbinService *CasbinService) Casbin() *casbin.SyncedEnforcer {
	once.Do(func() {
		m := model.NewModel()
		m.AddDef("r", "r", "sub,obj,act")
		m.AddDef("p", "p", "sub,obj,act")
		m.AddDef("g", "g", "_,_")
		m.AddDef("e", "e", "some(where (p.eft == allow))")
		m.AddDef("m", "m", "r.sub == p.sub && keyMatch2(r.obj,p.obj) && r.act == p.act")
		a, _ := gormadapter.NewAdapterByDB(global.GVA_DB)
		syncedEnforcer, _ = casbin.NewSyncedEnforcer(m /*global.GVA_CONFIG.Casbin.ModelPath*/, a)
	})
	_ = syncedEnforcer.LoadPolicy()
	return syncedEnforcer
}
```
@dtlalala

**Comment by dtlalala** [comment]
@pnck 好的，谢谢。我已经定位到了具体的地方了，一进入`casbinService.Casbin()`这个方法，后面就没有return，卡在这个函数里面了。但还是没弄清具体的原因是什么，Casbin函数里面都做了err的判断，once.Do这个函数在第一次确实执行了，没有问题。但出现该问题的时候，函数就卡在里面了。加载casbin model的地方我已经直接硬编码了，没从配置文件读取。

**Comment by pnck** [comment]
> @pnck 好的，谢谢。我已经定位到了具体的地方了，一进入`casbinService.Casbin()`这个方法，后面就没有return，卡在这个函数里面了。但还是没弄清具体的原因是什么，Casbin函数里面都做了err的判断，once.Do这个函数在第一次确实执行了，没有问题。但出现该问题的时候，函数就卡在里面了。加载casbin model的地方我已经直接硬编码了，没从配置文件读取。

你的定位方法其实不一定对。因为在一个多线程程序里情况会非常复杂。你还有机会调试的话提醒你观察几个东西：
-  打log的线程有没有发生pannic
- 打log前的成员函数调用，其receiver或者说成员函数的instance是否是有效的
- 日志输出是否发生了阻塞而没打出来
- once的锁被谁持有，是否发生了死锁
- 其它线程此时在干什么

上面这些点，靠打日志是打不出来的，试试 `dlv`

**Comment by realpg** [comment]
> ```go
> 		waitUse, err := utils.GetClaims(c)
> ```

看了前后代码，感觉无论这个故障跟这个是否有关系，你加的这段判断都应该是必须的啊，要不潜在故障很多

**Comment by xiaomlove** [comment]
[这里](https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/core/server_win.go)  的超时时间是个坑啊，还不能配置。
