### ISSUE TITLE
[Bug]: 分页按钮样式问题

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1065]
### gin-vue-admin 版本

2.5.0b

### Node 版本

v14

### Golang 版本

go 1.17

### 是否依旧存在

未测试

### bug描述

样式小问题：
当前页的下一页按钮左边缺少边框
![image](https://user-images.githubusercontent.com/83160341/167994036-fa943a52-d682-4f06-92cb-7b3c6afe7b60.png)

### 修改建议

rt

**Comment by piexlmax** [comment]
![image](https://user-images.githubusercontent.com/29840023/168278111-34881a51-3fdb-41da-b43d-36c4d6bd5b6f.png)
main 已修复
