### ISSUE TITLE
[Feature]: 一点小建议

### ISSUE THREAD

**Issue by yzqdev** [flipped-aurora/gin-vue-admin#1069]
### 功能描述以及必要性描述

1. 如果添加新的vue组件,可以按照vue官方推荐的style-guide来写,更规范一些,[style-guide文档地址](https://vuejs.org/style-guide/rules-strongly-recommended.html#component-files),就比如vue文件名推荐使用`TodoList.vue`,而不是`todoList,vue`,以免有时候出现奇怪的问题

2. element-plus 等等组件可以使用按需导入,不用直接引入所有组件,以便减小打包后的体积,[文档链接](https://element-plus.org/zh-CN/guide/quickstart.html#%E6%8C%89%E9%9C%80%E5%AF%BC%E5%85%A5)
3. 可以逐步的使用typescript, 以提供更好的类型支持, esnext语法等, 提高开发体验.
4. 初始化之后,登录界面的`前往初始化`按钮可以直接隐藏掉,表示已经初始化过了

当然,以上只是一点小建议,完全可以忽略,大佬们觉得怎么舒服怎么来就好.

**Comment by piexlmax** [comment]
感谢提交issue 会采纳部分建议
