### ISSUE TITLE
[Bug]: 前端build后运行报错

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1072]
### gin-vue-admin 版本

V2.5.0b

### Node 版本

v14

### Golang 版本

go 1.17

### 是否依旧存在

未测试

### bug描述

1 每个页面都报错
![image](https://user-images.githubusercontent.com/83160341/168779579-8d81e782-0bbb-43a2-bb42-33ee622bf327.png)

2 按钮样式不对
![image](https://user-images.githubusercontent.com/83160341/168779656-0c50fbb0-f7ad-4bfb-a7cd-1d10d723aa44.png)

3 yarn build的时候"*zoom" warn
![image](https://user-images.githubusercontent.com/83160341/168780199-4dfb16c6-2167-43fc-b62f-b70630c93e67.png)

4  css charset不在第一行warn
![image](https://user-images.githubusercontent.com/83160341/168780081-05a87414-eef5-43b6-8c14-b45346bbca75.png)

ps: 线上demo打不开

**Comment by ilylx** [comment]
我这linux上yarn build ，npm run build报*zoom warn，按钮样式有问题

windows上npm run build，报charset警告，按钮样式好了

第一个报错都存在

**Comment by piexlmax** [comment]
> 我这linux上yarn build ，npm run build报*zoom warn，按钮样式有问题
> 
> windows上npm run build，报charset警告，按钮样式好了
> 
> 第一个报错都存在

看样子像是本地缓存导致的冲突 清理浏览器缓存后重试

**Comment by ilylx** [comment]
> 

应该不是缓存的问题，我换了好几个机器都这样。

**Comment by bypanghu** [comment]
请删除npm的淘宝代理，并且锁定vite版本号在实验

**Comment by pnck** [comment]
*zoom 应该是陈年代码本来就有问题

https://github.com/flipped-aurora/gin-vue-admin/blob/954859bd5bed5e5e0d69634c0ce2800089828a3e/web/src/style/base.scss#L1-L3

**Comment by bypanghu** [comment]
删除node modules 删除cnpm配置，重新安装

发自我的iPhone
