### ISSUE TITLE
[Feature]:  有没有考虑把代码生成器和字典等功能做成插件呢

### ISSUE THREAD

**Issue by pnck** [flipped-aurora/gin-vue-admin#1078]
### 功能描述以及必要性描述

相信大家使用这个项目也主要是来做二次开发的对吧

但是对于二次开发来说代码生成器这样的工具功能肯定不会留在二开后的产品里的

那能不能调整一下结构让这些非框架功能的耦合度更小呢？
理想的情况是这些service和前端页面都在独立的namespace里，二开后去掉一些注册性的引用就能直接把这些功能从产品里去掉。

实际上这些功能也的确是能拆的，并没有耦合到框架的关键（动态路由和权限机制）部分

**Comment by piexlmax** [comment]
可行
