### ISSUE TITLE
[Bug]: el表格内自定义列值方法被多次执行

### ISSUE THREAD

**Issue by cncap** [flipped-aurora/gin-vue-admin#1079]
### gin-vue-admin 版本

v2.5.1

### Node 版本

v16.14.2

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

在表格使用 js函数返回列值时，JS函数将执行多次。
问题复现：

将 src\view\superAdmin\user\user.vue 中的
`<el-table-column align="left" label="用户名" min-width="150" prop="userName" />`
改为：
`        <el-table-column align="left" label="用户名" min-width="150" prop="userName">
          <template #default="scope">
            {{getUser(scope.row.userName)}}
          </template>
        </el-table-column>
`
同时添加方法：
`const getUser=(u)=>{
 // 这里执行5次，并且第一次为 undefined
  console.log(u)  
  return u
}
`

### 修改建议

排查了大半天没发现原因所在，el-table以外的地方没有这种情况。

**Comment by bypanghu** [comment]
非bug，写法问题，请先学习基础知识

**Comment by cncap** [comment]
> 非bug，写法问题，请先学习基础知识

请问能否明示？我参照的是官方作法，一直是这么写的。在untils下format.js 的 filterDict() 中输出也可以发现是多次调用。

在网上找到的办法是去掉列中 fixed 选项可以解决，似乎element官方问题？

**Comment by piexlmax** [comment]
> > 非bug，写法问题，请先学习基础知识
> 
> 请问能否明示？我参照的是官方作法，一直是这么写的。在untils下format.js 的 filterDict() 中输出也可以发现是多次调用。
> 
> 在网上找到的办法是去掉列中 fixed 选项可以解决，似乎element官方问题？

表格行内使用function，每一行都会调用此方法用于数据的填充，这个是必然存在的。fixed是另外一个问题，会导致调用次数X2，原因是其实现为两个表格的重叠覆盖使用导致。

**Comment by bypanghu** [comment]
这属于你自己写的bug，不属于框架bug


发自我的iPhone
