### ISSUE TITLE
server 后端启动报错

### ISSUE THREAD

**Issue by jacklovebella** [flipped-aurora/gin-vue-admin#108]
![image](https://user-images.githubusercontent.com/24713273/83595422-91517900-a594-11ea-960b-1a8dfecb8a24.png)

Fatal error config file: open config.yaml: no such file or directory

**Comment by piexlmax** [comment]
代码拉取以后做过修改吗 这个是没有发现config.yaml 看一下server文件夹下是否拥有此文件

**Comment by arronf2e** [comment]
我也是这个问题。路径下是有这个文件的。没有做过任务修改~

**Comment by SliverHorn** [comment]
> 我也是这个问题。路径下是有这个文件的。没有做过任务修改~

检查版本，有个版本windows会找不到路径文件，使用master分支代码是没问题的

**Comment by arronf2e** [comment]
![image](https://user-images.githubusercontent.com/15780058/98917432-553d1f80-2507-11eb-8046-d09a6c4a77e9.png)

我直接拉的 master 代码，run main.go ，用的 osx 系统呀~

**Comment by SliverHorn** [comment]
@arronf2e 我用mac没有遇到这个问题

**Comment by arronf2e** [comment]
> @arronf2e 我用mac没有遇到这个问题

可以啦，默认会创建一个 admin 的用户吗

**Comment by SliverHorn** [comment]
> > @arronf2e 我用mac没有遇到这个问题
> 
> 可以啦，默认会创建一个 admin 的用户吗

www.gin-vue-admin.com/docs/server
