### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by lboquan** [flipped-aurora/gin-vue-admin#1088]
### gin-vue-admin 版本

2.5.1b

### Node 版本

v14.19.3

### Golang 版本

go 1.18.2

### 是否依旧存在

可以

### bug描述

1. 依照文档步骤编译后台
    go build server.exe main.go
2. 进入 web 资料夹执行
    npm run serve
3. 点击菜单的系统工具->代码生成器出现以下错误:
Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/marked.js?v=5190db0f' does not provide an export named 'default' (at previewCodeDialg.vue:12:8)
4. 点击菜单的系统工具->自动化代码管理->新增出现以下错误:
vue-router.esm-bundler.js:3308 SyntaxError: The requested module '/node_modules/.vite/deps/marked.js?v=5190db0f' does not provide an export named 'default' (at previewCodeDialg.vue:12:8)
triggerError @ vue-router.esm-bundler.js:3308
(匿名) @ vue-router.esm-bundler.js:3040
Promise.catch (非同步)
pushWithRedirect @ vue-router.esm-bundler.js:3034
push @ vue-router.esm-bundler.js:2969
goAutoCode @ index.vue:143
_createVNode.onClick._cache.<computed>._cache.<computed> @ index.vue:5
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:721
(匿名) @ runtime-core.esm-bundler.js:7343
handleClick @ button.vue:153
createElementBlock.onClick._cache.<computed>._cache.<computed> @ button.vue:22
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:369
previewCodeDialg.vue:12 Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/marked.js?v=5190db0f' does not provide an export named 'default' (at previewCodeDialg.vue:12:8)

**Comment by piexlmax** [comment]
初始化用的npm 还是 cnpm 还是 yarn 感觉拉下来的 marked 包版本不同

**Comment by bypanghu** [comment]
首先你需要排除你是用的不是cnpm 。其次你需要排除你的npm yarn 并非淘宝代理镜像！
```
import { marked  } from 'marked'
```

类似于下方的解决方法

**Comment by lboquan** [comment]
初始化是用 npm

**Comment by bypanghu** [comment]
看到了，是用的一个库 更新了写法没有锁包，导致下载的是最新的
