### ISSUE TITLE
前端路由都是用name去进行跳转，不太好处理不同路由引用相同组件这种情况

### ISSUE THREAD

**Issue by q946666800** [flipped-aurora/gin-vue-admin#109]
大佬你好，里面的前端路由似乎都是用name去进行跳转，似乎不太好处理不同路由引用相同组件这种情况，比如 /layout/page/1 , /layout/page/2 ,

**Comment by piexlmax** [comment]
> 大佬你好，里面的前端路由似乎都是用name去进行跳转，似乎不太好处理不同路由引用相同组件这种情况，比如 /layout/page/1 , /layout/page/2 ,

后面的path可以打开参数配置 这样就可以通过name加params的形式实现所说情况

**Comment by piexlmax** [comment]
> 大佬你好，里面的前端路由似乎都是用name去进行跳转，似乎不太好处理不同路由引用相同组件这种情况，比如 /layout/page/1 , /layout/page/2 ,

此功能为近两次更新添加 测试环境暂时没有同步

**Comment by q946666800** [comment]
> > 大佬你好，里面的前端路由似乎都是用name去进行跳转，似乎不太好处理不同路由引用相同组件这种情况，比如 /layout/page/1 , /layout/page/2 ,
> 
> 此功能为近两次更新添加 测试环境暂时没有同步

感谢回复，这里主要是 history.vue 这个文件需要改为path跳转的形式，然后需要在store/module/router.js里面添加相关动态路由配置，我这边改了一个版本，稍后提个 pr，
另外2.0的版本，关闭右边存在一个小bug，具体代码大致是这样
        let reduceSize = this.historys.length - leftIndex - 1;
        if (reduceSize < 0) {
          reduceSize = 0
        }
        this.historys.splice(leftIndex + 1, reduceSize)
