### ISSUE TITLE
[Bug]: vue打包上线出现BUG:Converting circular structure to JSON

### ISSUE THREAD

**Issue by jaryf** [flipped-aurora/gin-vue-admin#1090]
### gin-vue-admin 版本

2.5.1

### Node 版本

v16.14.0

### Golang 版本

go1.16.14

### 是否依旧存在

未测试

### bug描述

1.项目正常开发,vue项目打包上线,然后点击菜单出现bug
2.本地开发时没有出现过这个bug,只有在打包之后上线了,访问线上才出现这个bug
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Object'
    |     property 'vnode' -> object with constructor 'Object'
    |     ...
    |     property 'ref' -> object with constructor 'Lt'
    --- property '_rawValue' closes the circle
    at JSON.stringify (<anonymous>)
    at history.vue:258:43
    at Wt (runtime-core.esm-bundler.js:155:22)
    at Gt (runtime-core.esm-bundler.js:164:21)
    at Array.f (runtime-core.esm-bundler.js:1779:44)
    at dn (runtime-core.esm-bundler.js:328:31)
    at fn (runtime-core.esm-bundler.js:369:5)

**Comment by frui85** [comment]
本地和线上部署环境有什么差异呢？比如有无负载均衡、反向代理、ssl 重定向啥的？

**Comment by piexlmax** [comment]
问题为2.5.0问题 新版本已修复 此issue关闭
