### ISSUE TITLE
[Feature]: comfig.yaml 配置文件，怎么区分测试环境，开发环境，生成环境 

### ISSUE THREAD

**Issue by vic220309** [flipped-aurora/gin-vue-admin#1098]
### 功能描述以及必要性描述

config.yaml 文件，是否提交到git 里面版本库，提交后，测试和生成配置不一样怎么办

### 建议和方案

有一个环境变量作为区分

**Comment by pnck** [comment]
config.yaml会被随时重写的。。 建议手动管理

server可以用 `-c` flag 和环境变量指定使用的配置文件
https://github.com/flipped-aurora/gin-vue-admin/blob/bab8aac349c8a4dc52c389db82e718c50378d127/server/core/viper.go#L23-L39
