### ISSUE TITLE
[Bug]: #1102 此次更新造成侧边栏菜单路由监听失效

### ISSUE THREAD

**Issue by lin93h** [flipped-aurora/gin-vue-admin#1110]
### gin-vue-admin 版本

v2.5.2b

### Node 版本

v16.14.2

### Golang 版本

go 1.18.2

### 是否依旧存在

可以

### bug描述

#1102此次更新造成侧边栏菜单路由监听失效
![image](https://user-images.githubusercontent.com/18698414/171142723-7df18d14-c00a-45f9-b7bd-bbc061714168.png)

**Comment by piexlmax** [comment]
更新代码即可，已解决。
