### ISSUE TITLE
[Bug]: 每次重启server服务后，登录时会报错“用户不存在”；每次都需要重新初始化数据库，才能重新登录

### ISSUE THREAD

**Issue by luckyhacking** [flipped-aurora/gin-vue-admin#1111]
### gin-vue-admin 版本

2.5

### Node 版本

v18

### Golang 版本

go1.18

### 是否依旧存在

可以

### bug描述

1. 使用docker重新部署server
2. 无法用之前的用户直接登录，需要重新初始化数据库，才能登录

**Comment by songzhibin97** [comment]
请截图&前台后台报错

**Comment by piexlmax** [comment]
docker仅供体验使用，docker关闭后内部数据库会被清理，正式上线的docker请自行制作

**Comment by luckyhacking** [comment]
![image](https://user-images.githubusercontent.com/8591495/172192344-a2309a48-0193-4b4d-acf1-38dc6003aa04.png)

**Comment by luckyhacking** [comment]
重新部署server服务后，返回“Couldn't handle this token:”，重新登录时报错“用户不存在”，查了一下日志，实际上是“db not init”导致的，这个怎么解决？

我的github action脚本中涉及重启服务的step如下：

![image](https://user-images.githubusercontent.com/8591495/172193181-e6006b3b-d224-49ac-a02f-1f28f8ddc527.png)

每次部署服务后，都需要重新初始化数据库

**Comment by izyh** [comment]
有两个地方需要修改：
1. Dockerfile 中用到了 config.docker.yaml 这个配置文件，需要挂载到volume上，以便持久化
2. 数据库连接失败时改为panic，让容器重启，这样数据库ready之后，服务会自动重启，重新连接数据库
