### ISSUE TITLE
[Feature]: 上传文件的时候直接502

### ISSUE THREAD

**Issue by WinKingFace** [flipped-aurora/gin-vue-admin#1112]
### 功能描述以及必要性描述

本地上传大于30m的时候没有报错，发布到nginx 则出现错误

nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  600;
    send_timeout 100m;
    client_header_timeout 100m;
    client_body_timeout 100m;
    client_max_body_size 512m;
    large_client_header_buffers 8 32k;
    gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

# my.conf
server {
    listen       8080;
    server_name localhost;
    client_max_body_size 512m;
    proxy_buffer_size 512k;
    proxy_buffers 4 1024k;
    proxy_busy_buffers_size 1024k;
    proxy_read_timeout 3600;
    proxy_send_timeout 3600;
    #charset koi8-r;
    access_log  logs/host.access.log  main;
    location / {
        root /usr/share/nginx/html;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        rewrite ^/api/(.*)$ /$1 break;  #重写
        proxy_pass http://xxxx;
     }

    location /api/swagger/index.html {
        proxy_pass http://xxxx;
     }

**Comment by piexlmax** [comment]
nginx配置问题，文件过大拦截了。
