### ISSUE TITLE
[Bug]: Violation 和  vue-router.esm

### ISSUE THREAD

**Issue by mqzhifu** [flipped-aurora/gin-vue-admin#1123]
### gin-vue-admin 版本

v2.5.2

### Node 版本

v14.16.1

### Golang 版本

go1.16.5 darwin/amd64

### 是否依旧存在

可以

### bug描述

我的版本是v2.5.2
1. [Violation] Added non-passive event listener to a scroll-blocking <某些> 事件  xxxx ，这次我更新完后，这个提示真的是太烦人了，点一次菜单出一次，我查了下，可能是chrom高版本，提高对监听事件的定义
2. vue-router.esm-bundler.js:72 [Vue Router warn]: No match found for location with path "/xxx/xxxx“ ，这个也很烦人，刷新一下页面即出现一次，可能是JS加载顺序造成的

两个问题都不太影响程序，但是日常开发打开F12，就能看见，挺头疼的....

### 修改建议

1 2 都不太影响程序，好像也不太难改

**Comment by piexlmax** [comment]
No match found for location with path "/xxx/xxxx“  这个问题原因为异步路由导致 如果有好的修改方案可以pr一下 我这边也会找一下修改方案

Added non-passive event listener to a scroll-blocking  这边提升一下浏览器版本 复现一下

**Comment by mqzhifu** [comment]
我的chrom 版本 102.0.5005.61（正式版本） (x86_64) ， mac pro(10.15.6 ,非M1)
