### ISSUE TITLE
[Feature]: 代码生成器是否能增加导出功能

### ISSUE THREAD

**Issue by q629988171** [flipped-aurora/gin-vue-admin#1127]
### 功能描述以及必要性描述

导出功能：用于EXCEL表数据统计。

![表格示例](https://user-images.githubusercontent.com/2260447/173182199-39131ebd-64dd-49c1-955c-66ec47e1bb71.png)

### 建议和方案

增加一个导出按钮，默认导出所有数据。
![按钮实例](https://user-images.githubusercontent.com/2260447/173182315-ae8791d7-ef6c-444a-afd5-d0d091dd06e7.png)

**Comment by SliverHorn** [comment]
插件市场已经有后端插件了

**Comment by q629988171** [comment]
> 插件市场已经有后端插件了

是这个吗？ [excel 导入导出封装](https://plugin.gin-vue-admin.com/#/layout/plugin-info?id=24)  有演示视频吗？

**Comment by piexlmax** [comment]
系统默认示例功能有免费的
