### ISSUE TITLE
测试环境添加角色报错

### ISSUE THREAD

**Issue by anstns** [flipped-aurora/gin-vue-admin#113]
http://qmplus.henrongyi.top 报错了
我想做一个这样的角色权限关系 系统管理员->站长->部门总监->主管->员工
请问怎么实现

**Comment by piexlmax** [comment]
> http://qmplus.henrongyi.top 报错了
> 我想做一个这样的角色权限关系 系统管理员->站长->部门总监->主管->员工
> 请问怎么实现

主角色为管理员 然后往下依次添加其子角色 多层添加完成以后 然后去设置资源权限进行控制其可用资源 菜单和api就按照单一角色分配即可  测试华宁已修复

**Comment by anstns** [comment]
还有搭建2.0的时候 数据永兴qmplus 但是开发报错 获取失败，Error 1146: Table 'admin.authority_menu' doesn't exist，我查了了下代码，确实执行的这个表

**Comment by anstns** [comment]
type HandlerFunc func(c *Context)
func Handle(h HandlerFunc) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := &Context{
			c,
		}
		h(ctx)
	}
}
type Context struct {
	*gin.Context
}
func (c *Context) ToJSON(code int, message string, data interface{}) {
	var is bool
	if data != nil {
		is = true
	}
	c.JSON(200, gin.H{
		"code":      code,
		"existData": is,
		"message":   message,
		"data":      data,
	})
}
这个是我常用 gin封装，我看你的每次都返回都需要填写上下文，如果觉得不错可以采用一下哈

**Comment by piexlmax** [comment]
> 还有搭建2.0的时候 数据永兴qmplus 但是开发报错 获取失败，Error 1146: Table 'admin.authority_menu' doesn't exist，我查了了下代码，确实执行的这个表

2.0需要用2.0版本的数据库 它有一张视图就是报错的这个内容

**Comment by granty1** [comment]
```
func Handle(h HandlerFunc) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := &Context{
			c,
		}
		h(ctx)
	}
}
```

那这样我怎么在handler中使用gin的ctx呢

**Comment by granty1** [comment]
> type HandlerFunc func(c *Context)
> func Handle(h HandlerFunc) gin.HandlerFunc {
> return func(c *gin.Context) {
> ctx := &Context{
> c,
> }
> h(ctx)
> }
> }
> type Context struct {
> *gin.Context
> }
> func (c *Context) ToJSON(code int, message string, data interface{}) {
> var is bool
> if data != nil {
> is = true
> }
> c.JSON(200, gin.H{
> "code": code,
> "existData": is,
> "message": message,
> "data": data,
> })
> }
> 这个是我常用 gin封装，我看你的每次都返回都需要填写上下文，如果觉得不错可以采用一下哈

其实这种做法最终也是ctx.ToJSON，还是有ctx存在，就看你怎么读了

另外
```
func Handle(h HandlerFunc) gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := &Context{
			c,
		}
		h(ctx)
	}
}
```

目前的需求还没到这一步，但是总的来说您的建议不错！

**Comment by anstns** [comment]
> > 还有建造2.0的时候数据永兴qmplus但是开发报错获取失败，错误1146：表'admin.authority_menu'不存在，我查了了下代码，确实执行的这个表
> 
> 2.0需要用2.0版本的数据库它有一张表就是就是报错的这个内容

![image](https://user-images.githubusercontent.com/36152763/84006760-dc5afa00-a9a1-11ea-84ec-2a711d970907.png)
我用的2.0.0版本 倒入的就是这个数据库，这个数据库不是2.0的吗

**Comment by piexlmax** [comment]
检查一下数据库是否存在 authority_menu 这个视图  看脚本中存在本视图创建语句
