### ISSUE TITLE
sql文件跟model不匹配

### ISSUE THREAD

**Issue by iepngs** [flipped-aurora/gin-vue-admin#114]
拉取master分支代码运行，登录后报错：

> 获取失败，Error 1146: Table 'gva.authority_menu' doesn't exist

数据库导入的是`gin-vue-admin/server/db/qmplus.sql`，是不是代码运行的model跟此文件数据库表结果不匹配？model里面用的表名是`authority_menu`，sql文件里表结构是`sys_authority_menus`.

**Comment by piexlmax** [comment]
> 拉取master分支代码运行，登录后报错：
> 
> > 获取失败，Error 1146: Table 'gva.authority_menu' doesn't exist
> 
> 数据库导入的是`gin-vue-admin/server/db/qmplus.sql`，是不是代码运行的model跟此文件数据库表结果不匹配？model里面用的表名是`authority_menu`，sql文件里表结构是`sys_authority_menus`.

我立刻排查一下 昨天更新了新版本 可能是据库脚本有漏掉 这里查询的是一个视图  可能视图脚本丢失了

**Comment by piexlmax** [comment]
> 拉取master分支代码运行，登录后报错：
> 
> > 获取失败，Error 1146: Table 'gva.authority_menu' doesn't exist
> 
> 数据库导入的是`gin-vue-admin/server/db/qmplus.sql`，是不是代码运行的model跟此文件数据库表结果不匹配？model里面用的表名是`authority_menu`，sql文件里表结构是`sys_authority_menus`.

请查看一下是否存在视图 authority_menu 本地看是存在本视图的

**Comment by iepngs** [comment]
好像没有…

**Comment by piexlmax** [comment]
db脚本中的

**Comment by anstns** [comment]
sys_authority_menus 

> db脚本中的
> 
> DROP VIEW IF EXISTS `authority_menu`;
> CREATE ALGORITHM = UNDEFINED DEFINER = `root`@`localhost` SQL SECURITY DEFINER VIEW `authority_menu` AS select `sys_base_menus`.`id` AS `id`,`sys_base_menus`.`created_at` AS `created_at`,`sys_base_menus`.`updated_at` AS `updated_at`,`sys_base_menus`.`deleted_at` AS `deleted_at`,`sys_base_menus`.`menu_level` AS `menu_level`,`sys_base_menus`.`parent_id` AS `parent_id`,`sys_base_menus`.`path` AS `path`,`sys_base_menus`.`name` AS `name`,`sys_base_menus`.`hidden` AS `hidden`,`sys_base_menus`.`component` AS `component`,`sys_base_menus`.`title` AS `title`,`sys_base_menus`.`icon` AS `icon`,`sys_base_menus`.`nick_name` AS `nick_name`,`sys_base_menus`.`sort` AS `sort`,`sys_authority_menus`.`sys_authority_authority_id` AS `authority_id`,`sys_authority_menus`.`sys_base_menu_id` AS `menu_id`,`sys_base_menus`.`keep_alive` AS `keep_alive`,`sys_base_menus`.`default_menu` AS `default_menu` from (`sys_authority_menus` join `sys_base_menus` on((`sys_authority_menus`.`sys_base_menu_id` = `sys_base_menus`.`id`)));
> 
> 就是创建这个视图的语句 如果没能自动执行的话 手动执行一下看看

必须是root用户吗

**Comment by ashanyue** [comment]
用sqlite的怎么搞？

**Comment by piexlmax** [comment]
> 用sqlite的怎么搞？

sqlite 这边没有继续维护了
