### ISSUE TITLE
[Bug]: Readme document and VSCode workspace file need update after PR #1144

### ISSUE THREAD

**Issue by bustezero** [flipped-aurora/gin-vue-admin#1146]
### gin-vue-admin 版本

master

### Node 版本

v14.16.0

### Golang 版本

go1.18

### 是否依旧存在

可以

### bug描述

README.md:110
> # 编译 
> go build -o server main.go (windows编译命令为go build -o server.exe main.go )

gin-vue-admin.code-workspace:30
>        "program": "${workspaceFolder:backend}/main.go"

that need update, old cmd will build failed due to embed.go after PR #1144

### 修改建议

README.md:110
> go build -o server main.go (windows编译命令为go build -o server.exe main.go )
to
> go build -o server (windows编译命令为go build -o server.exe)

gin-vue-admin.code-workspace:30
>        "program": "${workspaceFolder:backend}/main.go"
to
>        "program": "${workspaceFolder:backend}"

**Comment by piexlmax** [comment]
已采纳pr，感谢提交issue
