### ISSUE TITLE
[Bug]: 样式问题

### ISSUE THREAD

**Issue by wxyShine** [flipped-aurora/gin-vue-admin#1153]
### gin-vue-admin 版本

最新版demo

### Node 版本

最新版demo

### Golang 版本

最新版demo

### 是否依旧存在

未测试

### bug描述

百分浏览器 所有按钮样式 如图  ![1](https://www.helloimg.com/images/2022/07/04/Z2E0vu.png)  

浏览器 ![2](https://www.helloimg.com/images/2022/07/04/Z2ENfv.png)

**Comment by SliverHorn** [comment]
不会适配百分浏览器的，请使用google浏览器或者edge浏览器

**Comment by SliverHorn** [comment]
edge浏览器 效果如图
<img width="2596" alt="image" src="https://user-images.githubusercontent.com/45428434/177081001-5f38852b-109f-4969-a059-f1a542d64306.png">

**Comment by wxyShine** [comment]
> edge浏览器 效果如图 <img alt="image" width="2000" src="https://user-images.githubusercontent.com/45428434/177081001-5f38852b-109f-4969-a059-f1a542d64306.png">

是的我试过edg 没问题

**Comment by bypanghu** [comment]
非代码性`bug`，关闭此issues
