### ISSUE TITLE
[Bug]: 部署到服务器，点击tab后，tab页面没有数据，需要强制刷新url才有数据

### ISSUE THREAD

**Issue by hotwheelsBo** [flipped-aurora/gin-vue-admin#1164]
### gin-vue-admin 版本

master

### Node 版本

v14.20.0

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

1. 部署到centos，npm run build，配置好nginx
2. chrome打开
3. 点击某个tab，对应的tab页面是空白页，没有数据，强制刷新url才有数据
4. F12查看network，发现请求下载了对应的js，但是js里的方法没有执行（正常情况下，js里应该会请求对应的api接口）

点击tab，failed请求，network窗口：
<img width="501" alt="image" src="https://user-images.githubusercontent.com/1224488/178099915-5907a68f-b7f1-4f86-b8ee-9adca7f42f9f.png">

刷新url，succ请求，network窗口：
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1224488/178099944-421bdca9-6e82-403f-8e69-ff1ee4137592.png">

**Comment by piexlmax** [comment]
demo无法复现，猜测是使用的旧版代码升级上来合并错误，请按照官方的package.json选择依赖包的版本。

**Comment by zhaozhiwei66** [comment]
怎么解决的，我也遇到了这个问题
