### ISSUE TITLE
[Bug]: 自动创建数据库失败!

### ISSUE THREAD

**Issue by chenlixin93** [flipped-aurora/gin-vue-admin#1165]
### gin-vue-admin 版本

v2.5.3

### Node 版本

v13.14.0

### Golang 版本

go version go1.16.15 windows/amd64

### 是否依旧存在

未测试

### bug描述

我的mysql版本是5.5（用的镜像openshift/mysql-55-centos7），填了数据库信息后，点击立即初始化显示“创建数据库失败，查看后台日志”
{"error": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`path` varc' at line 1"}

另外报错之后，刷新页面改成`全新的数据库地址或者数据库名称`，还是会提示`已存在数据库配置!`

**Comment by piexlmax** [comment]
mysql版本过低
