### ISSUE TITLE
表单生成器加载失败

### ISSUE THREAD

**Issue by cold-runner** [flipped-aurora/gin-vue-admin#1167]
### gin-vue-admin 版本

2.5.2

### Node 版本

v16.16.0

### Golang 版本

go1.16.14

### 是否依旧存在

可以

### bug描述

初始化数据库之后前端报错如下
![image](https://user-images.githubusercontent.com/86516312/178693489-9a76e4a7-88ba-4baa-b963-ae6018bf49ea.png)

登录后表单生成器加载不出来
![image](https://user-images.githubusercontent.com/86516312/178693316-4f7d3d80-9b9d-473b-baf9-059547ea0622.png)

**Comment by bypanghu** [comment]
会不会存在一种情况，你后端报错了……，或者说 你后端都没启动，请先根据文档启动

**Comment by cold-runner** [comment]
创建角色添加用户什么的都管用，我是按照文档先启动的后端，后启动的前端。数据库初始化也的确是成功了，只是这个表单生成器加载不出来

**Comment by cold-runner** [comment]
![image](https://user-images.githubusercontent.com/86516312/178761854-2a77cca7-5914-4061-8cb5-e11f2e713cea.png)

貌似是前端JS部分调用出了问题

**Comment by cold-runner** [comment]
![image](https://user-images.githubusercontent.com/86516312/178763060-8b33110f-18c5-4b65-b015-bdd41ae1fe46.png)

解决了，是浏览器的cookie问题，需要把cookie打开
