### ISSUE TITLE
[Feature]: 关于时间日期的格式化

### ISSUE THREAD

**Issue by mqzhifu** [flipped-aurora/gin-vue-admin#1175]
### 功能描述以及必要性描述

1. 我们公司的date 字段值均是：unixstamp ,10位整数，是否可以考虑在js端加个公共函数
2. 对于表格内的一个td 的内容过长时，是否可以考虑在js端加个公共函数

### 建议和方案

1. export const formatUnixtDate = (time) => {
  if (time !== null && time !== '' && time > 0) {
    time = time + "000"
    time = parseInt(time);
    var date = new Date(time)
    return formatTimeToStr(date, 'yyyy-MM-dd hh:mm:ss')
  } else {
    return '--'
  }
}

2.

const substrContent = (val) => {
  var v = val.headerCommon
  if( v.length > 40){
    return v.substr(0,40)
  }else{
    return v
  }
}

**Comment by piexlmax** [comment]
element-plug已经内置了date.js 更多的方法实际有点重复了
