### ISSUE TITLE
[Feature]: 登录页面加载动画缺失

### ISSUE THREAD

**Issue by QYG2297248353** [flipped-aurora/gin-vue-admin#1179]
### 功能描述以及必要性描述

1. 用户输入账户密码验证码后点击登录有加载动画，当用户网络状况不好或者本地调用远程开发时会出现登录页面无动画等待状态。
2. 操作方法：
2.1.  打开[Gin-Vue_Admin](https://demo.gin-vue-admin.com/) 在线体验网站 调用f12调节网络为低速3g，进行登录。
2.2. 记载动画仅仅保持在登录接口返回后。获取路由接口并不会出现加载动画

### 建议和方案

1. 登录界面加载动画优化可以局部化，控制在登录按钮或from表单范围内
2. 全局加载动画，用户刷新操作，路由(导航)页面加载，触发全局自定义加载动画
2.1. 全局刷新页面完整加载动画
2.2. 标签页刷新标签页内加载动画
2.3. 接管浏览器刷新操作替换自定义加载动画

**Comment by bypanghu** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/aa81a2925713f8a66409d226d9cbc7b9e1ae95ea 已经在此 commit  加上接管浏览器加载动画
