### ISSUE TITLE
表说明还有加吗， 亲爱的作者

### ISSUE THREAD

**Issue by qinjia127** [flipped-aurora/gin-vue-admin#118]
表说明还有加吗， 亲爱的作者

_Originally posted by @qinjia127 in https://github.com/flipped-aurora/gin-vue-admin/issues/115#issuecomment-641898998_

**Comment by piexlmax** [comment]
已经添加

> 表说明还有加吗， 亲爱的作者
> 
> _Originally posted by @qinjia127 in [#115 (comment)](https://github.com/flipped-aurora/gin-vue-admin/issues/115#issuecomment-641898998)_

已经添加

**Comment by granty1** [comment]
> 已经添加
> 
> > 表说明还有加吗， 亲爱的作者
> > _Originally posted by @qinjia127 in [#115 (comment)](https://github.com/flipped-aurora/gin-vue-admin/issues/115#issuecomment-641898998)_
> 
> 已经添加

Thanks~ ， 亲爱的作者
