### ISSUE TITLE
[Bug]: Error 1071: Specified key was too long; max key length is 1000 bytes  

### ISSUE THREAD

**Issue by PittYao** [flipped-aurora/gin-vue-admin#1189]
### gin-vue-admin 版本

master

### Node 版本

v16.16.0

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

Mysql Version:
![image](https://user-images.githubusercontent.com/26101917/182068398-4a3d58f4-8f35-47ee-afee-2641ad66e141.png)

1. 按页面初始化gva数据库成功
2. 页面登录admin账号
3. 后台panic，casbin_rule表创建INDEX
 Specified key was too long; max key length is 1000 bytes  
![image](https://user-images.githubusercontent.com/26101917/182068293-c6116fdd-f09c-420b-bbc7-5147bcc317cf.png)

**Comment by songzhibin97** [comment]
https://www.gin-vue-admin.com/guide/manual/qa.html#%E5%88%9D%E5%A7%8B%E5%8C%96%E7%9A%84%E6%97%B6%E5%80%99%E5%87%BA%E7%8E%B0-github-com-casbin-gorm-adapter-v3-v3-7-3-adapter-go-389-error-1071-specified-key-was-too-long-max-key-length-is-1000-bytes%E5%AD%97%E6%A0%B7
