### ISSUE TITLE
这个项目实在是太棒了

### ISSUE THREAD

**Issue by liuts** [flipped-aurora/gin-vue-admin#119]
才发现这个项目，这个项目太好了。好多代码都可以自动生成，希望以后越走越好。
过几天关闭issues。

**Comment by piexlmax** [comment]
单服务版本现在plug分支提供了注入式的插件系统  马上会开发微服务版本gin-vue-admin 共给大型系统使用

**Comment by piexlmax** [comment]
> 才发现这个项目，这个项目太好了。好多代码都可以自动生成，希望以后越走越好。
> 过几天关闭issues。

有好的建议或者方向可以告诉我们~一起让项目更加强大
