### ISSUE TITLE
自动生成代码页面加载加载空白[Bug]: 

### ISSUE THREAD

**Issue by erosiners** [flipped-aurora/gin-vue-admin#1191]
### gin-vue-admin 版本

v2.5.3b

### Node 版本

v14.18.2

### Golang 版本

go 1.16

### 是否依旧存在

不可以

### bug描述

组合式API多语言分支最新代码，自动生成代码页面打开卡住，查看日志如下图：
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/6299779/182113424-d993c484-773c-471c-9037-f2e0a312c610.png">
切换到主分支代码是没问题的

**Comment by piexlmax** [comment]
此问题主干已修复，具体原因在于keepaliverouter的数组中存在underfind的数据导致，对此数组做下空值清理即可，目前很难抽出人手维护I18N版本，您如果可以尝试修复，也非常感谢您提交PR。
