### ISSUE TITLE
[Bug]: ALTER TABLE Varchar Column Data too long for column

### ISSUE THREAD

**Issue by PittYao** [flipped-aurora/gin-vue-admin#1192]
### gin-vue-admin 版本

master

### Node 版本

v16.16.0

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

1. db中字段类型是text
2. 通过自动生成代码，启动server后 将text的字段ALTER TABLE 到varchar(191)，导致数据太长插入不进去（ Data too long for column）
3. 修改db的字段为text后，启动server后，再次将字段修改为archar(191)。怎么不让他修改类型
![image](https://user-images.githubusercontent.com/26101917/182284208-d6d4d819-2b55-43c6-a282-9596ab214840.png)

5. datatime默认长度是3，能改为0吗 
![image](https://user-images.githubusercontent.com/26101917/182284160-2a3ded26-18b2-45ef-a9e0-f82567b36566.png)

**Comment by piexlmax** [comment]
gorm已经自动迁移生成的字段后续修改不会自动同步，需要自行手动修改。

**Comment by PittYao** [comment]
> 

因为是先建的db，gorm的AutoMigrate会我把类型改掉，我把他注释了
![image](https://user-images.githubusercontent.com/26101917/182332089-69962afe-2bde-4c3f-a1b8-67475e7dc33f.png)
