### ISSUE TITLE
[Bug]: 日志输出sql乱码

### ISSUE THREAD

**Issue by Sir-yuChen** [flipped-aurora/gin-vue-admin#1198]
### gin-vue-admin 版本

2.5.3

### Node 版本

v14.16

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

zap 输出 json 格式日志
会导致gin输出的sql日志无法解析
由于要分析收集日志
请问作者有什么解决方案嘛？

![微信截图_20220812164614](https://user-images.githubusercontent.com/64669688/184318951-a2e37c91-7807-4891-8ad3-8440e95e4ceb.png)
![image](https://user-images.githubusercontent.com/64669688/184319154-0ead2c30-aa65-43d9-ba30-edcd021c3db6.png)

**Comment by songzhibin97** [comment]
自己查看zap文档，有输出模式，不带颜色
