### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by traywzk** [flipped-aurora/gin-vue-admin#1199]
### gin-vue-admin 版本

2.5.3b

### Node 版本

v17.7.1

### Golang 版本

go 17.8

### 是否依旧存在

可以

### bug描述

后台添加pkg 正常
文件夹和enter都正常生成

然后操作代码生成器 生成代码
api model文件都是正常的

但包下的enter都还是pkg生成的空代码

<img width="615" alt="image" src="https://user-images.githubusercontent.com/35022330/185273029-fa99d8d5-1bb6-42a6-99f8-afa42fa192f5.png">
<img width="614" alt="image" src="https://user-images.githubusercontent.com/35022330/185273049-998b4577-e531-4a4f-904f-b26377db9b71.png">

本地文件夹：
![image](https://user-images.githubusercontent.com/35022330/185273299-79361bc5-d0d7-4743-9627-d1615d7e6853.png)
![image](https://user-images.githubusercontent.com/35022330/185273327-23663052-351a-4783-b060-eb79e652f9dd.png)

包括 service和router也是这样的

**Comment by songzhibin97** [comment]
提供请求内容

**Comment by traywzk** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/35022330/185274408-a65f5f92-9f3c-4bdf-b8ec-a203c329a0f8.png">
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/35022330/185274426-2405d584-863b-4b83-a57a-5d6fb58ff131.png">


createTemp请求没有返回

**Comment by songzhibin97** [comment]
看后端错误

**Comment by traywzk** [comment]
![image](https://user-images.githubusercontent.com/35022330/185274600-2c6fdd65-ded9-49d3-a372-41d36b2802d4.png)

控制台也没给出报错

**Comment by piexlmax** [comment]
修改过文件名字吧 或者是升级上来的 配置文件没有跟着升级

**Comment by traywzk** [comment]
comment:Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT. not found

> 修改过文件名字吧 或者是升级上来的 配置文件没有跟着升级

debug 找到问题所在了，我本地测试的时候生成过，然后删除了initialize下 gorm和router里的 注释

<img width="457" alt="image" src="https://user-images.githubusercontent.com/35022330/185279942-75d6a102-d312-4860-bfcc-a7cd6340ade9.png">

**Comment by traywzk** [comment]
以解决，谢谢回复
