### ISSUE TITLE
请问有计划适配 MongoDB 吗

### ISSUE THREAD

**Issue by King-tu** [flipped-aurora/gin-vue-admin#120]

**Comment by piexlmax** [comment]
mongodb需要自行增加 gorm的mongodb方言 github有类似支持的包 自行安装即可

**Comment by King-tu** [comment]
> mongodb需要自行增加gorm的mongodb方言github有类似支持的包自行安装即可

https://github.com/grails/gorm-mongodb
github上找到的是Groovy语言实现的，请问有没有go实现的库推荐呢
