### ISSUE TITLE
[Feature]: keepalive动态化，当关闭tab标签时候，自动杀死keepalive

### ISSUE THREAD

**Issue by piexlmax** [flipped-aurora/gin-vue-admin#1201]
### 功能描述以及必要性描述

目前的keepalive在标签关闭后依然会保存内容，这样操作不符合用户习惯。

### 建议和方案

将keepalive动态化，关闭tab时候从keepalive中剔除对应的路由name

**Comment by Ale6333499** [comment]
您好2.5.4优化此操作逻辑了么

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/52e6a927becad02a346d938438af4080b8b21c84
