### ISSUE TITLE
[Feature]: 有没有考虑增加排序相关的功能

### ISSUE THREAD

**Issue by heyangfan** [flipped-aurora/gin-vue-admin#1203]
### 功能描述以及必要性描述

有很多时候需要对主键进行正序倒序的排序。
也有一些项目有要求新增一些排序的字段（如接口按照排序字段数字大小进行排序）
我个人还是觉得在实际项目中，排序功能还是有需求的。
不知道开发的大大什么意见？

### 建议和方案
举例：
在代码生成时添加一个开关，是否开启主键排序功能，该功能开启后，可在列表页通过点击主键标题，进行正序倒叙的排序。 

在代码生成时可以额外有一个开启数据排序功能，如点击开启该功能，会默认在生成数据库的时候新增一个SORT字段用来排序。同时可在列表页面进行排序，可在列表页面进行编辑（双击可编辑）或者在新增（编辑）页面进行编辑也可以。

在代码生成时可以给每个字段添加一个是否开启排序的开关（不可在列表页面编辑，仅在点击该字段标题时进行排序）

**Comment by piexlmax** [comment]
sort功能可以做到自动化，但是存在注入风险，故此暂未加入。 预计在2.5.5会进行添加。

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/5955bfeebad92d58dd74b3769e6d30db5208cc83
