### ISSUE TITLE
[Bug]: api/menu/getMenu接口报错

### ISSUE THREAD

**Issue by ChZhg123** [flipped-aurora/gin-vue-admin#1208]
### gin-vue-admin 版本

2.4.5

### Node 版本

v16.13.0

### Golang 版本

go 1.18.3

### 是否依旧存在

未测试

### bug描述

报错信息：
github.com/casbin/gorm-adapter/v3@v3.8.0/adapter.go:406 Error 1071: Specified key was too long; max key length is 1000 bytes

runtime error: invalid memory address or nil pointer dereference

**Comment by songzhibin97** [comment]
看文档
