### ISSUE TITLE
[Feature]: 建议增加微服务版本

### ISSUE THREAD

**Issue by quqiangsheng** [flipped-aurora/gin-vue-admin#1211]
### 功能描述以及必要性描述

使用go构建分布式系统越来越普遍，目前go的微服务框架多为基础技术框架偏运行时层和服务治理能力，本项目个人觉得定位是偏业务快速开发和构建，其实可以很好的融合，1+1>2的效果，可能这样整体解决方案在市场还没有出现，例如可以和kratos结合下，改造量也不大，也是除了gf-vue-admin外的另个示范，个人感觉gf框架有点强制性风格绑定和基础组件绑定，做单体没问题，做微服务在各个具体项目中不灵活，提个建议，望团队参考，本人也可贡献部分力量。

**Comment by piexlmax** [comment]
微服务版本不考虑制作开源版了，见谅。

**Comment by West121** [comment]
> 微服务版本不考虑制作开源版了，见谅。

微服务版本的现在有吗，可以购买吗？

**Comment by West121** [comment]
> > 微服务版本不考虑制作开源版了，见谅。
> 
> 微服务版本的现在有吗，可以购买吗？

@piexlmax
