### ISSUE TITLE
[Bug]: api管理创建/更新api数据没有进行校验

### ISSUE THREAD

**Issue by ZQCard** [flipped-aurora/gin-vue-admin#1217]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

 api管理创建/更新api数据没有进行校验，开源随意输入Path和Method

### 修改建议

将操作的api进行校验

**Comment by piexlmax** [comment]
存在先输入api再完善后端接口的情况，将不会进行校验操作。
