### ISSUE TITLE
[Bug]: gin-vue-admin存在安全漏洞

### ISSUE THREAD

**Issue by 0xngs** [flipped-aurora/gin-vue-admin#1220]
### gin-vue-admin 版本

v2.5.3b

### Node 版本

16

### Golang 版本

go1.19.1

### 是否依旧存在

可以

### bug描述

详情已发送至邮箱

### 修改建议

进行限制即可

**Comment by piexlmax** [comment]
此漏洞可以理解为在配置错误的情况下才可以触发，利用难度较大，配置文件配置页面一般为内部且高权限人员使用，不对外开放，我们内部会对此漏洞进行讨论。

0xngs ***@***.***> 于2022年9月18日周日 22:28写道：

**Comment by 0xngs** [comment]
我认为还是需要结合一下实际产生的危害，不能因为此功能只对高权限用户开放就认定不会产生影响（某些弱口令，权限分配错误）都会导致问题产生。当然认不认可，最后还是尊重你们内部讨论的结果哈。

**Comment by 0xngs** [comment]
> 此漏洞可以理解为在配置错误的情况下才可以触发，利用难度较大，配置文件配置页面一般为内部且高权限人员使用，不对外开放，我们内部会对此漏洞进行讨论。

我认为还是需要结合一下实际产生的危害，不能因为此功能只对高权限用户开放就认定不会产生影响（某些弱口令，权限分配错误）都会导致问题产生。当然认不认可，最后还是尊重你们内部讨论的结果哈。
