### ISSUE TITLE
[Bug]: validator.go 判断中文字符串长度错误

### ISSUE THREAD

**Issue by FanYiboaa** [flipped-aurora/gin-vue-admin#1221]
### gin-vue-admin 版本

v2.5.3b

### Node 版本

v16.17.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

1.当判断字符串长度时，中文字符串长度为3，会导致判断错误

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1222
