### ISSUE TITLE
[Bug]: c.ShouldBind应处理错误，而不是忽略

### ISSUE THREAD

**Issue by myface-wang** [flipped-aurora/gin-vue-admin#1224]
### gin-vue-admin 版本

2.5.3

### Node 版本

v16.16.0

### Golang 版本

go 1.19.1

### 是否依旧存在

可以

### bug描述

项目中所有接口参数转结构体均忽略错误，类似：
_ = c.ShouldBindJSON(&user)
若转换产生错误，将导致所有传参丢失，从而导致查询数据库条件不可预测

例1，如何触发：结构体int类型，但传参NaN，（前端Number()转换产生错误）
例2，会发生的问题：若参数含有page，pagesize，解析错误后，其值也会丢失，导致sql查询不再分页，查询所有

### 修改建议

建议处理该错误

**Comment by songzhibin97** [comment]
底下有自定义校验器

**Comment by piexlmax** [comment]
体力活，可以统一处理下，拦截解析失败场景。
