### ISSUE TITLE
[Bug]: request api twice

### ISSUE THREAD

**Issue by wangjintianya** [flipped-aurora/gin-vue-admin#1227]
### gin-vue-admin 版本

2.4.5beta

### Node 版本

v14.16.0

### Golang 版本

go1.16

### 是否依旧存在

可以

### bug描述

request api twice
![image](https://user-images.githubusercontent.com/15353320/191714557-f19a7b7c-b586-40ca-a467-0a135b3dfd13.png)

### 修改建议

无

**Comment by piexlmax** [comment]
收到，尝试复现排查。

**Comment by piexlmax** [comment]
可否提供下版本以及复现步骤，目前无法复现
