### ISSUE TITLE
[Feature]: 怎么安全的访问图片等资源文件，目前就是以公共的方式访问，这样未经授权就可以遍历目录访问所有文件。

### ISSUE THREAD

**Issue by athmoon** [flipped-aurora/gin-vue-admin#1233]
### 功能描述以及必要性描述

怎么安全的访问图片等资源文件，目前就是以公共的方式访问，这样未经授权就可以遍历目录访问所有文件。对有权限的用户生成一个临时访问链接，这样就无法遍历。公共资源也是临时访问链接的话，那就等同于防盗链了。

**Comment by piexlmax** [comment]
目前还没制作相关功能，纳入开发计划。

**Comment by Asura-one** [comment]
可以试试这个方法 https://github.com/gin-gonic/gin/issues/2645
