### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ilylx** [flipped-aurora/gin-vue-admin#1239]
### gin-vue-admin 版本

2.5.4

### Node 版本

v14

### Golang 版本

go 1.17

### 是否依旧存在

未测试

## 1
* 'zap.prefix' expected type 'string', got unconvertible type '[]interface {}', value: '[github.com/flipped-aurora/gin-vue-admin/server]'

## 2

go: finding module for package github.com/swaggo/gin-swagger/swaggerFiles
github.com/flipped-aurora/gin-vue-admin/server/initialize imports
        github.com/swaggo/gin-swagger/swaggerFiles: module github.com/swaggo/gin-swagger@latest found (v1.5.3), but does not contain package github.com/swaggo/gin-swagger/swaggerFiles
main.go:13: running "go": exit status 1

https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/initialize/router.go
"github.com/swaggo/gin-swagger/swaggerFiles"
这个包貌似没有了

## 3
有俩输出
无鉴权插件安装==》 &{[0x18e7e60 0x18e8ca0] / 0xc00016cea0 false}
鉴权插件安装==》 &{[0x18e7e60 0x18e8ca0] / 0xc00016cea0 false}

**Comment by piexlmax** [comment]
执行go get 拉取对应缺失包即可，本体mod无改动情况下无法复现。
