### ISSUE TITLE
[Bug]: 自动创建数据库失败!     {"error": "错误: 语法错误 在 \"-\" 或附近的 (SQLSTATE 42601)"}

### ISSUE THREAD

**Issue by ciscolive** [flipped-aurora/gin-vue-admin#1244]
### gin-vue-admin 版本

最新版

### Node 版本

v14.16

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

无法初始化成功

```ruby
o:34    自动创建数据库失败!     {"error": "错误: 语法错误 在 \"-\" 或附近的 (SQLSTATE 42601)"}
[github.com/flipped-aurora/gin-vue-admin/server]2022/10/10 - 10:58:22.289       error   D:/golang/gin-vue-admin/server/api/v1/system/sys_initdb.go:34    自动创建数据库失败!     {"error": "错误: 语法错误 在 \"-\" 或附近的 (SQLSTATE 42601)"}
[GIN] 2022/10/10 - 10:58:22 | 200 |         6m33s |       127.0.0.1 | POST     "/init/initdb"
[GIN] 2022/10/10 - 10:58:22 | 200 |     8.733174s |       127.0.0.1 | POST     "/init/initdb"

```

### 修改建议

无法初始化成功
```ruby
o:34    自动创建数据库失败!     {"error": "错误: 语法错误 在 \"-\" 或附近的 (SQLSTATE 42601)"}
[github.com/flipped-aurora/gin-vue-admin/server]2022/10/10 - 10:58:22.289       error   D:/golang/gin-vue-admin/server/api/v1/system/sys_initdb.go:34    自动创建数据库失败!     {"error": "错误: 语法错误 在 \"-\" 或附近的 (SQLSTATE 42601)"}
[GIN] 2022/10/10 - 10:58:22 | 200 |         6m33s |       127.0.0.1 | POST     "/init/initdb"
[GIN] 2022/10/10 - 10:58:22 | 200 |     8.733174s |       127.0.0.1 | POST     "/init/initdb"

```

**Comment by SliverHorn** [comment]
什么数据库，什么版本？

**Comment by mngogo** [comment]
我也卡在初始化數據報錯。 數據庫裏只生成兩個表，報錯信息說不認 nick_name.  刪除表再操作。就沒用。手動填寫config后， server端。報錯  只允許配置 一個端口 socket， 而實際檢查出 8888 . 
數據庫版本都正常。目測是你的初始化裏bug。 和配置服務端口有點邏輯鎖死了

**Comment by piexlmax** [comment]
> 我也卡在初始化數據報錯。 數據庫裏只生成兩個表，報錯信息說不認 nick_name. 刪除表再操作。就沒用。手動填寫config后， server端。報錯 只允許配置 一個端口 socket， 而實際檢查出 8888 . 數據庫版本都正常。目測是你的初始化裏bug。 和配置服務端口有點邏輯鎖死了

提供数据库类型和版本以及操作方式。

**Comment by YunxiGuo** [comment]
我这边也碰到该问题了,
数据库:postgres14
服务器操作系统:linux
CPU架构:arm64
部署方式:docker
操作:调用初始化数据库,提示"自动创建数据库失败",输入信息如下
{
  "dbName": "gva",
  "dbType": "pgsql",
  "host": "192.168.53.207",
  "password": "xxx",
  "port": "5432",
  "userName": "xxx"
}
错误信息如下:
/server/api/v1/system/sys_initdb.go:34  自动创建数据库失败!     {"error": "ERROR: syntax error at or near \"-\" (SQLSTATE 42601)"}

注:在本地调试运行时,能成功创建数据库

**Comment by piexlmax** [comment]
> 

如果不在docker中的话是可以的对吗 我构建一套环境复现修补

**Comment by ccxdd** [comment]
数据库:postgres14
操作系统:macOS
GO:1.22.1

也是遇到这个问题了，还没解决吗?
