### ISSUE TITLE
[Feature]: 使用SQLite3，登录的时候后台提示no such column admin

### ISSUE THREAD

**Issue by albinhdk** [flipped-aurora/gin-vue-admin#1256]
### 功能描述以及必要性描述

1、打印了后台SQL
SELECT * FROM `sys_users` WHERE username = "admin" AND `sys_users`.`deleted_at` IS NULL ORDER BY `sys_users`.`id` LIMIT 1;
SELECT * FROM `sys_users` WHERE username = 'admin' AND `sys_users`.`deleted_at` IS NULL ORDER BY `sys_users`.`id` LIMIT 1;
第一条是系统打印，在navicat里执行，就会提示no such column admin。导致总是无法查到用户，no record。
2、目前还不会使用SQlite3初始化数据，我用mysql的初始化数据一个一个执行SQL来做的，感觉还有些问题
3、比如对于时间CREATE_AT，SQLite3是用的text，这个就需要在数据库连接里添加&parseTime=true

### 建议和方案

能否提供一个SQLite3的初始化数据文件？

**Comment by SliverHorn** [comment]
无法提供，团队人力有限，只能适配与维护mysql与postgresql数据库，其他数据库自行匹配并解决对应的报错
