### ISSUE TITLE
[Feature]: 路由Layout可自定义

### ISSUE THREAD

**Issue by Znonymous29** [flipped-aurora/gin-vue-admin#1257]
### 功能描述以及必要性描述

前端新增路由均为`view/layout/index.vue`的嵌套路由，不能灵活自定义layout页面。

### 建议和方案

可以在菜单页面新增layout选项，并相应调整数据库相关数据。可以自己定义layout页面，这样方便创建更多自定义页面。

**Comment by Znonymous29** [comment]
刚仔细看了一下代码，请问是不是后端`SysBaseMenu`里面`Meta`中的`DefaultMenu 是否是基础路由（开发中）`是准备实现类似的路由定义功能吗？

**Comment by piexlmax** [comment]
此功能原本计划为前端修改router添加 不经过后端

**Comment by piexlmax** [comment]
已采纳 感谢issue和pr
