### ISSUE TITLE
[Bug]: vite依赖冲突

### ISSUE THREAD

**Issue by DomineCore** [flipped-aurora/gin-vue-admin#1259]
### gin-vue-admin 版本

2.4.x

### Node 版本

v16.18.0

### Golang 版本

go 1.18.3

### 是否依旧存在

可以

### bug描述

有一些依赖冲突
<img width="669" alt="image" src="https://user-images.githubusercontent.com/50765823/196154212-f268fb3a-905b-47b7-ad4d-399cc47f1e27.png">

**Comment by piexlmax** [comment]
将会在后续版本调整修复
