### ISSUE TITLE
自动代码生成器： 服务端多了一个花括号，server/model/autocode.go

### ISSUE THREAD

**Issue by tangx** [flipped-aurora/gin-vue-admin#126]
# 代码如下

自动代码生成器： 服务端多了一个花括号，server/model/autocode.go

```go
// 如果含有time.Time 请自行import time包
type Record struct {
      gorm.Model
      Domain  string `json:"domain" form:"domain" gorm:"column:domain;comment:'domain'"`
      RR  string `json:"rr" form:"rr" gorm:"column:解析记录名称;comment:'rr'"`
      Value  string `json:"value" form:"value" gorm:"column:value;comment:'解析记录值'"`
      TTL  int `json:"ttl" form:"ttl" gorm:"column:ttl;comment:'ttl'"`
      Enabled  *bool `json:"enabled" form:"enabled" gorm:"column:enabled;comment:'是否生效'"`
      Comment  string `json:"comment" form:"comment" gorm:"column:comment;comment:'解析记录描述信息'"` 
}
}

```

**Comment by piexlmax** [comment]
感谢 我马上修改 可能是昨天的pr导致 感谢

**Comment by piexlmax** [comment]
> # 代码如下
> 自动代码生成器： 服务端多了一个花括号，server/model/autocode.go
> 
> ```go
> // 如果含有time.Time 请自行import time包
> type Record struct {
>       gorm.Model
>       Domain  string `json:"domain" form:"domain" gorm:"column:domain;comment:'domain'"`
>       RR  string `json:"rr" form:"rr" gorm:"column:解析记录名称;comment:'rr'"`
>       Value  string `json:"value" form:"value" gorm:"column:value;comment:'解析记录值'"`
>       TTL  int `json:"ttl" form:"ttl" gorm:"column:ttl;comment:'ttl'"`
>       Enabled  *bool `json:"enabled" form:"enabled" gorm:"column:enabled;comment:'是否生效'"`
>       Comment  string `json:"comment" form:"comment" gorm:"column:comment;comment:'解析记录描述信息'"` 
> }
> }
> ```

已修复
