### ISSUE TITLE
[Bug]: gin-vue-admin存在安全漏洞

### ISSUE THREAD

**Issue by 0xngs** [flipped-aurora/gin-vue-admin#1263]
### gin-vue-admin 版本

v2.5.4

### Node 版本

16

### Golang 版本

go1.19.1

### 是否依旧存在

可以

### bug描述

已发邮件

**Comment by piexlmax** [comment]
已确认，将开启sec，请填充sec内容，感谢。

**Comment by piexlmax** [comment]
漏洞已修复 填充sec后，将申请CVE且发布。
