### ISSUE TITLE
[Bug]: 自定义接口权限不足

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1265]
### gin-vue-admin 版本

v2.5.4b main

### Node 版本

v16.15.0

### Golang 版本

go version go1.18.1 windows/amd64

### 是否依旧存在

可以

### bug描述

自定义接口权限不足：
1. 编写接口文件，重新运行，可以在路径接口看到；
2. 【api管理】添加api；
3. 【角色管理】api赋权，可以在casbin_rule表看到权限情况；
4. 前端调用，{"code":7,"data":{},"msg":"权限不足"}

### 修改建议

暂不确定

**Comment by bypanghu** [comment]
删除api前后空格

发自我的iPhone

**Comment by cffycls** [comment]
果然，多谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月24日(星期一) 晚上6:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flipped-aurora/gin-vue-admin] [Bug]: 自定义接口权限不足 (Issue #1265)





 删除api前后空格
 
 发自我的iPhone
 
 &gt; 在 2022年10月24日，18:36，cffycls ***@***.***&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; Assigned #1265 to @bypanghu.
 &gt; 
 &gt; —
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; You are receiving this because you were assigned.
