### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wwgtowei** [flipped-aurora/gin-vue-admin#1266]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v16.18.0

### Golang 版本

go 1.19.2

### 是否依旧存在

可以

### bug描述

前端“系统配置/Redis admin数据库/库"修改后更新报错如下：
![微信图片_20221024185551](https://user-images.githubusercontent.com/71633947/197511409-e1b54793-9ce5-4828-91ed-5738f0314b1b.jpg)

### 修改建议

![微信截图_20221024185658](https://user-images.githubusercontent.com/71633947/197511477-de3bb77e-3fcf-4f53-bf97-ee44e787cd87.png)

文件“gin-vue-admin/web/src/view/systemTools/system/system.vue”中第90行修改为“<el-input v-model.number="config.redis.db" />”可以解决

**Comment by bypanghu** [comment]
收到，已在 pr (https://github.com/flipped-aurora/gin-vue-admin/pull/1267)中修复，感谢。本issue 将关闭。
