### ISSUE TITLE
[Bug]: 显示时区错乱

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1274]
### gin-vue-admin 版本

v2.5.4b

### Node 版本

v16.15.0

### Golang 版本

go version go1.18.1 windows/amd64

### 是否依旧存在

可以

### bug描述

1. 数据库已配置时区：default-time_zone = '+8:00'，但是接口查询`2022-12-29 06:00:00`会带上 TZ `2022-12-29T06:00:00Z`（明明去掉这2个字母就正常的）。这个数据是外部服务接口来的，而系统数据表的时间是0时区（看到 sys_operation_records，显示时+8），安装时未说明数据库需要0时区呀。这里很混乱，改怎么处理

### 修改建议

不确定，但感觉应该默认统一数据库时区到 +8 时区，接口不应该修改时间、力求时间的查询、修改所见即所得【兼容外部服务、接口调用】

**Comment by songzhibin97** [comment]
服务器时区和数据库时区保持一致

**Comment by cffycls** [comment]
> 服务器时区和数据库时区保持一致

服务器和数据库都是+8时区，是系统表的不正常

**Comment by piexlmax** [comment]
2022-12-29T06:00:00Z  这是时间标准格式 格林尼治时间  一切都会以标准化运行
