### ISSUE TITLE
[Bug]: 请教下关于刷新页面报警告的问题

### ISSUE THREAD

**Issue by beclass** [flipped-aurora/gin-vue-admin#1282]
### gin-vue-admin 版本

2.4.5

### Node 版本

v18.12.1

### Golang 版本

1.17

### 是否依旧存在

未测试

### bug描述

本地pnpm i 然后启动，登陆后再刷新当前页面报这个警告
<img width="669" alt="image" src="https://user-images.githubusercontent.com/12541388/201690846-cffcf2f1-b3ca-4240-9fae-792378825940.png">

**Comment by beclass** [comment]
加上 :key="$route.name" 也不行呀

**Comment by bypanghu** [comment]
因为是动态路由，在页面转跳的时候进入 router 的钩子函数，第一次进入其实没有路由数组，所以会弹出这个警告。没有路由数组会去后端获取路由数组并组装，所以 可以无视这个

**Comment by beclass** [comment]
ok   看了网上一些办法也都不行😂
