### ISSUE TITLE
[Feature]: 分包更彻底

### ISSUE THREAD

**Issue by Ylarod** [flipped-aurora/gin-vue-admin#1285]
### 功能描述以及必要性描述

目前生成的前端代码，都放在 `src/api` 和 `src/view` 下面

如果需要代码生成一个用户表 `user`，会提示 `api/user.js` 已存在，无法生成

### 建议和方案

1. 将前端代码生成到各自包下
2. 在注册router时添加对应包名作为前缀

**Comment by piexlmax** [comment]
这个问题只能选择自己重命名，分包情况下也会存在分包命名冲突的情况，并不能解决实际问题。
