### ISSUE TITLE
[Bug]: 飞书登录使用tenant key作为默认用户名，会导致同企业下用户飞书注册冲突

### ISSUE THREAD

**Issue by ryetan** [flipped-aurora/gin-vue-admin#1290]
### gin-vue-admin 版本

default

### Node 版本

default

### Golang 版本

default

### 是否依旧存在

不可以

### bug描述

![image](https://user-images.githubusercontent.com/34364785/203306563-b8b75e82-f606-4585-931b-7ea3a6100ce8.png)

代码具体位置 ：server/plugin/fslogin/service/service.go [line 23]

### 修改建议

Username:    FsUserInfo.Email

**Comment by tauycode** [comment]
拼个名字上去就可以避免了

**Comment by piexlmax** [comment]
这里是插件中的方法，可以自行修改为自己需要的name
