### ISSUE TITLE
[Feature]: 请问是否有开发里程碑/计划？

### ISSUE THREAD

**Issue by qiuchengw** [flipped-aurora/gin-vue-admin#1291]
### 功能描述以及必要性描述

首先非常感谢各位大佬的辛苦开源付出。

个人非常喜欢这个项目，也正在基于此项目开发了一个业余项目。在我关注的这段时间里，GVA项目更新还是很活跃的（再次感谢各位的付出），但是并未看到此项目上的一个长期的，明确的  版本/里程碑计划。

请问是否有打算设定一些项目目标/里程碑呢？

### 建议和方案

建议设立开发计划，让关注者知道此项目的开发走向。

**Comment by piexlmax** [comment]
官方团队对于维护不能做到某个时间节点完成某些功能，大家都是非全职维护，因此没有定制目标/里程碑等。

**Comment by qiuchengw** [comment]
> 官方团队对于维护不能做到某个时间节点完成某些功能，大家都是非全职维护，因此没有定制目标/里程碑等。

了解。其实不一定要设定时间节点，主要还是功能性规划。比如下一阶段打算先实现哪些大的功能点等，未来较长时间上希望实现哪些功能点……，这样目标会相对明确一些。
