### ISSUE TITLE
[Bug]: 使用docker-compose部署后，使用admin登录报授权已过期

### ISSUE THREAD

**Issue by wujianqiangwjq** [flipped-aurora/gin-vue-admin#1300]
### gin-vue-admin 版本

2.5.4

### Node 版本

default

### Golang 版本

default

### 是否依旧存在

可以

### bug描述

使用docker-compose部署后，使用admin登录报授权已过期

**Comment by piexlmax** [comment]
配置文件指定错误 jwt未配置正确的时间

**Comment by nightzjp** [comment]
早期的jwt配置没有单位。默认为秒。后期jwt配置加了单位。比如：7d，24h这种。
