### ISSUE TITLE
[Bug]: 每次重啟都會改我數據庫裡的數據表

### ISSUE THREAD

**Issue by kinnyhuang529** [flipped-aurora/gin-vue-admin#1301]
### gin-vue-admin 版本

i18n 最新版

### Node 版本

 v16.17.0

### Golang 版本

go1.19.1

### 是否依旧存在

可以

### bug描述

使用代碼生成工具時都會在gorm.go裡邊寫入struct
為何會需要動我原本數據庫的table？
能否新增一個選項讓他不要動我原來的table
例如我很多數據庫裡的資料類型是text
系統會想把它改成varchar(191)

**Comment by SliverHorn** [comment]
1. main.go 可以自己注释代码关闭同步结构体生成表
2. text改varchar(191) 是因为结构体的字段的gorm tag没写，自己看看gorm.io或者gorm.cn
