### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by passerbyon** [flipped-aurora/gin-vue-admin#1303]
### gin-vue-admin 版本

2.5.4

### Node 版本

v16.18.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

在exa_breakpoint_continue.go的67行
`Delete(&chunks).Unscoped()`
Unscoped()方法放到Delete()之后，执行的Update语句
`Unscoped().Delete(&chunks)`
放到Delete()之前，执行的就是Delete语句，我遇到的是这种情况，有些搞不明白

**Comment by bypanghu** [comment]
请自行看gorm文档 参考地址 gorm.io

发自我的iPhone
