### ISSUE TITLE
[Feature]: 注册API时，自动导入数据库

### ISSUE THREAD

**Issue by HuskarTang** [flipped-aurora/gin-vue-admin#1319]
### 功能描述以及必要性描述

1，无需手动注册API，自动化程度更高，用户使用更方便，用户只需要管理授权即可
2，解耦开发环境和线上环境，关于API管理的数据库，无需进行数据库迁移（这个在迭代更新时，很麻烦）

### 建议和方案

1，服务初始化过程中，后端向gin router注册API时，自动适配到数据库记录（自动增删）

**Comment by piexlmax** [comment]
有好的方案可以pr，无法采用建议方案，没办法对api做归类区分和描述。

**Comment by snans** [comment]
可以在“超级管理员”-“api管理”中添加一个“批量新增”的功能，开发人员根据规则导入即可。
简单点么就用个textarea，由开发人员往里复制csv格式的搞一搞就行了，例如：
```csv
/test/getList,post,test,获取列表
/test/getData,post,test,获取数据
/test/createData,post,test,新增数据
/test/updateData,post,test,更新数据
/test/deleteData,post,test,删除数据
```

**Comment by zztdandan** [comment]
建议在api管理界面，创建api时根据之前的做法，在各个文件对应创建对应代码，只到router层和apic层。否则创建api要在多个层级操作，略为麻烦

**Comment by ccfish86** [comment]
自动导入API，是可行的，只是目前的swagger方案比较难实现。
我APP端的接口使用的是另一大API（openapi v3）的接口文档方案，是通过反射生成的API文档，同时应该也可以在启动的时候，追加回调方法，往数据库里写接口。
接口定义，如图：
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/15622514/19834994-2676-41dc-911c-b9f3ec9d180f)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/15622514/c214007a-a156-401d-a9eb-eab1de6929ce)

**Comment by pixelmaxQm** [comment]
目前添加了表格导入功能来暂时支持本问题，自动注册同步产生较多的连锁反应因此无法采纳。
