### ISSUE TITLE
[Bug]: 单元测试尝试初始化gorm会出现循环依赖的问题

### ISSUE THREAD

**Issue by HuskarTang** [flipped-aurora/gin-vue-admin#1320]
### gin-vue-admin 版本

2.5.3

### Node 版本

8.19.2

### Golang 版本

go 1.19.0

### 是否依旧存在

可以

### bug描述

在service添加业务逻辑后，添加单元测试，如果单元测试中依赖数据库访问，那么不管是在业务模块中添加数据库初始化（引用initialize相关初始化接口）还是在测试套件中添加数据库初始化，都会出现循环依赖的问题。

### 修改建议

将组件（数据库，viper，redis，zap等）初始化接口移动到core目录下，业务流程初始化放到initialize下，这样service层单元测试初始化组件时，引用core包，就不会出现循环依赖。

**Comment by piexlmax** [comment]
单元测试自行创建单测所需依赖数据库等，理论上也不应使用业务库进行测试。
