### ISSUE TITLE
点击搜索图标，展开下拉后，跳转浏览器窗口后返回，下拉菜单仍显示[Bug]: 

### ISSUE THREAD

**Issue by 292435** [flipped-aurora/gin-vue-admin#1321]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

1.点击头部搜索图标展示下拉菜单
2.切换到浏览器其他窗口页面
3.切回到项目窗口、下拉菜单显示在左上角。而搜索框已隐藏

### 修改建议

无

**Comment by piexlmax** [comment]
将会在主干尝试复现并修复。

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/9092d3ba693c0bb559c54d3d97bf8eba26d6b03f
