### ISSUE TITLE
[Feature]: 配置不使用CDN

### ISSUE THREAD

**Issue by TangJinJian** [flipped-aurora/gin-vue-admin#1326]
### 功能描述以及必要性描述

项目部署在内网，无法访问CDN的资源。是否有地方可以配置，不使用CDN资源？

**Comment by piexlmax** [comment]
新版本无任何cdn使用了呀

**Comment by TangJinJian** [comment]
> 新版本无任何cdn使用了呀

那老版本，怎么优雅的去除CDN呢？

**Comment by piexlmax** [comment]
直接把整个数组清空 然后npm i 安装里面的这些依赖
