### ISSUE TITLE
在python3下npm install 会报错

### ISSUE THREAD

**Issue by chenyingqiao** [flipped-aurora/gin-vue-admin#133]
/usr/bin/python -c "import sys;print '%s.%s.%s' % sys.version_info[:3];"
![image](https://user-images.githubusercontent.com/8207331/86526910-552f7200-becc-11ea-9b22-922afea68f65.png)

主要是print写法不兼容

**Comment by piexlmax** [comment]
sass问题 可以更换成sass-node 这个我下个版本调换一下
