### ISSUE TITLE
[Bug]: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hxs9712** [flipped-aurora/gin-vue-admin#1330]
### gin-vue-admin 版本

2.5.5

### Node 版本

v16.15.0

### Golang 版本

go 1.19.4

### 是否依旧存在

可以

### bug描述

项目clone到本地后，按照教程成功跑起来了前端和后端，登录也是正常的，但是登录后调取/api/menu/getMenu时报了runtime error: invalid memory address or nil pointer dereference；整体报错如下：
2023/01/06 15:58:09 [Recovery] 2023/01/06 - 15:58:09 panic recovered:
POST /menu/getMenu HTTP/1.1
Host: 127.0.0.1:8888
Connection: close
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: close
Content-Length: 0
Cookie: Phpstorm-63d925b2=f588192d-8c21-425e-950d-31dc42d55d24; Hm_lvt_a046ce178828e393614822a297b8d296=1654849395
Origin: http://localhost:8080
Referer: http://localhost:8080/
Sec-Ch-Ua: "Not?A_Brand";v="8", "Chromium";v="108", "Microsoft Edge";v="108"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.42
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiNDUyNjM4NzQtMDMwNC00MGFkLThhNzgtYmZjMjIzOTY2ZDI4IiwiSUQiOjEsIlVzZXJuYW1lIjoiYWRtaW4iLCJOaWNrTmFtZSI6Ik1yLuWlh-a3vCIsIkF1dGhvcml0eUlkIjo4ODgsIkJ1ZmZlclRpbWUiOjg2NDAwLCJleHAiOjE2NzM1OTY2MjIsImlzcyI6InFtUGx1cyIsIm5iZiI6MTY3Mjk5MDgyMn0.VX3AaldrhE9Fb803FguO1zjO-rwETe0KvHNllqfpb8k
X-User-Id: undefined

runtime error: invalid memory address or nil pointer dereference
C:/work/Go/src/runtime/panic.go:260 (0x86c7b5)
        panicmem: panic(memoryError)
C:/work/Go/src/runtime/signal_windows.go:255 (0x86c785)
        sigpanic: panicmem()
C:/work/Go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.7.3/adapter.go:466 (0x113ea80)
        (*Adapter).IsFiltered: return a.isFiltered
C:/work/Go/pkg/mod/github.com/casbin/casbin/v2@v2.51.0/enforcer.go:178 (0x133384a)
        (*Enforcer).InitWithModelAndAdapter: if e.adapter != nil && (!ok || ok && !fa.IsFiltered()) {
C:/work/Go/pkg/mod/github.com/casbin/casbin/v2@v2.51.0/enforcer.go:115 (0x13332c5)
        NewEnforcer: err := e.InitWithModelAndAdapter(p0.(model.Model), params[1].(persist.Adapter))
C:/work/Go/pkg/mod/github.com/casbin/casbin/v2@v2.51.0/enforcer_cached.go:42 (0x133670b)
        NewCachedEnforcer: e.Enforcer, err = NewEnforcer(params...)
C:/work/Go_Workpace/go-server/gin-vue-admin/server/service/system/sys_casbin.go:129 (0x134dc84)
        (*CasbinService).Casbin.func1: cachedEnforcer, _ = casbin.NewCachedEnforcer(m, a)
C:/work/Go/src/sync/once.go:74 (0x893f41)
        (*Once).doSlow: f()
C:/work/Go/src/sync/once.go:65 (0x134dd10)
        (*Once).Do: o.doSlow(f)
C:/work/Go_Workpace/go-server/gin-vue-admin/server/service/system/sys_casbin.go:106 (0x134dcf4)
        (*CasbinService).Casbin: once.Do(func() {
C:/work/Go_Workpace/go-server/gin-vue-admin/server/middleware/casbin_rbac.go:25 (0x15d0ba4)
        CasbinHandler.func1: e := casbinService.Casbin() // 判断策略中是否存在
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0x15d156a)
        (*Context).Next: c.handlers[c.index](c)
C:/work/Go_Workpace/go-server/gin-vue-admin/server/middleware/jwt.go:77 (0x15d13c8)
        JWTAuth.func1: c.Next()
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0x12afe01)
        (*Context).Next: c.handlers[c.index](c)
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/recovery.go:99 (0x12afdec)
        CustomRecoveryWithWriter.func1: c.Next()
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/context.go:165 (0x12aef46)
        (*Context).Next: c.handlers[c.index](c)
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/logger.go:241 (0x12aef29)
        LoggerWithConfig.func1: c.Next()
        (*Context).Next: c.handlers[c.index](c)
        (*Engine).handleHTTPRequest: c.Next()
C:/work/Go/pkg/mod/github.com/gin-gonic/gin@v1.7.0/gin.go:445 (0x12ad824)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
C:/work/Go/src/net/http/server.go:2947 (0xb50b2b)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
C:/work/Go/src/net/http/server.go:1991 (0xb4bd46)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
C:/work/Go/src/runtime/asm_amd64.s:1594 (0x887440)
        goexit: BYTE    $0x90   // NOP

**Comment by hxs9712** [comment]
请大佬协助，万分感谢

**Comment by piexlmax** [comment]
> 已解决，是因为casbin_rule这张表创建索引时索引长度太长导致的

文档有些此常见问题，数据库表引擎类型不是innodb导致
