### ISSUE TITLE
[Bug]: 关于前端项目的格式化与eslint问题

### ISSUE THREAD

**Issue by justfeizai** [flipped-aurora/gin-vue-admin#1331]
### gin-vue-admin 版本

v2.5.5

### Node 版本

18.13.0

### Golang 版本

1.19.4

### 是否依旧存在

可以

### bug描述

保存文件格式化报错，和prettier与vetur的配置均有冲突，导致代码一大片的报错

### 修改建议

可以补充一下相关的配置文件

**Comment by piexlmax** [comment]
将会下个版本做出调整，大致方向将以vetur配置为主导。

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commits/main
