### ISSUE TITLE
swag init ERROR

### ISSUE THREAD

**Issue by LiQingMuBai** [flipped-aurora/gin-vue-admin#134]
cd server and run "swag init"

**ERROR MESSAGE**
`ParseComment error in file api/v1/sys_dictionary_detail.go :cannot find type definition: gorm.Model`

**Comment by piexlmax** [comment]
请先设置goland或者当前项目为go.mod模式 然后通过mod模式把依赖下载完成 并且在goland工具或者当前mod模式下进行性 swag init

**Comment by zhaojingadmin** [comment]
小白菜一颗，能不能说的仔细点，我在mod 模式下执行swag init 还是报以上错误

**Comment by softmaxs** [comment]
@zhaojingadmin 我也遇到生成文档失败，环境 go version go1.15.3 ubuntu 20,你有解决这问题没？求指点！
