### ISSUE TITLE
gva有办法平滑升级到最新版本吗？

### ISSUE THREAD

**Issue by hapihacking** [flipped-aurora/gin-vue-admin#1344]
### 功能描述以及必要性描述

项目仍然在使用2021年年底的某个版本，目前运转良好。刚刚看到2022年的release又多了很多新功能，想要升级到最新版本，但是这类脚手架我不知道有没有办法做到平滑升级呢？

**Comment by piexlmax** [comment]
存在大版本更新的情况下无法平滑升级了，小版本可以。

**Comment by hapihacking** [comment]
好的喔，谢谢啦，我们确实把项目里改的太多了，下午把release细细看了一遍，很多功能我们也重复实现了一遍，如果能一直跟着大版本改就好了。现在估计是迁移不动了。
