### ISSUE TITLE
[Bug]: 个人信息页更新

### ISSUE THREAD

**Issue by tauycode** [flipped-aurora/gin-vue-admin#1347]
### gin-vue-admin 版本

main

### Node 版本

v16.16.0

### Golang 版本

go1.19

### 是否依旧存在

可以

### bug描述

个人信息页person.vue,设置昵称和头像更新的时候，会把用户的相关信息给重置掉。比如enable会被置为0等。
const res = await setSelfInfo({
    nickName: nickName.value,
 });

func (b *BaseApi) SetSelfInfo(c *gin.Context) {
	var user systemReq.ChangeUserInfo
	err := c.ShouldBindJSON(&user)
	if err != nil {
		response.FailWithMessage(err.Error(), c)
		return
	}
	user.ID = utils.GetUserID(c)
	err = userService.SetUserInfo(system.SysUser{
		GVA_MODEL: global.GVA_MODEL{
			ID: user.ID,
		},
		NickName:  user.NickName,
		HeaderImg: user.HeaderImg,
		Phone:     user.Phone,
		Email:     user.Email,
		SideMode:  user.SideMode,
		Enable:    user.Enable,
	})
	if err != nil {
		global.GVA_LOG.Error("设置失败!", zap.Error(err))
		response.FailWithMessage("设置失败", c)
		return
	}
	response.OkWithMessage("设置成功", c)
}

**Comment by piexlmax** [comment]
纳入修复计划

**Comment by piexlmax** [comment]
无法复现

**Comment by tauycode** [comment]
请看下 fix:修复用户管理手机号邮箱无法置空bug (https://github.com/flipped-aurora/gin-vue-admin/pull/1339)
@piexlmax

**Comment by piexlmax** [comment]
个人中心页面调用的是非map的，我检查下设置用户信息这里产生的问题。

**Comment by piexlmax** [comment]
已经在主干修复
