### ISSUE TITLE
[Bug]:  新项目初始化登录报错

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1348]
### gin-vue-admin 版本

v2.5.5

### Node 版本

v16.19.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

1. git clone项目（切换到`2.5.4升级为2.5.5`这里也一样），运行；
2. 初始化连接数据库；
3. 登录 admin/123456 ，报错：runtime error: invalid memory address or nil pointer dereference

**Comment by piexlmax** [comment]
https://www.gin-vue-admin.com/guide/introduce/project.html#%E6%8A%80%E6%9C%AF%E9%80%89%E5%9E%8B  注意数据库引擎 innodb

**Comment by cffycls** [comment]
本地phpstudy mysql确实默认启动的不是 innodb

**Comment by Chopper8888** [comment]
> 本地phpstudy mysql确实默认启动的不是 innodb

确实，我也是这个问题，把mysql的默认引擎改下就好了
