### ISSUE TITLE
post接收数据绑定问题

### ISSUE THREAD

**Issue by lu569368** [flipped-aurora/gin-vue-admin#136]
我在使用代码的时候发现版主用的是ShouBindldJSON我是用postman提交数据的时候无法绑定，但是使用Bind就没有问题，个人意见。版主的代码写的不错非常赞

**Comment by piexlmax** [comment]
> 我在使用代码的时候发现版主用的是ShouBindldJSON我是用postman提交数据的时候无法绑定，但是使用Bind就没有问题，个人意见。版主的代码写的不错非常赞

ShouBindldJSON是从body中raw获取json字符串绑定 Headers中Content-Type 设置为 application/x-www-form-urlencoded 即可 

bind默认是从form中获取 获取的格式为form-data 这个需要做一下区分的~ 感谢提出issues
