### ISSUE TITLE
[warn]:  管理后台路由warn提示

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1361]
### gin-vue-admin 版本

v2.5.5

### Node 版本

v16.19.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

管理后台前端warn提示（每打开一个页面都有），如：
```
[Vue Router warn]: No match found for location with path "/layout/dashboard"
[ECharts] DEPRECATED: textStyle hierarchy in axisLabel has been removed since 4.0. All textStyle properties are configured in axisLabel directly now.
```

### 修改建议

去除提示

**Comment by piexlmax** [comment]
不影响使用，但我们尽快处理。

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/4bcd35220a76579a0743ea755abfff989d0e70ab
