### ISSUE TITLE
[Bug]: panic: handlers are already registered for path 'xxx'

### ISSUE THREAD

**Issue by yehao-li** [flipped-aurora/gin-vue-admin#1362]
### gin-vue-admin 版本

2.5.5

### Node 版本

v18.14.2

### Golang 版本

go 1.20.1

### 是否依旧存在

可以

### bug描述

1. 自动化创建struct
2. 删库回滚
3. 创建同名struct
4. 路由注册时报错: panic: handlers are already registered for path 'xxx'
5. 在server/initialize/router.go删除对应的initrouter可以解决

### 修改建议

修改server/initialize/router.go的生成逻辑，在删库回滚时也把这里面的路由注册一并删除

**Comment by yehao-li** [comment]
删库回滚后创建同名struct时，路由注册不再会重复生成，但数据库也不会生成了

**Comment by piexlmax** [comment]
main 修好了
