### ISSUE TITLE
[Bug]: 无法显示网页（一直白屏加载）

### ISSUE THREAD

**Issue by yehao-li** [flipped-aurora/gin-vue-admin#1365]
### gin-vue-admin 版本

2.5.5

### Node 版本

v18.14.2

### Golang 版本

go 1.20.1

### 是否依旧存在

可以

### bug描述

1. 更改菜单中dashboard名（非展示名）为Dashboard（或其他名字）
2. 不可改的路由path也会跟着一起被修改
3. 刷新后无法显示网页（一直白屏加载），但前后端均不报错
4. 修改mysql中对应记录后恢复正常

### 修改建议

dashboard的名字设置为不可更改，或修改路由path跟着一起更改的逻辑

**Comment by piexlmax** [comment]
更改过path，刷新后路由path理论上会跳转到404。

**Comment by yehao-li** [comment]
可能是dashboard默认为起始页路由的原因，我使用的时候是切换了角色，刷新，导致无法加载出任何网页，抱歉没有说明白

**Comment by piexlmax** [comment]
我尝试复现修复，感谢您提出问题。

**Comment by Shiban22** [comment]
gin-vue-admin 同版本2.5.5
go : 1.20
node : 18.15.0
跟随旧厂街项目：banner后端开发视频，添加完角色用户后，只展示轮播图的父级目录。更换了前端banner的目录名字为bannerfish，同样修改菜单路径后，还是无法加载轮播图，又把bannerfish目录名字修改回去，此时重启前台，前台界面一直加载白屏。F12发现报错：e-router.mjs:35 [Vue Router warn]: Unexpected error when starting the router: Error: No match for
 {"name":"dashboard","params":{}}
    at createRouterError (vue-router.mjs:798:23)
    at Object.resolve (vue-router.mjs:1414:23)
    at resolve (vue-router.mjs:3045:38)
    at vue-router.mjs:3179:63
warn @ vue-router.mjs:35
(anonymous) @ vue-router.mjs:3532
Promise.catch (async)
install @ vue-router.mjs:3530
use @ runtime-core.esm-bundler.js:4399
(anonymous) @ main.js:41
后台无报错，前台报错为：22:02:13 [vite] http proxy error at /menu/getMenu:
Error: connect ECONNREFUSED 127.0.0.1:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

**Comment by Xue0919** [comment]
这个问题是什么原因导致的啊，现在有解决吗，我也遇见了同样的问题

**Comment by piexlmax** [comment]
看报错是丢失了默认路由，前端可以处理一下，当默认路由不存在的时候，主动跳转至404.
