### ISSUE TITLE
[Bug]: 表单设计器是用的Variant Form吗？和我之前看的Variant Form 一模一样，但是readme里说用的form-generate

### ISSUE THREAD

**Issue by luojinggit** [flipped-aurora/gin-vue-admin#1366]
### gin-vue-admin 版本

lasted

### Node 版本

v14.18.0

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

表单设计器是用的Variant Form吗？和我之前看的Variant Form 一模一样，但是readme里说用的form-generate，是不是描述错误了

**Comment by piexlmax** [comment]
后续修改了，应该是Variant Form，早期用的form-generate 我尽快调整

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/152f2c40ce91ff516e72f2db18ffc4ae37e33c4f
