### ISSUE TITLE
[Bug]: 无法使用redis

### ISSUE THREAD

**Issue by cffycls** [flipped-aurora/gin-vue-admin#1369]
### gin-vue-admin 版本

2.5.5

### Node 版本

v16.19.1

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

**正常使用redis的set以及get均报错**；例如
```
	AccessTokenKey := "ADMIN-AccessToken"
	redis := global.GVA_REDIS
	if AccessToken := redis.Get(context.Background(), AccessTokenKey); AccessToken != nil {
		fmt.Println(AccessToken)
		return nil
	}
```
`runtime error: invalid memory address or nil pointer dereference`

### 修改建议

完善

**Comment by piexlmax** [comment]
配置开启了吗？

**Comment by cffycls** [comment]
打印redis对象也是空，配置里已添加



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 晚上6:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flipped-aurora/gin-vue-admin] [Bug]: 无法使用redis (Issue #1369)





 
配置开启了吗？

**Comment by cffycls** [comment]
尝试开，好了
