### ISSUE TITLE
[Bug]: 中回滚代码后，不会删除router中的注入，下次生成时会重复注入路由。

### ISSUE THREAD

**Issue by mrhuangyong** [flipped-aurora/gin-vue-admin#1377]
### gin-vue-admin 版本

2.5.5

### Node 版本

v16.19.1

### Golang 版本

1.20.1

### 是否依旧存在

可以

### bug描述

1、[自动化代码管理]中回滚代码后，不会删除router中的注入，下次生成时会重复注入路由。

**Comment by piexlmax** [comment]
是最新的main版本吗？我周末修复的啊。

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/419c677aba06fcea7564221f2629b8ee4e168ff9
