### ISSUE TITLE
[Bug]: 自动化生成代码选择业务库如果存在中划线(-)会导致自动化代码变量命名失败

### ISSUE THREAD

**Issue by piexlmax** [flipped-aurora/gin-vue-admin#1380]
### gin-vue-admin 版本

main

### Node 版本

v16.14.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

选择业务库 业务库名称为 gva-client

会在gorm.go 下生成 go-client := xxxxx 导致代码报错

### 修改建议

自动化代码 gorm.go部分使用之前检测中划线自动剔除并将后面的内容变为大写字母

**Comment by bypanghu** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1382
