### ISSUE TITLE
[Bug]: 自动化代码搜索条件过多，搜索条件不会自动撑开高度，导致不美观。

### ISSUE THREAD

**Issue by piexlmax** [flipped-aurora/gin-vue-admin#1381]
### gin-vue-admin 版本

main

### Node 版本

v16.14.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

![image](https://user-images.githubusercontent.com/29840023/226186991-a8e1e23c-81c9-4822-b6cc-378852d852dc.png)

### 修改建议

使用el-row和el-col对其进行包裹，可以顺带添加响应式span

**Comment by bypanghu** [comment]
doing

**Comment by bypanghu** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1382
