### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by marklinglon** [flipped-aurora/gin-vue-admin#1385]
### gin-vue-admin 版本

main

### Node 版本

v16.13.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

![image](https://user-images.githubusercontent.com/18097531/227109698-8dbca1e5-6271-45ad-9e89-023519dd4c71.png)

### 修改建议

sd

**Comment by bypanghu** [comment]
你怎么安装的？ node 版本，npm版本？有没有代理到其他？例如淘宝？
