### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by lc-c** [flipped-aurora/gin-vue-admin#1399]
### 功能描述以及必要性描述

downloadImage方法为什么需要先用canvas转base64转后下载  请问直接下载有什么弊端吗
  const a = document.createElement('a') // 生成一个a元素
  const event = new MouseEvent('click') // 创建一个单击事件
  a.download = name || 'photo' // 设置图片名称
  a.href = imgsrc // 将生成的URL设置为a.href属性
  a.dispatchEvent(event) // 触发a的单击事件

**Comment by piexlmax** [comment]
个人习惯问题

**Comment by lmb1113** [comment]
直接下载会预览，不会触发下载
