### ISSUE TITLE
casbin AddPolices 会导致角色Policy被全部删除

### ISSUE THREAD

**Issue by hubeidon** [flipped-aurora/gin-vue-admin#1403]
### gin-vue-admin 版本

v2.5.5

### Node 版本

v14

### Golang 版本

go1.18

### 是否依旧存在

可以

### bug描述

![2023-04-01 18-34-07屏幕截图](https://user-images.githubusercontent.com/58875867/229281251-76bc16f2-1b1a-4921-a2f0-abe80ce71e50.png)

更新角色api权限的接口，是先全部删除再添加，但是casbin 的AddPolicies 这个接口有bug。
![2023-04-01 18-26-30屏幕截图](https://user-images.githubusercontent.com/58875867/229281298-310b6357-2556-47c9-9dc7-ebef40e525e5.png)
实际上这个接口是删除policy的。这导致了角色api删除后无法被添加上。

### 修改建议

AddPolicies  -->  AddPolicy

**Comment by tlyyxjz** [comment]
老哥，我也在折腾权限这块，看到你这个"删了加不回来"的情况有点好奇，想多问两句：

1. 出问题的时候，角色原来的权限是已经被清空了吧？清完之后数据库 casbin_rule 表里还留着旧数据不？
2. 报错时 AddPolicies 具体报的什么错呀？是不是那种"重复记录、唯一约束冲突"之类的？
3. 方便说下用的 MySQL 还是别的库、gorm adapter 不？casbin_rule 表有没有主键或者唯一索引？
4. 要是改成一条一条加，是不是只有重复的那几条失败，其他都能加上？

这几个弄清楚了，大概就能看出来是数据重复、索引冲突，还是别的环节的事，蹲个后续～

**Comment by tlyyxjz** [comment]
顺着之前在这帖的排查接着说——我后来把这种「casbin 行为跟预期对不上、但不知道差在哪」的排查思路做成了一个开源小工具：casbin-config-doctor（Python，还有个 Go 版 authztest）。

它的核心不是再封装一遍 enforce，而是当结果不对时告诉你：最接近的那条 policy 是哪条、具体哪个字段（sub/obj/act/dom）没对上、是不是 g 角色继承的问题、有没有 wildcard 误用。像你这个 AddPolicies 之后规则消失的情况，用它跑一遍能很快区分是重复键/唯一索引冲突还是别的原因。

已经开源在 github.com/tlyyxjz/casbin-config-doctor，想不想我拿你这个 case 实际跑一下、看看能不能复现并定位？有需要随时说。
