### ISSUE TITLE
[Feature]: 关于目录结构设计

### ISSUE THREAD

**Issue by LinFeng1987** [flipped-aurora/gin-vue-admin#1408]
### 功能描述以及必要性描述

我是刚学习go 了解到这个非常好的框架，但技术水平有限所以来请教下各位前辈，我们在使用其它语言的时候 会将admin和api的路由和控制器甚至服务层都存放在不同的目录中，当我看了一下go的开源项目后发现几乎市面上大部分的后台管理系统的server项目都不存在前台api的目录设计。请好心前辈帮我这个小白解答一下 谢谢

**Comment by bypanghu** [comment]
其实对于真正的公司服务  admin 和 api 都会分开，并不会部署在一个 框架里面

**Comment by LinFeng1987** [comment]
> 其实际上对真正的公司服务 admin 和 api 都会分开，而不会部属在一个框架里面

原来如此，感谢大佬解惑。
