### ISSUE TITLE
菜单权限和资源权限

### ISSUE THREAD

**Issue by lu569368** [flipped-aurora/gin-vue-admin#141]
查看代码好像用户设置了菜单权限但是好像并不能起作用啊吗

**Comment by piexlmax** [comment]
> 查看代码好像用户设置了菜单权限但是好像并不能起作用啊吗

操作流程  新增菜单--->给角色增加菜单权限--->刷新

**Comment by lu569368** [comment]
这个功能我知道就是添加完菜单权限并没有写入到casbin_rule里面啊！有可能是我理解错了或者大神有其他的思路

**Comment by piexlmax** [comment]
> 这个功能我知道就是添加完菜单权限并没有写入到casbin_rule里面啊！有可能是我理解错了或者大神有其他的思路

菜单权限不是casbin维护的 casbin维护的是api  菜单通过sys_authority_menu 加视图维护

**Comment by pwli0755** [comment]
what‘s the difference among "menu permissions" "resource permissions" and "api permissions" ? @piexlmax

**Comment by SliverHorn** [comment]
> what‘s the difference among "menu permissions" "resource permissions" and "api permissions"

menu permissions ：This is the menu item on the left side of the front page, and it will fetch the menu id through the role ID whether it is in the database, the specific implementation depends on the code
resource permissions：This is for the front page `示例文件`-> `客户列表(资源权限) `，The implementation looks at the code
api permissions： This is the API corresponding permission of each API request, and it will judge whether the address and request mode of API request are in the database through the role ID, and the specific implementation depends on the code

**Comment by pwli0755** [comment]
> > what‘s the difference among "menu permissions" "resource permissions" and "api permissions"
> 
> menu permissions ：This is the menu item on the left side of the front page, and it will fetch the menu id through the role ID whether it is in the database, the specific implementation depends on the code
> resource permissions：This is for the front page `示例文件`-> `客户列表(资源权限) `，The implementation looks at the code
> api permissions： This is the API corresponding permission of each API request, and it will judge whether the address and request mode of API request are in the database through the role ID, and the specific implementation depends on the code

Is it possible to store the menu permissions into casbin too? what's the purpose storing these data into specific database table ?

**Comment by aixj1984** [comment]
同问，期待

**Comment by TrumanH** [comment]
> 

Just take a look at this code snipt (https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/middleware/casbin_rbac.go#L14): 
```
func CasbinHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		waitUse, _ := utils.GetClaims(c)
		// 获取请求的PATH
		obj := c.Request.URL.Path
		// 获取请求方法
		act := c.Request.Method
		// 获取用户的角色
		sub := waitUse.AuthorityId
		e := casbinService.Casbin()
		// 判断策略中是否存在
		success, _ := e.Enforce(sub, obj, act)
		if global.GVA_CONFIG.System.Env == "develop" || success {
			c.Next()
		} else {
			response.FailWithDetailed(gin.H{}, "权限不足", c)
			c.Abort()
			return
		}
	}
}
```
We can see it only added api resource filter here, if add menu resource filter, front-end need call api everytime on menu view, which is wasteful but possible been implement, below a wild draft as a reference which not ensure quanlity:
```
func CasbinHandler1() gin.HandlerFunc {
	return func(c *gin.Context) {
		waitUse, _ := utils.GetClaims(c)
		// get memu(resource name) from header or from otherwhere
		obj := c.Request.Header.Get("resource")
		// no resource need to be filtered
		if obj == "" {
			c.Next()
		}
		act := c.Request.Method
		sub := waitUse.AuthorityId
		e := casbinService.Casbin()
		// 判断策略中是否存在
		success, _ := e.Enforce(sub, obj, act)
		if global.GVA_CONFIG.System.Env == "develop" || success {
			c.Next() // then: 1.go to a uniform endpoint(to be implement) to resposne success 2.go to api handler
		} else {
			response.FailWithDetailed(gin.H{}, "权限不足", c)
			c.Abort()
			return
		}
	}
}
```

**Comment by TrumanH** [comment]
It's a simple way to maintain static resource permissions like menus, that u just need add a json field(notice last field `Permissions`):
```
type SysUser struct {
	global.GVA_MODEL
	UUID        uuid.UUID      `json:"uuid" gorm:"comment:用户UUID"`                         // 用户UUID
	Username    string         `json:"userName" gorm:"uniqueIndex:username;comment:用户登录名"` // 用户登录名
	Password    string         `json:"-"  gorm:"comment:用户登录密码"`                           // 用户登录密码
	NickName    string         `json:"nickName" gorm:"default:系统用户;comment:用户昵称"`          // 用户昵称
	HeaderImg   string         `json:"headerImg" gorm:"default:null;comment:用户头像"`         // 用户头像
	Phone       string         `json:"phone" gorm:"comment:手机号"`                           // 手机号
	Email       string         `json:"email" gorm:"comment:邮箱"`                            // 邮箱
	Authority   SysAuthority   `json:"authority" gorm:"foreignKey:AuthorityId;references:AuthorityId;comment:用户角色"`
	AuthorityId string         `json:"authorityId" gorm:"default:888;comment:用户角色ID"`    // 用户角色ID
	SideMode    string         `json:"sideMode" gorm:"default:dark;comment:用户侧边主题"`      // 用户侧边主题
	ActiveColor string         `json:"activeColor" gorm:"default:#1890ff;comment:活跃颜色"`  // 活跃颜色
	BaseColor   string         `json:"baseColor" gorm:"default:#fff;comment:基础颜色"`       // 基础颜色
	Authorities []SysAuthority `json:"authorities" gorm:"many2many:sys_user_authority;"` //

	Permissions datatypes.JSON `json:"authlist" gorm:"column:authlist;type:json;null;comment:menu permissions"` // menu permissions and so on
}
```
