### ISSUE TITLE
[Feature]: 重新初始化功能

### ISSUE THREAD

**Issue by bypanghu** [flipped-aurora/gin-vue-admin#1410]
### 功能描述以及必要性描述

系统设置强制初始化功能，将配置文件恢复初始化，数据库需要选择其他数据库，不可重名

**Comment by piexlmax** [comment]
强制初始化操作不需要采纳，建议用户自行使用git重置。初始化按钮显隐不建议用接口形式调用，在用户量大的情况下浪费多次http调用。建议修改为前端core中的配置项即可。
