### ISSUE TITLE
[Feature]: 单元测试跑不起来

### ISSUE THREAD

**Issue by oldsaltedfish** [flipped-aurora/gin-vue-admin#1414]
### 功能描述以及必要性描述

单元测试跑不起来，希望优化初始项和全局变量加载及依赖关系

**Comment by piexlmax** [comment]
单元测试你肯定要自己去把global前置调用啊 你的单测写错了

**Comment by oldsaltedfish** [comment]
> 单元测试你肯定要自己去把global前置调用啊 你的单测写错了

我希望能通过 init 隐式初始化，执行main和test有一个统一的组件加载逻辑，而不是main写一套test写一套

**Comment by songzhibin97** [comment]
隐式会存在调用关系混乱以及初始化必要条件缺少
