### ISSUE TITLE
[Bug]: 创建api后不关联角色直接删除会报错

### ISSUE THREAD

**Issue by ChocolateAceCream** [flipped-aurora/gin-vue-admin#1416]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

新增基础api service中没有去创建相应的casbin policy, 但删除基础api的service中却去删除对应的casbin policy.  那创建api后如果没有去关联角色的话，直接删除会报错，因为此时并没有创建过的casbin policy可以删。

### 修改建议

清除匹配的权限 这个ClearCasbin service中先确认是否存在该policy再删除，如果不存policy直接返回true就行了

**Comment by piexlmax** [comment]
感谢 我现在复现修改下

**Comment by wd16yuan** [comment]
在casbin删除规则时，执行到 [RemoveFilteredPolicy](https://github.com/casbin/casbin/blob/6b2c686aea10f2b2845f015827c00c554b44e17e/internal_api.go#L245) 方法，如果没有匹配到规则，会返回false，err是nil 。 
我是在方法ClearNamedCasbin中添加了”未匹配规则、错误返回“的判断。如：
![123](https://user-images.githubusercontent.com/10648853/234464500-9804502b-3026-493f-8552-68f982735725.png)
