### ISSUE TITLE
[Bug]: readme 勘误

### ISSUE THREAD

**Issue by ssmmtt** [flipped-aurora/gin-vue-admin#1419]
### gin-vue-admin 版本

最新

### Node 版本

最新

### Golang 版本

最新

### 是否依旧存在

可以

### bug描述

![image](https://user-images.githubusercontent.com/16244320/234210389-b2a5a525-1366-40ca-923d-fabf2e69fe9c.png)

**Comment by bypanghu** [comment]
收到，感谢
