### ISSUE TITLE
系统使用参数公开系列。

### ISSUE THREAD

**Issue by prlei** [flipped-aurora/gin-vue-admin#142]
hi，能否在readme中给些系统参数，比如前端、后端需要最低内存配置是多少，比如跑一周后，内存占用多少。

**Comment by piexlmax** [comment]
> hi，能否在readme中给些系统参数，比如前端、后端需要最低内存配置是多少，比如跑一周后，内存占用多少。

很好的建议 这边会去做性能测定后发出来，感谢~！

**Comment by prlei** [comment]
好的，非常期待，给小型vps一些指引。
