### ISSUE TITLE
[Bug]: 排序报错 Error 1054: Unknown column '***' in 'order clause'

### ISSUE THREAD

**Issue by austfish** [flipped-aurora/gin-vue-admin#1422]
### gin-vue-admin 版本

v2.5.6

### Node 版本

v16.15.0

### Golang 版本

go 1.20.2

### 是否依旧存在

可以

### bug描述

1. 自动化代码排序报错，Unknown column 'ossComponentCount' in 'order clause'
2. 获取失败!	{"error": "Error 1054: Unknown column '***' in 'order clause'"}
3. 数据表字段存在下划线，oss_component_count

### 修改建议

统一数据库字段名采用驼峰命名法，和FieldJSON保持一直

**Comment by songzhibin97** [comment]
你可以尝试修复它吗？如果可以将分配给你

**Comment by mayooot** [comment]
> 你可以尝试修复它吗？如果可以将分配给你

我 clone 了 master 代码，看到数据库是用 `RegisterTables` 方法初始化表结构的，但并未找到 `oss_component_count` 字段的定义，可以详细的说明下需求吗，我可以帮忙解决这个 issue，thanks

**Comment by piexlmax** [comment]
此问题已经在最新分支自动化中修复了

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/deb32fa0fa32fe695ae09da1c92231fbbbe95151
