### ISSUE TITLE
[Bug]: 数据库初始化后菜单父子级关系混乱

### ISSUE THREAD

**Issue by bigno-feng** [flipped-aurora/gin-vue-admin#1423]
### gin-vue-admin 版本

main

### Node 版本

v18.14.2

### Golang 版本

go 1.20.1

### 是否依旧存在

可以

### bug描述

1. 数据库初始化
2. 登录页面
3. 菜单父子级关系混乱
mysql版本：5.7.34
![0fcccf7cd8eb4b8af845ea63503141c](https://user-images.githubusercontent.com/37724987/236369184-1f85a4da-09bf-4b08-82f2-3471dd278862.png)
![d4e3ce7f95a61f72eb29f4674bfeb1c](https://user-images.githubusercontent.com/37724987/236369211-b8994b8b-7228-4e92-892c-784bee1a01a2.png)
数据库中存在重复数据，parent_id与id对应关系有误

### 修改建议

升级mysql版本到8.0.33，重新初始化后菜单显示正常，数据库中无重复数据

**Comment by SliverHorn** [comment]
应该是初始化了两次

**Comment by bigno-feng** [comment]
开了日志看了下会执行5次insert, 第二次又成功了15条。

[5.179ms] [rows:30] INSERT INTO `sys_base_menus` (`created_at`,`updated_at`,`deleted_at`,`menu_level`,`parent_id`,`path`,`name`,`hidden`,`component`,`sort`,`active_n
ame`,`keep_alive`,`default_menu`,`title`,`icon`,`close_tab`) VALUES ('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','dashboard','dashboard',false,'vi
ew/dashboard/index.vue',1,'',false,false,'仪表盘','odometer',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','about','about',false,'view/about
/index.vue',9,'',false,false,'关于我们','info-filled',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','admin','superAdmin',false,'view/superAd
min/index.vue',3,'',false,false,'超级管理员','user',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','authority','authority',false,'view/superA
dmin/authority/authority.vue',1,'',false,false,'角色管理','avatar',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','menu','menu',false,'view/s
uperAdmin/menu/menu.vue',2,'',true,false,'菜单管理','tickets',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','api','api',false,'view/superAdm
in/api/api.vue',3,'',true,false,'api管理','platform',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','user','user',false,'view/superAdmin/user
/user.vue',4,'',false,false,'用户管理','coordinate',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','dictionary','dictionary',false,'view/supe
rAdmin/dictionary/sysDictionary.vue',5,'',false,false,'字典管理','notebook',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','dictionaryDetail/
:id','dictionaryDetail',true,'view/superAdmin/dictionary/sysDictionaryDetail.vue',1,'dictionary',false,false,'字典详情-${id}','list',false),('2023-05-05 11:35:25.759
','2023-05-05 11:35:25.759',NULL,0,'3','operation','operation',false,'view/superAdmin/operation/sysOperationRecord.vue',6,'',false,false,'操作历史','pie-chart',false
),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','person','person',true,'view/person/person.vue',4,'',false,false,'个人信息','message',false),('2023
-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','example','example',false,'view/example/index.vue',7,'',false,false,'示例文件','management',false),('2023-0
5-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','upload','upload',false,'view/example/upload/upload.vue',5,'',false,false,'媒体库（上传下载）','upload',fals
e),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','breakpoint','breakpoint',false,'view/example/breakpoint/breakpoint.vue',6,'',false,false,'断点续
','upload-filled',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','customer','customer',false,'view/example/customer/customer.vue',7,'',fal l
se,false,'客户列表（资源示例）','avatar',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','systemTools','systemTools',false,'view/systemTools/i
ndex.vue',5,'',false,false,'系统工具','tools',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','autoCode','autoCode',false,'view/systemTools/a
utoCode/index.vue',1,'',true,false,'代码生成器','cpu',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','formCreate','formCreate',false,'view/s
ystemTools/formCreate/index.vue',2,'',true,false,'表单生成器','magic-stick',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','system','system'
,false,'view/systemTools/system/system.vue',3,'',false,false,'系统配置','operation',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','autoCode
Admin','autoCodeAdmin',false,'view/systemTools/autoCodeAdmin/index.vue',1,'',false,false,'自动化代码管理','magic-stick',false),('2023-05-05 11:35:25.759','2023-05-05
 11:35:25.759',NULL,0,'16','autoCodeEdit/:id','autoCodeEdit',true,'view/systemTools/autoCode/index.vue',0,'',false,false,'自动化代码-${id}','magic-stick',false),('20
23-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','autoPkg','autoPkg',false,'view/systemTools/autoPkg/autoPkg.vue',0,'',false,false,'自动化package','folde
r',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','https://www.gin-vue-admin.com','https://www.gin-vue-admin.com',false,'/',0,'',false,false,
'官方网站','home-filled',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','state','state',false,'view/system/state.vue',8,'',false,false,'服务 
器状态','cloudy',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','plugin','plugin',false,'view/routerHolder.vue',6,'',false,false,'插件系统','
cherry',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','https://plugin.gin-vue-admin.com/','https://plugin.gin-vue-admin.com/',false,'https:
//plugin.gin-vue-admin.com/',0,'',false,false,'插件市场','shop',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','installPlugin','installPlugi
n',false,'view/systemTools/installPlugin/index.vue',1,'',false,false,'插件安装','box',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','autoPl
ug','autoPlug',false,'view/systemTools/autoPlug/autoPlug.vue',2,'',false,false,'插件模板','folder',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0
,'25','plugin-email','plugin-email',false,'plugin/email/view/index.vue',3,'',false,false,'邮件插件','message',false),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','chatTable','chatTable',false,'view/chatgpt/chatTable.vue',6,'',false,false,'万用表格','chat-dot-square',false)

[2.661ms] [rows:15] INSERT INTO `sys_base_menus` (`created_at`,`updated_at`,`deleted_at`,`menu_level`,`parent_id`,`path`,`name`,`hidden`,`component`,`sort`,`active_n
ame`,`keep_alive`,`default_menu`,`title`,`icon`,`close_tab`,`id`) VALUES ('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','dashboard','dashboard',fals
e,'view/dashboard/index.vue',1,'',false,false,'仪表盘','odometer',false,1),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','about','about',false,'vie
w/about/index.vue',9,'',false,false,'关于我们','info-filled',false,2),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','admin','superAdmin',false,'vie
w/superAdmin/index.vue',3,'',false,false,'超级管理员','user',false,3),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','authority','authority',false,'
view/superAdmin/authority/authority.vue',1,'',false,false,'角色管理','avatar',false,4),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','menu','menu',
false,'view/superAdmin/menu/menu.vue',2,'',true,false,'菜单管理','tickets',false,5),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','api','api',false
,'view/superAdmin/api/api.vue',3,'',true,false,'api管理','platform',false,6),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','user','user',false,'vie
w/superAdmin/user/user.vue',4,'',false,false,'用户管理','coordinate',false,7),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','dictionary','dictionar
y',false,'view/superAdmin/dictionary/sysDictionary.vue',5,'',false,false,'字典管理','notebook',false,8),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'
3','dictionaryDetail/:id','dictionaryDetail',true,'view/superAdmin/dictionary/sysDictionaryDetail.vue',1,'dictionary',false,false,'字典详情-${id}','list',false,9),('
2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'3','operation','operation',false,'view/superAdmin/operation/sysOperationRecord.vue',6,'',false,false,'操作
史','pie-chart',false,10),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','person','person',true,'view/person/person.vue',4,'',false,false,'个人信   
息','message',false,11),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','example','example',false,'view/example/index.vue',7,'',false,false,'示例文件
,'management',false,12),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','upload','upload',false,'view/example/upload/upload.vue',5,'',false,false,''
媒体库（上传下载）','upload',false,13),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','breakpoint','breakpoint',false,'view/example/breakpoint/brea
kpoint.vue',6,'',false,false,'断点续传','upload-filled',false,14),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'12','customer','customer',false,'view/
example/customer/customer.vue',7,'',false,false,'客户列表（资源示例）','avatar',false,15),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','systemTool
s','systemTools',false,'view/systemTools/index.vue',5,'',false,false,'系统工具','tools',false,16),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','a
utoCode','autoCode',false,'view/systemTools/autoCode/index.vue',1,'',true,false,'代码生成器','cpu',false,17),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NUL
L,0,'16','formCreate','formCreate',false,'view/systemTools/formCreate/index.vue',2,'',true,false,'表单生成器','magic-stick',false,18),('2023-05-05 11:35:25.759','202
3-05-05 11:35:25.759',NULL,0,'16','system','system',false,'view/systemTools/system/system.vue',3,'',false,false,'系统配置','operation',false,19),('2023-05-05 11:35:2
5.759','2023-05-05 11:35:25.759',NULL,0,'16','autoCodeAdmin','autoCodeAdmin',false,'view/systemTools/autoCodeAdmin/index.vue',1,'',false,false,'自动化代码管理','magi
c-stick',false,20),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','autoCodeEdit/:id','autoCodeEdit',true,'view/systemTools/autoCode/index.vue',0,''
,false,false,'自动化代码-${id}','magic-stick',false,21),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','autoPkg','autoPkg',false,'view/systemTools/
autoPkg/autoPkg.vue',0,'',false,false,'自动化package','folder',false,22),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','https://www.gin-vue-admin.c
om','https://www.gin-vue-admin.com',false,'/',0,'',false,false,'官方网站','home-filled',false,23),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','st
ate','state',false,'view/system/state.vue',8,'',false,false,'服务器状态','cloudy',false,24),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'0','plugin',
'plugin',false,'view/routerHolder.vue',6,'',false,false,'插件系统','cherry',false,25),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','https://plugi
n.gin-vue-admin.com/','https://plugin.gin-vue-admin.com/',false,'https://plugin.gin-vue-admin.com/',0,'',false,false,'插件市场','shop',false,26),('2023-05-05 11:35:2
5.759','2023-05-05 11:35:25.759',NULL,0,'25','installPlugin','installPlugin',false,'view/systemTools/installPlugin/index.vue',1,'',false,false,'插件安装','box',false
,27),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','autoPlug','autoPlug',false,'view/systemTools/autoPlug/autoPlug.vue',2,'',false,false,'插件模板
,'folder',false,28),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'25','plugin-email','plugin-email',false,'plugin/email/view/index.vue',3,'',false,faa
lse,'邮件插件','message',false,29),('2023-05-05 11:35:25.759','2023-05-05 11:35:25.759',NULL,0,'16','chatTable','chatTable',false,'view/chatgpt/chatTable.vue',6,'',false,false,'万用表格','chat-dot-square',false,30) ON DUPLICATE KEY UPDATE `id`=`id`

**Comment by piexlmax** [comment]
注意数据库版本 数据库版本错误导致的
