### ISSUE TITLE
caught SyntaxError: Identifier 'ElementPlus' has already been declared (at main.js:3:1)[Bug]: 

### ISSUE THREAD

**Issue by cruelwolfking** [flipped-aurora/gin-vue-admin#1428]
### gin-vue-admin 版本

最新版

### Node 版本

v16

### Golang 版本

18

### 是否依旧存在

可以

### bug描述

main.js 报错
caught SyntaxError: Identifier 'ElementPlus' has already been declared (at main.js:3:1)
console 可以看到重复定义import ElementPlus from 'element-plus'
但是代码只看到一行

**Comment by bypanghu** [comment]
你这是ie18的分支 请在上面标注分支
