### ISSUE TITLE
[Feature]: 对Gorm Gen的支持

### ISSUE THREAD

**Issue by nanakura** [flipped-aurora/gin-vue-admin#1429]
### 功能描述以及必要性描述

希望GVA集成[Gorm Gen](https://gorm.io/gen/)

**Comment by SliverHorn** [comment]
团队讨论结果：
piexlmax: 由gorm更换为gen，技术栈发生改变，升级了小白上手难度
songzhibin97: 没必要
SliverHorn：支持
ipanghu：支持
@pnck 你怎么看？

**Comment by pnck** [comment]
`gorm gen` 与 `gorm` 是两个不同的建立数据库映射的方向，如果模型以 _SQL DDL_ 为标准，那么就该用 `gorm gen` 生成 go 结构体；如果表的精细结构并不那么重要，以 go 代码定义的结构体为标准模型，那理论上可以不需要 `gorm gen`。

所以我其实不太确定你们双方的预期是什么， 如果引入 gen 的话是准备 model 有关的定义都重写，改用 gen 生成吗？ 还是说是用于优化代码生成那部分功能的？

而且用gen重写model的话基础查询的逻辑应该也会大改，这样至少得滚一个大版本号了。



我看这个 issue 也没关联其它的 issue，所以我理解目前其实暂时没遇到需要 `gorm gen` 来解决的需求。如果贵团队是准备下个大版本引入新机制来彻底重构一下代码，那我个人倒是没理由反对；但如果是想在项目里加个 _能根据现成的库生成代码模板_ 之类的功能，那我就觉得没必要。
