### ISSUE TITLE
[Bug]: 授权多个角色后，仅一个角色生效 

### ISSUE THREAD

**Issue by jianjustin** [flipped-aurora/gin-vue-admin#1437]
### gin-vue-admin 版本

2.5.0

### Node 版本

v14

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

目前`GetMenu()`等方法都是使用`utils.GetUserAuthorityId(c)`获取用户对应角色；如果授权多个角色，则无法生效
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/18155107/d8dd33b0-6343-4e9a-aad0-26b3ded6b417)

**Comment by SliverHorn** [comment]
多角色，但是只有一个活跃角色

**Comment by jianjustin** [comment]
> <img alt="image" width="423" src="https://user-images.githubusercontent.com/45428434/240536399-36be4c09-c68a-4cc7-b35b-fc7ed3fb7f10.png">

非常感谢，我试下
