### ISSUE TITLE
[Feature]: 是否考虑支持Sqlite3数据库

### ISSUE THREAD

**Issue by nageslan** [flipped-aurora/gin-vue-admin#1442]
### 功能描述以及必要性描述

1.gorm是支持sqlite3的, 我个人比较喜欢sqlite3希望最好能支持.

**Comment by piexlmax** [comment]
希望可以提交pr

**Comment by Kafumio** [comment]
你好 @piexlmax ，我对这个issue有兴趣并想尝试实现这个功能，你能将它指派给我吗？

**Comment by SliverHorn** [comment]
> 你好 @piexlmax ，我对这个issue有兴趣并想尝试实现这个功能，你能将它指派给我吗？

可以的

**Comment by zyw0605688** [comment]
这个功能怎么样了，是否可以使用。我现在有个嵌入式设备，需要用到sqlite3
