### ISSUE TITLE
最新版swagger生成后空白问题

### ISSUE THREAD

**Issue by dreamlu** [flipped-aurora/gin-vue-admin#1445]
### gin-vue-admin 版本

main最新

### Node 版本

v16.15.0

### Golang 版本

go 1.20.4

### 是否依旧存在

可以

### bug描述

swagger生成后空白问题：
1.按照最新的go.mod swag版本v1.16.1：
`go install github.com/swaggo/swag/cmd/swag@v1.16.1`
2.swag init
空白，docs/swagger.json和swagger.yaml中接口数据没了

临时解决办法：
1.`go install github.com/swaggo/swag/cmd/swag@v1.7.0`
2.swag init又可以了

新版本无法生成

**Comment by SliverHorn** [comment]
已经更新了[go.mod/swag版本为1.61.1](https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/go.mod#LL33C2-L33C24)

**Comment by SliverHorn** [comment]
在main分之无法复现次bug
<img width="2559" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/45428434/8ebe6d76-8442-4120-831c-8041c6035579">
<img width="1280" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/45428434/149244f9-c574-46bf-92ee-c3b3cb26b52a">
<img width="2559" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/45428434/d99a9d8f-468b-4f5c-af6c-e9f15207efa5">

**Comment by dreamlu** [comment]
再次测试仍然如次(没有你截图中生成api的过程)：
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/21306894/977dfe57-2137-4b8f-b8db-f27268fe80ea)

**Comment by dreamlu** [comment]
再次换成v1.7.0就可以：
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/21306894/33271f8c-9e37-4643-b712-cf1c6f46dbf2)

**Comment by piexlmax** [comment]
windows,mac 均无法复现

**Comment by piexlmax** [comment]
安装方式不要携带version，按照文档的安装指令操作。

**Comment by SliverHorn** [comment]
@dreamlu 建议去 swag 仓库提issues。即使定位到问题，我们使用第三方开源库也无法进行维护修复的

**Comment by zyw0605688** [comment]
> 在main分支无法复现次bug <img alt="image" width="2000" src="https://user-images.githubusercontent.com/45428434/242140472-8ebe6d76-8442-4120-831c-8041c6035579.png"> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/45428434/242140522-149244f9-c574-46bf-92ee-c3b3cb26b52a.png"> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/45428434/242140514-d99a9d8f-468b-4f5c-af6c-e9f15207efa5.png">

上图中
Errors
Resolver errorCannot read properties of undefined (reading '1')
这个报错，我也同样遇到了。可以解决掉吗，如何处理？

**Comment by zyw0605688** [comment]
> 在main分支无法复现次bug <img alt="image" width="2000" src="https://user-images.githubusercontent.com/45428434/242140472-8ebe6d76-8442-4120-831c-8041c6035579.png"> <img alt="image" width="1280" src="https://user-images.githubusercontent.com/45428434/242140522-149244f9-c574-46bf-92ee-c3b3cb26b52a.png"> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/45428434/242140514-d99a9d8f-468b-4f5c-af6c-e9f15207efa5.png">

顶部出现
Errors
Resolver errorCannot read properties of undefined (reading '1')
这个问题已找到解决办法，只需要升级gin-swagger到最新即可。
