### ISSUE TITLE
M1 mac部署时候提示错误

### ISSUE THREAD

**Issue by anan1310** [flipped-aurora/gin-vue-admin#1452]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.18.2

### Golang 版本

 go1.18.7 darwin/arm64

### 是否依旧存在

可以

### bug描述

../../../pkg/mod/modernc.org/sqlite@v1.23.0/lib/sqlite_darwin_arm64.go:156917:9: undefined: libc.Xpread

**Comment by anan1310** [comment]
替换一下最新版本中的内容即可
	modernc.org/libc v1.15.1 // indirect
	modernc.org/mathutil v1.4.1 // indirect
	modernc.org/memory v1.0.7 // indirect
	modernc.org/sqlite v1.16.0 // indirect
<img width="682" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/75241895/986f59c8-bb56-4e2c-81e9-96335b2ebf18">

**Comment by piexlmax** [comment]
main分支可以复现吗？

**Comment by xusenlin** [comment]
我的 Intel  mac 也有此错误
在main分支
```
# modernc.org/sqlite/lib
../../../go/pkg/mod/modernc.org/sqlite@v1.23.0/lib/sqlite_darwin_amd64.go:158407:9: undefined: libc.Xpread
```

**Comment by xusenlin** [comment]
> 我的 Intel mac 也有此错误 在main分支
> 
> ```
> # modernc.org/sqlite/lib
> ../../../go/pkg/mod/modernc.org/sqlite@v1.23.0/lib/sqlite_darwin_amd64.go:158407:9: undefined: libc.Xpread
> ```

[anan1310](https://github.com/anan1310)的方案可以解决

**Comment by SliverHorn** [comment]
为什么我复现不出来啊?

**Comment by atidat** [comment]
> > 我的 Intel mac 也有此错误 在main分支
> > ```
> > # modernc.org/sqlite/lib
> > ../../../go/pkg/mod/modernc.org/sqlite@v1.23.0/lib/sqlite_darwin_amd64.go:158407:9: undefined: libc.Xpread
> > ```
> 
> [anan1310](https://github.com/anan1310)的方案可以解决

当前版本仍有该问题

**Comment by tesun** [comment]
运行：go mod tidy
