### ISSUE TITLE
[Bug]: 更新角色权限后，用户token未刷新

### ISSUE THREAD

**Issue by gaojixiaoyu** [flipped-aurora/gin-vue-admin#1454]
### gin-vue-admin 版本

2.5.5

### Node 版本

v18.14.0

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

角色权限修改后，用户使用之前的token可以继续越权访问

### 修改建议

在更新角色权限后，刷新角色下用户的token

**Comment by piexlmax** [comment]
目前此代码处于注释状态，可以自行打开检测，位置在jwt中间件中，或者加入ws长连接监听。
