### ISSUE TITLE
[Bug]: typo in 'function xxx.XXX() Filed', should be 'Failed' instead

### ISSUE THREAD

**Issue by ChocolateAceCream** [flipped-aurora/gin-vue-admin#1460]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

multiple files in server/utils/upload have misspelled 'Filed', should be 'Failed'

### 修改建议

globally change Filed to Failed

**Comment by bypanghu** [comment]
请问你用的是哪个上传？

**Comment by ChocolateAceCream** [comment]
我其实哪个都没用，只是读代码的时候发现了
.比如
"function os.MkdirAll() Filed“
”function file.Open() Filed“
”function formUploader.Put() Filed“
这些应该都是failed不是filed吧

**Comment by piexlmax** [comment]
> 我其实哪个都没用，只是读代码的时候发现了 .比如 "function os.MkdirAll() Filed“ ”function file.Open() Filed“ ”function formUploader.Put() Filed“ 这些应该都是failed不是filed吧

可以帮忙提交PR解决typo问题，这些可能是因为我的烂英文水平导致的
