### ISSUE TITLE
[Feature]: 权限部分能增加个人/部门/全部的权限标识吗

### ISSUE THREAD

**Issue by haskio** [flipped-aurora/gin-vue-admin#1466]
### 功能描述以及必要性描述

权限部分目前没有按个人/部门等进行区分，默认都是全部的控制。

### 建议和方案

希望能够增加更多的权限标识。
例如当某个用户创建的记录，只能由他可以看到，其他人无法看到。

**Comment by SliverHorn** [comment]
我想你需要的是这个 [插件](https://plugin.gin-vue-admin.com/#/layout/newPluginInfo?id=36)

**Comment by piexlmax** [comment]
> ### 功能描述以及必要性描述
> 权限部分目前没有按个人/部门等进行区分，默认都是全部的控制。
> 
> ### 建议和方案
> 希望能够增加更多的权限标识。 例如当某个用户创建的记录，只能由他可以看到，其他人无法看到。

插件市场的组织插件就是干这个的。
