### ISSUE TITLE
node-gyp安装失败

### ISSUE THREAD

**Issue by zhuiyi9009** [flipped-aurora/gin-vue-admin#147]
Traceback (most recent call last):
  File "E:\vue-test\gin-vue-admin\web\node_modules\node-gyp\gyp\gyp_main.py", li
ne 13, in <module>
    import gyp
ImportError: No module named gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (E:\vue-test\gin-vue-admin\web\node_
modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:272:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\nodejs\\node.exe" "E:\\vue-test\\gin-vue-admin\\web\\node_
modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--l
ibsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\vue-test\gin-vue-admin\web\node_modules\node-sass
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.12.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     e:\node-cache\cache\_logs\2020-07-14T02_33_23_178Z-debug.log

环境python3

**Comment by piexlmax** [comment]
尝试  sudo npm i --unsafe-perm
