### ISSUE TITLE
[Bug]: RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by Ryze-T** [flipped-aurora/gin-vue-admin#1474]
### gin-vue-admin 版本

2.5.6

### Node 版本

16.20

### Golang 版本

go1.20

### 是否依旧存在

可以

### bug描述

启动后初始化数据库，然后登录时一直加载，前端报错
RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
<img width="540" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/76553352/2a203d4e-5295-48cc-92fd-2df2a4d8ff85">

**Comment by piexlmax** [comment]
此问题未能复现，可以详细写一下复现步骤吗？
