### ISSUE TITLE
请问下我用代码生成器放入代码后为什么显示 undefined

### ISSUE THREAD

**Issue by VGTsome** [flipped-aurora/gin-vue-admin#148]
initialize\db_table.go:25:3: undefined: model.Testtest
initialize\router.go:43:2: undefined: router.InitTesttestRouter

**Comment by VGTsome** [comment]
搞明白了，不能用sys开头的文件名？？？看了半天差点怀疑人生

**Comment by granty1** [comment]
怀疑人生是好事，吾日三省吾身~

**Comment by piexlmax** [comment]
> 搞明白了，不能用sys开头的文件名？？？看了半天差点怀疑人生

不是的  可以用sys 直接拽入文件 有时候mod会识别不到 这个问题 有时候重启一次goland或者cmd就解决了
