### ISSUE TITLE
[Bug]: 代码生成器生成文件上传类型数据，不选择必填，在修改时报错

### ISSUE THREAD

**Issue by richarduncle** [flipped-aurora/gin-vue-admin#1480]
### gin-vue-admin 版本

2.5.6

### Node 版本

v20.2.0

### Golang 版本

 go1.18.1 darwin/arm64

### 是否依旧存在

可以

### bug描述

1.使用代码生成器生成字段含有文件类型（json字符串），不选择必填。
2.创建数据时不上传文件
3.点击列表页编辑报错
<img width="623" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/19268769/0ae6d579-0ea2-45a9-beab-4ed50fff869c">

**Comment by piexlmax** [comment]
此问题已在main修复，测试下即可。
