### ISSUE TITLE
[Feature]: 将字典值改为string类型

### ISSUE THREAD

**Issue by Horus-K** [flipped-aurora/gin-vue-admin#1484]
### 功能描述以及必要性描述

方便直接查询表数据，省的连表查

版本: 2023/06/10 正式版，仅初始化一个包
我修改了前端的展示与与后端的struct 值类型后已实现
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/48319268/71ba09c8-42aa-4ac8-bb79-ad8c8c40edd3)

但是目前不清楚原有的这些字典是否可以全部删掉，我没找到这些字典在哪里用(除了自动化代码生成数据库字段)
还有这个文件中server/source/system/dictionary_detail.go
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/48319268/aa8a7139-ab70-4e69-83ef-8948826894aa)
这些直接初始化的字典是否有使用到

**Comment by SliverHorn** [comment]
生成代码也可以用啊

**Comment by SliverHorn** [comment]
- 不接受你的提案，改成string是你自己的需求，请不要pr给本项目仓库
- 为什么用int类型，这个无需解释，自己研究。
- 至于联表，有可解决的方案，但是确实是联表操作会使得数据更合理性，因为字典功能就是为了动态键和动态值
