### ISSUE TITLE
[Bug]: SQLite 数据没写到db文件里

### ISSUE THREAD

**Issue by q447552640** [flipped-aurora/gin-vue-admin#1488]
### gin-vue-admin 版本

main branch

### Node 版本

v18.17.0

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

1.如果系统出现panic，则sqlite数据会不写入db文件，导致数据丢失。
2.初始化之后如果ctrl+c直接关闭数据库，db文件里面有表，但表为空。

**Comment by vanloswang** [comment]
v2.5.6手动合并 https://github.com/flipped-aurora/gin-vue-admin/pull/1467
windows 11 编译通过，正常使用，未遇到上述问题

**Comment by piexlmax** [comment]
未能复现
