### ISSUE TITLE
stringFun.js 下划线转换驼峰的时候是不是可以不转义

### ISSUE THREAD

**Issue by qizhoumeng** [flipped-aurora/gin-vue-admin#149]
`
// 下划线转换驼峰
export const  toHump = (name) => {
  return name.replace(/\_(\w)/g, function(all, letter){
      return letter.toUpperCase();
  });
}
`
这里改成`name.replace(/_(\w)/g ...`，也是可以运行的，不太清楚这里特意转义一下是有什么特别需要注意的地方？

**Comment by piexlmax** [comment]
> `// 下划线转换驼峰 export const toHump = (name) => { return name.replace(/\_(\w)/g, function(all, letter){ return letter.toUpperCase(); }); }`
> 这里改成`name.replace(/_(\w)/g ...`，也是可以运行的，不太清楚这里特意转义一下是有什么特别需要注意的地方？

这个就是代码习惯问题了，下意识把符号都转译了

**Comment by qizhoumeng** [comment]
好的，明白了，好习惯学习了。
