### ISSUE TITLE
# 启动web项目 npm run serve,直接报错

### ISSUE THREAD

**Issue by Xuzan9396** [flipped-aurora/gin-vue-admin#1492]
### gin-vue-admin 版本

2.5.6

### Node 版本

v18.16.0

### Golang 版本

go 1.2.0

### 是否依旧存在

可以

### bug描述

![image](https://github.com/flipped-aurora/gin-vue-admin/assets/24741439/32bcc021-a62f-48bf-ad86-1eb34a283178)

启动报错啊，啥都没改

**Comment by piexlmax** [comment]
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/29840023/df8be6b2-9f6d-4c6d-94bf-aa99020c8e73)
并没有去main测试，问题原因是element-ui的不兼容更新导致。提交ISSUE请按照格式测试。用main即可解决本问题。
