### ISSUE TITLE
[Bug]: 菜单中是否为基础页面选项，功能未实现

### ISSUE THREAD

**Issue by darcyjoven** [flipped-aurora/gin-vue-admin#1498]
### gin-vue-admin 版本

2.5.6

### Node 版本

ndoe 16.20.1

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

![image](https://github.com/flipped-aurora/gin-vue-admin/assets/17287553/83d61398-9e05-437a-aa28-9c7bc808d3d1)
+ 前端菜单设置此选项，选择是之后，期望页面打开时不显示侧边栏和顶部信息，但实际和其它菜单一样。
+ 对应数据库表为sys_base_menus，字段为default_menu

> 功能未实现，还是我自己的理解有问题？

**Comment by piexlmax** [comment]
之前做过功能调整 我尝试复现修复下

**Comment by piexlmax** [comment]
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/29840023/6d519f24-1974-423a-a1cc-5397f103f42c)
经过测试 一级展示不存在问题

二级展示需要外层父级别也为基础页面才可呈现效果

**Comment by darcyjoven** [comment]
> ![image](https://user-images.githubusercontent.com/29840023/258381798-6d519f24-1974-423a-a1cc-5397f103f42c.png) 经过测试 一级展示不存在问题
> 
> 二级展示需要外层父级别也为基础页面才可呈现效果

测试了一下，确实是这样。
是我测试少了。谢谢
