### ISSUE TITLE
[Bug]: router-view 下存在 div 子元素，在使用 v-loading 时，element-loading-text 设置无效。

### ISSUE THREAD

**Issue by wd16yuan** [flipped-aurora/gin-vue-admin#1501]
### gin-vue-admin 版本

main

### Node 版本

v16.9.0

### Golang 版本

go 18.8

### 是否依旧存在

可以

### bug描述

[[](url)](https://github.com/flipped-aurora/gin-vue-admin/blob/16c79bbc641f385f38dbd8ffbf33ff84ca9d27b1/web/src/view/layout/index.vue#L99C11-L99C11)
router-view 下存在 div 子元素，在使用 v-loading 时，element-loading-text 设置无效。

**Comment by piexlmax** [comment]
main分支已修复
