### ISSUE TITLE
[Feature]: 自己手动配置好数据库后，不会导入数据

### ISSUE THREAD

**Issue by twelvet-s** [flipped-aurora/gin-vue-admin#1502]
### 功能描述以及必要性描述

自己手动配置好数据库后，启动后端，发现表导入了，但是没有数据

### 建议和方案

希望在执行  initialize.RegisterTables()  导入数据表后也同样进行数据导入

**Comment by SliverHorn** [comment]
看文档！

**Comment by twelvet-s** [comment]
我知道在前端有个初始化数据的，但是我看后端里面也写了一个初始化的，在我配置数据库信息后会自动建立表。意思是这个过程能否也导入数据

**Comment by SliverHorn** [comment]
自己看代码自己研究

**Comment by twelvet-s** [comment]
err := db.AutoMigrate(
		// 系统模块表
		system.SysApi{},
		system.SysUser{},
		system.SysBaseMenu{},
		system.JwtBlacklist{},
		system.SysAuthority{},
		system.SysDictionary{},
		system.SysOperationRecord{},
		system.SysAutoCodeHistory{},
		system.SysDictionaryDetail{},
		system.SysBaseMenuParameter{},
		system.SysBaseMenuBtn{},
		system.SysAuthorityBtn{},
		system.SysAutoCode{},
		system.SysChatGptOption{},

		example.ExaFile{},
		example.ExaCustomer{},
		example.ExaFileChunk{},
		example.ExaFileUploadAndDownload{},
	)
	执行完这个后，去执行导入数据

**Comment by SliverHorn** [comment]
支持的，自己去研究吧

**Comment by twelvet-s** [comment]
我是想官方看看能否优化一下这个呢

**Comment by SliverHorn** [comment]
不能

**Comment by SliverHorn** [comment]
因为后端无法确定是否要初始化这个动作

**Comment by twelvet-s** [comment]
好的，感谢。我看看这个
