### ISSUE TITLE
[Bug]: 每一个err不是应该只被处理一次吗？

### ISSUE THREAD

**Issue by bellingham07** [flipped-aurora/gin-vue-admin#1506]
### gin-vue-admin 版本

2.4.5

### Node 版本

v1.16

### Golang 版本

go1.20

### 是否依旧存在

可以

### bug描述

`if err != nil {
		global.GVA_LOG.Error("接收文件失败!", zap.Error(err))
		response.FailWithMessage("接收文件失败", c)
		return
	}`
类似于这种对错误进行了两次的处理，是否显得冗余

### 修改建议

在这里是否可以通过直接return err的方式，将错误抛给调用者

**Comment by piexlmax** [comment]
@SliverHorn CC

**Comment by bypanghu** [comment]
一个只是为了打 log 日志 ，一个是返回到发自我的 iPhone在 2023年8月9日，16:04，奇淼（piexlmax ***@***.***> 写道：﻿
@SliverHorn CC

**Comment by SliverHorn** [comment]
> @SliverHorn CC 抄送

这个我给过解决方案你啊，但是不认同啊

**Comment by piexlmax** [comment]
> > @SliverHorn CC 抄送
> 
> 这个我给过解决方案你啊，但是不认同啊

啥方案来着。。。

**Comment by piexlmax** [comment]
> > @SliverHorn CC 抄送
> 
> 这个我给过解决方案你啊，但是不认同啊

我记起来了，一个是记录到日志库的内容，一个是返回内容，这两者可能存在不同。所以这样设计了。

**Comment by tesun** [comment]
这样没问题啊，日志记录的和response给前端的并不会完全一样。

**Comment by nanpucoding** [comment]
没啥问题，一个是抛给前端的，一个是记录到日志里做留存的

**Comment by xliamh** [comment]
稳定安全，免费vpn, 支持chatgpt(https://monkeyff02.online/#/portal?c=ad01)
