### ISSUE TITLE
[Bug]: pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:239:46: too many errors

### ISSUE THREAD

**Issue by Elixin** [flipped-aurora/gin-vue-admin#1510]
### gin-vue-admin 版本

2.5.7

### Node 版本

无

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

启动后台项目出现sqlite的相关内容的找不到
`
# modernc.org/sqlite/lib
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\Administrator\go\pkg\mod\modernc.org\sqlite@v1.23.0\lib\mutex.go:239:46: too many errors
`

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/issues/1452

**Comment by piexlmax** [comment]
是目前的main分支的吗？系统环境是什么我这边看下。

**Comment by bboyHan** [comment]
我也遇到相同问题了
go version  1.20

main分支

我尝试了modernc.org\sqlite@v1.23.0
modernc.org\sqlite@v1.25.0

都是这个报错

**Comment by bboyHan** [comment]
我切换了 go version为 1.21，测试正常了，目前发现 1.20的有问题。 @piexlmax

**Comment by hidakafinzelz** [comment]
1.18.5也有这个问题

**Comment by qiaochengqiang** [comment]
go version为 1.21.0 
modernc.org/sqlite v1.23.0
还是报这个错

**Comment by heimeropen** [comment]
go 1.18 1.19 均异常

go version为 1.21.0
modernc.org/sqlite 升级为v1.26.0 
启动正常

**Comment by CoffeeSwt** [comment]
win11
main分支
go version 1.21.4
modernc.org/sqlite v1.26~v1.20 全试了
仍然报错

**Comment by piexlmax** [comment]
目前依然无法定位出稳定版本。且目前已经提供的环境下都无法复现，此bug有点难以捉摸。

**Comment by CoffeeSwt** [comment]
将go升级到1.22.0
modernc.org/sqlite 升级到1.28.0后问题解决

> win11 main分支 go version 1.21.4 modernc.org/sqlite v1.26~v1.20 全试了 仍然报错

**Comment by QsonXu** [comment]
check go env, param GOARCH=amd64 & GOHOSTOS=windows。

lib version: sqlite@v1.23.0 
variable sqlite3_index_constraint & sqlite3_index_orderby & sqlite3_index_constraint_usage in the sqlte_windows_amd64 or sqlite_windows_arm64 code file。

so set the env GOARCH & GOHOSTOS

go env -w GOHOSTOS=windows
go env -w GOARCH =amd64
go env -w GOHOSTARCH=amd64

last, go install.

**Comment by hellozdq** [comment]
上面的方法都试过了，都不行，有什么其他解决的方法吗

**Comment by CoffeeSwt** [comment]
> 上面的方法都试过了，都不行，有什么其他解决的方法吗

使用windows-amd64版本的go
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/83854560/1a8f1ba7-7c48-4551-ac92-fb74d3b7084b)

**Comment by pixelmaxQm** [comment]
需要使用amd版本的go 一般出现问题可以看go env 此时可以发现GOARC大概率为386 手动设置为amd64或者arm64都可以。
