### ISSUE TITLE
[Bug]: socket hang up at connResetException

### ISSUE THREAD

**Issue by tc7326** [flipped-aurora/gin-vue-admin#1513]
### gin-vue-admin 版本

master

### Node 版本

18.17.1

### Golang 版本

1.20.4

### 是否依旧存在

可以

### bug描述

就正常初始化数据库
后端无异常 是在初始化数据库完成后

弹窗提示响应了500错误 按F12查看确实无返回信息为500响应

再查看前端服务器 发现响应给前端的回调时 前端的node发生错误

后端日志：
```
[github.com/flipped-aurora/gin-vue-admin/server]2023/08/15 - 11:27:39.865       info    C:/dev/go/gin-vue-admin/server/api/v1/system/sys_initdb.go:41   数据库
创建完毕 给前端响应 200
[GIN] 2023/08/15 - 11:27:39 | 200 |   21.6501244s |       127.0.0.1 | POST     "/init/initdb"
```

可以看到初始化耗时21秒左右 可能和初始化时间过长有关系？

具体node报错异常：

```
11:27:39 [vite] http proxy error at /init/initdb:      
Error: socket hang up
    at connResetException (node:internal/errors:720:14)
    at Socket.socketOnEnd (node:_http_client:525:23)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

可以看到错误来自vite 或者 node？

### 修改建议

我找到了一个类似的bug 来自于 vite

https://github.com/vitejs/vite/discussions/12839

似乎没有什么解决方案

然后我找到了一篇知乎

https://zhuanlan.zhihu.com/p/86749934

我不太懂前端 抱歉无法提供更加详细的错误信息 或 解决方案

**Comment by piexlmax** [comment]
看起来是超时导致的，没有给到前端响应。

**Comment by bypanghu** [comment]
超时了，gva 默认请求好像最长是 10s 发自我的 iPhone在 2023年8月31日，11:21，奇淼（piexlmax ***@***.***> 写道：﻿
看起来是超时导致的，没有给到前端响应。

**Comment by bypanghu** [comment]
由于长时间未回复，改 issue 将被关闭
