### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by beijJxy** [flipped-aurora/gin-vue-admin#1514]
### 功能描述以及必要性描述

[Bug]: 加群始终没法通过  加群问题是项目名称：我输入gin vue admin / Gin-Vue-Admin 若干答案都说不对

### 建议和方案

[Bug]: 加群始终没法通过  加群问题是项目名称：我输入gin vue admin / Gin-Vue-Admin 若干答案都说不对

**Comment by SliverHorn** [comment]
亲， 您看下是这个项目名： [gin-vue-admin](https://github.com/flipped-aurora/gin-vue-admin) 吗？
