### ISSUE TITLE
[Bug]: /gin-vue-admin/blob/main/deploy/docker/Dockerfile:12

### ISSUE THREAD

**Issue by China-zhang-hui** [flipped-aurora/gin-vue-admin#1518]
### gin-vue-admin 版本

2.4.5beta

### Node 版本

v16.8.3

### Golang 版本

v1.16

### 是否依旧存在

可以

### bug描述

12行语句有点问题，yum -y install yum -y install *epel* 

### 修改建议

是否可以改为 yum -y install epel-release

**Comment by piexlmax** [comment]
@tscuite
