### ISSUE TITLE
[Bug]: 使用代码生成器时报错

### ISSUE THREAD

**Issue by KD-one** [flipped-aurora/gin-vue-admin#1519]
### gin-vue-admin 版本

最新

### Node 版本

v18.17.1

### Golang 版本

go 1.18

### 是否依旧存在

未测试

### bug描述

在使用代码生成器时，按要求填写好内容，点击生成时报错：template%3A+table.vue.tpl%3A256%3A+function+"item"+not+defined

**Comment by zyfjfj** [comment]
我也遇到了，将模板中的
             {{- if eq .FieldType "file" }}
                        <div class="fileBtn" v-for="(item,index) in formData.{{ .FieldJson }}" :key="index">
                          <el-button type="primary" text bg @click="onDownloadFile(item.url)">
                            <el-icon style="margin-right: 5px"><Download /></el-icon>
                            {{item.name}}
                          </el-button>
                        </div>
                {{- end }}
去掉就正常，应该是file类型的bug

**Comment by hesu-aurora** [comment]
template%3A+table.vue.tpl%3A256%3A+function+"item"+not+defined
我也遇到了

**Comment by StephenMing** [comment]
这个问题已解决，更新一下就好了

**Comment by KD-one** [comment]
> 这个问题已解决，更新一下就好了

谢谢

**Comment by KD-one** [comment]
> 

谢谢

**Comment by hesu-aurora** [comment]
收到已更新&nbsp;谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月21日(星期一) 中午11:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flipped-aurora/gin-vue-admin] [Bug]: 使用代码生成器时报错 (Issue #1519)





  
这个问题已解决，更新一下就好了
  
谢谢

**Comment by piexlmax** [comment]
已修复
