### ISSUE TITLE
用户修改密码post请求

### ISSUE THREAD

**Issue by lu569368** [flipped-aurora/gin-vue-admin#152]
用户修改密码路由中定义的是POST请求但是swagger的注释是PUT请求，小问题
`UserRouter.POST("changePassword", v1.ChangePassword)  `
`// @Router /user/changePassword [put]`

**Comment by piexlmax** [comment]
> 用户修改密码路由中定义的是POST请求但是swagger的注释是PUT请求，小问题
> `UserRouter.POST("changePassword", v1.ChangePassword) `
> `// @Router /user/changePassword [put]`

感谢感谢 我去修改 ~

**Comment by lu569368** [comment]
版主好，用户在退出登录时候前端页面是不是应该清除localStorage而不是sessionStorage，前端不太懂，你看下，涉及到的文件目录web\src\store\module
