### ISSUE TITLE
[Feature]: DB Migrate 操作 移除table 欄位問題

### ISSUE THREAD

**Issue by jasonwu513** [flipped-aurora/gin-vue-admin#1523]
### 功能描述以及必要性描述

1. 目前在移除 table column時, 有兩種做法
a. 使用自動化代碼管理, 回滾並刪表,  然後用程式碼產生器 重新產出table 和程式碼, git diff  差異後再把程式碼補回
b. 直接於資料庫移除 column 後, 修改前後端代碼．
, 兩種做法都沒有修改ＤＢ的紀錄,第一種方式有點繁瑣, 第二種團隊合作時有時會不知道成員修改了DB需花時間追蹤.
2. 請問各位大神移除,修改table欄位都怎麼操作? 

### 建议和方案

是否有可能引入類似 Laravel Migration 的做法, 將對ＤＢ的操做都進行記錄, 方便回滾追蹤？

**Comment by SliverHorn** [comment]
手动修改，代码生成器的回滚功能只能作为辅助
