### ISSUE TITLE
[Bug]: rich-edit缺少watch导入

### ISSUE THREAD

**Issue by yefuchao** [flipped-aurora/gin-vue-admin#1528]
### gin-vue-admin 版本

main

### Node 版本

v18.14.0

### Golang 版本

 go1.19.1

### 是否依旧存在

可以

### bug描述

行26. 
` import { onBeforeUnmount, ref, shallowRef, onMounted } from 'vue'`
行85  
`watch(()=>props.modelValue,()=>{
  valueHtml.value = props.modelValue
})
`

**Comment by piexlmax** [comment]
以确定bug，尽快修复。
