### ISSUE TITLE
系统设置 mysql 日志模式错误

### ISSUE THREAD

**Issue by sun-wenming** [flipped-aurora/gin-vue-admin#153]
[mysql-log-mode](https://github.com/flipped-aurora/gin-vue-admin/blob/e9410d884862078da0aeef7e189ac5147b1cc8d9/web/src/view/systemTools/system/system.vue#L49)

`<el-checkbox v-model="config.log.logMode"></el-checkbox>`
应该为：吧
`<el-checkbox v-model="config.mysql.logMode"></el-checkbox>`

**Comment by piexlmax** [comment]
> [mysql-log-mode](https://github.com/flipped-aurora/gin-vue-admin/blob/e9410d884862078da0aeef7e189ac5147b1cc8d9/web/src/view/systemTools/system/system.vue#L49)
> 
> `<el-checkbox v-model="config.log.logMode"></el-checkbox>`
> 应该为：吧
> `<el-checkbox v-model="config.mysql.logMode"></el-checkbox>`

是的  应该是 mysql.logMode 感谢指出 编程疏忽了

**Comment by piexlmax** [comment]
已修复，感谢提issue
