### ISSUE TITLE
[Bug]: 为角色添加权限时，如果有重复api权限，该角色“所有权限”均添加失败（包括登录）

### ISSUE THREAD

**Issue by geek-dream999** [flipped-aurora/gin-vue-admin#1533]
### gin-vue-admin 版本

2.4.5beta

### Node 版本

v20.3.1

### Golang 版本

go1.20.6

### 是否依旧存在

可以

### bug描述

bug发生场景描述：
前置条件：协作开发过程中，假设有两个开发者分别为A和B。会存在一种场景：测试环境到生产环境，api一般会通过sql批量进行添加。

1.在模块【超级管理员/api管理】中，A添加了一个api，B不知道A已经添加了，也添加了同一个api。（通过数据库sql添加）

2.在模块【超级管理员/角色管理】中，为【超级管理员角色】添加api时，程序员一般会习惯性勾选同一个api组的所有api，不会注意到有重复api存在。

3.点击确定。此时代码逻辑会执行进行下面步骤

3.1.清除当前所有api（包括登录和获取菜单树），casbinService.ClearCasbin(0, authorityId)

3.2.添加所有被勾选的api，success, _ := e.AddPolicies(rules)

3.3.如果有重复api，数据库执行sql失败，api添加失败。

4.此时【超级管理员角色】没有任何权限，页面加载失败。而其他角色没有api添加权限，casbin开启的情况下超级管理员账号报废。【严重bug】

## 方案一：
为角色添加api权限时进行api去重处理。代码修改如下
代码目录：gin-vue-admin-main/server/service/system/sys_casbin.go
### 原始代码
`
func (casbinService *CasbinService) UpdateCasbin(AuthorityID uint, casbinInfos []request.CasbinInfo) error {
	authorityId := strconv.Itoa(int(AuthorityID))
	casbinService.ClearCasbin(0, authorityId)
	rules := [][]string{}
	for _, v := range casbinInfos {
		rules = append(rules, []string{authorityId, v.Path, v.Method})
	}
	e := casbinService.Casbin()
	success, _ := e.AddPolicies(rules)
	if !success {
		return errors.New("存在相同api,添加失败,请联系管理员")
	}
	return nil
}
`
### 修改后的代码
`func (casbinService *CasbinService) UpdateCasbin(AuthorityID uint, casbinInfos []request.CasbinInfo) error {
	authorityId := strconv.Itoa(int(AuthorityID))
	casbinService.ClearCasbin(0, authorityId)
	rules := [][]string{}
	//做权限去重处理
	deduplicateMap := make(map[string]bool)
	for _, v := range casbinInfos {
		key := authorityId + v.Path + v.Method
		if _, ok := deduplicateMap[key]; !ok {
			deduplicateMap[key] = true
			rules = append(rules, []string{authorityId, v.Path, v.Method})
		}
	}
	e := casbinService.Casbin()
	success, _ := e.AddPolicies(rules)
	if !success {
		return errors.New("存在相同api,添加失败,请联系管理员")
	}
	return nil
}`

![Snipaste_2023-09-02_20-28-06](https://github.com/flipped-aurora/gin-vue-admin/assets/77595358/f6280c54-999b-4a06-9923-c4115a4f7899)

## 方案二：
【【前端页面维度限制】】
【超级管理员/api管理】
前端页面添加api时，如果有重复的api，后端响应给前端错误并不允许添加。
## 方案三
【【数据库设计维度限制】】
表【sys_apis】
为这三个字段增加唯一索引`path`, `api_group`, `method`

**Comment by piexlmax** [comment]
感谢，我们会在复现后尝试修复，您可以提交pr来自行修复此问题~

**Comment by geek-dream999** [comment]
好的，我稍后会提交一个pr

**Comment by geek-dream999** [comment]
https://github.com/flipped-aurora/gin-vue-admin/compare/main...geek-dream999:gin-vue-admin-fork:casbin?expand=1

**Comment by piexlmax** [comment]
您好,pr似乎没有提交成功。

**Comment by geek-dream999** [comment]
你好，我已经从新创建pr了哦。
https://github.com/flipped-aurora/gin-vue-admin/pull/1539

**Comment by piexlmax** [comment]
> 你好，我已经从新创建pr了哦。 #1539

PR已采纳，感谢您支持和贡献开源。

**Comment by tlyyxjz** [comment]
兄弟，你复盘得很细，我追着问几个小细节哈：

1. A、B 是直接 SQL 往 sys_apis 表里插的重复 api 吧？那这表对 path + method 有没有唯一约束？没有的话重复数据就一直躺在表里了。
2. 报错那会儿 AddPolicies 具体给的啥错误？是 "Duplicate entry" 那种不？
3. 失败之后 casbin_rule 表是彻底空了，还是插进去了一部分？
4. 最后咋恢复的？把重复的删掉重新勾选就好了，还是手动补的数据？

主要想分辨下是"重复数据把批量写入搞挂了"，还是"清空后压根没写进去"——两种情况解法不太一样，等你回复～

**Comment by tlyyxjz** [comment]
之前在这帖一起跟进了「重复 api 权限导致角色所有权限（含登录）失败」的问题，你那个 PR #1539 修得漂亮。

我想顺带说个相关的：这种「加权限时因为某条重复就整批失败」的坑，根源往往是 casbin 的 AddPolicies 对重复项的处理。我做了个诊断工具 casbin-config-doctor / authztest，专门在 enforce 结果不符合预期时，逐字段告诉你最接近的策略和差在哪里（含 g 角色继承、wildcard、域），方便以后类似问题秒定位。

已经开源：github.com/tlyyxjz/casbin-config-doctor。后面要是再遇到 casbin 相关的坑，欢迎来提 issue，我帮你用工具跑。
