### ISSUE TITLE
[Bug]: enter重复写入问题。

### ISSUE THREAD

**Issue by wangxingge** [flipped-aurora/gin-vue-admin#1534]
### gin-vue-admin 版本

2.5.7a

### Node 版本

v18.17.1

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

使用的是自动化package  和 代码生成器的功能。
1. 在同一个包里通过代码生成器创建多个Struct时会有enter文件写入错误的问题，比如 service包自定义package的enter中会覆盖上一次的写入的Struct， 应该是继续添加。   在server包中的enter会重复添加同一个包的Service Group.
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/4143166/f8f95f07-83cb-430c-a735-9ececef74d7d)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/4143166/aee43fe3-9e0d-43c6-b112-2bc716ed66bc)

2. 在初始化数据库的过程中缺少对CreateTable或MigrateTables的注入，只在gorm中RegisterTables的有注入，但是这么做需要重启之后才能生效。这是设计上的bug。

3. 还有很多使用上的不合理情况，自动化代码管理器上不能方便的修改现有的model.

### 修改建议

都改了就行。 哈哈哈

**Comment by wangxingge** [comment]
这个bug不是一直能复现的。

**Comment by piexlmax** [comment]
能够提供一下具体的复现场景吗？比如说是快速点击并发之类的，目前来看只有并发操作可能会出现这样的问题。

**Comment by piexlmax** [comment]
第二个是合理的，因为自动添加的内容不仅仅有数据库，还有api，逻辑等，不重启本身就不会生效。
第三个功能会在后续商业版本提供，开源版本不耗费精力制作。
