### ISSUE TITLE
[Bug]: 设置多个环境变量会报错

### ISSUE THREAD

**Issue by qq919006380** [flipped-aurora/gin-vue-admin#1537]
### gin-vue-admin 版本

2.5.7

### Node 版本

15

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

1，删掉原来两个默认的.env.development和.env.production 
2，改成自己的--mode trunk 然后添加.env.trunk 运行会报错 
3，全局搜索development也没搜索到那里用了development
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/26406811/50567a3f-cacf-4c87-91ba-e50c90592fbd)

### 修改建议

支持自定义环境变量

**Comment by bypanghu** [comment]
报错详情呢？发自我的 iPhone在 2023年9月8日，21:53，SummerBytes ***@***.***> 写道：﻿
Assigned #1537 to @bypanghu.

**Comment by bypanghu** [comment]
这个是 vue的相关知识，请自行查看文档，gva前端并没有修改发自我的 iPhone在 2023年9月8日，21:53，SummerBytes ***@***.***> 写道：﻿
gin-vue-admin 版本
2.5.7
Node 版本
15
Golang 版本
1.16
是否依旧存在
可以
bug描述
1，删掉原来两个默认的.env.development和.env.production
2，改成自己的--mode trunk 然后添加.env.trunk 运行会报错
3，全局搜索development也没搜索到那里用了development

修改建议
支持自定义环境变量

**Comment by zyw0605688** [comment]
> ### gin-vue-admin 版本
> 2.5.7
> 
> ### Node 版本
> 15
> 
> ### Golang 版本
> 1.16
> 
> ### 是否依旧存在
> 可以
> 
> ### bug描述
> 1，删掉原来两个默认的.env.development和.env.production 2，改成自己的--mode trunk 然后添加.env.trunk 运行会报错 3，全局搜索development也没搜索到那里用了development ![image](https://user-images.githubusercontent.com/26406811/266630243-50567a3f-cacf-4c87-91ba-e50c90592fbd.png)
> 
> ### 修改建议
> 支持自定义环境变量

别整事儿，没这个玩法，参考vite配置文档https://cn.vitejs.dev/guide/env-and-mode.html

**Comment by piexlmax** [comment]
main已修复
