### ISSUE TITLE
提示“用户名密码错误或record not found”

### ISSUE THREAD

**Issue by mentallxm** [flipped-aurora/gin-vue-admin#154]
数据库也导入了 记录也有 admin 123456 就是没法登陆

**Comment by piexlmax** [comment]
> 数据库也导入了 记录也有 admin 123456 就是没法登陆

方便发一下数据库的截图吗

**Comment by mentallxm** [comment]
![1](https://user-images.githubusercontent.com/13169104/87766119-42615980-c84b-11ea-8412-4dbc3c3d2123.png)
麻烦你看一下，这是数据库的截图

**Comment by mentallxm** [comment]
大佬，请问解决了吗？

**Comment by piexlmax** [comment]
> 大佬，请问解决了吗？

图片一直加载失败，可以加微信 我帮你看下

**Comment by mentallxm** [comment]
> > 大佬，请问解决了吗？
> 
> 图片一直加载失败，可以加微信 我帮你看下

大佬，你微信号发给我吧

**Comment by VGTsome** [comment]
友情提醒下，如果让大佬给你调bug，请先红包加vip群再请教，代码都开源了有问题要不自己调试，要不请知识付费



---原始邮件---
发件人: "mentallxm"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 上午8:06
收件人: "flipped-aurora/gin-vue-admin"<gin-vue-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [flipped-aurora/gin-vue-admin] 提示“用户名密码错误或record not found” (#154)




   
大佬，请问解决了吗？
  
图片一直加载失败，可以加微信 我帮你看下
  
大佬，你微信号发给我吧

**Comment by mentallxm** [comment]
亲人，不好意思，我是个小白，不大懂流程，我加了大佬的微信 了
