### ISSUE TITLE
[Bug]: 添加三级路由，路由与面包屑成功识别，但是页面无法加载，权限也设置了

### ISSUE THREAD

**Issue by Jokerdeath** [flipped-aurora/gin-vue-admin#1548]
### gin-vue-admin 版本

2.5.4

### Node 版本

14.16.0

### Golang 版本

前后端分离了

### 是否依旧存在

可以

### bug描述

1. 给二级菜单对应的页面添加详情页，并且注册为二级页面的子页面
2. 角色设置权限
3. 路由与面包屑成功跳转，但是页面没有跳转

**Comment by bypanghu** [comment]
通过你的描述，我只能了解到，你的详情页面注册在二级菜单的子页面中，但是子级页面需要 <router-view> 组件才能被展示，所以大概率是你使用的问题，请先查看 vue-router 的文档。

**Comment by Jokerdeath** [comment]
> 通过你的描述，我只能了解到，你的详情页面注册在二级菜单的子页面中，但是子级页面需要 组件才能被展示，所以大概率是你使用的问题，请先查看 vue-router 的文档。

有对应的组件，后端返回的路由也都正确，路由可以跳转，但是页面不展示，个人怀疑是keeplive的作用，因为示例也是将本该放在三级的页面放在了二级

**Comment by bypanghu** [comment]
> > 通过你的描述，我只能了解到，你的详情页面注册在二级菜单的子页面中，但是子级页面需要 组件才能被展示，所以大概率是你使用的问题，请先查看 vue-router 的文档。
> 
> 有对应的组件，后端返回的路由也都正确，路由可以跳转，但是页面不展示，个人怀疑是keeplive的作用，因为示例也是将本该放在三级的页面放在了二级

你看示例的 三级页面的父级写的组件是什么组件，不是所有的vue 页面都能作为 父组件的
