### ISSUE TITLE
[Bug]: AutoCode 的时候没有在 TableCreated 中添加新建的表

### ISSUE THREAD

**Issue by tre4sure** [flipped-aurora/gin-vue-admin#1555]
### gin-vue-admin 版本

基于 main 最新版本

### Node 版本

v20.6.1

### Golang 版本

go 1.19.10

### 是否依旧存在

可以

### bug描述

自动代码中添加了 db 自动迁移，为什么没有添加 db 自动创建呢，当前只添加 db 自动迁移的情况下，假如在部署的时候不想导入数据库，而是想直接新建数据库，就需要重新启动后端进行数据迁移的时候创建

### 修改建议

auto code 的时候在 TableCreated 方法中添加表

**Comment by piexlmax** [comment]
此功能无意义，自动化代码不重启后端，api无法生效。
