### ISSUE TITLE
[Feature]: 一个用户登陆时Session自动激活其全部角色，不用切换角色

### ISSUE THREAD

**Issue by Hi-Alan** [flipped-aurora/gin-vue-admin#1556]
### 功能描述以及必要性描述

如题，一个用户可通过组合多个角色获得权限：
- 便于简化单个角色的复杂度，也方便将某个角色的权限授予他人
- 当用户的角色较多时，方便用户使用，无需依次切换角色

### 建议和方案

可基于安全原因，在登陆时自动不激活特定角色。
例如一个人同时具备普通注册用户与系统管理员两个角色，系统管理员角色可手动切换，切换后不再具备普通注册用户角色

**Comment by piexlmax** [comment]
你的角色api权限是分配错误的，切换角色权限为必选api。
