### ISSUE TITLE
角色修改

### ISSUE THREAD

**Issue by diaozhegenyan** [flipped-aurora/gin-vue-admin#156]
提示
![image](https://user-images.githubusercontent.com/67667794/87843263-a9335100-c8e5-11ea-96e2-08a67bbd8857.png)
传输过去的是int类型，后台接收的是string

vue里面怎么转换成string都不行~！

**Comment by diaozhegenyan** [comment]
![image](https://user-images.githubusercontent.com/67667794/87843291-e3045780-c8e5-11ea-9383-40e6349079ff.png)
![image](https://user-images.githubusercontent.com/67667794/87843303-fe6f6280-c8e5-11ea-8d64-440a0077b2da.png)

**Comment by diaozhegenyan** [comment]
![image](https://user-images.githubusercontent.com/67667794/87843310-15ae5000-c8e6-11ea-9001-b93a7dbb0fbe.png)

**Comment by piexlmax** [comment]
更新一下即可 有一个版本存在此bug

**Comment by diaozhegenyan** [comment]
好的 ，已经更新了~。
