### ISSUE TITLE
部署上 kubernates 後遇到 router conflict

### ISSUE THREAD

**Issue by dsfwoo8172** [flipped-aurora/gin-vue-admin#1560]
### gin-vue-admin 版本

2.5.6

### Node 版本

18

### Golang 版本

go 1.18

### 是否依旧存在

未测试

### bug描述

在 server/Dockerfile build image 後在 local 一切正常 部署到 kubernetes 遇到下面 error
`panic: '/swagger/*any' in new path '/swagger/*any' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'`

註解掉後再部署會遇到
`panic: '/health' in new path '/health' conflicts with existing wildcard '/*filepath' in existing prefix '/*filepath'`

**Comment by no-f** [comment]
后续怎么解决的，我也遇到了
