### ISSUE TITLE
[Bug]: mac电脑inter芯片下载安装依赖后运行时报错：../../../go/pkg/mod/modernc.org/libc@v1.24.1/libc_unix.go:34:2: cannot find package

### ISSUE THREAD

**Issue by aa12gq** [flipped-aurora/gin-vue-admin#1561]
### gin-vue-admin 版本

2023/08/11 修正版 L

### Node 版本

v16.16.0

### Golang 版本

go 1.19

### 是否依旧存在

可以

### bug描述

1.拉去项目至本地进入serve文件夹go mod tidy
2. 运行时报错：
 mac@macdeMacBook-Pro  ~/GolandProjects/gin-vue-admin/server  go run .       
../../../go/pkg/mod/modernc.org/libc@v1.24.1/libc_unix.go:29:2: cannot find package
../../../go/pkg/mod/modernc.org/libc@v1.24.1/libc_unix.go:30:2: cannot find package
../../../go/pkg/mod/modernc.org/libc@v1.24.1/libc_unix.go:31:2: cannot find package
../../../go/pkg/mod/modernc.org/libc@v1.24.1/libc_unix.go:34:2: cannot find package

尝试使用go get modernc.org/libc@v1.24.1 手动安装并未解决问题

**Comment by piexlmax** [comment]
升级go到1.21
