### ISSUE TITLE
还有个问题 ，前台怎么访问静态文件啊？

### ISSUE THREAD

**Issue by diaozhegenyan** [flipped-aurora/gin-vue-admin#157]
![image](https://user-images.githubusercontent.com/67667794/87843343-5d34dc00-c8e6-11ea-94cb-ef258d8ec954.png)
我把图片上传到本地，但是前端访问不了。。怎么才能访问呢？

**Comment by piexlmax** [comment]
> ![image](https://user-images.githubusercontent.com/67667794/87843343-5d34dc00-c8e6-11ea-94cb-ef258d8ec954.png)
> 我把图片上传到本地，但是前端访问不了。。怎么才能访问呢？

image标签src属性挂地址即可

**Comment by mentallxm** [comment]
gin的静态文件方式

**Comment by diaozhegenyan** [comment]
嗯嗯 好的。谢谢了~
