### ISSUE TITLE
[Bug]: swagger文档生成后页面不展示

### ISSUE THREAD

**Issue by aaaaaaanthony** [flipped-aurora/gin-vue-admin#1571]
### gin-vue-admin 版本

v2.5.7

### Node 版本

v14.16.0

### Golang 版本

go 1.21.4

### 是否依旧存在

可以

### bug描述

在后台生成完代码,先swag init  再冲洗重新启动,接口也能正常调用,但是swagger文档没有这个接口

**Comment by piexlmax** [comment]
swagger会有浏览器缓存，需要清理掉缓存后尝试。
