### ISSUE TITLE
【建议】前端和后端代码拆分成单独的仓库

### ISSUE THREAD

**Issue by cppfuns** [flipped-aurora/gin-vue-admin#158]

**Comment by piexlmax** [comment]
> _No description provided._

感谢提出建议，本身gin-vue-admin是为了全栈开发而制作，设计初衷是前后端共同使用的，故此没有拆分开两个仓库。

**Comment by cppfuns** [comment]
> > _No description provided._
> 
> 感谢提出建议，本身gin-vue-admin是为了全栈开发而制作，设计初衷是前后端共同使用的，故此没有拆分开两个仓库。
这个和全栈有什么关系。 前后端两个没有关系的框架，一个修改会整体提交 git log， 别人基于这个二次开发也会没法合并维护的。

**Comment by cppfuns** [comment]
算我没说。。。。。。。。

**Comment by FWangZil** [comment]
> > > _No description provided._
> > 
> > 
> > 感谢提出建议，本身gin-vue-admin是为了全栈开发而制作，设计初衷是前后端共同使用的，故此没有拆分开两个仓库。
> 
> 这个和全栈有什么关系。 前后端两个没有关系的框架，一个修改会整体提交 git log， 别人基于这个二次开发也会没法合并维护的。
> 
> 并且前后端的版本也应该是分开的， 现在这样git 很伤心啊。。

我觉得有道理......

**Comment by Ruio9244** [comment]
其实早在第二版刚出来的时候，我们有考虑过前后端项目分仓，后来没有这么做是因为，这个项目作为一个全栈来学习，他们本就是一个单体式架构，只要对项目有个整体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓的，感谢你的建议

**Comment by cppfuns** [comment]
> 体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓

你们是不是对全栈有误解？一个仓库就是全栈？ 要是非得放一个目录。可以试试 Submodule， 
真得分开。。你要是把这个当成自己的项目，一个人维护那凑合随便，但现在是要作为开源框架使用的。。无论怎么将 放一起都是不合适的，git log 混在一起，不能把git 当成备份工具在用。。  我看了下已有的 git log，各种merge。。 算了。。这种问题真没有必要再说了。。

**Comment by granty1** [comment]
> > 体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓
> 
> 你们是不是对全栈有误解？一个仓库就是全栈？ 要是非得放一个目录。可以试试 Submodule，
> 真得分开。。你要是把这个当成自己的项目，一个人维护那凑合随便，但现在是要作为开源框架使用的。。无论怎么将 放一起都是不合适的，git log 混在一起，不能把git 当成备份工具在用。。 我看了下已有的 git log，各种merge。。 算了。。这种问题真没有必要再说了。。

我觉得我们已经说得够清楚了，拆分本来就在计划内的，你非要一直这儿秀智商、刷存在感我也没有办法。

**Comment by cppfuns** [comment]
> > > 体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓
> > 
> > 
> > 你们是不是对全栈有误解？一个仓库就是全栈？ 要是非得放一个目录。可以试试 Submodule，
> > 真得分开。。你要是把这个当成自己的项目，一个人维护那凑合随便，但现在是要作为开源框架使用的。。无论怎么将 放一起都是不合适的，git log 混在一起，不能把git 当成备份工具在用。。 我看了下已有的 git log，各种merge。。 算了。。这种问题真没有必要再说了。。
> 
> 我觉得我们已经说得够清楚了，拆分本来就在计划内的，你非要一直这儿秀智商、刷存在感我也没有办法。

.......  我好心说这么多，被说成秀智商？存在感？   我服了

**Comment by granty1** [comment]
> > > > 体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓
> > > 
> > > 
> > > 你们是不是对全栈有误解？一个仓库就是全栈？ 要是非得放一个目录。可以试试 Submodule，
> > > 真得分开。。你要是把这个当成自己的项目，一个人维护那凑合随便，但现在是要作为开源框架使用的。。无论怎么将 放一起都是不合适的，git log 混在一起，不能把git 当成备份工具在用。。 我看了下已有的 git log，各种merge。。 算了。。这种问题真没有必要再说了。。
> > 
> > 
> > 我觉得我们已经说得够清楚了，拆分本来就在计划内的，你非要一直这儿秀智商、刷存在感我也没有办法。
> 
> ....... 我好心说这么多，被说成秀智商？存在感？ 我服了

从第一条开始，我们就说感谢你的建议，并且使我们的问题开始没有考虑好

**Comment by piexlmax** [comment]
> > > > 体架构图的描述和项目结构描述，就没有必要分仓。之后的微服务版本一定是会分仓
> > > 
> > > 
> > > 你们是不是对全栈有误解？一个仓库就是全栈？ 要是非得放一个目录。可以试试 Submodule，
> > > 真得分开。。你要是把这个当成自己的项目，一个人维护那凑合随便，但现在是要作为开源框架使用的。。无论怎么将 放一起都是不合适的，git log 混在一起，不能把git 当成备份工具在用。。 我看了下已有的 git log，各种merge。。 算了。。这种问题真没有必要再说了。。
> > 
> > 
> > 我觉得我们已经说得够清楚了，拆分本来就在计划内的，你非要一直这儿秀智商、刷存在感我也没有办法。
> 
> ....... 我好心说这么多，被说成秀智商？存在感？ 我服了

非常抱歉，grant是本项目联合开发者，当时项目设计的时候是前后端需要搭配使用的，考虑到用户需要去另外仓库拉取代码并不方便，并且前后端逻辑以来挺大的，因此放在同一个仓库，这是设计的初衷。再次感谢您的建议。

**Comment by liyang-it** [comment]
我就遇到过前后端项目都在一个库，后端和前端人员独立写项目，两个人提交拉取代码经常冲突，搞半天
