### ISSUE TITLE
[Bug]: ast 包的单元测试无效并且无法通过

### ISSUE THREAD

**Issue by 1000Delta** [flipped-aurora/gin-vue-admin#1590]
### gin-vue-admin 版本

main

### Node 版本

\-

### Golang 版本

\-

### 是否依旧存在

可以

### bug描述

对于 `TestImportForAutoEnter()` 和 `TestAddRouterCode()`：

1. 使用了 Windows 下的静态绝对路径，在不同路径，或者 MacOS/Linux 环境下会找不到文件
2. 测试文件在项目目录下不存在

对于 `TestRollRouterBack()` 和 `TestRollGormBack()`：

1. 回滚的内容不存在，并且函数使用的配置在单测中没有初始化
2. 测试的函数内部 error 没有提前 return，会导致后续逻辑出现 nil pointer 等问题最后失败

---

以上问题会导致服务在 ci 等自动化测试场景下失败，建议修复。

### 修改建议

对于文件路径，可以考虑先指定一个默认路径，然后通过 flag 传递特定场景下的路径

例：

```go
package ast

import (
	"flag"
	"testing"
)

// autoEnterPath for user can specify the path of the file to be modified
var autoEnterPath string

func init() {
	flag.StringVar(&autoEnterPath, "autoEnterPath", "../../../server/api/v1/test/enter.go", "The path of the file to be modified in TestImportForAutoEnter")
}

func TestImportForAutoEnter(t *testing.T) {
	flag.Parse()

	ImportForAutoEnter(autoEnterPath, "ApiGroup", "test")
}
```

---

回滚相关的逻辑，建议在测试函数中，补充对应生成代码的逻辑。或者添加多个测试用例之后再通过 `testing.Main` 进行限定测试用例执行的顺序

**Comment by songzhibin97** [comment]
应该是错误提交
