### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zero7cola** [flipped-aurora/gin-vue-admin#1598]
### gin-vue-admin 版本

v2.5.8

### Node 版本

v20.7.0

### Golang 版本

go 1.21.4

### 是否依旧存在

可以

### bug描述

[GIN] 2023/12/18 - 11:13:41 | 200 |     58.9226ms |       127.0.0.1 | POST     "/base/login"

2023/12/18 11:13:41 [Recovery] 2023/12/18 - 11:13:41 panic recovered:
POST /menu/getMenu HTTP/1.1
Host: 127.0.0.1:8888
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: close
Content-Length: 0
Origin: http://localhost:8080
Referer: http://localhost:8080/
Sec-Ch-Ua: "Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiNDg3ODcxOWEtZDFhMy00NDk2LTlkNzQtY2IwY2FhMDA3YWUzIiwiSUQiOjEsIlVzZXJuYW1lIjoiYWRtaW4iLCJOaWNrTmFtZSI6Ik1yLuWlh-a3vCIsIkF1dGhvcml0eUlkIjo4ODgsIkJ1ZmZlclRpbWUiOjg2NDAwLCJpc3MiOiJxbVBsdXMiLCJhdWQiOlsiR1ZBIl0sImV4cCI6MTcwMzQ3NDAyMSwibmJmIjoxNzAyODY5MjIxfQ.XE-phYmCtxhIQUHhWck_n38KUfh_ksEiHMEbu1qhdpA
X-User-Id: 1

runtime error: invalid memory address or nil pointer dereference
C:/Program Files/Go/src/runtime/panic.go:261 (0x90f686)
        panicmem: panic(memoryError)
C:/Program Files/Go/src/runtime/signal_windows.go:364 (0x90f656)
        sigpanic: panicmem()
E:/www/go/pkg/mod/github.com/casbin/casbin/v2@v2.71.1/enforcer_cached_synced.go:61 (0x10879fa)
        (*SyncedCachedEnforcer).Enforce: if atomic.LoadInt32(&e.enableCache) == 0 {
E:/www/go-project/gin-vue-admin/gin-vue-admin-main/server/middleware/casbin_rbac.go:29 (0x1982bee)
        Routers.CasbinHandler.func3: success, _ := e.Enforce(sub, obj, act)
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x152ed0a)
        (*Context).Next: c.handlers[c.index](c)
E:/www/go-project/gin-vue-admin/gin-vue-admin-main/server/middleware/jwt.go:77 (0x1982a09)
        Routers.JWTAuth.func2: c.Next()
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x153ba79)
        (*Context).Next: c.handlers[c.index](c)
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x153ba67)
        CustomRecoveryWithWriter.func1: c.Next()
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x153ac1d)
        (*Context).Next: c.handlers[c.index](c)
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x153abec)
        LoggerWithConfig.func1: c.Next()
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x1539d1a)
        (*Context).Next: c.handlers[c.index](c)
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x15399ad)
        (*Engine).handleHTTPRequest: c.Next()
E:/www/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x15394dc)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
C:/Program Files/Go/src/net/http/server.go:2938 (0xbf9e6d)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
C:/Program Files/Go/src/net/http/server.go:2009 (0xbf5d53)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
C:/Program Files/Go/src/runtime/asm_amd64.s:1650 (0x92bb60)
        goexit: BYTE    $0x90   // NOP

**Comment by songzhibin97** [comment]
请走正常初始化

**Comment by zero7cola** [comment]
> 请走正常初始化

就是正常初始化，在页面上点的

**Comment by zero7cola** [comment]
文档上找到问题了
