### ISSUE TITLE
[Bug]: 自动跳到首页

### ISSUE THREAD

**Issue by beclass** [flipped-aurora/gin-vue-admin#1599]
### gin-vue-admin 版本

2.4.5

### Node 版本

v18.12.1

### Golang 版本

1.18

### 是否依旧存在

未测试

### bug描述

1.打开一个页面，过会儿直接会跳到首页，偶然的。比如页面上输入文字，写着写着，也突然跳到首页，然后内容都没了，也是偶然的，找不到原因。不是有没有人遇到过。

2.一个页面开始没问题，打开console没报错，停留一会儿就报错了
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/12541388/150c413a-8b60-4905-b449-d56a566fdc82)

**Comment by piexlmax** [comment]
没有遇到过 在官方代码demo可否复现
