### ISSUE TITLE
linux下docker快速部署方式

### ISSUE THREAD

**Issue by chenlinzhong** [flipped-aurora/gin-vue-admin#16]
花了点时间，打包了一个docker镜像，方便在linux环境下快速部署

#启动容器
docker run -itd   --net=host --name=go_container   shareclz/go_node /bin/bash;

#进入容器
docker exec -it go_container /bin/bash;
git clone https://github.com/piexlmax/gin-vue-admin.git   /data1/www/htdocs/go/admin;

#启动前端
cd /data1/www/htdocs/go/admin/QMPlusVuePage;
cnpm i ;
npm run serve;

#修改数据库配置
vi  /data1/www/htdocs/go/admin/QMPlusServer/static/dbconfig/config.json;

#启动后端
cd /data1/www/htdocs/go/admin/QMPlusServer;
go run main.go;

**Comment by piexlmax** [comment]
感谢 我将其加入readme并署名
