### ISSUE TITLE
建议分离前后端的代码库，并且新增docker-compose上去方便开发者一键拉起一套依赖环境

### ISSUE THREAD

**Issue by theWayToAI** [flipped-aurora/gin-vue-admin#160]
建议分离前后端的代码库，并且新增docker-compose上去方便开发者一键拉起。

`version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcdefghijk
    ports: 
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379`

我本地亲测可行

**Comment by piexlmax** [comment]
感谢您提出建议，本项目前后端逻辑依赖较大，放在一个库初期考虑是为了方便用户直接拉取使用，后期微服务版本回作为前后端项目分库开发的。再次感谢您的建议。
