### ISSUE TITLE
[Feature]: 关于初始化数据建表的问题

### ISSUE THREAD

**Issue by chenhd** [flipped-aurora/gin-vue-admin#1613]
### 功能描述以及必要性描述

现有自动化生成代码很方便，但是在做环境部署与迁移时，是否能有一种以文本的方式去生成原来的自动化代码，避免再手动生成一次代码

### 建议和方案

通过文本配置的方式，导入配置文件生成目标代码

**Comment by chenhd** [comment]
还有一个疑问是生成的代码是不是不能删除，删除后后续无法正常生成代码

**Comment by piexlmax** [comment]
配置文件模式可以采纳，生成代码删除可以通过回滚功能操作。
