### ISSUE TITLE
[Bug]: 在Edge和chrome浏览器上，清除cookie操作有不同的表现

### ISSUE THREAD

**Issue by HNQX** [flipped-aurora/gin-vue-admin#1614]
### gin-vue-admin 版本

2023/12/31版本

### Node 版本

nodejs 18.19.0

### Golang 版本

go 1.21.5

### 是否依旧存在

可以

### bug描述

先说正常情况，在chrome浏览器上，登陆后清除cookie，会弹出
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/32836634/5e11f209-2f9f-47ec-a476-e61aa915188f)
点击完成按钮后，会跳转路由到登录页面。

不正常情况，按理说edge也是chrome内核，但是当清除cookie后，不会弹窗，也不会跳转路由，这让我感觉有点奇怪。下面是重现视频

chrome【正常】:

https://github.com/flipped-aurora/gin-vue-admin/assets/32836634/caa49b50-81b7-46be-b160-d473cb558f6c

edge【不正常】:

https://github.com/flipped-aurora/gin-vue-admin/assets/32836634/7a5e55f6-03de-44e7-9e7a-65cd7aecf325

**Comment by MQPearth** [comment]
你有没有发现两个弹框内容不太一样?

**Comment by HNQX** [comment]
> 你有没有发现两个弹框内容不太一样?

是啊，都是chromium，可是为什么清除cookie的机制不一样呢？

**Comment by piexlmax** [comment]
我来尽快测试复现修改

**Comment by piexlmax** [comment]
已修复，大概率是cookie设置了httpOnly 目前开发者机器已测试通过。
