### ISSUE TITLE
[Feature]: 登录表单里的密码加MD5

### ISSUE THREAD

**Issue by Mickeywaugh** [flipped-aurora/gin-vue-admin#1618]
### 功能描述以及必要性描述

登录表单里的密码加MD5

### 建议和方案

前端密码字段未加密，存在安全隐患。

**Comment by piexlmax** [comment]
通过抓包获取到任何文字的情况 md5等同与明文 可以自己根据业务修改为 hash加盐模式 目前入库模式为hash加盐 传输过程请自行处理
