### ISSUE TITLE
[Feature]: 时间类型

### ISSUE THREAD

**Issue by ayang2002** [flipped-aurora/gin-vue-admin#1619]
### 功能描述以及必要性描述

项目支持时间类型的更改吗
如果所有时间类型我不想用DataTime而是全部使用TimeStamp需要去哪里配置
如果不支持的话希望大佬能稍微给点更改的建议

**Comment by piexlmax** [comment]
目前支持时间类型 但是用的都是标准Date  如果需要自己修改 可以改动一下后端的生成模板
