### ISSUE TITLE
jwt设置动态更新

### ISSUE THREAD

**Issue by lu569368** [flipped-aurora/gin-vue-admin#162]
版主好，jwt能否设置为动态更新
ExpiresAt: time.Now().Unix() + 60*60*24*7, // 过期时间 一周

**Comment by piexlmax** [comment]
> 版主好，jwt能否设置为动态更新
> ExpiresAt: time.Now().Unix() + 60_60_24*7, // 过期时间 一周

正在开发jwt在接近掉线时间期内自动续期操作

**Comment by xioayangguang** [comment]
版主说的jwt接近过期自动续期，有什么优雅的做法呢，它并不像token一样，完全由后端控制

**Comment by SliverHorn** [comment]
> 版主说的jwt接近过期自动续期，有什么优雅的做法呢，它并不像token一样，完全由后端控制

这个自动续期，指的是旧token作废，重新发个新token

**Comment by xioayangguang** [comment]
发个新token，具体实现步骤？

**Comment by SliverHorn** [comment]
> 发个新token，具体实现步骤？

https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/middleware/jwt.go这个文件里面有个RefreshToken方法，传入旧token的，验证通过了，就会返回一个新token，然后以api形式返回给前端即可

**Comment by xioayangguang** [comment]
但是前端不知道什么时候需要重新获取新token呀，已经过期的token不能换取新token吧。

**Comment by SliverHorn** [comment]
> 但是前端不知道什么时候需要重新获取新token呀，已经过期的token不能换取新token吧。

有token过期时间,前端判断即可，我说的是旧token，而不是过期token

**Comment by mazhuang96** [comment]
> 但是前端不知道什么时候需要重新获取新token呀，已经过期的token不能换取新token吧。

后端判断token是否过期，过期后生成新的token然后返回 HTTP Header: `set-Cookie`, 前端根据`set-cookie`更新x-token  
还有个建议是jwt black list 存储没过期的token, 异地登录被挤掉的token 直接删除就好了，这样数据库不会一直添加无效token，几个用户就有几个token

**Comment by xioayangguang** [comment]
@SliverHorn   假如过期时间是4小时，用户玩到3小时59 分了去上厕所去了，回来token过期，重新登陆，这样体验好吗？

**Comment by xioayangguang** [comment]
@mazhuang96  你说的存黑名单有违jwt的设计初衷，它就是想不用服务端保存任何状态。所以无法让jwt提前过期，即使你知道jwt的token已经泄露，如果加黑名单，这样又回归到了常规的token解决方案上去了，都要去查一次redis 或者其他存储介质。

**Comment by SliverHorn** [comment]
> @SliverHorn 假如过期时间是4小时，用户玩到3小时59 分了去上厕所去了，回来token过期，重新登陆，这样体验好吗？

你还不明白原理吗？前端是知道token的过期时间的，用你的例子，过期时间是4小时，用户玩到3小时59 分了去上厕所去了，这时候你只需要判断快到过期时间的前5分钟（比如），然后去后端带着旧token刷新token，替代旧token不就行嘛？

**Comment by mazhuang96** [comment]
> @mazhuang96 你说的存黑名单有违jwt的设计初衷，它就是想不用服务端保存任何状态。所以无法让jwt提前过期，即使你知道jwt的token已经泄露，如果加黑名单，这样又回归到了常规的token解决方案上去了，都要去查一次redis 或者其他存储介质。

@xioayangguang  黑名单是这个系统自带的，我只是建议改下存储方式，jwt的初衷尽可能短有效期的token，但是，又不能让用户频繁登录，所以可以有两种方法：
1. 我上面说过后端检测过期主动让前端更新，
2. 借鉴OAuth2.0, 后端一次给前端两个token, 时间久一点的`refresh-token`和时间短一点的`access-token`, 前端得到token过期响应时,用 `refresh-token` 去获取新的 `access-token`

@SliverHorn  检测过期的工作一般都是后端做的，不会增加前端工作量

**Comment by xioayangguang** [comment]
一般前端是不知道过期时间的，你返给他的是一个token一串字符，只有解析后才知道里面的过期时间，解析要服务端解析，服务端才有密钥，即使你的消息体是明文，前端可以看到过期时间，但是一般的过期都是以你最后和服务端的交付时间 + left 作为过期时间。就如你所说假设前端在能看到过期时间的前提下，提前五分钟去刷新token，那我玩到3小时54分出去了呢，然后玩了7分钟回来，还是要重新登陆。这种不是解决问题的根本办法。要是不追求完美都是可以接受的，我提前2小时刷新token。

**Comment by SliverHorn** [comment]
> > @mazhuang96 你说的存黑名单有违jwt的设计初衷，它就是想不用服务端保存任何状态。所以无法让jwt提前过期，即使你知道jwt的token已经泄露，如果加黑名单，这样又回归到了常规的token解决方案上去了，都要去查一次redis 或者其他存储介质。
> 
> @xioayangguang 黑名单是这个系统自带的，我只是建议改下存储方式，jwt的初衷尽可能短有效期的token，但是，又不能让用户频繁登录，所以可以有两种方法：
> 
> 1. 我上面说过后端检测过期主动让前端更新，
> 2. 借鉴OAuth2.0, 后端一次给前端两个token, 时间久一点的`refresh-token`和时间短一点的`access-token`, 前端得到token过期响应时,用 `refresh-token` 去获取新的 `access-token`
> 
> @SliverHorn 检测过期的工作一般都是后端做的，不会增加前端工作量

2的机制是可行的，之前我写过python的django rest framework，就是这样做的。

**Comment by xioayangguang** [comment]
> 2\. 后端一次给前端两个token, 时间久一点的

第一种方案：有的端是不支持cookie的，比如微信小程序，你除非在返回数据字段中添加一个特殊字段来做到平台通用，但是这不规范，当然也可以自定义一个响应头。 我感觉这样很麻烦，但是这样能做到 jwt想要的服务端无状态的要求。
第二种方案：refresh-token的方式，网络上好多人都说这样做，但是你想过没有，我都在存refresh-token了，就是脱离了jwt的设计原则，服务端有状态了，失去了jwt的优势，我为什么不用传统的token + redis 来实现呢？

**Comment by mazhuang96** [comment]
> > 2. 后端一次给前端两个token, 时间久一点的
> 
> 第一种方案：有的端是不支持cookie的，比如微信小程序，你除非在返回数据字段中添加一个特殊字段来做到平台通用，但是这不规范，当然也可以自定义一个响应头。 我感觉这样很麻烦，但是这样能做到 jwt想要的服务端无状态的要求。
> 第二种方案：refresh-token的方式，网络上好多人都说这样做，但是你想过没有，我都在存refresh-token了，就是脱离了jwt的设计原则，服务端有状态了，失去了jwt的优势，我为什么不用传统的token + redis 来实现呢？

@xioayangguang  其实`jwt`的使用要看场景的，不是什么都能用，它用来做第三方临时登录、或者验签之类的工作还是蛮好的，但要用在账户保持登录状态，确实有些牵强，也只能用另外的手段保证它不过期

**Comment by xioayangguang** [comment]
@mazhuang96   赞同
这个文章我也很赞同
 https://baijiahao.baidu.com/s?id=1640086402150385071&wfr=spider&for=pc&qq-pf-to=pcqq.group

**Comment by SliverHorn** [comment]
功能已经实现了
