### ISSUE TITLE
[Bug]: 执行 go build -o server main.go报错：package net/netip is not in GOROOT ；更换GOPROXY，go mod tidy 不能解决

### ISSUE THREAD

**Issue by mailrun** [flipped-aurora/gin-vue-admin#1624]
### gin-vue-admin 版本

2.4.5

### Node 版本

10.24.0

### Golang 版本

1.20.10

### 是否依旧存在

可以

### bug描述

:执行 go build -o server main.go报错：package net/netip is not in GOROOT ；
更换GOPROXY，再go mod tidy 不能解决问题

**Comment by bypanghu** [comment]
本地环境问题，非 gva 问题，此 issue 将被关闭
