### ISSUE TITLE
[Bug]: Error 1822 (HY000): Failed to add the foreign key constr aint. Missing index for constraint 'fk_sys_users_authority' in the referenced table 'sys_users'

### ISSUE THREAD

**Issue by yinjunfa** [flipped-aurora/gin-vue-admin#1627]
### gin-vue-admin 版本

master

### Node 版本

v 16

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

初始化建表的时候报错了

### 修改建议

sys_user中缺少外键索引

**Comment by bypanghu** [comment]
fk_sys_users_authority 是什么玩意儿，我咋记得 gva 初始化信息里面没有这个东西

**Comment by yinjunfa** [comment]
在gorm AutoMigrate 初始化建表的时候.
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/44217935/ce714ed4-6413-4c27-ad4a-81d0d8facaa4)

**Comment by piexlmax** [comment]
fk_sys_users_authority 这个key是哪里来的
