### ISSUE TITLE
[Bug]: 请求/api/autoCode/installPlugin接口header头信息里没有带x-token

### ISSUE THREAD

**Issue by haimait** [flipped-aurora/gin-vue-admin#1629]
请求/api/autoCode/installPlugin接口header头信息里没有带x-token

### gin-vue-admin 版本

v2.5.9

### Node 版本

v16.14.2

### Golang 版本

go 1.21.4

### 是否依旧存在

可以

### bug描述

![图片](https://github.com/flipped-aurora/gin-vue-admin/assets/40926384/45c7f803-473d-4bb5-80c9-293cd5bdb1a1)
![图片](https://github.com/flipped-aurora/gin-vue-admin/assets/40926384/9f4c1018-3ca4-411e-a9ec-291c84dce78f)

请求/api/autoCode/installPlugin接口header头信息里没有带x-token

### 修改建议

header头信息里带x-token

**Comment by piexlmax** [comment]
已调整
