### ISSUE TITLE
[Bug]: 配置文件备注错误

### ISSUE THREAD

**Issue by layueshiba** [flipped-aurora/gin-vue-admin#1631]
### gin-vue-admin 版本

master

### Node 版本

14.16

### Golang 版本

1.20

### 是否依旧存在

可以

### bug描述

/server/core/server.go 13行注释拼写错误，因该是“使用mongo”
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/34375375/cf860dbe-3e3a-413d-8c3a-66d771f6b956)

**Comment by songzhibin97** [comment]
可以提个pr来改 如果可以我会将这个任务分配给你 @layueshiba
