### ISSUE TITLE
[Bug]: viper 读取gin自带的环境变量目的未达到

### ISSUE THREAD

**Issue by WaterCool8258** [flipped-aurora/gin-vue-admin#1636]
### gin-vue-admin 版本

v2.5.9

### Node 版本

v20.11

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

服务启动时会先去core.Viper里switch gin.Mode()，代码位置：core/viper.go:29，如下图：
![03{D%X 0XD4I%VG43BGZE(7](https://github.com/flipped-aurora/gin-vue-admin/assets/154291037/8d42a9ad-44c3-4c2c-967c-862ad29ab7cf)
但是设置gin mode的操作却在initialize/router.go:17里，此时gin的mode未经设置，如果命令行不传值且常量存储的环境变量为空时，switch判断永远会走gin.DebugMode。感觉这种处理方式，未达到“viper 读取gin自带的环境变量GIN_MODE,用于区分开发,测试,生产三个环境”的目的

难道是要用export GIN_MODE=release提前设置gin mode？

**Comment by songzhibin97** [comment]
这里可能确实是写的问题，提个pr吧 switch哪里判断configEnv

**Comment by piexlmax** [comment]
gin.Mode()是自动读取环境变量  `GIN_MODE`

![image](https://github.com/flipped-aurora/gin-vue-admin/assets/29840023/46f348f0-9301-4a6e-a223-449ac9b46d35)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/29840023/e3f32270-7695-406c-819c-37822c55299d)

**Comment by WaterCool8258** [comment]
> gin.Mode()是自动读取环境变量 `GIN_MODE`
> 
> ![image](https://private-user-images.githubusercontent.com/29840023/298532648-46f348f0-9301-4a6e-a223-449ac9b46d35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzMzMTUsIm5iZiI6MTcwNTk3MzAxNSwicGF0aCI6Ii8yOTg0MDAyMy8yOTg1MzI2NDgtNDZmMzQ4ZjAtOTMwMS00YTZlLWEyMjMtNDQ5YWM5YjQ2ZDM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAxMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMzE5YTVjZTRiNTlkMTBjODVjOWMwNDEyNWI2MTMwOGZjMmJkM2QzNGJmMDkxZTE5YWQ2MzNiYTVkN2ZjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vt6pgmPOZrVfmMyp5ustdiiVc4DrBNqBV4y7ekwDfUk) ![image](https://private-user-images.githubusercontent.com/29840023/298532684-e3f32270-7695-406c-819c-37822c55299d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzMzMTUsIm5iZiI6MTcwNTk3MzAxNSwicGF0aCI6Ii8yOTg0MDAyMy8yOTg1MzI2ODQtZTNmMzIyNzAtNzY5NS00MDZjLTgxOWMtMzc4MjJjNTUyOTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAxMjMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2N2FmYTYzMDIzZTRmYWJiMWZkYzc4NzkyMjRjZTFiMjY1ZDhiMjllYWYzNmEzZjcwMDZhMzBmZmNmMTNkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B0ru6azyp9Q8m2UKVdKKKP29KSDaSxSEO9Qb0kkr2-4)

可能我没表述清楚，我的意思是，
