### ISSUE TITLE
Docker build fail

### ISSUE THREAD

**Issue by binggg** [flipped-aurora/gin-vue-admin#164]
Building: /usr/bin/node /usr/local/share/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/usr/local/share/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.17.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/share/.config/yarn/global/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/share/.config/yarn/global/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/share/.config/yarn/global/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/usr/local/share/.config/yarn/global/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/share/.config/yarn/global/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/share/.config/yarn/global/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/local/share/.config/yarn/global/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/share/.config/yarn/global/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/share/.config/yarn/global/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21)
gyp verb `which` failed  python Error: not found: python
gyp verb `which` failed     at getNotFoundError (/usr/local/share/.config/yarn/global/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/usr/local/share/.config/yarn/global/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/usr/local/share/.config/yarn/global/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/which/which.js:89:16
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /usr/local/share/.config/yarn/global/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:167:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/share/.config/yarn/global/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/share/.config/yarn/global/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/share/.config/yarn/global/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/share/.config/yarn/global/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/share/.config/yarn/global/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/share/.config/yarn/global/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
gyp ERR! System Linux 4.4.0-130-generic
gyp ERR! command "/usr/bin/node" "/usr/local/share/.config/yarn/global/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/local/share/.config/yarn/global/node_modules/node-sass
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
[0minfo Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command '/bin/sh -c yarn global add cross-env node-sass' returned a non-zero code: 1
script returned exit code 1

**Comment by piexlmax** [comment]
收到 会尽快调试修复

**Comment by binggg** [comment]
@piexlmax 👍

我是 @TencentCloudbase 云开发团队的
在尝试把使用 [https://github.com/TencentCloudBase/cloudbase-framework](https://github.com/TencentCloudBase/cloudbase-framework) 这个工具来把咱们项目一键部署到云开发上

**Comment by piexlmax** [comment]
> @piexlmax 👍
> 
> 我是 @TencentCloudBase 云开发团队的
> 在尝试把使用 https://github.com/TencentCloudBase/cloudbase-framework 这个工具来把咱们项目一键部署到云开发上

感谢认可 团队会尽快修复此bug

**Comment by SliverHorn** [comment]
Hello, our project already supports docker-compose, you can try again, if you need to modify the server parameters, go to docker/server-handle.sh and modify as needed.

**Comment by binggg** [comment]
thanks~
