### ISSUE TITLE
[Feature]: 我想请问下大家做单元测试的方式

### ISSUE THREAD

**Issue by chenhd** [flipped-aurora/gin-vue-admin#1646]
### 功能描述以及必要性描述

因为有一些业务依赖于框架的context，如果写test案例去调用的话 global相关的数据会报引用错误，想请问下大家平时都是怎么做的业务接口单元测试

**Comment by piexlmax** [comment]
创建一个用于单元测试的global 跑单测时候 走测试用global

**Comment by chenhd** [comment]
thanks！
