### ISSUE TITLE
登录密码问题

### ISSUE THREAD

**Issue by universon123** [flipped-aurora/gin-vue-admin#165]
大佬好，登录时总是报错，即使输入了正确的账号和密码也是一样，报错：用户名密码错误或record not found
![image](https://user-images.githubusercontent.com/34357161/88272421-4558c000-cd0b-11ea-97dc-2eccfdb1b46f.png)

**Comment by SliverHorn** [comment]
请问你有没有导入server/db里面的sql？

**Comment by piexlmax** [comment]
> 大佬好，登录时总是报错，即使输入了正确的账号和密码也是一样，报错：用户名密码错误或record not found
> ![image](https://user-images.githubusercontent.com/34357161/88272421-4558c000-cd0b-11ea-97dc-2eccfdb1b46f.png)

此类情况检查数据库版本 低于5.6确实会有此类现象发生
