### ISSUE TITLE
[Feature]: 界面支持分栏

### ISSUE THREAD

**Issue by zyw0605688** [flipped-aurora/gin-vue-admin#1650]
### 功能描述以及必要性描述

[参考地址](https://vue-admin-beautiful.com/admin-plus/?hmsr=authorization&hmpl=&hmcu=&hmkw=&hmci=#/index)

![微信截图_20240204143643](https://github.com/flipped-aurora/gin-vue-admin/assets/40220158/5637d792-c50c-491e-bcd5-286664267e2b)

界面更加时尚大气

### 建议和方案
有子链接时，显示二级列表。没有子链接时不显示。
默认是否打开子链接的第一个，由客户自己决定
参考https://admin.spicyboy.cn/#/home/index，需要设置成分栏布局才能体验

**Comment by piexlmax** [comment]
开源版不提供此类支持
