### ISSUE TITLE
[Feature]: 对移动端不是很友好，希望有夜间模式

### ISSUE THREAD

**Issue by pd5200** [flipped-aurora/gin-vue-admin#1654]
### 功能描述以及必要性描述

1.用手机端查看或者修改东西，特别是弹窗。字段显示，都很不友好。都紧缩在一起。
2.各种表格等的边框显示太淡了，特别是权限哪些按钮，根本看不出来有按钮。。
3.什么时候上一个夜间模式。现在是商务黑，也不是夜间模式。
只是小小建议，可以不满足。可能是自己的感觉到的不足吧。

**Comment by piexlmax** [comment]
开源版不添加手机适配和夜间模式

**Comment by pd5200** [comment]
付费版本 有适配吗
