### ISSUE TITLE
[Bug]: tab栏的问题

### ISSUE THREAD

**Issue by beclass** [flipped-aurora/gin-vue-admin#1658]
### gin-vue-admin 版本

2.4.5

### Node 版本

v18.12.1

### Golang 版本

1.18

### 是否依旧存在

可以

### bug描述

首先用饿了么ui的el-pagination分页，为了实现刷新页面后数据还在当前页，所以页数变化的时候去更新路由参数，加上了page。但是url?page=1,url?page=2,url?page=xxx 每个都会进到tab栏里，翻了10页就有10个tab，这个怎么修复呢？

### 修改建议

一个页面就一个tab栏

**Comment by piexlmax** [comment]
后面会针对本功能增加配置，适配此类情况。

**Comment by piexlmax** [comment]
使用方法 emitter.on('setQuery', (query))

**Comment by beclass** [comment]
场景是这样的，首先有一个打开了tab，是文章列表页，在这个页面上加伤了筛选，出来后有两条数据。然后从这个页面跳出去开了一个新的tab。这个时候再点到文章列表那个tab，就又回到了全部列表，我想保留上次的筛选条件，我如果把参数加到地址栏query里，那么就会多出一个文章列表tab。
