### ISSUE TITLE
[Feature]: 建议添加和当前项目的ESlint配套的.prettierrc

### ISSUE THREAD

**Issue by qazwsx9288** [flipped-aurora/gin-vue-admin#1662]
### 功能描述以及必要性描述

# 建议添加和当前项目的ESlint配套的.prettierrc

直接在当前ESlint环境下编写代码的体验相对比较糟糕，如果有条件的话，建议出一个GVA项目官方的prettier配置文件。

**Comment by piexlmax** [comment]
当前项目存在.eslintrc.js 
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/29840023/489ba0ff-61b2-4435-a9ad-4f358ac232d3)
目前项目的格式化基于webstrom的 fix eslint进行格式化，后续会配置prettier文件。
