### ISSUE TITLE
[Feature]: 预留了命令行启动读取配置文件，为啥不启用

### ISSUE THREAD

**Issue by BinRich** [flipped-aurora/gin-vue-admin#1663]
### 功能描述以及必要性描述

在main.go入口第24行`global.GVA_VP = core.Viper() // 初始化Viper`，进入函数Viper看到`func Viper(path ...string) *viper.Viper {
	var config string

	if len(path) == 0 {}else{}`有对参数path判断来决定，是读取当前默认配置文件还是命令行启动之地路径读取配置文件

### 建议和方案

把main.go入口第24行`global.GVA_VP = core.Viper() // 初始化Viper`改成`global.GVA_VP = func()*viper.Viper {
		if len(os.Args) > 1 {
			return core.Viper(os.Args[1]) // 使用命令行参数初始化Viper
		}
		return core.Viper() // 使用默认配置初始化Viper
	}()`

**Comment by piexlmax** [comment]
这一块书写时候遵循了传统的模式进行，实际上go不是特别依赖与环境变量来调整配置文件，后续会开发一个更加合适的方案来替换。
