### ISSUE TITLE
[Feature]: support mongo

### ISSUE THREAD

**Issue by bryanchen463** [flipped-aurora/gin-vue-admin#1666]
### 功能描述以及必要性描述

请问支持mongodb吗，我看代码里面已经预留了mongodb的支持，但是初始化数据库没有mongo的选项，目前是否支持了mongodb。

### 建议和方案

如上

**Comment by piexlmax** [comment]
提供了mongo工具封装，配置好参数即可使用。并不是库可以完全使用mongo
