### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by liu2015** [flipped-aurora/gin-vue-admin#1681]
### gin-vue-admin 版本

main

### Node 版本

18

### Golang 版本

1.22.1

### 是否依旧存在

可以

### bug描述

server/utils/ast/ast_enter.go

以下这句传入的参数0o600 改成0600
	return os.WriteFile(filepath, buffer.Bytes(), 0600)

func ImportReference(filepath, importCode, structName, packageName, groupName string) error {
	fSet := token.NewFileSet()
	fParser, err := parser.ParseFile(fSet, filepath, nil, parser.ParseComments)
	if err != nil {
		return err
	}
	importCode = strings.TrimSpace(importCode)
	v := &Visitor{
		ImportCode:  importCode,
		StructName:  structName,
		PackageName: packageName,
		GroupName:   groupName,
	}
	if importCode == "" {
		ast.Print(fSet, fParser)
	}

	ast.Walk(v, fParser)

	var output []byte
	buffer := bytes.NewBuffer(output)
	err = format.Node(buffer, fSet, fParser)
	if err != nil {
		log.Fatal(err)
	}
	// 写回数据
	return os.WriteFile(filepath, buffer.Bytes(), 0o600)
}

以下这句传入的参数0o600 改成0600
	return os.WriteFile(filepath, buffer.Bytes(), 0600)

### 修改建议

以下这句传入的参数0o600 改成0600
	return os.WriteFile(filepath, buffer.Bytes(), 0600)

**Comment by SliverHorn** [comment]
<img width="516" alt="image" src="https://github.com/flipped-aurora/gin-vue-admin/assets/45428434/cebc6eeb-9410-4067-901d-10e0090ef292">
