### ISSUE TITLE
[Bug]: 从数据库存在表生成代码,如果数据表 已经 有created_at 字段,生成代码 重复

### ISSUE THREAD

**Issue by vlbyurpn34336** [flipped-aurora/gin-vue-admin#1695]
### gin-vue-admin 版本

2.6.2

### Node 版本

v18

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

![image](https://github.com/flipped-aurora/gin-vue-admin/assets/120798766/decf34af-f9c4-4ff4-9e67-b3fecc3312fb)

### 修改建议

从数据库存在表生成代码,如果数据表 已经 有created_at 字段,生成代码 重复

**Comment by pixelmaxQm** [comment]
此处增加检测，将会尽快修复
