### ISSUE TITLE
[Bug]: 最新2.6.2版本。出现   json: cannot unmarshal string into Go struct field abc.level of type int

### ISSUE THREAD

**Issue by pd5200** [flipped-aurora/gin-vue-admin#1698]
### gin-vue-admin 版本

2.6.2

### Node 版本

最新版

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

这个问题，我查看提交的信息，是字典本来应该提交的的是数字，但是现在变成了字符串。。

### 修改建议

本人小白，不知道如何修改..

**Comment by pd5200** [comment]
我的字典一个选择整型一个选择字符串类型，出来都是 
 
{abc: "0", bbbb: "1"}
 那么哪里选择，怎么控制上传选择的类型。不然默认都是string型。我的字典都是int型的

**Comment by bypanghu** [comment]
前端可以强制转成 数字就可以了发自我的手机

**Comment by pd5200** [comment]
好吧。先强制转换了

**Comment by pixelmaxQm** [comment]
字典如果跟随版本更新前端也会修改为字符串 合并即可
