### ISSUE TITLE
关于配置https证书的问题

### ISSUE THREAD

**Issue by lu569368** [flipped-aurora/gin-vue-admin#171]
func LoadTls() gin.HandlerFunc {
	return func(c *gin.Context) {
		middleware := secure.New(secure.Options{
			SSLRedirect: true,
			SSLHost:     "localhost:443",
		})
		err := middleware.Process(c.Writer, c.Request)
		if err != nil {
			//如果出现错误，请不要继续。
			fmt.Println(err)
			return
		}
		// 继续往下处理
		c.Next()
	}
}
版主好，请问一下这块如何配置https的证书呢！

**Comment by SliverHorn** [comment]
Hello, please see the configuration of this warehouse and configure it according to the actual situation. The github address is [github.com/unrolled/secure](https://github.com/unrolled/secure)

**Comment by live106** [comment]
我怀疑这块儿根本就没有测过，调了个中间件以为就好使了，代码里连监听tls的服务都没调用。
