### ISSUE TITLE
[Bug]: 媒体库上传图片回显404

### ISSUE THREAD

**Issue by xiasiqiu** [flipped-aurora/gin-vue-admin#1718]
### gin-vue-admin 版本

2.4.5

### Node 版本

16.20.1

### Golang 版本

1.21.1

### 是否依旧存在

可以

### bug描述

1、部署到线上环境（官方测试环境同样）后，在媒体库上传图片（普通或压缩）；
2、上传成功，但图片回显404，地址为代理地址拼接；

**Comment by bypanghu** [comment]
请设置 nginx 代理

**Comment by xiasiqiu** [comment]
前端项目部署已按文档设置代理，访问接口交互正常，就图片回显404，访问官方的测试环境看也有同样的情况，请问是还有其他地方需要配置吗？

**Comment by xiasiqiu** [comment]
> 请设置nginx代理

项目部署已按文档设置代理，接口访问交互正常，就图片回显404，访问官方的测试环境看也有同样的情况，请问还有其他地方需要配置吗？

**Comment by pixelmaxQm** [comment]
粘贴一下你的图片访问相关代码

**Comment by xiasiqiu** [comment]
> 粘贴一下你的图片访问相关代码

pull了最新的代码直接打包部署到服务器上，前端部署时单独设置了nginx如下：
   location /api {
       proxy_set_header Host $http_host;
       proxy_set_header  X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header X-Forwarded-Proto $scheme;
       rewrite ^/api/(.*)$ /$1 break;  #重写
       proxy_pass http://127.0.0.1:8889; # 设置代理服务器的协议和地址
    }

   location /api/swagger/index.html {
       proxy_pass http://127.0.0.1:8889/swagger/index.html;
    }




接口配置域名：http://api.demo.com/（例子）
前端配置域名：http://admin.demo.com/（例子）

前端配置：
ENV = 'production'
#下方为上线需要用到的程序代理前缀，一般用于nginx代理转发
VITE_BASE_API = /api
VITE_FILE_API = /api
#下方修改为你的线上ip（如果需要在线使用表单构建工具时使用，其余情况无需使用以下环境变量）
VITE_BASE_PATH = http://api.demo.com/（例子）

前端访问功能正常，只是图片上传功能回显的图片地址404,
图片链接：http://admin.demo.com/api/uploads/file/04e766bed1042cdaab1e3e20e7343c1e_20240417103301.jpg

**Comment by pixelmaxQm** [comment]
大概率你是用的宝塔部署，宝塔内部自动过滤了.png等后缀的访问 自行关闭即可

**Comment by xiasiqiu** [comment]
> 大概率你是用的宝塔部署，宝塔内部自动过滤了.png等后缀的访问 自行关闭即可

解决了，前端确实使用的宝塔部署的，创建网站后默认配置的nginx里面过滤了这些图片的访问，涨姿势了

**Comment by xiasiqiu** [comment]
nginx中关闭图片后缀过滤限制
