### ISSUE TITLE
代码生成后的数据表不存在问题

### ISSUE THREAD

**Issue by theWayToAI** [flipped-aurora/gin-vue-admin#172]
按照文档的操作步骤：http://doc.henrongyi.top/base/pubic.html#%E6%8E%A8%E8%8D%90%E7%9A%84%E5%BC%80%E5%8F%91%E6%A8%A1%E5%BC%8F
然后后台启动后报如下错误：
`panic: Error 1146: Table 'qmPlus.api_accounts' doesn't exist`
这个表还需要自己写sql把字段类型啥的都自己创建吗？

**Comment by theWayToAI** [comment]
如果是这样的话，那能否新增一个功能：导出的文件里面包含这个表数据结构的sql文件？

**Comment by piexlmax** [comment]
> 如果是这样的话，那能否新增一个功能：导出的文件里面包含这个表数据结构的sql文件？

您需要到 http://doc.henrongyi.top/help/#step4%EF%BC%9A%E6%B3%A8%E5%86%8C%E8%B7%AF%E7%94%B1%E5%92%8C%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8

**Comment by theWayToAI** [comment]
我注册了autoMigrate了的，就是因为我做了这些东西还是不行所以我才觉得疑惑，才在这里开了issue的，我根据你的文档：http://doc.henrongyi.top/
完全都看完了，也都走通了所有流程了，就是数据库表是我自己建立的，就只剩这个问题，而且增删改查的demo我都写好并且成功实现了，但是这里的autoMigrate后如果没有这张表的话就会报上面的这个错误，我觉得很奇怪

**Comment by theWayToAI** [comment]
我把你原来的数据表删掉几个试了下，你原来的表是可以生成，但是我加上我的model.APIAccount{}就不行，就会报`panic: Error 1146: Table 'qmPlus.api_accounts' doesn't exist`，感觉好奇怪啊，我把文档和代码都看了遍，没遗漏啥呀

**Comment by piexlmax** [comment]
是否重复创建了 id created_at 等字段

**Comment by theWayToAI** [comment]
没有呢，数据结构是这样的：
`type APIAccount struct {
      gorm.Model
      ApiKey  string `json:"apiKey" form:"apiKey" gorm:"column:api_key;comment:'apiKey账号';type:varchar"`
      Secret  string `json:"secret" form:"secret" gorm:"column:secret;comment:'秘钥';type:varchar"`
      Password  string `json:"password" form:"password" gorm:"column:password;comment:'密码';type:varchar"`
      Exchange  string `json:"exchange" form:"exchange" gorm:"column:exchange;comment:'交易所';type:varchar"`
      AccountName  string `json:"accountName" form:"accountName" gorm:"column:account_name;comment:'账户名称';type:varchar"`
      Balance  float64 `json:"balance" form:"balance" gorm:"column:balance;comment:'余额';type:decimal"`
      Remark  string `json:"remark" form:"remark" gorm:"column:remark;comment:'备注';type:varchar"` 
}`

**Comment by SliverHorn** [comment]
gorm的Tag的类型type:varchar，这个varchar没有大小，gorm生成sql会报创建模型的创建sql语句报错，你需要把server/config.yaml的log-mode选项设置为true，查看sql是否生成正确

**Comment by theWayToAI** [comment]
@SliverHorn 可以了，就是这个问题，谢谢了，这个代码是自动生成的，字段长度不是必选的所以没填。如果可以的话可以加上适当的校验可能会好些。 算是一个小坑吧，还在摸索学习中，谢谢大家，我关了这个issue
