### ISSUE TITLE
[Bug]: DisableForeignKeyConstraintWhenMigrating为true时角色表会创建失败

### ISSUE THREAD

**Issue by coincoc** [flipped-aurora/gin-vue-admin#1720]
### gin-vue-admin 版本

2.6.2

### Node 版本

18.0.0

### Golang 版本

1.22.2

### 是否依旧存在

可以

### bug描述

大佬，你好
1. 我在学习这个帅气的框架时发现将DisableForeignKeyConstraintWhenMigrating注释会导致创建sys_authorities表失败，如果这不是个bug，请让我删除这个问题
2. 当我将model/sys_user.go文件中的references:AuthorityId删除可以创建
3. 目前我还go和gorm还是学习阶段，在搜索引擎中搜索之后没有解决它，如果这个问题很小白，我很抱歉。
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/67940946/72bff82f-e571-417a-aaf9-56d43508a7a8)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/67940946/d3cf384a-54d9-4326-b4cf-17094d865180)

**Comment by pixelmaxQm** [comment]
这里是需要关闭的，开启状态下比较依赖数据库配置。

**Comment by coincoc** [comment]
> 这里是需要关闭的，开启状态下比较依赖数据库配置。

谢谢你的解答，我了解到了
