### ISSUE TITLE
[Bug]: table.vue.tpl  getDetails方法没有定义

### ISSUE THREAD

**Issue by Starismoon** [flipped-aurora/gin-vue-admin#1726]
### gin-vue-admin 版本

v2.6.3

### Node 版本

V

### Golang 版本

go 1.20

### 是否依旧存在

可以

### bug描述

server/resource/autocode_template/web/table.vue.tpl    getDetails方法没有定义

**Comment by DG9Jww** [comment]
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/84201009/36c27468-0c0f-4dc3-abe2-603f79d18c05)

复议，同样存在此问题，目前所有条目都无法查看详细！

**Comment by pixelmaxQm** [comment]
此功能已经剔除，页面条目忘记删除，目前已调整。
