### ISSUE TITLE
富文本报错

### ISSUE THREAD

**Issue by stivein** [flipped-aurora/gin-vue-admin#1734]
### gin-vue-admin 版本

last

### Node 版本

v18.15.0

### Golang 版本

go version go1.21.6 windows/amd64

### 是否依旧存在

可以

### bug描述

1.创建富文本编辑框
2.在富文本中输入内容内容只要是带标签的,超链或者加粗斜体
3.创建成功之后再次点击变更就会报错

**Comment by pixelmaxQm** [comment]
已修复
