### ISSUE TITLE
Casbin 权限问题 [Bug]: 

### ISSUE THREAD

**Issue by colbort** [flipped-aurora/gin-vue-admin#1738]
### gin-vue-admin 版本

main

### Node 版本

18

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

1、同一份代码发布之后；api/menu/getMenu 报错 权限不足；本地没有任何问题
2、https://xochat.sn12.xyz/#/login
[game_2024-05-08.sql.zip](https://github.com/flipped-aurora/gin-vue-admin/files/15270701/game_2024-05-08.sql.zip)

### 修改建议

<img width="1039" alt="Snipaste_2024-05-10_13-36-51" src="https://github.com/flipped-aurora/gin-vue-admin/assets/47207881/b99f542d-5c76-4809-88ca-fb48b1dd6aa5">
<img width="1039" alt="Snipaste_2024-05-10_13-36-51" src="https://github.com/flipped-aurora/gin-vue-admin/assets/47207881/bbd6e6a9-0366-4031-b49b-6ebf85413377">

**Comment by richarduncle** [comment]
碰到过，清理一下浏览器缓存解决了。

**Comment by pixelmaxQm** [comment]
> 碰到过，清理一下浏览器缓存解决了。

那估计是缓存使用了上一个版本的token
