### ISSUE TITLE
[Bug]: 使用了未定义方法

### ISSUE THREAD

**Issue by Ale6333499** [flipped-aurora/gin-vue-admin#1741]
### gin-vue-admin 版本

2.6.4

### Node 版本

v20.0.0

### Golang 版本

go 1.0.0

### 是否依旧存在

可以

### bug描述

此issue不算是bug，pluginTable.vue中使用了未定义的方法,建议调整。
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/113077418/ba6d1e8e-b52b-4259-b112-3fe57cf48978)

**Comment by pixelmaxQm** [comment]
感谢，将会完善本方法。
