### ISSUE TITLE
[Bug]: 超级管理员-用户管理-编辑当前用户头像成功后，没有更新右上角账号头像

### ISSUE THREAD

**Issue by wdy6688** [flipped-aurora/gin-vue-admin#1744]
### gin-vue-admin 版本

2024年5月16号10点50分版本

### Node 版本

2024年5月16号10点50分版本

### Golang 版本

2024年5月16号10点50分版本

### 是否依旧存在

未测试

### bug描述

官网demo版本：
1.此时用户管理列表里的本人用户头像与当前登录账号上一致
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/d986b623-f13c-4e69-b9b6-aea74c46feb2)
2.超级管理员-用户管理：编辑本人用户头像
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/a1a70761-b026-4292-961a-a073860c78d7)
3.修改成功后，右上角的头像没有同步更新
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/79233221-b6ef-44f5-9b57-1ab89c849067)

### 修改建议

当修改的用户是当前用户时，修改成功后及时更新userStore.userInfo.headerImg

**Comment by pixelmaxQm** [comment]
编辑用户中无法直接修改右上角 需要刷新
