### ISSUE TITLE
[Bug]: 【超级管理员-用户管理】用户头像错乱的bug

### ISSUE THREAD

**Issue by wdy6688** [flipped-aurora/gin-vue-admin#1745]
### gin-vue-admin 版本

2024年5月16号16点10分版本

### Node 版本

2024年5月16号16点10分版本

### Golang 版本

2024年5月16号16点10分版本

### 是否依旧存在

可以

### bug描述

【超级管理员-用户管理】
1.非本人的其他用户-编辑用户-去掉头像-确定保存，没有更新到用户列表头像
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/e3cc7743-f999-4aea-a942-7a677beceb65)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/33555113-f88a-44c3-a302-b0e323d1f455)
2.本人用户-编辑-去掉头像-确认保存后，用户列表中没有更新，但刷新页面后用户列表中所有头像都变成无头像，只要本用户再次选择头像并报错，刷新后其他头像也重新出现了
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/b2c11de9-0e74-4244-b428-237e7e52155b)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/cd71c15a-428c-4aa2-b30b-d061ef4b6385)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/ca18c5d1-51f9-4b57-a958-860522a284e2)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/96fb1876-6dad-4373-8e14-dbed70856e9c)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/5ec41a4b-3def-4963-aba9-5646e474c08f)
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/71632722/aa1188c2-e87f-482a-9807-cbb092f4bd36)

### 修改建议

1.CustomPic组件把userStore.userInfo.headerImg改为picSrc
2.右上角的头像显示，引入CustomPic组件时传递 :picSrc=userStore.userInfo.headerImg"

**Comment by pixelmaxQm** [comment]
我们尽快复现

**Comment by pixelmaxQm** [comment]
无法复现
