### ISSUE TITLE
[Feature]: 是否可以使用vxe-table替换el-table

### ISSUE THREAD

**Issue by juneyx** [flipped-aurora/gin-vue-admin#1752]
### 功能描述以及必要性描述

想要让table区域实现高度自适应页面，当数据条数比较多的时候在table内进行滚动而不是页面内滚动，保持页数选择和查询条件控件区域一直在页面中固定显示，感觉上操作起来会更舒服或者方便。

### 建议和方案

我用[vxe-table](https://github.com/x-extends/vxe-table)替换el-table进行了测试，目前效果是页面加载时会自动处理高宽，能实现计划的效果，但是页面如果加载完成之后分辨率或者缩放比例发生变化，table还是会超出页面。

目前效果像这样子吧
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/63502979/c69a3fd8-9534-4467-9dfb-033dd23b1a3f)

**Comment by calvinchan22** [comment]
想要实现表格高度自适应 改一下样式就好了吧 el-table本身也是支持设置height

**Comment by calvinchan22** [comment]
> > 想要实现表格高度自适应 改一下样式就好了吧 el-table本身也是支持设置height
> 
> 主要我没整明白el-table怎么去自适应不同分辨率下的高度，比如说2k屏下可能查询条件就一行，但是1080下查询条件就会变成两行，写固定height的话这种情况要么超出去要么少一节。有没有大致思路方向我再去学习下看看。

我理解你现在的问题点在于 头部的搜索栏在低分辨率下会导致换行，高分辨率和低分辨率下高度不一致

1.用Y轴的三栏布局，表格外面还是要套一层div 设置flex：1，el-table height设置100%，可以实现表格高度自适应不会出现全屏滚动，但是解决不了搜索换行的问题

2.搜索换行可以自己封装一个展开，收起的容器去做
3.如果要兼容1080，就不建议表格高度自适应了，因为1080下 搜索筛选项过多，可能表格内部可视区域就2条数据，滚动就很鸡肋了
