### ISSUE TITLE
[Bug]:导入excel数据报空指针异常

### ISSUE THREAD

**Issue by Rulessly** [flipped-aurora/gin-vue-admin#1766]
### gin-vue-admin 版本

2.6.1

### Node 版本

v15.14.0

### Golang 版本

go 1.22

### 是否依旧存在

未测试

### bug描述

needCreated := tx.Migrator().HasColumn(template.TableName, "created_at")
needUpdated := tx.Migrator().HasColumn(template.TableName, "updated_at")
在导入excel数据时，HasColumn方法的第一个参数接收字符串数据会报空指针异常，但传入结构体正常。
![fafd9d4cb85051d95f5cb60d79650fdb](https://github.com/flipped-aurora/gin-vue-admin/assets/41173895/6e49e897-2596-463e-8050-ae91eb1149be)
![1717655679436](https://github.com/flipped-aurora/gin-vue-admin/assets/41173895/486941d8-d720-44ec-9b7c-3574a6c5ec2b)

**Comment by Rulessly** [comment]
第二张图弄错了，应该是这个
![1717656127698](https://github.com/flipped-aurora/gin-vue-admin/assets/41173895/6bfbf307-30da-4a7f-ba92-97d03d36162d)

**Comment by pixelmaxQm** [comment]
此问题新版本已修复
