### ISSUE TITLE
[Bug]: GVA城市地区管理插件所需的geoDB没了

### ISSUE THREAD

**Issue by SimonUTD** [flipped-aurora/gin-vue-admin#1769]
### gin-vue-admin 版本

2.4.5

### Node 版本

14.16

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

GVA城市地区管理插件所需的geoDB没了

### 修改建议

哪里可以下到？

**Comment by pixelmaxQm** [comment]
https://github.com/flipped-aurora/geoDB

**Comment by SimonUTD** [comment]
> https://github.com/flipped-aurora/geoDB

缺少了数据库初始化脚本

**Comment by pixelmaxQm** [comment]
自己执行这三个SQL文件呀
