### ISSUE TITLE
[Bug]: Error #01: write tcp 127.0.0.1:8888->127.0.0.1:52938: i/o timeout

### ISSUE THREAD

**Issue by brook-w** [flipped-aurora/gin-vue-admin#1779]
### gin-vue-admin 版本

latest

### Node 版本

18

### Golang 版本

go 1.21

### 是否依旧存在

可以

### bug描述

1. 会时不时出现这个错误
windows linux 都会出现 机器配置都很高不会出现资源不够的情况
win: win10 专业版 96G 内存
linux: rocky9.3 内存 512G
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/42824702/b106fb17-4013-4a25-92a4-c7a8d87edff3)

### 修改建议

1. 会时不时出现这个错误
windows linux 都会出现 机器配置都很高不会出现资源不够的情况
win: win10 专业版 96G 内存
linux: rocky9.3 内存 512G
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/42824702/b106fb17-4013-4a25-92a4-c7a8d87edff3)

**Comment by brook-w** [comment]
func initServer(address string, router *gin.Engine) server {
	return &http.Server{
		Addr:           address,
		Handler:        router,
		ReadTimeout:    120 * time.Second,
		WriteTimeout:   120 * time.Second,
		MaxHeaderBytes: 1 << 30,
	}
}

**Comment by brook-w** [comment]
```go
func initServer(address string, router *gin.Engine) server {
	return &http.Server{
		Addr:           address,
		Handler:        router,
		ReadTimeout:    120 * time.Second,
		WriteTimeout:   120 * time.Second,
		MaxHeaderBytes: 1 << 30,
	}
}

```

**Comment by pixelmaxQm** [comment]
你这个接口读写超时了 1分钟 自行修改超时时间
![image](https://github.com/flipped-aurora/gin-vue-admin/assets/165128580/0e425147-7e4d-4620-be1f-dcc7e59dfbd3)
