### ISSUE TITLE
[Feature]: 小程序得到响应的时候需要data.data,加一个V2公共Response把所有放在同一层级

### ISSUE THREAD

**Issue by xue-ding-e** [flipped-aurora/gin-vue-admin#1780]
### 功能描述以及必要性描述

 小程序得到响应的时候需要data.data,加一个V2公共Response把所有放在同一层级,

### 建议和方案

type ResponseV2 struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

func ResultV2(code int, data interface{}, msg string, c *gin.Context) {
	responseData := map[string]interface{}{
		"code": code,
		"msg":  msg,
	}

	// 反射遍历 data 并添加到 responseData 中
	if data != nil {
		val := reflect.ValueOf(data)
		typ := reflect.TypeOf(data)

		for i := 0; i < val.NumField(); i++ {
			fieldName := typ.Field(i).Tag.Get("json")
			if fieldName == "" {
				fieldName = typ.Field(i).Name
			}
			responseData[fieldName] = val.Field(i).Interface()
		}
	}
	c.JSON(http.StatusOK, responseData)
}

func OkV2(c *gin.Context) {
	ResultV2(SUCCESS, map[string]interface{}{}, "操作成功", c)
}

func OkWithMessageV2(message string, c *gin.Context) {
	ResultV2(SUCCESS, map[string]interface{}{}, message, c)
}

func OkWithDataV2(data interface{}, c *gin.Context) {
	ResultV2(SUCCESS, data, "查询成功", c)
}

func OkWithDetailedV2(data interface{}, message string, c *gin.Context) {
	ResultV2(SUCCESS, data, message, c)
}

func FailV2(c *gin.Context) {
	ResultV2(ERROR, map[string]interface{}{}, "操作失败", c)
}

func FailWithMessageV2(message string, c *gin.Context) {
	ResultV2(ERROR, map[string]interface{}{}, message, c)
}

func NoAuthV2(message string, c *gin.Context) {
	c.JSON(http.StatusUnauthorized, ResponseV2{
		Code: 7,
		Msg:  message,
	})
}

func FailWithDetailedV2(data interface{}, message string, c *gin.Context) {
	ResultV2(ERROR, data, message, c)
}

**Comment by xue-ding-e** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1781#issue-2353936916

**Comment by xue-ding-e** [comment]
https://github.com/flipped-aurora/gin-vue-admin/pull/1782#issue-2353992614

**Comment by pixelmaxQm** [comment]
此操作需要在前端封装，直接修改后端返回data是错误行为
