### ISSUE TITLE
[Bug]: 创建带有2个params类型的参数菜单，通过route获取值错误

### ISSUE THREAD

**Issue by chusevip8** [flipped-aurora/gin-vue-admin#1786]
### gin-vue-admin 版本

2.6

### Node 版本

v16.20

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

1:创建菜单，新增菜单参数，参数类型选择：params
例如：
参数类型    参数key   参数值
params       app          douyin
params       type         1

路径  page:app:type

vue中用const route = useRoute() 获取结果
route.params.app=d
route.params.type=ouyin1

环境： mac ,浏览器 chrome

**Comment by pixelmaxQm** [comment]
路径 page/:app/:type

**Comment by chusevip8** [comment]
谢谢
