### ISSUE TITLE
model.SysUser无法完成AutoMigrate自动迁移，报错提示: Table 'atta_offical.sys_users' doesn't exist

### ISSUE THREAD

**Issue by iHDJ** [flipped-aurora/gin-vue-admin#179]
![image](https://user-images.githubusercontent.com/56471245/89867797-4bdca800-dbe4-11ea-928e-96260f8ea545.png)
![image](https://user-images.githubusercontent.com/56471245/89867882-6f9fee00-dbe4-11ea-8b82-22a49bf72837.png)
![image](https://user-images.githubusercontent.com/56471245/89867952-8cd4bc80-dbe4-11ea-8a31-6a9b0c2300f4.png)
经过测试发现，只有sys_user无法完成AutoMigrate。其他的表都能够自动创建。mysql用的是5.7版本

**Comment by SliverHorn** [comment]
Hello, please turn on the use-multipoint of server/config.yaml to be true, and print the synchronized SQL to the terminal, you can see what the problem is.

**Comment by iHDJ** [comment]
> Hello, please turn on the use-multipoint of server/config.yaml to be true, and print the synchronized SQL to the terminal, you can see what the problem is.

![image](https://user-images.githubusercontent.com/56471245/89868892-1cc73600-dbe6-11ea-8221-6c74138db586.png)
![image](https://user-images.githubusercontent.com/56471245/89868923-26509e00-dbe6-11ea-8646-0a41d635c5a3.png)
useless

**Comment by SliverHorn** [comment]
Oh no, not use-multipoint in server/config.yaml, but log-mode under mysql is true

**Comment by iHDJ** [comment]
> Oh no, not use-multipoint in server/config.yaml, should be log-mode under mysql is true

¿

**Comment by SliverHorn** [comment]
Hello, please turn on the log-mode of server/config.yaml to be true, and print the synchronized SQL to the terminal, you can see what the problem is.

**Comment by iHDJ** [comment]
> Hello, please turn on the log-mode of server/config.yaml to be true, and print the synchronized SQL to the terminal, you can see what the problem is.

![image](https://user-images.githubusercontent.com/56471245/89869881-99a6df80-dbe7-11ea-8119-fdbdaa7d888b.png)
问题找到了，让开发者出来挨打吧

**Comment by SliverHorn** [comment]
This problem may be caused by the 1.0 version of gin-vue-admin. When gin-vue-admin2.0 is used, the data of 1.0 is still used. There is no problem using db/qmPlus.sql to initialize the data. You can use the following 
Can the code try to synchronize successfully
```go
package model

import (
	"github.com/jinzhu/gorm"
	"github.com/satori/go.uuid"
)

type SysUser struct {
	gorm.Model
	UUID        uuid.UUID    `json:"uuid" gorm:"comment:'用户UUID'"`
	Username    string       `json:"userName" gorm:"comment:'用户登录名'"`
	Password    string       `json:"-"  gorm:"comment:'用户登录密码'"`
	NickName    string       `json:"nickName" gorm:"column:'nick_name';default:'系统用户';comment:'用户昵称'" `
	HeaderImg   string       `json:"headerImg" gorm:"default:'http://qmplusimg.henrongyi.top/head.png';comment:'用户头像'"`
	Authority   SysAuthority `json:"authority" gorm:"ForeignKey:AuthorityId;AssociationForeignKey:AuthorityId;comment:'用户角色'"`
	AuthorityId string       `json:"authorityId" gorm:"default:888;comment:'用户角色ID'"`
}
```

**Comment by iHDJ** [comment]
> This problem may be caused by the 1.0 version of gin-vue-admin. When gin-vue-admin2.0 is used, the data of 1.0 is still used. There is no problem using db/qmPlus.sql to initialize the data. You can use the following
> Can the code try to synchronize successfully
> 
> ```go
> package model
> 
> import (
> 	"github.com/jinzhu/gorm"
> 	"github.com/satori/go.uuid"
> )
> 
> type SysUser struct {
> 	gorm.Model
> 	UUID        uuid.UUID    `json:"uuid" gorm:"comment:'用户UUID'"`
> 	Username    string       `json:"userName" gorm:"comment:'用户登录名'"`
> 	Password    string       `json:"-"  gorm:"comment:'用户登录密码'"`
> 	NickName    string       `json:"nickName" gorm:"column:'nick_name';default:'系统用户';comment:'用户昵称'" `
> 	HeaderImg   string       `json:"headerImg" gorm:"default:'http://qmplusimg.henrongyi.top/head.png';comment:'用户头像'"`
> 	Authority   SysAuthority `json:"authority" gorm:"ForeignKey:AuthorityId;AssociationForeignKey:AuthorityId;comment:'用户角色'"`
> 	AuthorityId string       `json:"authorityId" gorm:"default:888;comment:'用户角色ID'"`
> }
> ```

是数据库方面的问题，需要先设置允许中文就可以了。但是因为我的是本地docker测试，我直接把中文改成System User了
另外，你觉得我很像老外是吗？

**Comment by piexlmax** [comment]
> > This problem may be caused by the 1.0 version of gin-vue-admin. When gin-vue-admin2.0 is used, the data of 1.0 is still used. There is no problem using db/qmPlus.sql to initialize the data. You can use the following
> > Can the code try to synchronize successfully
> > ```go
> > package model
> > 
> > import (
> > 	"github.com/jinzhu/gorm"
> > 	"github.com/satori/go.uuid"
> > )
> > 
> > type SysUser struct {
> > 	gorm.Model
> > 	UUID        uuid.UUID    `json:"uuid" gorm:"comment:'用户UUID'"`
> > 	Username    string       `json:"userName" gorm:"comment:'用户登录名'"`
> > 	Password    string       `json:"-"  gorm:"comment:'用户登录密码'"`
> > 	NickName    string       `json:"nickName" gorm:"column:'nick_name';default:'系统用户';comment:'用户昵称'" `
> > 	HeaderImg   string       `json:"headerImg" gorm:"default:'http://qmplusimg.henrongyi.top/head.png';comment:'用户头像'"`
> > 	Authority   SysAuthority `json:"authority" gorm:"ForeignKey:AuthorityId;AssociationForeignKey:AuthorityId;comment:'用户角色'"`
> > 	AuthorityId string       `json:"authorityId" gorm:"default:888;comment:'用户角色ID'"`
> > }
> > ```
> 
> 是数据库方面的问题，需要先设置允许中文就可以了。但是因为我的是本地docker测试，我直接把中文改成System User了
> 另外，你觉得我很像老外是吗？

毕竟中国人都挺客气的

**Comment by iHDJ** [comment]
> > > This problem may be caused by the 1.0 version of gin-vue-admin. When gin-vue-admin2.0 is used, the data of 1.0 is still used. There is no problem using db/qmPlus.sql to initialize the data. You can use the following
> > > Can the code try to synchronize successfully
> > > ```go
> > > package model
> > > 
> > > import (
> > > 	"github.com/jinzhu/gorm"
> > > 	"github.com/satori/go.uuid"
> > > )
> > > 
> > > type SysUser struct {
> > > 	gorm.Model
> > > 	UUID        uuid.UUID    `json:"uuid" gorm:"comment:'用户UUID'"`
> > > 	Username    string       `json:"userName" gorm:"comment:'用户登录名'"`
> > > 	Password    string       `json:"-"  gorm:"comment:'用户登录密码'"`
> > > 	NickName    string       `json:"nickName" gorm:"column:'nick_name';default:'系统用户';comment:'用户昵称'" `
> > > 	HeaderImg   string       `json:"headerImg" gorm:"default:'http://qmplusimg.henrongyi.top/head.png';comment:'用户头像'"`
> > > 	Authority   SysAuthority `json:"authority" gorm:"ForeignKey:AuthorityId;AssociationForeignKey:AuthorityId;comment:'用户角色'"`
> > > 	AuthorityId string       `json:"authorityId" gorm:"default:888;comment:'用户角色ID'"`
> > > }
> > > ```
> > 
> > 
> > 是数据库方面的问题，需要先设置允许中文就可以了。但是因为我的是本地docker测试，我直接把中文改成System User了
> > 另外，你觉得我很像老外是吗？
> 
> 毕竟中国人都挺客气的

客气客气
