### ISSUE TITLE
[Bug]: 前端编译css报错

### ISSUE THREAD

**Issue by hesu-aurora** [flipped-aurora/gin-vue-admin#1816]
### gin-vue-admin 版本

2.6.7

### Node 版本

v18.18.2

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

前段编译的时候报错，是有问题吗 还是我有啥问题
![QQ截图20240711225120](https://github.com/flipped-aurora/gin-vue-admin/assets/95602525/6de9afde-c775-47f1-bac5-f81d02a4c96d)

**Comment by pixelmaxQm** [comment]
可能是element最新版本有问题，建议去element-plus查看其是否解决，如果他们解决了，可以选择删除package-lock.json和node_modules重新npm i & npm build，如果未解决，建议降低一个版本号。

**Comment by pixelmaxQm** [comment]
https://github.com/element-plus/element-plus/pull/17549

**Comment by btea** [comment]
把sass版本降到 `<1.77.7` 就可以了。
