### ISSUE TITLE
[Bug]: 使用表格模板功能会导出已删除的数据

### ISSUE THREAD

**Issue by jskils** [flipped-aurora/gin-vue-admin#1821]
### gin-vue-admin 版本

v2.6.7

### Node 版本

v20.11.1

### Golang 版本

go 1.20.2

### 是否依旧存在

可以

### bug描述

正常配置表格模板，使用内置组件ExportExcel 携带模板id导出数据，会将逻辑删除的数据一并导出。
![image](https://github.com/user-attachments/assets/8233c855-2508-4c06-bf80-cf0809afd40e)
![image](https://github.com/user-attachments/assets/3c22024f-0fb7-4372-a1e4-ac5d0e16246c)

**Comment by pixelmaxQm** [comment]
这里就需要你带上导出条件，导出功能并不会自动识别软删除，框架无法得知用户是否需要导出已经软删除的内容。

**Comment by jskils** [comment]
噢，原来设计如此，感谢！
