### ISSUE TITLE
[Bug]: 创建Package报错

### ISSUE THREAD

**Issue by nange-Blog** [flipped-aurora/gin-vue-admin#1822]
### gin-vue-admin 版本

main

### Node 版本

latest

### Golang 版本

latest

### 是否依旧存在

可以

### bug描述

新部署后，创建package会报错，日志显示：
error   /go/src/github.com/flipped-aurora/gin-vue-admin/server/api/v1/system/sys_auto_code.go:193    创建失败!       {"error": "mkdir /server: not a directory"}

**Comment by pixelmaxQm** [comment]
部署后不支持自动化代码
