### ISSUE TITLE
[Bug]: 发送邮件出现'mail: expected single address'错误信息

### ISSUE THREAD

**Issue by Mique2011** [flipped-aurora/gin-vue-admin#1831]
### gin-vue-admin 版本

2.6.7

### Node 版本

18.18.0

### Golang 版本

1.22.1

### 是否依旧存在

未测试

### bug描述

1. 在yaml文件中配置好邮箱信息后。重点是配置了nickname，
2. 在发送邮件的时候报“mail: expected single address, got \"<***@***>\"”错误，经查询是由配置了nickname所致，在ulits/email.go中send方法中，将nickname加入到了from中，而格式是不被接收的。
3. 经查询https://github.com/gophish/gophish/issues/759，接收格式为“[a.different@email.com](mailto:a.different@email.com)”<[example@example.com](mailto:example@example.com)>。
4. 将e.From = fmt.Sprintf("%s <%s>", nickname, from)改造成e.From = fmt.Sprintf("\"%s\"<%s>", nickname, from)即可。

### 修改建议

在ulits/email.go的send方法中，将e.From = fmt.Sprintf("%s <%s>", nickname, from)改造成e.From = fmt.Sprintf("\"%s\"<%s>", nickname, from)

**Comment by pixelmaxQm** [comment]
好的 我们尽快调整 或者 提交pr我们采纳
