### ISSUE TITLE
[Bug]:2个菜单指向同一个页面，路径不一样，切换菜单，页面不刷新，切换tab也不刷新 

### ISSUE THREAD

**Issue by chusevip8** [flipped-aurora/gin-vue-admin#1832]
### gin-vue-admin 版本

2.6

### Node 版本

v16.20

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

2个菜单指向同一个页面，路径不一样，切换菜单，页面不刷新，切换tab也不刷新

**Comment by pixelmaxQm** [comment]
这种情况是vueRouter不重新渲染组件的问题，框架无法解决，需要自己对路由进行监听。
