### ISSUE TITLE
用户注册账号允许输入AuthorityId

### ISSUE THREAD

**Issue by whileW** [flipped-aurora/gin-vue-admin#184]
建议可以在代码中默认AuthorityId ，不开放给用户。

**Comment by whileW** [comment]
刚才没有看到新增用户调得也是这个接口，这个接口是否应该放到用户路由下，加上鉴权

**Comment by piexlmax** [comment]
> 建议可以在代码中默认AuthorityId ，不开放给用户。

前端注册会默认为普通用户 注册接口需要在未登录情况下 此处注册为考虑到安全性问题 会单独注册游客注册接口 感谢issue
