### ISSUE TITLE
[Bug]: 运行前后端服务后，状态栏与介绍的不太一样

### ISSUE THREAD

**Issue by nange-Blog** [flipped-aurora/gin-vue-admin#1842]
### gin-vue-admin 版本

main

### Node 版本

v22.5.1

### Golang 版本

go1.22.3

### 是否依旧存在

可以

### bug描述

1 按照指引，前端后端运行起来之后，界面是如下效果，菜单栏不对，是不是还有其他要配置的吗：
<img width="1459" alt="image" src="https://github.com/user-attachments/assets/8b156903-644b-487f-be07-8433c36c2829">

**Comment by pixelmaxQm** [comment]
是什么数据库

**Comment by nange-Blog** [comment]
Mysql 数据库

**Comment by nange-Blog** [comment]
我看视频显示是这样的
![image](https://github.com/user-attachments/assets/1bbd2733-2e45-438c-a0ce-53878f5b94e4)

**Comment by pixelmaxQm** [comment]
初始化后你左侧的菜单栏确实不太正常，方便的话 微信shouzi_1994我看下你环境，我无法复现这bug。视频你看的是旧的，后面我更新新版链接。

**Comment by nange-Blog** [comment]
> 是什么数据库

mysql 8.0.37

**Comment by pixelmaxQm** [comment]
已调整完成  换数据库后解决

**Comment by nange-Blog** [comment]
之前是服务器apt安装mysql，换了docker镜像 Version: '8.0.38' 正常运行
