### ISSUE TITLE
[Feature]: 对象存储支持 cloudflare r2

### ISSUE THREAD

**Issue by okatu-loli** [flipped-aurora/gin-vue-admin#1847]
### 功能描述以及必要性描述

**功能描述**
目前，gin-vue-admin 框架支持多种对象存储服务，如 阿里云 OSS 等。然而，Cloudflare R2 作为一项新兴的对象存储解决方案，以其低成本和高性能的特点逐渐受到开发者的关注。此功能请求旨在为 gin-vue-admin 添加对 Cloudflare R2 的原生支持，使得用户能够更便捷地将 R2 作为其数据备份或静态资源存储解决方案。

**必要性描述**
- **降低成本**: 相对于其他对象存储服务，Cloudflare R2 提供了显著的成本优势。通过支持 R2，用户可以在不牺牲性能的前提下，大幅减少存储和带宽成本。

- **提高可用性和性能**: Cloudflare 拥有全球分布的网络和缓存机制，能够为静态文件提供低延迟的访问体验。这对于那些拥有全球用户的应用程序尤其重要。

- **简化集成**: 提供对 R2 的直接支持将减少用户的配置和定制化工作，从而帮助开发者更快速地部署和迁移其应用程序。

**框架便利性**
首先，增加云存储的选项可以让开发者依据自身需求和预算选择更适合自己的方案。在初期开发阶段，开发者可以借助测试环境中较低的存储成本快速进行迭代。

然后，为框架引入更多对象存储集成的支持，将提升其市场竞争力和吸引力。这将帮助 gin-vue-admin 吸引更多潜在用户和贡献者，促进社区的成长和发展。

通过支持 Cloudflare R2，gin-vue-admin 将不仅提供成本优势，还能增强框架的灵活性，使开发者能够在不同的环境中无缝操作和迁移其存储解决方案。

**Comment by cnbattle** [comment]
看看源码，已经支持了

[server/utils/upload/cloudflare_r2.go](https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/utils/upload/cloudflare_r2.go)

**Comment by pixelmaxQm** [comment]
确实已经支持了 但是还没加入到文档里
