### ISSUE TITLE
参数写的有问题，生成文档有报错  exa_simple_uploader.go

### ISSUE THREAD

**Issue by netyum** [flipped-aurora/gin-vue-admin#185]
@Param params md5 get "测试文件是否已经存在和判断已经上传过的切片"
@Param md5 query string get "合并文件"

exa_simple_uploader.go

参数写的有问题，生成文档有报错

**Comment by SliverHorn** [comment]
> @param params md5 get "测试文件是否已经存在和判断已经上传过的切片"
> @param md5 query string get "合并文件"
> 
> exa_simple_uploader.go
> 
> 参数写的有问题，生成文档有报错

Hello, could you please describe your question in detail? What's wrong with slice uploading?

**Comment by piexlmax** [comment]
> @param params md5 get "测试文件是否已经存在和判断已经上传过的切片"
> @param md5 query string get "合并文件"
> 
> exa_simple_uploader.go
> 
> 参数写的有问题，生成文档有报错

忘记测试swagger 我修复一下 感谢

**Comment by piexlmax** [comment]
已修复
