### ISSUE TITLE
[Bug]: 任意页面刷新存在页面丢失问题

### ISSUE THREAD

**Issue by x2358473** [flipped-aurora/gin-vue-admin#1857]
### gin-vue-admin 版本

2.7.2

### Node 版本

v18.20

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

在项目的任意页面刷新都可能出现页面走丢的情况，查看network发现没有请求menu与getuserinfo导到无法获取到页面路由与用户信息，有时要多刷新几次才能正常进入页面。在正常页面重复刷新几次也会出现页面无法展示的情况，一直显示  “系统正在加载中，请稍候...”

### 修改建议

可否使用store的持久化把用户路由与页面路由存在缓存中，或者查看下是什么原因导至刷新时出现接口不请求情况

**Comment by x2358473** [comment]
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/e3f57125-5fbc-45d6-bd82-ca28302e609e">
控制台没有任何请求。这个页面会一直展示。除非手动刷新直到出现getMenu与getUserInfo这两个接口请求才能正常进入页面

**Comment by x2358473** [comment]
<img width="1509" alt="image" src="https://github.com/user-attachments/assets/557c2af1-6121-4b9d-9590-51cb57d0ad33">

今天点击右上角的退出登录，卡住了，刷新2次后进入登录页面，点击登录后卡在这了。控制台打印的那个是src/views/error/index.vue中的const userStore = useUserStore()这句后面console.log(userStore.userInfo)打印出来的。authority为空

**Comment by x2358473** [comment]
好像是src/permission.js中的router.beforeEach()方法没有触发。

**Comment by bypanghu** [comment]
在微信群还是 qq 群 艾特一下管理，给我远程码 我来瞅瞅

**Comment by yangshijunx** [comment]
pinia没有做持久化，持久化就可以了。

**Comment by pixelmaxQm** [comment]
> 好像是src/permission.js中的router.beforeEach()方法没有触发。

确实是这个问题导致，在修复

**Comment by pixelmaxQm** [comment]
目前已发布2.7.4稳定版，建议升级至稳定版，大多数问题都已修复。感谢！
