### ISSUE TITLE
[Bug]: 退出登录页面丢失

### ISSUE THREAD

**Issue by msebilly** [flipped-aurora/gin-vue-admin#1871]
### gin-vue-admin 版本

2.7.3

### Node 版本

v 22.7

### Golang 版本

go 1.23

### 是否依旧存在

可以

### bug描述

1、登录系统
2、登出系统
3、显示页面丢失
![671725265783_ pic](https://github.com/user-attachments/assets/535d922f-f805-4f3d-aed1-224d587968d7)

**Comment by bypanghu** [comment]
退出登录后的 url 可否复制一下，可以把写成本地数据

**Comment by x2358473** [comment]
很可能是跟这个#1857是同一个问题 我的更新到2.7.3后刷新页面就有大概率出现他的这个页面，原先的2.7.2是一直卡在加载中的页面

**Comment by chimojiacai** [comment]
> 很可能是跟这个 #1857 是同一个问题 我的更新到2.7.3后刷新页面就有大概率出现他的这个页面，原先的2.7.2是一直卡在加载中的页面

请问修复了吗？

**Comment by x2358473** [comment]
> > 很可能是跟这个 #1857 是同一个问题 我的更新到2.7.3后刷新页面就有大概率出现他的这个页面，原先的2.7.2是一直卡在加载中的页面
> 
> 请问修复了吗？

看到回复在修复中

**Comment by chimojiacai** [comment]
> > > 很可能是跟这个 #1857 是同一个问题 我的更新到2.7.3后刷新页面就有大概率出现他的这个页面，原先的2.7.2是一直卡在加载中的页面
> > 
> > 
> > 请问修复了吗？
> 
> 看到回复在修复中

好吧！

**Comment by pixelmaxQm** [comment]
已提交至main分支，劳烦各位帮忙测试是否可以复现，新的main分支需要重新 npm i

**Comment by x2358473** [comment]
> 已提交至main分支，劳烦各位帮忙测试是否可以复现，新的main分支需要重新 npm i

我代码同步到2.7.4之后使用了两天，目前刷新没有出现丢失情况了，原来的2.7.3与2.7.2都会在刷新时有大概率丢失。

**Comment by pixelmaxQm** [comment]
目前已发布2.7.4稳定版，建议升级至稳定版，大多数问题都已修复。感谢！
