### ISSUE TITLE
[Bug]: 初始化后密码登陆不上去(postgresql)

### ISSUE THREAD

**Issue by Alarak-Alex** [flipped-aurora/gin-vue-admin#1875]
### gin-vue-admin 版本

2.7.3

### Node 版本

v20.17.0

### Golang 版本

go 1.23

### 是否依旧存在

可以

### bug描述

1.初始化项目
2.尝试初始密码登录
3.最后注释掉密码验证部分的代码登录成功
4.登录成功后重置密码正常登录

**Comment by pixelmaxQm** [comment]
初始化密码是你自己初始化页面时候输入的密码，默认密码123456已经取消好久了。

**Comment by pixelmaxQm** [comment]
274版本，管理员密码处将会默认为123456有需要再改
