### ISSUE TITLE
[Bug]: 用户管理里停用一个用户，没有处理这个用户的登录状态

### ISSUE THREAD

**Issue by huweiup** [flipped-aurora/gin-vue-admin#1891]
### gin-vue-admin 版本

v2.7.4

### Node 版本

v18.20.4

### Golang 版本

go1.22.6

### 是否依旧存在

可以

### bug描述

在用户管理里停用一个用户，看服务端代码没有处理该用户的jwt token

**Comment by pixelmaxQm** [comment]
这里不做统一配置，每次交互都差库或者记录每个用户的活跃token都存在开销，如果需要请自行实现。
