### ISSUE TITLE
[Feature]: 数据库，数据信息升级模块

### ISSUE THREAD

**Issue by layueshiba** [flipped-aurora/gin-vue-admin#1893]
### 功能描述以及必要性描述

1.以mysql为例：目前数据库的表可以字段升级，但是表内的数据是否可以做一个模块自动升级呢
2. 例如：部署了v2.0.0版本运行了一段时间，升级到了最新版本v2.7.4里面的api新增了很多。但是数据表内的信息不会自动升级。

数据新增升级考虑做吗。或者有什么顾虑呢

**Comment by pixelmaxQm** [comment]
有啥方案吗

**Comment by pixelmaxQm** [comment]
我们给与授权用户也只能提供部分sql脚本，新增内容会体现在更新日志，我们会辅助授权用户做升级。
