### ISSUE TITLE
[Bug]: MariaDB 10.6.18数据库修改用户配置失败

### ISSUE THREAD

**Issue by as564335sa** [flipped-aurora/gin-vue-admin#1894]
### gin-vue-admin 版本

main

### Node 版本

v18.17.1

### Golang 版本

go 1.22.3

### 是否依旧存在

可以

### bug描述

我的数据库是MariaDB10.6.18，修改用户配置失败，GORM生产的sql如下
```
UPDATE
	`sys_users`
SET
	`origin_setting` = CAST('{"weakness":false,"grey":false,"primaryColor":"#3b82f6","showTabs":true,"darkMode":"auto","layout_side_width":256,"layout_side_collapsed_width":80,"layout_side_item_height":48,"show_watermark":false,"side_mode":"normal"}' AS JSON),
	`updated_at` = '2024-09-29 11:46:18.246'
WHERE
	id = 1
	AND `sys_users`.`deleted_at` IS NULL
```
会报错：```设置失败!       {"error": "Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON),`updated_at`=? WHERE id = ? AND `sys_users`.`deleted_at` IS NULL' at line 1"}```

需要去掉SET里面的CAST才行，改成这样手写sql测试可以
```
UPDATE
	`sys_users`
SET
	`origin_setting` = '{"weakness":false,"grey":false,"primaryColor":"#3b82f6","showTabs":true,"darkMode":"auto","layout_side_width":256,"layout_side_collapsed_width":80,"layout_side_item_height":48,"show_watermark":false,"side_mode":"normal"}',
	`updated_at` = '2024-09-29 11:46:18.246'
WHERE
	id = 1
	AND `sys_users`.`deleted_at` IS NULL
```

这个该怎么兼容一下？

**Comment by pixelmaxQm** [comment]
什么时间的main分支，后面修复过这个问题，和数据库的交互都是按照string进行的，理论上不会有这个JSON问题

**Comment by as564335sa** [comment]
> 什么时间的main分支，后面修复过这个问题，和数据库的交互都是按照string进行的，理论上不会有这个JSON问题

就昨天clone的

**Comment by pixelmaxQm** [comment]
[	OriginSetting common.JSONMap `json:"originSetting" form:"originSetting" gorm:"type:text;default:null;column:origin_setting;comment:配置;"` //配置](https://github.com/flipped-aurora/gin-vue-admin/blob/a5e8980b23fd23687dc1ead6a05a4b3df076d857/server/model/system/sys_user.go#L33)
	
	对比一下这行一行吗

**Comment by as564335sa** [comment]
> [ OriginSetting common.JSONMap `json:"originSetting" form:"originSetting" gorm:"type:text;default:null;column:origin_setting;comment:配置;"` //配置](https://github.com/flipped-aurora/gin-vue-admin/blob/a5e8980b23fd23687dc1ead6a05a4b3df076d857/server/model/system/sys_user.go#L33) 对比一下这行一样吗

一样的，刚刚我全都删了重新clone了一下，还是一样的效果

**Comment by pixelmaxQm** [comment]
更新一下代码，已修复。

**Comment by as564335sa** [comment]
> 更新一下代码，已修复。

可以了，神速👍👍👍
