### ISSUE TITLE
[Bug]: 主题darkMode不正常了

### ISSUE THREAD

**Issue by as564335sa** [flipped-aurora/gin-vue-admin#1901]
### gin-vue-admin 版本

V2.7.5测试版(main)

### Node 版本

v18.17.1

### Golang 版本

go 1.22.3

### 是否依旧存在

可以

### bug描述

1、main分支最新commit的V2.7.5测试版，黑暗模式不正常了，菜单列表背景颜色还是白的，貌似是因为删除了main.js中的
`import 'element-plus/theme-chalk/dark/css-vars.css'`这个导致的
2、切换dark light没有保存，刷新一下就恢复了

**Comment by pixelmaxQm** [comment]
现在切换为后端保存了，皮肤跟随用户，不保存就是刷新后变回。

**Comment by as564335sa** [comment]
> 现在切换为后端保存了，皮肤跟随用户，不保存就是刷新后变回。

这个我知道啊，在系统设置里设置的dark mode，保存是可以的，在切换主题按钮上，没有保存，刷新就恢复了

**Comment by pixelmaxQm** [comment]
main已调整
