### ISSUE TITLE
[Bug]: npm run server error report status 500

### ISSUE THREAD

**Issue by baipangbai** [flipped-aurora/gin-vue-admin#1907]
### gin-vue-admin 版本

2.7.5 serve

### Node 版本

v20.18.0

### Golang 版本

go 1.22.6

### 是否依旧存在

可以

### bug描述

具体报错信息：`检测到接口错误AxiosError: Request failed with status code 500  错误码 500 ：此类错误内容常见于后台panic，请先查看后台日志，如果影响您正常使用可强制登出清理缓存`

首次下载该项目，按照quick start步骤操作如下
1. 在main分支，web目录下运行npm i
2. 接着运行npm run serve

浏览器打开的后台会报错
![image](https://github.com/user-attachments/assets/ed2bc8aa-7adf-48ce-a76a-dce2746a7759)

对应的命令行，输出的错误日志
![image](https://github.com/user-attachments/assets/e0583761-9331-4a1a-8bdf-3a1cf908b075)

**Comment by pixelmaxQm** [comment]
后端没启动

**Comment by baipangbai** [comment]
谢谢，打扰啦~
