### ISSUE TITLE
[Bug]: 代码生成器字段编辑有问题

### ISSUE THREAD

**Issue by kaylee595** [flipped-aurora/gin-vue-admin#1913]
### gin-vue-admin 版本

Commits on Oct 11, 2024

### Node 版本

v20.18.0.

### Golang 版本

go1.23.2

### 是否依旧存在

可以

### bug描述

字段高级编辑数据源配置并确定后, 再次点开编辑不会继上次保存继续编辑.
https://github.com/user-attachments/assets/44178e01-29e5-4c89-84fd-7e7f0e5e4fe0

**Comment by pixelmaxQm** [comment]
已修复
