### ISSUE TITLE
[Bug]: getXXXDataSource接口有BUG

### ISSUE THREAD

**Issue by kaylee595** [flipped-aurora/gin-vue-admin#1918]
### gin-vue-admin 版本

git信息被我移除了, 不知道哪个版本了

### Node 版本

v20.18.0.

### Golang 版本

go1.23.2

### 是否依旧存在

可以

### bug描述

使用代码生成的getXXXDataSource接口存在问题, 它会获取到被软删除的记录. 查看代码发现使用的是Table, 改成结构体可以解决.

### 修改建议

```
// 会获取到软删除记录的代码
global.MustGetGlobalDBByDBName("user_manager").Table("apps").Select("name as label,id as value").Scan(&appId)
// 修改为如下代码可以解决
global.MustGetGlobalDBByDBName("user_manager").Model(&userManager.Apps{}).Select("name as label,id as value").Scan(&appId)
```

**Comment by pixelmaxQm** [comment]
已知bug，会在版本2.7.7解决，授权用户可以私聊我加急处理。
