### ISSUE TITLE
[Bug]: 无法新增搜索项

### ISSUE THREAD

**Issue by lmb1113** [flipped-aurora/gin-vue-admin#1926]
### gin-vue-admin 版本

2.7.7

### Node 版本

v22

### Golang 版本

go 1.23

### 是否依旧存在

可以

### bug描述

fieldType!=='json
![image](https://github.com/user-attachments/assets/7a20f115-ed6b-441c-9d7c-d1c77f510c9a)

zhe'g这个判断有问题吧，判断反了

### 修改建议

fieldType==='json

**Comment by pixelmaxQm** [comment]
好的 我们尽快复现修复
