### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by cocosip** [flipped-aurora/gin-vue-admin#193]
- pg数据库的分支为什么不合并进来? 都用orm了,好歹要维护多个数据库啊, 不然意义何在
- 大部分都是代码生成器自动生成的代码,为什么会用到 redis 这些大杀器?
- 非测试代码为什么加了下划线? 
- 为什么强制依赖七牛云? 依赖七牛云如何做到私有化部署? 用aws-sdk 对接 s3 协议的存储不香么

昨天研究了一天的框架,到今天部署的时候发现竟然依赖七牛云存储，这个没法接受!!!

**Comment by piexlmax** [comment]
首先感谢提出建议
orm这个将会在gromv2版本时候加入代码维护工作，目前gorm尚不稳定，所以未合并进入主干
redis只是用于异地登陆存储活跃状态的账号jwt 如果不使用多点登录功能 不会依赖redis
规范性问题这个不好回答，见谅
七牛云并不是强制依赖，只是一个文件示例代码，可以删除自己编码，至于为什么用七牛，因为开源目前没有收费点，七牛是免费的（穷

**Comment by cocosip** [comment]
> 首先感谢提出建议
> orm这个将会在gromv2版本时候加入代码维护工作，目前gorm尚不稳定，所以未合并进入主干
> redis只是用于异地登陆存储活跃状态的账号jwt 如果不使用多点登录功能 不会依赖redis
> 规范性问题这个不好回答，见谅
> 七牛云并不是强制依赖，只是一个文件示例代码，可以删除自己编码，至于为什么用七牛，因为开源目前没有收费点，七牛是免费的（穷

用aws s3 标准,能兼容目前市面上绝大多数的云存储产品。私有化部署也只需要弄个minio就可以适配。
