### ISSUE TITLE
[Bug]: SetUserAuthorities 存在严重越权漏洞，可以通过遍历ID将其他所有用户设置为最低权限的角色

### ISSUE THREAD

**Issue by Inmanu2024** [flipped-aurora/gin-vue-admin#1932]
### gin-vue-admin 版本

2.7.7

### Node 版本

node 22

### Golang 版本

go 1.23

### 是否依旧存在

可以

### bug描述

SetUserAuthorities接口检测不够严格，该接口中，并未严格验证权限，会导致一个拥有该接口的角色，可以将其他所有用户（包括超级管理员）的角色，全部强行指定为自己该角色的下级角色，可以直接将其设置为权限最低的角色

里面传入的user id是没有经过任何检测验证的，并没有检测自己这个用户是否有资格操作该用户的角色。及时自己只是普通管理员，拥有该权限后，也可以将超级管理员的角色设置为比自己权限还低的角色

### 修改建议

严格检测要修改的用户，获取其拥有的全部角色，该用户权限必须处于自身下级才可以修改，否则就会出现普通用户强制修改超级管理员角色的情况。

**Comment by Inmanu2024** [comment]
超级管理员（拥有全部权限）
    后台管理员（拥有设置角色权限）
        普通商户（无设置角色权限，无切换角色权限）
        普通客服（无设置角色权限，无切换角色权限）

假设是类似以上角色配置，后台管理员用户可以直接将超级管理员的角色设置为自己的下级普通商户或普通客服角色，这将导致超级管理员只有强行从数据库修改才能恢复自己的权限。

后台管理员拥有该权限时，只需要从 ID 1 开始递增发起请求，将所有ID都尝试一遍，指定设置角色为普通角色，就可以把其他用户全坑一遍，最终只能从数据库强行改回来

**Comment by Inmanu2024** [comment]
要彻底杜绝类似事情，最省事的方式就是放弃使用user id，而是直接改用user的uuid，这样不至于被人简单的用user id++这样操作所有账户，直接用数字id来操作账户太不安全。

**Comment by pixelmaxQm** [comment]
setUserAuthorities 为最高权限级别用户可以使用的权限 业务分配 需要用户自行严格把控

**Comment by pixelmaxQm** [comment]
你修改建议里面的内容，可以开启config中的严格模式，系统本身是有这个设计的。

**Comment by pixelmaxQm** [comment]
![image](https://github.com/user-attachments/assets/31c9a04e-7315-421f-a58d-c4e87d610b5b)
![image](https://github.com/user-attachments/assets/5f0496fd-43e9-4dd8-b61b-0f5209de5066)
![image](https://github.com/user-attachments/assets/eff650bb-2b32-478c-bf6a-9d7f545d678f)
此issue close
