### ISSUE TITLE
建议将go-logging替换为zap

### ISSUE THREAD

**Issue by qpb8023** [flipped-aurora/gin-vue-admin#194]

**Comment by SliverHorn** [comment]
Hello, this go-logging has been discontinued for maintenance. The team has already planned to change to zap, so stay tuned!

**Comment by SliverHorn** [comment]
在gva_gormv2_dev分支已经完成了对zap的适配，等测试完成后就会合并到master分支的，如果你想提前使用的话，请拉去本项目的，然后切换到gva_gormv2_dev分支进行体验
