### ISSUE TITLE
[Bug]: 该项目代码质量为何如此低下?

### ISSUE THREAD

**Issue by tangxusc** [flipped-aurora/gin-vue-admin#1952]
### gin-vue-admin 版本

2.4.4

### Node 版本

v17

### Golang 版本

go 1.22

### 是否依旧存在

可以

### bug描述

- sql包提供了对于空的判断,为何大量使用*Type? 
- service 中list接口返回 interface , 这对于生成代码有何意义 脱裤子放屁? 放弃编译检查?
- 要么完整实现依赖注入,要么就老老实实的  放到一个serviceGroup中, 降智商?
- 主键uint类型,查询后的对象返回*int 这是没睡醒还是没睡着?

### 修改建议

建议好好的完善一下此仓库的代码质量

**Comment by pixelmaxQm** [comment]
1 需要前后端交互，判断参数传递是否为空
2 这问题修了一年了
3 用户可以自行选择使用一次性new或者单独new一个单独的server组件 依赖注入你不如去玩java
4 自动化代码不知道你是不是主键 自动化不代表完全信赖
5 开源项目来去自如，用2.4.4版本已经是一年多以前的东西了，不了解新的直接开喷，挺没素质的。

**Comment by pixelmaxQm** [comment]
![image](https://github.com/user-attachments/assets/bb206010-ba1d-4b5f-93ac-bc208c9321a3)

**Comment by xue-ding-e** [comment]
期待你的pr

**Comment by pixelmaxQm** [comment]
第三条我还回错你了，你用的模式已经被放弃了三年了。哥们如果加班怨气大，就去骂你的领导，不要在这里虚空索敌。

**Comment by xue-ding-e** [comment]
期待你fork之后的分支 / pr

**Comment by bibobat04** [comment]
不是，哥们你现实无能现在来网上找存在感了？还是太久没人跟你说过话了，看了代码又好像没什么优化的地方，于是找了很久之前的版本，再去问了ai感觉哪里能优化的就过来提，怕没人理你又故意贬低一下，不会是给裁员了吧？没了工作家里又压力你，对象也没有，干了好几年程序员一事无成，现在哪哪都不如意，不攻击一下别人就感觉活不下去了？

看看附件哪栋楼高，实在不行找个楼跳一下吧

**Comment by Azir-11** [comment]
我很好奇是谁给你的脸让你可以以一个如此高高在上的态度对一个开源的项目如此攻击？看你仓库之前提交代码也都有好几年了，这么早入行，干这么久了怎么都攒了些钱了吧？到现在真过的这么不如意？对开源的项目有意见你可以提，攻击别人让你感觉很爽？天天说国内开源环境差，就是你这种臭傻逼太多才差的

看你19年前的时候就在搞Java，之后又全换成了go，还建了很多什么test之类的仓库，那个时候不会已经干不下去了吧？换语言又苟延残喘了五年，现在又不行了，而且还在玩什么过时的依赖注入，你真学Java学傻了？盲猜一下，你这个Java思想写的go，这几年没少被吐槽吧，也不知道你自己是不知道还是当没看到？要是不知道也太惨了，身边的人都不希望你好，你也从来没试过其他的思路，只能一条路走到黑，这就是蠢；要是当没看到的话那有点可怜，19年的时候在学DDD，思想被入侵完了之后再换门语言，写的东西也不过是换汤不换药罢了，以至于你能在五年之后的go仓库里还在大声嚷嚷**依赖注入**，平常不会还玩AOP吧？这也是蠢；我看你是纯蠢上加蠢蠢到头了，生活不如意跑这里骂娘，你是又坏又恶心

就你这种家教，尼马送我床上我都不带碰一下的，还项目质量为何如此低下，你怎么不问问你家里人是怎么教的你，让你的素质如此低下？这么没家教，不会家里没有人了吧？你要是想念亲人了可以找我，我拉面手艺一绝，可以拿他们的骨灰给你拉碗面，让你再感受感受亲人的味道和温暖

**Comment by Azir-11** [comment]
翻了一下你的文章，发现有一篇挺有意思的：

![image](https://github.com/user-attachments/assets/08aa98df-b4f5-4982-a9e4-d0e8e38158bc)

4年前快30了，那时候还大方离开指的不会是团队发生矛盾被裁了或者被恶心出走了吧？

> 每天为自己安排一个任务

这个说的不会是学go吧？
最后面你说你要上善若水，你觉得是平凡，那么为何五年之后的你又充满了戾气去抨击，去肆意攻击一个开源的项目呢？这五年家破人亡了？

**Comment by bibobat04** [comment]
我很好奇是谁给你的脸让你可以以一个如此高高在上的态度对一个开源的项目如此攻击？看你仓库之前提交代码也都有好几年了，这么早入行，干这么久了怎么都攒了些钱了吧？到现在真过的这么不如意？对开源的项目有意见你可以提，攻击别人让你感觉很爽？天天说国内开源环境差，就是你这种臭傻逼太多才差的

看你19年前的时候就在搞Java，之后又全换成了go，还建了很多什么test之类的仓库，那个时候不会已经干不下去了吧？换语言又苟延残喘了五年，现在又不行了，而且还在玩什么过时的依赖注入，你真学Java学傻了？盲猜一下，你这个Java思想写的go，这几年没少被吐槽吧，也不知道你自己是不知道还是当没看到？要是不知道也太惨了，身边的人都不希望你好，你也从来没试过其他的思路，只能一条路走到黑，这就是蠢；要是当没看到的话那有点可怜，19年的时候在学DDD，思想被入侵完了之后再换门语言，写的东西也不过是换汤不换药罢了，以至于你能在五年之后的go仓库里还在大声嚷嚷依赖注入，平常不会还玩AOP吧？这也是蠢；我看你是纯蠢上加蠢蠢到头了，生活不如意跑这里骂娘，你是又坏又恶心

就你这种家教，尼马送我床上我都不带碰一下的，还项目质量为何如此低下，你怎么不问问你家里人是怎么教的你，让你的素质如此低下？这么没家教，不会家里没有人了吧？你要是想念亲人了可以找我，我拉面手艺一绝，可以拿他们的骨灰给你拉碗面，让你再感受感受亲人的味道和温暖

**Comment by bibobat04** [comment]
翻了一下你的文章，发现有一篇挺有意思的：

![image](https://github.com/user-attachments/assets/45bb6736-d27f-472d-b9e3-4e7b0a5db751)



4年前快30了，那时候还大方离开指的不会是团队发生矛盾被裁了或者被恶心出走了吧？

> 每天为自己安排一个任务

这个说的不会是学go吧？

最后面你说你要上善若水，你觉得是平凡，那么为何五年之后的你又充满了戾气去抨击，去肆意攻击一个开源的项目呢？这五年家破人亡了？

**Comment by pixelmaxQm** [comment]
此issue关闭，不再做任何回复
