### ISSUE TITLE
[Feature]: 不建议值接收器和指针接收器同时出现

### ISSUE THREAD

**Issue by bellingham07** [flipped-aurora/gin-vue-admin#1955]
### 功能描述以及必要性描述

1.源代码中有多处同时出现了值接收器和指针接收器
2.官方说法（https://go.dev/doc/faq）
![image](https://github.com/user-attachments/assets/99cb2b97-7e39-4d2e-9e64-d11d9db3d496)
如果类型的某些方法是指针接收器，其他的应该也是
在 gin-vue-admin\server\source  目录下有很多，别的地方没看到

**Comment by pixelmaxQm** [comment]
好的 我马上调整 感谢提出建议

**Comment by bellingham07** [comment]
> 好的 我马上调整 感谢提出建议

https://github.com/flipped-aurora/gin-vue-admin/pull/1956，这个pr中调整了一部分，可能还存在没看见的地方

**Comment by pixelmaxQm** [comment]
#1956
