### ISSUE TITLE
[Feature]: 支持go自带的动态链接库插件加载形式

### ISSUE THREAD

**Issue by nibabashilkk** [flipped-aurora/gin-vue-admin#1962]
### 功能描述以及必要性描述

后续会支持go自带的plugin吗

**Comment by clh021** [comment]
我觉得这是一个 很好的插件模式。我也期待这个功能特性。不过可能没有那么快支持上。

**Comment by pixelmaxQm** [comment]
go 自带的plugin兼容性很差  我们会做成另外一种依赖于grpc的模式
