### ISSUE TITLE
没有支持antd vue的计划

### ISSUE THREAD

**Issue by chennqqi** [flipped-aurora/gin-vue-admin#197]
目前element-ui已经停更了，而且不支持vue3.0. 请问有无antd vue支持计划？

**Comment by piexlmax** [comment]
> 目前element-ui已经停更了，而且不支持vue3.0. 请问有无antd vue支持计划？

gin-vue-admin会在后期计划开发3.0版本，待3.0拥有稳定的vue UI框架后 会用它进行替换，antd vue为备选方案。
