### ISSUE TITLE
[Bug]: gorm_logger_writer.go空指针

### ISSUE THREAD

**Issue by JaydenForYou** [flipped-aurora/gin-vue-admin#1972]
### gin-vue-admin 版本

2.7.8-beta1

### Node 版本

v18

### Golang 版本

1.22.0

### 是否依旧存在

可以

### bug描述

gorm_logger_writer.go 中NewWriter方法去掉了writer参数，导致第36行空指针报错。

### 修改建议

初始化writer或使用global.GVA_LOG

**Comment by pixelmaxQm** [comment]
感谢，bug已修复
