### ISSUE TITLE
windows10执行docker-compose up出现错误

### ISSUE THREAD

**Issue by wo642436249** [flipped-aurora/gin-vue-admin#198]
Building server
Step 1/33 : FROM node:12.16.1 as gva-web
 ---> 88c089733a3b
Step 2/33 : WORKDIR /gva_web/
 ---> Using cache
 ---> 0bbd90593689
Step 3/33 : COPY web/ .
 ---> Using cache
 ---> 7e96c4b8530c
Step 4/33 : RUN cat .env.production
 ---> Using cache
 ---> 3466d46941b0
Step 5/33 : COPY docker/web-handle.sh .
 ---> Using cache
 ---> e7b191eb892b
Step 6/33 : RUN sh ./web-handle.sh
 ---> Running in 1e2e7a8b63b5
: not founde.sh: 2: ./web-handle.sh:
: not founde.sh: 10: ./web-handle.sh:
Service 'server' failed to build: The command '/bin/sh -c sh ./web-handle.sh' returned a non-zero code: 127

**Comment by SliverHorn** [comment]
Please check if the web-handle.sh file in the docker folder of your project exists

**Comment by wo642436249** [comment]
> 
存在的

**Comment by SliverHorn** [comment]
You add a sentence of code `RUN ls -al` below line 7 of the dockerfile_server file to try

**Comment by piexlmax** [comment]
> > 
> 
> 存在的

我们会尽快对win10下的docker-compose 进行检测，感谢issue，这边会尽快修复或给出方案。

**Comment by wo642436249** [comment]
> > > 
> > 
> > 
> > 存在的
> 
> [温 10] 多克 - 组合[问题]，

好的，我试试，我的英文水平很差，不过我明白你的意思，我先自己调试一下，大概知道问题了

**Comment by wo642436249** [comment]
> You add a sentence of code `RUN ls -al` below line 7 of the dockerfile_server file to try

wo xian ziji tiaoshi yixia,ganxie tigong fangfa

**Comment by SliverHorn** [comment]
> > You add a sentence of code `RUN ls -al` below line 7 of the dockerfile_server file to try
> 
> wo xian ziji tiaoshi yixia,ganxie tigong fangfa

您好，我在gva_gorm_v2里更新了docker-compose文件，更新了mysql的制作方法，不使用团队自制的mysql镜像而是使用了官方mysql的镜像，也为排查docker-compose up产生的错误做了相应的输出，你可以试试。如果还不能解决，请联系我+WX:SliverHorn或者+QQ:503551462。

**Comment by wo642436249** [comment]
> > > You add a sentence of code `RUN ls -al` below line 7 of the dockerfile_server file to try
> > 
> > 
> > wo xian ziji tiaoshi yixia,ganxie tigong fangfa
> 
> 您好，我在gva_gorm_v2里更新了docker-compose文件，更新了mysql的制作方法，不使用团队自制的mysql镜像而是使用了官方mysql的镜像，也为排查docker-compose up产生的错误做了相应的输出，你可以试试。如果还不能解决，请联系我+WX:SliverHorn或者+QQ:503551462。

好的，谢谢
