### ISSUE TITLE
在服务器上运行时, /menu/getMenu接口报500错误, sys_casbin.go中报了空指针异常

### ISSUE THREAD

**Issue by EmbraceUU** [flipped-aurora/gin-vue-admin#202]
我在服务器上运行时, 按照步骤运行, /menu/getMenu接口报500错误, sys_casbin.go中报了空指针异常, 我跟踪代码好像是数据库的问题, 但是重新带入sql文件后还是会报错,
我看issues里面没有相关的提问, 是有什么步骤遗漏了吗 ?

**Comment by SliverHorn** [comment]
视图没导入成功

**Comment by EmbraceUU** [comment]
所以说还是数据库的问题是么 ?

**Comment by SliverHorn** [comment]
你用的是什么版本？

**Comment by EmbraceUU** [comment]
最新版本, 昨天clone的, 我在本地可以运行, 但是部署到服务器上会出现这个问题

**Comment by SliverHorn** [comment]
初始化数据打开了吗？

**Comment by SliverHorn** [comment]
确认好服务器数据库里有authority_menu这个视图

**Comment by EmbraceUU** [comment]
有authority_menu视图, 我在服务器上没有打开need-init-data, 我把本地的数据库dump出来导入到服务器上了,

**Comment by SliverHorn** [comment]
> 有authority_menu视图, 我在服务器上没有打开need-init-data, 我把本地的数据库dump出来导入到服务器上了,

有报错的截图不？

**Comment by EmbraceUU** [comment]
![image](https://user-images.githubusercontent.com/26841787/92549174-47f78080-f28b-11ea-8a32-70284f728694.png)
这个是报错的截图

**Comment by EmbraceUU** [comment]
我刚才把数据库清理了, 把need-init-data打开后重新运行, 数据库中的表和视图都正常创建了, 但是还是报这个问题

**Comment by EmbraceUU** [comment]
HAHA..  问题找到了, 是因为服务器上打包后的目录下少了resource下的文件, 运行时的目录和源码目录分开导致了这个问题.
