### ISSUE TITLE
数据库的sys_users表的数据结构定义和model中的SysUser struct的authority_id字段定义不一致

### ISSUE THREAD

**Issue by jackeyjin2002** [flipped-aurora/gin-vue-admin#205]
新手学习中……
数据库的sys_users表的数据结构定义和model中的SysUser struct好像不一致哎，如果authority_id的确应该为double的话，有什么特别之处吗？
![image](https://user-images.githubusercontent.com/51749070/92701089-2927e580-f382-11ea-9238-16e28050e7d5.png)
![image](https://user-images.githubusercontent.com/51749070/92701241-52487600-f382-11ea-85f2-e5ede9fb7d10.png)
谢谢

**Comment by SliverHorn** [comment]
现在已经取消用sql导入表结构和数据，数据表由gorm生成，数据由代码进行生成，使用方法看[#200](https://github.com/flipped-aurora/gin-vue-admin/issues/200)

**Comment by jackeyjin2002** [comment]
了解了，感谢回复。
