### ISSUE TITLE
数据库初始化方法探讨

### ISSUE THREAD

**Issue by maplepie** [flipped-aurora/gin-vue-admin#209]
现在数据库初始化是通过后端修改配置文件完成，能否改为首次使用时跳转到安装页来初始化数据库呢？这样用起来会更加直观，还能方便选择对应的数据库，如果能再加个类似php探针的功能就更好了。

**Comment by SliverHorn** [comment]
Our team plans to use the cli method to initialize the data, then there is no need to manually initialize the data in the backend. An installation page on the front end to initialize the data, I think it is risky. 
The probe function of php may not be applicable to golang.

**Comment by maplepie** [comment]
Ok,Thanks
