### ISSUE TITLE
前端新增表单date字段，后端使用datetime字段对应，能否提供例子

### ISSUE THREAD

**Issue by jiftle** [flipped-aurora/gin-vue-admin#210]
前端新增表单date字段，后端使用datetime字段对应，能否提供例子

现在是类型	`err := c.ShouldBindJSON(&productDelivers)`报错数据绑定失败，parsing time ""2020-09-01 11:10:10"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 11:10:10"" as "T"

**Comment by piexlmax** [comment]
> 前端新增表单date字段，后端使用datetime字段对应，能否提供例子
> 
> 现在是类型 `err := c.ShouldBindJSON(&productDelivers)`报错数据绑定失败，parsing time ""2020-09-01 11:10:10"" as ""2006-01-02T15:04:05Z07:00"": cannot parse " 11:10:10"" as "T"

前端需要给后端传输 new Date类型 后端才可以接受

**Comment by jiftle** [comment]
强行拼凑成go可以识别的time.Time格式，虽然不美观但是好歹解决问题了。 网上的自定义time.Time类型，做了尝试。入库没有问题，但是从库提取数据时，go.orm不是识别，所以放弃。 
```
    async enterDialog() {
      console.log("-----------------")
      let res;
      switch (this.type) {
        case "create":
        //    console.log("------------- formdata -------------")
        //    console.log(this.formData);
            var strCustCreateTime;
          strCustCreateTime = this.formData.custCreateTime;
          if (strCustCreateTime.length < 20) {
              this.formData.custCreateTime += "T01:01:01Z";
          }
```
