### ISSUE TITLE
element-ui 加载方式改成按需加载什么时候优化？

### ISSUE THREAD

**Issue by zhangyanFE** [flipped-aurora/gin-vue-admin#215]

**Comment by piexlmax** [comment]
已经在进行优化，内容包括且不限于按需加载，打包过后404bug修复等。

**Comment by zhangyanFE** [comment]
> 已经在进行优化，内容包括且不限于按需加载，打包过后404bug修复等。

好的，大概什么时候上线呢

**Comment by piexlmax** [comment]
> > 已经在进行优化，内容包括且不限于按需加载，打包过后404bug修复等。
> 
> 好的，大概什么时候上线呢

如果着急可以自行百度优化，项目不想定工期给自己在工作之余增加额外负担，见谅。

**Comment by zhangyanFE** [comment]
> > > 已经在进行优化，内容包括且不限于按需加载，打包过后404bug修复等。
> > 
> > 
> > 好的，大概什么时候上线呢
> 
> 如果着急可以自行百度优化，项目不想定工期给自己在工作之余增加额外负担，见谅。
