### ISSUE TITLE
提个修改

### ISSUE THREAD

**Issue by sonwa** [flipped-aurora/gin-vue-admin#216]
下拉选择，单选，多选等这些值应该有个是整形还是字符选择。现在默认生成出来是全是整形的

**Comment by sonwa** [comment]
[表单生成器]这个可以放一下源码不？看代码是经过压缩的，有源码这个其实都可以自己改一下。

**Comment by SliverHorn** [comment]
> [表单生成器]这个可以放一下源码不？看代码是经过压缩的，有源码这个其实都可以自己改一下。

表单生成器：表单生成器借助 [@form-generator](https://github.com/JakHuang/form-generator)。

**Comment by piexlmax** [comment]
> 下拉选择，单选，多选等这些值应该有个是整形还是字符选择。现在默认生成出来是全是整形的

字典模式默认是整形，自动生成字典类型，规定必须为整形，如果要设置字符串需要自行开发select。框架自动化代码只能做到尽可能通用，没办法满足所有需求，见谅。
