### ISSUE TITLE
【表单生成器】根据代码生成表单

### ISSUE THREAD

**Issue by luyc** [flipped-aurora/gin-vue-admin#220]
想利用表单设计工具修改表单，只能重新开始，不能根据已有的代码生成表单，直接进行设计

**Comment by SliverHorn** [comment]
[@form-generator](https://github.com/JakHuang/form-generator)

**Comment by piexlmax** [comment]
> 想利用表单设计工具修改表单，只能重新开始，不能根据已有的代码生成表单，直接进行设计

这种情况在代码上修改可能会比可视化修改速度更快，感谢提出issue
