### ISSUE TITLE
x-user-id安全漏洞

### ISSUE THREAD

**Issue by luamas** [flipped-aurora/gin-vue-admin#225]
operation.go的文件中取得的userId并未在jwt.go中校验userId的真实性，真实代码应该从jwt校验中取得userId

claims, _ := c.Get("claims")
waitUse := claims.(*request.CustomClaims)
userId, err := strconv.Atoi(strconv.Itoa(int(waitUse.ID)))

**Comment by SliverHorn** [comment]
前端会传递用户id的
因为某些场景不需要jwt鉴权的

**Comment by piexlmax** [comment]
> operation.go的文件中取得的userId并未在jwt.go中校验userId的真实性，真实代码应该从jwt校验中取得userId
> 
> claims, _ := c.Get("claims")
> waitUse := claims.(*request.CustomClaims)
> userId, err := strconv.Atoi(strconv.Itoa(int(waitUse.ID)))

userid不会用于危险场景 此处只用于日志记录 危险场景取自jwt

**Comment by luamas** [comment]
其实比较建议在jwt中重新赋值下c.Request.Header.Set("x-user-id",strconv.Itoa(int(claims.ID)))

**Comment by SliverHorn** [comment]
> 其实比较建议在jwt中重新赋值下c.Request.Header.Set("x-user-id",strconv.Itoa(int(claims.ID)))

好的，后续维护可以加上，感谢你的issues

**Comment by piexlmax** [comment]
> 其实比较建议在jwt中重新赋值下c.Request.Header.Set("x-user-id",strconv.Itoa(int(claims.ID)))

有些场景不存在jwt 比如登录等

**Comment by piexlmax** [comment]
> 其实比较建议在jwt中重新赋值下c.Request.Header.Set("x-user-id",strconv.Itoa(int(claims.ID)))

这种情况会导致对jwt的强依赖 一切需要userid的接口必定需要鉴权

**Comment by piexlmax** [comment]
> @piexlmax 是有这种情况，但是我的理解是有优先原则，如果传了jwt token应该以jwt token解析的为主

可以按照这个做优先调整

**Comment by SliverHorn** [comment]
> @piexlmax 是有这种情况，但是我的理解是有优先原则，如果传了jwt token应该以jwt token解析的为主

此issue已采纳，将在下个版本进行更新，感谢你的issue
