### ISSUE TITLE
創建表沒有帶s, Error 1146: Table 'test.sys_data_authority_ids' doesn't exist

### ISSUE THREAD

**Issue by qinmin328** [flipped-aurora/gin-vue-admin#227]
gin-vue-admin/server/gva/init_data/init_data.go:420 Error 1146: Table 'test.sys_data_authority_ids' doesn't exist
[0.314ms] [rows:0] INSERT INTO `sys_data_authority_ids` (`sys_authority_authority_id`,`data_authority_id_authority_id`) VALUES ("888","888"),("888","8881"),("888","9528"),("9528","8881"),("9528","9528")

將init_data.go:420 中if tx.Table("sys_data_authority_ids").Create(&insert).Error != nil 更改為if tx.Table("sys_data_authority_id").Create(&insert).Error != nil

**Comment by SliverHorn** [comment]
感谢issues。我们会尽快修复的

**Comment by dbgrowth** [comment]
> 感谢issues。我们会尽快修复的

在线等，大兄弟

**Comment by piexlmax** [comment]
> > 感谢issues。我们会尽快修复的
> 
> 在线等，大兄弟

主干已经修复，gorm1.2.0升级1.2.1 关联模式有变化 这边没有测出来 已经修复
