### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by faddei** [flipped-aurora/gin-vue-admin#229]
service 里面定义一个结构体好操作点例如sys_user.go里面
```go
type SysUser struct {
     ...... //这里可以添加一些下面用到的也可以忽略
}

func (this *SysUser) Register(u model.SysUser) (err error, userInter model.SysUser) {
	....
}
```

用的时候直接

``` go
var service service.SysUser
service.Register(u)
```

**Comment by piexlmax** [comment]
> service 里面定义一个结构体好操作点例如sys_user.go里面
> 
> ```go
> type SysUser struct {
>      ...... //这里可以添加一些下面用到的也可以忽略
> }
> 
> func (this *SysUser) Register(u model.SysUser) (err error, userInter model.SysUser) {
> 	....
> }
> ```
> 
> 用的时候直接
> 
> ```go
> var service service.SysUser
> service.Register(u)
> ```

此模式为1.0模式时候使用的 2.0尝试统一为面向方法模式 3.0重构模式将会重新使用此模式来做面向接口类型的开发~model将会获得更多操作通道，建议合理~感谢issue
