### ISSUE TITLE
下载master代码直接运行出现以下错误：

### ISSUE THREAD

**Issue by ice616** [flipped-aurora/gin-vue-admin#230]
panic: json: unknown field "$ref"

goroutine 1 [running]:
github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
	C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/spec.go:68
github.com/go-openapi/spec.initResolutionCache(0xc0003702a0, 0xc000370270)
	C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:57 +0x1cb
github.com/go-openapi/spec.init.0()
	C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:51 +0x29

Process finished with exit code 2

**Comment by piexlmax** [comment]
> panic: json: unknown field "$ref"
> 
> goroutine 1 [running]:
> github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/spec.go:68
> github.com/go-openapi/spec.initResolutionCache(0xc0003702a0, 0xc000370270)
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:57 +0x1cb
> github.com/go-openapi/spec.init.0()
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:51 +0x29
> 
> Process finished with exit code 2

可以提供一下运行步骤吗？$ref为前端内容，现在在后端报错出现，有点匪夷所思

**Comment by piexlmax** [comment]
> panic: json: unknown field "$ref"
> 
> goroutine 1 [running]:
> github.com/go-openapi/spec.MustLoadSwagger20Schema(...)
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/spec.go:68
> github.com/go-openapi/spec.initResolutionCache(0xc0003702a0, 0xc000370270)
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:57 +0x1cb
> github.com/go-openapi/spec.init.0()
> C:/Users/Admin/go/pkg/mod/github.com/go-openapi/spec@v0.19.7/cache.go:51 +0x29
> 
> Process finished with exit code 2

提供一下go版本，大部分报错在pkg，可能跟版本有关

**Comment by ice616** [comment]
go 1.13.5

**Comment by SliverHorn** [comment]
> go 1.13.5

你是做了什么操作导致的？

**Comment by ice616** [comment]
我什么操作也没做，就是下载后修改了mysql地址运行就出现这个错误了。

刚刚说升级golang版本到 1.15.2 ；可以正常使用项目了。
