### ISSUE TITLE
初始化Pgsql时SysOperationRecord创建失败

### ISSUE THREAD

**Issue by lemontreehuang** [flipped-aurora/gin-vue-admin#233]
原因：SysOperationRecord中的Resp的类型为longtext，Pgsql中没有这个数据类型，改成text就可以了，
刚接触gva，请问操作记录里有什么情况需要longtext来保存数据吗？

**Comment by SliverHorn** [comment]
Pgsql的问题需要自己解决
- Pgsql与Mysql冲突点多，团队人力不足，无法对Pgsql进行维护
- 操作记录设置为longtext是为了防止使用中间件记录的返回json太长而导致的报错，具体场景看自身的业务需求
