### ISSUE TITLE
密码明文问题

### ISSUE THREAD

**Issue by pizan** [flipped-aurora/gin-vue-admin#235]
{
"username": "admin",
"password": "123456",
"captcha": "233456",
"captchaId": "XykQRMHNZs7F9g4UEfRO"
}
登录密码明文请求会不会不太安全

**Comment by SliverHorn** [comment]
您有好的建议嘛？有的话建议你告诉我们该如何改

**Comment by pizan** [comment]
> 您有好的建议嘛？有的话建议你告诉我们该如何改

AES加密算法

**Comment by piexlmax** [comment]
> > 您有好的建议嘛？有的话建议你告诉我们该如何改
> 
> AES加密算法

加密模式目前只有入库之前后端做的md5 由于每个人对于加密需求不同 因此未作前台加密传输

**Comment by ccfish86** [comment]
我在另外一个项目上看到的RSA`密码`其实不错？要不给合过来？`https://github.com/piupuer/gin-web`

**Comment by aaftio** [comment]
> > 您有好的建议嘛？有的话建议你告诉我们该如何改
> 
> AES加密算法

结论：AES类型的对称加密并没有任何安全提升效果。
- 假设在https下，明文密码并没有明显的安全问题。
- 那么出问题的只是在http下，如果是http，那么总是无法防止重放攻击。那么对密码做对称加密的唯一作用只是让密码不会因为被窃取后，威胁到用户的其它网站（因为用户习惯在所有网站使用相同的密码），这也是数据库md5存储的原因。而AES类型的对称加密传输没有任何作用，因为加密的key要通过http传输到浏览器，这个明文传输的过程使得攻击者也可以拿到AES加密的key，那么在用户提交登录的时候，攻击者可以使用这个key对密文进行解密，得到明文密码，所以如果要提升http的一点安全性，只需要将密码md5的过程放到前端，这也是唯一能做的了

**Comment by murusu** [comment]
> > > 您有好的建议嘛？有的话建议你告诉我们该如何改
> > 
> > 
> > AES加密算法
> 
> 结论：AES类型的对称加密并没有任何安全提升效果。
> 
>     * 假设在https下，明文密码并没有明显的安全问题。
> 
>     * 那么出问题的只是在http下，如果是http，那么总是无法防止重放攻击。那么对密码做对称加密的唯一作用只是让密码不会因为被窃取后，威胁到用户的其它网站（因为用户习惯在所有网站使用相同的密码），这也是数据库md5存储的原因。而AES类型的对称加密传输没有任何作用，因为加密的key要通过http传输到浏览器，这个明文传输的过程使得攻击者也可以拿到AES加密的key，那么在用户提交登录的时候，攻击者可以使用这个key对密文进行解密，得到明文密码，所以如果要提升http的一点安全性，只需要将密码md5的过程放到前端，这也是唯一能做的了

http重放攻击是可以通过加入时间戳的方法来防止的

**Comment by aaftio** [comment]
> > > > 您有好的建议嘛？有的话建议你告诉我们该如何改
> 
> > > 
> 
> > > 
> 
> > > AES加密算法
> 
> > 
> 
> > 结论：AES类型的对称加密并没有任何安全提升效果。
> 
> > 
> 
> >     * 假设在https下，明文密码并没有明显的安全问题。
> 
> > 
> 
> >     * 那么出问题的只是在http下，如果是http，那么总是无法防止重放攻击。那么对密码做对称加密的唯一作用只是让密码不会因为被窃取后，威胁到用户的其它网站（因为用户习惯在所有网站使用相同的密码），这也是数据库md5存储的原因。而AES类型的对称加密传输没有任何作用，因为加密的key要通过http传输到浏览器，这个明文传输的过程使得攻击者也可以拿到AES加密的key，那么在用户提交登录的时候，攻击者可以使用这个key对密文进行解密，得到明文密码，所以如果要提升http的一点安全性，只需要将密码md5的过程放到前端，这也是唯一能做的了
> 
> 
> 
> http重放攻击是可以通过加入时间戳的方法来防止的
> 
> 

请问如何防止，因为http是明文的，当攻击者获取到了你的cookie，他就可以每次请求的时候携带你的cookie，对于服务端来说这和一个真正的用户来说没有任何区别。他可以利用你的cookie进行任何你可以做的操作。这是为什么Google等浏览器厂商强行推https的原因。在移动互联网时代一个恶意wifi就够了，只有https能解决这个问题，所以http可以不用再讨论了。

**Comment by FInW** [comment]
重点是用户并不想给你看到他的密码原文是什么。。这是很关键的

**Comment by bypanghu** [comment]
> > > > > 您有好的建议嘛？有的话建议你告诉我们该如何改
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > AES加密算法
> > 
> > 
> > > 
> > 
> > 
> > > 结论：AES类型的对称加密并没有任何安全提升效果。
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * 假设在https下，明文密码并没有明显的安全问题。
> > > ```
> > 
> > 
> > > 
> > 
> > 
> > > ```
> > > * 那么出问题的只是在http下，如果是http，那么总是无法防止重放攻击。那么对密码做对称加密的唯一作用只是让密码不会因为被窃取后，威胁到用户的其它网站（因为用户习惯在所有网站使用相同的密码），这也是数据库md5存储的原因。而AES类型的对称加密传输没有任何作用，因为加密的key要通过http传输到浏览器，这个明文传输的过程使得攻击者也可以拿到AES加密的key，那么在用户提交登录的时候，攻击者可以使用这个key对密文进行解密，得到明文密码，所以如果要提升http的一点安全性，只需要将密码md5的过程放到前端，这也是唯一能做的了
> > > ```
> > 
> > 
> > http重放攻击是可以通过加入时间戳的方法来防止的
> 
> 请问如何防止，因为http是明文的，当攻击者获取到了你的cookie，他就可以每次请求的时候携带你的cookie，对于服务端来说这和一个真正的用户来说没有任何区别。他可以利用你的cookie进行任何你可以做的操作。这是为什么Google等浏览器厂商强行推https的原因。在移动互联网时代一个恶意wifi就够了，只有https能解决这个问题，所以http可以不用再讨论了。
