### ISSUE TITLE
el-container 标签使用bug

### ISSUE THREAD

**Issue by miner1521** [flipped-aurora/gin-vue-admin#237]
![image](https://user-images.githubusercontent.com/63787277/94524241-efe9e380-0264-11eb-939c-3661597d3e63.png)

**Comment by miner1521** [comment]
![image](https://user-images.githubusercontent.com/63787277/94524920-dbf2b180-0265-11eb-8955-b882365b6eb4.png)
应该是这个问题导致的

**Comment by piexlmax** [comment]
为了实现当前的整体布局效果，css实现模式不会根据特定化开发需求做出调整，感谢issue，如需个性化调整，可以自行进行页面构建或者购买付费服务。
