### ISSUE TITLE
在线体验访问不了

### ISSUE THREAD

**Issue by jiaoshengkang** [flipped-aurora/gin-vue-admin#240]
http://demo.gin-vue-admin.com/#/login

Request URL: http://demo.gin-vue-admin.com/static/js/runtime.5627d3b3.js
Request Method: GET
Status Code: 404 Not Found
Remote Address: 139.9.113.229:80
Referrer Policy: no-referrer-when-downgrade

**Comment by piexlmax** [comment]
已经修复 感谢
