### ISSUE TITLE
有没有计划将 web 端升级为 vue3

### ISSUE THREAD

**Issue by MuRongXiaoDouBi** [flipped-aurora/gin-vue-admin#241]
如果可以的话，我愿意大量贡献代码

**Comment by SliverHorn** [comment]
> 如果可以的话，我愿意大量贡献代码

您好，我们团队有计划的，web项目的3.0在筹备中了，但是没有一个好用的UI，类似element ui这样的好UI，vue3也有像ant.design vue这样的，但前端团队觉得不好用故没有升级

**Comment by MuRongXiaoDouBi** [comment]
> 您好，我们团队有计划的，web项目的3.0在筹备中了，但是没有一个好用的UI，类似element ui这样的好UI，vue3也有像ant.design vue这样的，但前端团队觉得不好用故没有升级

vue3 的 element 版本新的项目为 element-plus ，好像是原来的 elemenet 团队开发的

**Comment by SliverHorn** [comment]
> > 您好，我们团队有计划的，web项目的3.0在筹备中了，但是没有一个好用的UI，类似element ui这样的好UI，vue3也有像ant.design vue这样的，但前端团队觉得不好用故没有升级
> 
> vue3 的 element 版本新的项目为 element-plus ，好像是原来的 elemenet 团队开发的

这个我们有所关注，但是据说是个人维护的

**Comment by MuRongXiaoDouBi** [comment]
其实 ant 也不错，ant 将一些常用方法封装成 useXXX ，写起来更自由了

**Comment by SliverHorn** [comment]
web项目升级vue3.0,server项目也会升级成3.0，会使用接口形式进行重构，会比现在的2.0更规范 开发速度都要再增进一倍，敬请期待

**Comment by SliverHorn** [comment]
> 其实 ant 也不错，ant 将一些常用方法封装成 useXXX ，写起来更自由了

还是要看项目作者及前端团队的选择，我主要负责的是后端的工作

**Comment by piexlmax** [comment]
目前有在关注element+ 看一下它的更新状态然后前端开始进行更换 3.0将会是一个大版本

**Comment by MuRongXiaoDouBi** [comment]
> 目前有在关注element+ 看一下它的更新状态然后前端开始进行更换 3.0将会是一个大版本

不知道 vue3.x 版本，将会使用什么样的技术栈，目前比较关心打包工具是继续使用 webpack ，还是会配合 vite 使用 rollup
