### ISSUE TITLE
[建议]希望使用单数表名

### ISSUE THREAD

**Issue by eureka101v** [flipped-aurora/gin-vue-admin#242]
gorm的实体类变为数据表时，默认会变为复数，这样一个是概念上奇怪，因为数据表也是更多代表一个实体而不是列表，一个是容易增加拼写上错误的可能性，如一些非常规的复数形式，例如y的复数ies，Child的复数children，Datum的复数Data，我觉得gorm的这个默认开启的增加复数的操作有些没有必要，gorm也提供了单数表名的配置选项，希望能考虑是否能在未来版本中的gorm初始化时关闭复数表名这一默认操作

**Comment by SliverHorn** [comment]
不会的，但是在你自己开发的应用了可以自定义表名来关闭gorm的复数表名

**Comment by piexlmax** [comment]
> gorm的实体类变为数据表时，默认会变为复数，这样一个是概念上奇怪，因为数据表也是更多代表一个实体而不是列表，一个是容易增加拼写上错误的可能性，如一些非常规的复数形式，例如y的复数ies，Child的复数children，Datum的复数Data，我觉得gorm的这个默认开启的增加复数的操作有些没有必要，gorm也提供了单数表名的配置选项，希望能考虑是否能在未来版本中的gorm初始化时关闭复数表名这一默认操作

gorm默认复数表名，这也是gorm的默认规范，这边就没有对它进行修改，这个issue可以提交给gorm，此处会遵循form所定制的规则，感谢iuuse
