### ISSUE TITLE
web 端在linux环境不能执行吧

### ISSUE THREAD

**Issue by bzyy1024** [flipped-aurora/gin-vue-admin#244]
web 端在linux环境不能执行吧，好像报错都是缺少exe

**Comment by piexlmax** [comment]
web端不会存在环境问题

**Comment by bzyy1024** [comment]
感谢大神恢复，麻烦大神在给看一下这个web端的报错。
linux 怎么会有 EXE 呢 spawn cmd.exe


bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ ls
README.md&nbsp; babel.config.js&nbsp; node_modules&nbsp; package-lock.json&nbsp; package.json&nbsp; public&nbsp; src&nbsp; vue.config.js
bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})


audited 1732 packages in 65.322s


49 packages are looking for funding
&nbsp; run `npm fund` for details


found 13 vulnerabilities (12 low, 1 high)
&nbsp; run `npm audit fix` to fix them, or `npm audit` for details
bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ npm run serve


&gt; qm-plus-vue-page@0.1.0 serve /mnt/f/www/gin-vue-admin/web
&gt; vue-cli-service serve


&nbsp;INFO&nbsp; Starting development server...
98% after emitting CopyPlugin




&nbsp;DONE&nbsp; Compiled successfully in 25818ms&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 11:41:02 AM




&nbsp; App running at:
&nbsp; - Local:&nbsp; &nbsp;http://localhost:8080&nbsp;
&nbsp; - Network: http://192.168.0.110:8080


&nbsp; Note that the development build is not optimized.
&nbsp; To create a production build, run npm run build.


events.js:291
&nbsp; &nbsp; &nbsp; throw er; // Unhandled 'error' event
&nbsp; &nbsp; &nbsp; ^


Error: spawn cmd.exe ENOENT
&nbsp; &nbsp; at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
&nbsp; &nbsp; at onErrorNT (internal/child_process.js:464:16)
&nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
&nbsp; &nbsp; at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
&nbsp; &nbsp; at onErrorNT (internal/child_process.js:464:16)
&nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:80:21) {
&nbsp; errno: -2,
&nbsp; code: 'ENOENT',
&nbsp; syscall: 'spawn cmd.exe',
&nbsp; path: 'cmd.exe',
&nbsp; spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8080' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! qm-plus-vue-page@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!&nbsp;
npm ERR! Failed at the qm-plus-vue-page@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:
npm ERR!&nbsp; &nbsp; &nbsp;/home/bzyy/.npm/_logs/2020-10-10T03_41_02_899Z-debug.log

**Comment by piexlmax** [comment]
> 感谢大神恢复，麻烦大神在给看一下这个web端的报错。 linux 怎么会有 EXE 呢 spawn cmd.exe bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ ls README.md&nbsp; babel.config.js&nbsp; node_modules&nbsp; package-lock.json&nbsp; package.json&nbsp; public&nbsp; src&nbsp; vue.config.js bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ npm install npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}) audited 1732 packages in 65.322s 49 packages are looking for funding &nbsp; run `npm fund` for details found 13 vulnerabilities (12 low, 1 high) &nbsp; run `npm audit fix` to fix them, or `npm audit` for details bzyy@DESKTOP-UJQ9B51:/mnt/f/www/gin-vue-admin/web$ npm run serve &gt; qm-plus-vue-page@0.1.0 serve /mnt/f/www/gin-vue-admin/web &gt; vue-cli-service serve &nbsp;INFO&nbsp; Starting development server... 98% after emitting CopyPlugin &nbsp;DONE&nbsp; Compiled successfully in 25818ms&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 11:41:02 AM &nbsp; App running at: &nbsp; - Local:&nbsp; &nbsp;http://localhost:8080&nbsp; &nbsp; - Network: http://192.168.0.110:8080 &nbsp; Note that the development build is not optimized. &nbsp; To create a production build, run npm run build. events.js:291 &nbsp; &nbsp; &nbsp; throw er; // Unhandled 'error' event &nbsp; &nbsp; &nbsp; ^ Error: spawn cmd.exe ENOENT &nbsp; &nbsp; at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19) &nbsp; &nbsp; at onErrorNT (internal/child_process.js:464:16) &nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:80:21) Emitted 'error' event on ChildProcess instance at: &nbsp; &nbsp; at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12) &nbsp; &nbsp; at onErrorNT (internal/child_process.js:464:16) &nbsp; &nbsp; at processTicksAndRejections (internal/process/task_queues.js:80:21) { &nbsp; errno: -2, &nbsp; code: 'ENOENT', &nbsp; syscall: 'spawn cmd.exe', &nbsp; path: 'cmd.exe', &nbsp; spawnargs: [ '/c', 'start', '""', '/b', 'http://localhost:8080' ] } npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! qm-plus-vue-page@0.1.0 serve: `vue-cli-service serve` npm ERR! Exit status 1 npm ERR!&nbsp; npm ERR! Failed at the qm-plus-vue-page@0.1.0 serve script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR!&nbsp; &nbsp; &nbsp;/home/bzyy/.npm/_logs/2020-10-10T03_41_02_899Z-debug.log

添加以下 shouzi_1994微信 这个问题很特殊 我可以微信看下

**Comment by bzyy1024** [comment]
这个问题是系统问题，ubuntu18,20版本 下存在出错的现象，在wsl下也出错，在centos下没有问题。
