### ISSUE TITLE
搭建后初始密码是多少

### ISSUE THREAD

**Issue by EverCurse** [flipped-aurora/gin-vue-admin#245]
搭建后初始密码是多少 数据库中没有用户 master分支

**Comment by SliverHorn** [comment]
> 搭建后初始密码是多少 数据库中没有用户 master分支

https://www.gin-vue-admin.com/docs/server#3%E6%95%B0%E6%8D%AE%E5%BA%93%E5%88%9D%E5%A7%8B%E5%8C%96， 初始账号admin，密码123456
