### ISSUE TITLE
使用postgresql数据库搭建系统,casbin部分代码出错（仅支持MySQL）

### ISSUE THREAD

**Issue by zgltao** [flipped-aurora/gin-vue-admin#247]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.13 windows/amd64

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
版本：v2.3.0 

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
使用postgresql数据库搭建系统

### 7. 您看到了什么 ?
此处仅支持MySQL，不支持其他数据库类型，需要修复
![image](https://user-images.githubusercontent.com/29600000/95966852-32ebaf80-0e3e-11eb-9c67-4e50f15a7906.png)

**Comment by zgltao** [comment]
> ### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
> go version go1.13 windows/amd64
> 
> ### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
> 版本：v2.3.0
> 
> ### 4. 可以在master版本中复现此问题吗 ?
> 可以
> 
> ### 5. 您做了什么 ?
> 使用postgresql数据库搭建系统
> 
> ### 7. 您看到了什么 ?
> 如下图此处仅支持MySQL，不支持其他数据库类型，需要修复
> ![image](https://user-images.githubusercontent.com/29600000/95966852-32ebaf80-0e3e-11eb-9c67-4e50f15a7906.png)
> v2.3.0版本出错代码位置是：\service\sys_casbin.go  第105行：
>func Casbin() *casbin.Enforcer {
>	admin := global.GVA_CONFIG.Mysql
>        a, _ := gormadapter.NewAdapter(global.GVA_CONFIG.System.DbType, >admin.Username+":"+admin.Password+"@("+admin.Path+")/"+admin.Dbname, true)

**Comment by SliverHorn** [comment]
- 使用postgresql请自行修改，postgresql与mysql会出现代码不兼容问题
- 开发团队人手不足，无法对postgresql完美支持，还请谅解
- pr上来可以，但是不建议，你或许能适配当前版本，但是gin-vue-admin更新版本太快了，无法做到面面俱到，还请谅解

**Comment by zgltao** [comment]
可以理解~谢谢回答
