### ISSUE TITLE
web前端多语言

### ISSUE THREAD

**Issue by xiongdi9456** [flipped-aurora/gin-vue-admin#248]
希望前端支持多语言啊

**Comment by piexlmax** [comment]
> 希望前端支持多语言啊

工作量略大 体力工作 建议自己使用i18n实现即可

**Comment by xiongdi9456** [comment]
不用全部搞成多语言啊，开一个新页面，在这个新页面实现就好了我觉得，框架里面有就OK，用户自己用的话参考这个页面自己改就行
