### ISSUE TITLE
register注册提示NickName不能为空

### ISSUE THREAD

**Issue by lzktest** [flipped-aurora/gin-vue-admin#251]
http://demo.gin-vue-admin.com/#/register

注册返回
{"code":7,"data":{},"msg":"NickName值不能为空"}

而前端页面只提交了这几个参数
{"username":"tianyu","password":"Aa123456","rePassword":"Aa123456"}

**Comment by piexlmax** [comment]
这个注册页面是非法的 后期准备拿掉 后台管理系统的注册在内部管理员手动分配

**Comment by piexlmax** [comment]
已修复
