### ISSUE TITLE
v2.3.31 自动生成表单项 默认值读取问题

### ISSUE THREAD

**Issue by andonglong** [flipped-aurora/gin-vue-admin#252]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.2 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
Nodejs v12.18.4
npm 6.14.8

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
v2.3.31

### 4. 可以在master版本中复现此问题吗 ?
是的

### 5. 您做了什么 ?

` <el-form-item label="灯继电器号" prop="relayidLamp">
          <el-input v-model="formData.relayidLamp" placeholder="请输入灯继电器号" clearable :style="{width: '100%'}">
          </el-input>
        </el-form-item>`

` formData: {
        relayidLamp: '4',
        relayidfan: '3',
      },`
### 6. 您期望看到什么 ?
每次打开新增窗口，显示默认值

### 7. 您看到了什么 ?
每次打开新增窗口，未能显示默认值，关闭菜单窗口，重新点击菜单，点击新增 才能显示默认值
并且仅第一次显示默认值，一但关闭弹窗，再次新增，默认值就不显示了。需要重新点击菜单后才行。

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
取消操作内部默认执行了清空form的操作，注释取消中的clear方法，或者将方法内默认值修改为你目前的默认值即可。
