### ISSUE TITLE
根据代码注释和issue记录配置https并未生效

### ISSUE THREAD

**Issue by live106** [flipped-aurora/gin-vue-admin#253]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.2 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

nodejs v12.18.3 
npm 6.14.6

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?

取消了router.go中的`Router.Use(middleware.LoadTls())`注释，项目目录下添加了证书文件 key.pem, cert.pem

### 6. 您期望看到什么 ?

1. 能够正常访问https接口；
2. swagger能够正常访问。

### 7. 您看到了什么 ?

1. 无法正常访问https接口；
2. swagger 跳转到https地址但无法连接

检查代码未发现任何调用对 ListenAndServeTls方法的调用，无法理解如何实现的tls监听。

### 8. 错误堆栈或者SQL打印

**Comment by live106** [comment]
server.go 代码中只看到了对ddd的调用。

```
package core

import (
	"fmt"
	"gin-vue-admin/global"
	"gin-vue-admin/initialize"
	"go.uber.org/zap"
	"time"
)

type server interface {
	ListenAndServe() error
}

func RunWindowsServer() {
	if global.GVA_CONFIG.System.UseMultipoint {
		// 初始化redis服务
		initialize.Redis()
	}
	Router := initialize.Routers()
	Router.Static("/form-generator", "./resource/page")

	address := fmt.Sprintf(":%d", global.GVA_CONFIG.System.Addr)
	s := initServer(address, Router)
	// 保证文本顺序输出
	// In order to ensure that the text order output can be deleted
	time.Sleep(10 * time.Microsecond)
	global.GVA_LOG.Info("server run success on ", zap.String("address", address))

	fmt.Printf(`欢迎使用 xdd-Admin
	默认自动化文档地址:http://127.0.0.1%s/swagger/index.html
	默认前端文件运行地址:http://127.0.0.1:8000
`, address)
	global.GVA_LOG.Error(s.ListenAndServe().Error())
}
```

**Comment by SliverHorn** [comment]
- 请问你看 [secure](https://github.com/unrolled/secure) 这个库的readme文档了吗？
- https是借助 [secure](https://github.com/unrolled/secure) 这个库做成的中间件

**Comment by live106** [comment]
看过。
麻烦问一下是否需要自行修改代码实现 ListenAndServeTLS 监听，我翻代码没有查到调用。
我之前是看的issue 19 [https://github.com/flipped-aurora/gin-vue-admin/issues/19](url)
以为已经全部集成好了。

**Comment by SliverHorn** [comment]
- 需要自行打开中间件的调用

**Comment by live106** [comment]
您是只`Router.Use(middleware.LoadTls())`这个调用吗？

**Comment by SliverHorn** [comment]
- 是的，如何配置看 [secure](https://github.com/unrolled/secure) 的readme就可以了

**Comment by live106** [comment]
行吧，确定https能正常跑是吗？从代码逻辑我真的没看懂:(

**Comment by SliverHorn** [comment]
> 行吧，确定https能正常跑是吗？从代码逻辑我真的没看懂:(

如果https不能跑，你应该去 [https://github.com/unrolled/secure](https://github.com/unrolled/secure) 去提issues了

**Comment by SliverHorn** [comment]
我看我们代码没什么问题的

**Comment by live106** [comment]
我在gva的代码没有看到监听tls, 没有起https server啊

**Comment by live106** [comment]
麻烦注意issue的第一个条件。

### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.2 darwin/amd64
