### ISSUE TITLE
经常频繁提示令牌过期或异地登陆，

### ISSUE THREAD

**Issue by cantinzing** [flipped-aurora/gin-vue-admin#254]
1. 您使用的是哪个版本的Go和系统类型/架构 ?
go version go1.15.1 windows/amd64

2. 您使用的是哪个版本的 Nodejs 和 npm 或 cnpm ?
Node.js v12.18.2
npm 6.14.5

3. 您使用的是哪个版本的 gin-vue-admin ?
master

4. 可以在master版本中复现此问题吗 ?
可以

5. 您做了什么 ?
没做什么，并没有异地登陆

6. 您期望看到什么 ?
希望在使用的过程中不要那么频繁的跳出令牌过期或异地登陆
7. 您看到了什么 ?
不定时的跳出令牌过期或异地登陆，有时几分钟，有时几十分钟，然后再登陆的时候一直提示密码错误，多提交几次却可以正常登陆

8. 错误堆栈或者SQL打印

**Comment by maplepie** [comment]
我之前遇到过类似的问题，我的问题是腾讯管家禁止了日志文件软连接，你可以看看终端是不是输出类似的信息。

**Comment by cantinzing** [comment]
> 我之前遇到过类似的问题，我的问题是腾讯管家禁止了日志文件软连接，你可以看看终端是不是输出类似的信息。
![image](https://user-images.githubusercontent.com/24792871/96564804-2e1f7380-12f6-11eb-9bbe-991ceef1b93f.png)
看了控制台好像是数据库连接被中断，不知道怎么解决

**Comment by fzqk9** [comment]
这个问题我也经常遇到

**Comment by fzqk9** [comment]
看来版主得认真看看了   1 数据库经常被断开  ,   2  前端经常提示什么异地登录

**Comment by PiKaChu-ff** [comment]
+1

**Comment by PiKaChu-ff** [comment]
> > 我之前遇到过类似的问题，我的问题是腾讯管家禁止了日志文件软连接，你可以看看终端是不是输出类似的信息。
> > ![image](https://user-images.githubusercontent.com/24792871/96564804-2e1f7380-12f6-11eb-9bbe-991ceef1b93f.png)
> > 看了控制台好像是数据库连接被中断，不知道怎么解决

请问找到原因了吗，我也遇到这个问题
