### ISSUE TITLE
swag init 不成功 

### ISSUE THREAD

**Issue by aochant** [flipped-aurora/gin-vue-admin#256]
**1. 您使用的是哪个版本的Go和系统类型/架构 ?**
go version go1.14   win 64

**2. 您使用的是哪个版本的 Nodejs 和 npm 或 cnpm ?**

**3. 您使用的是哪个版本的 gin-vue-admin ?**
master

**4. 可以在master版本中复现此问题吗 ?**
可以

**5. 您做了什么 ?**
 cd server
swag init

**6. 您期望看到什么 ?**

正常生成swagger文档

**7. 您看到了什么 ?**
 错误堆栈

**8. 错误堆栈或者SQL打印**
 
D:\workspace\gin-vue-admin_github\server>swag init
2020/10/21 11:33:57 Generate swagger docs....
2020/10/21 11:33:58 Generate general API Info, search dir:./
2020/10/21 11:33:59 Generating model.SysAuthority
2020/10/21 11:33:59 Skipping 'model.SysAuthority', recursion detected.
2020/10/21 11:33:59 Skipping 'model.SysAuthority', recursion detected.
2020/10/21 11:33:59 Generating model.SysBaseMenu
2020/10/21 11:33:59 ParseComment error in file api\v1\sys_authority.go :cannot find type definition: gorm.Model

**Comment by SliverHorn** [comment]
- 请按照issues模板进行提出issues

**Comment by piexlmax** [comment]
> **1. 您使用的是哪个版本的Go和系统类型/架构 ?**
> go version go1.14 win 64
> 
> **2. 您使用的是哪个版本的 Nodejs 和 npm 或 cnpm ?**
> 
> **3. 您使用的是哪个版本的 gin-vue-admin ?**
> master
> 
> **4. 可以在master版本中复现此问题吗 ?**
> 可以
> 
> **5. 您做了什么 ?**
> cd server
> swag init
> 
> **6. 您期望看到什么 ?**
> 
> 正常生成swagger文档
> 
> **7. 您看到了什么 ?**
> 错误堆栈
> 
> **8. 错误堆栈或者SQL打印**
> 
> D:\workspace\gin-vue-admin_github\server>swag init
> 2020/10/21 11:33:57 Generate swagger docs....
> 2020/10/21 11:33:58 Generate general API Info, search dir:./
> 2020/10/21 11:33:59 Generating model.SysAuthority
> 2020/10/21 11:33:59 Skipping 'model.SysAuthority', recursion detected.
> 2020/10/21 11:33:59 Skipping 'model.SysAuthority', recursion detected.
> 2020/10/21 11:33:59 Generating model.SysBaseMenu
> 2020/10/21 11:33:59 ParseComment error in file api\v1\sys_authority.go :cannot find type definition: gorm.Model

这个跟本机环境有关 有个朋友在微信也问过我这个问题 查看一下mod配置以及path配置

**Comment by softmaxs** [comment]
@aochant 我也遇到这问题，环境 go version go1.15.3 ubuntu 20,你有解决这问题没？求指点！

**Comment by mlsjla** [comment]
参考下这个问题， 官方那边同样问题。

https://github.com/swaggo/swag/issues/810

**Comment by softmaxs** [comment]
我怎么没看到解决办法，需要怎么处理？
@mlsjla

**Comment by softmaxs** [comment]
swag 不能高于1.6.7

**Comment by mlsjla** [comment]
@softmaxs 

是这个问题。 但是希望能升级兼容新版。 go的版本管理太坑了。

```
 go get -u github.com/swaggo/swag/cmd/swag@v1.6.7
```

**Comment by LioCisco** [comment]
swag 不能高于1.6.7
go get -u github.com/swaggo/swag/cmd/swag@v1.6.7

**Comment by songxiaokui** [comment]
021/04/28 15:44:59 Generating logic.FrontChartResult
2021/04/28 15:44:59 Skipping 'logic.FrontChartResult', recursion detected.
2021/04/28 15:44:59 Generating prediction.dailyPredictionIntervalResp
2021/04/28 15:44:59 Generating prediction.dailyPredictionMonthResp
2021/04/28 15:44:59 Generating logic.FrontChartResult
2021/04/28 15:44:59 Skipping 'logic.FrontChartResult', recursion detected.
2021/04/28 15:44:59 Generating prediction.dailyPredictionRateResp
2021/04/28 15:44:59 Generating prediction.energyAnalysisResp
2021/04/28 15:44:59 Generating prediction.historyEnergyCorrelationResp
2021/04/28 15:44:59 Generating logic.FrontChartResult
2021/04/28 15:44:59 Skipping 'logic.FrontChartResult', recursion detected.
2021/04/28 15:44:59 Generating prediction.monthlyEnergyResp
2021/04/28 15:44:59 Generating logic.FrontChartResult
2021/04/28 15:44:59 Skipping 'logic.FrontChartResult', recursion detected.
2021/04/28 15:44:59 Generating prediction.monthlyPredictionDeviationRateResp
2021/04/28 15:44:59 Generating prediction.monthlyPredictionIntervalResp
2021/04/28 15:44:59 Generating prediction.nextMonthDailyPredictResponse
2021/04/28 15:44:59 Generating logic.FrontChartResult
2021/04/28 15:44:59 Skipping 'logic.FrontChartResult', recursion detected.

how to resolve recursion detected.
