### ISSUE TITLE
关于动态路由用.vue扩展名文件的疑问

### ISSUE THREAD

**Issue by fxjs** [flipped-aurora/gin-vue-admin#259]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
os:linux
cpu nums:12
compiler:gc
go version:go1.15.3
goroutine nums:32

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
node v12.19.0
npm 6.14.8

---
请问web端路由是怎么直接使用的`.vue`扩展名文件的呢？
看getMenu接口输出到前端为：‘"component":"view/dashboard/index.vue"’， 
这里的vue文件在开发环境可以用，在prod环境 vue文件经过webapck打包之后，组件都是js了， 这个接口返回*.vue文件，还能运行么？ 这里有点疑惑，谢谢告知。

@piexlmax

**Comment by piexlmax** [comment]
已在微信群解答~此issue关闭
