### ISSUE TITLE
操作编辑按钮后点击确认，自动软删除

### ISSUE THREAD

**Issue by fengjiannan2010** [flipped-aurora/gin-vue-admin#263]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.14.2 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

go version go1.14.2 windows/amd64

6.14.5

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

v2.3.4

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?

使用官网的demo 网址，进入超级管理员菜单，api管理，点击编辑按钮，修改值，或者不修改，点击确认后，数据会软删除

### 6. 您期望看到什么 ?

解决这个软删除的bug,

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
感谢pr  经过测试确实存在此bug 正在修复

**Comment by piexlmax** [comment]
已修复
