### ISSUE TITLE
docker build 失败

### ISSUE THREAD

**Issue by rsaLive** [flipped-aurora/gin-vue-admin#265]
docker 内运行环境
docker-compose up --build
报错：
![gin 报错](https://user-images.githubusercontent.com/14867935/97671381-16e54080-1ac3-11eb-8d39-88f69f7a38ac.png)

**Comment by piexlmax** [comment]
提供一下当前使用版本 主干还是 某个tag

**Comment by SliverHorn** [comment]
1. 不建议在windows平台进行运行docker-compose的
2. 根据截图可以得出，脚本是写入容器内部成功，但是执行报错，这种错误我们无法解决，建议在linux或者mac上进行再次部署，如果还是失败，请告知我，
3. docker-compose是经过mac平台测试的

**Comment by rsaLive** [comment]
> 提供一下当前使用版本 主干还是 某个tag

master 版本

**Comment by rsaLive** [comment]
> 1. 不建议在windows平台进行运行docker-compose的
> 2. 根据截图可以得出，脚本是写入容器内部成功，但是执行报错，这种错误我们无法解决，建议在linux或者mac上进行再次部署，如果还是失败，请告知我，
> 3. docker-compose是经过mac平台测试的

好的 我换linux看看
