### ISSUE TITLE
登录用户不存在时提示位置异常 

### ISSUE THREAD

**Issue by FlameMida** [flipped-aurora/gin-vue-admin#266]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go 1.15

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v12.19.0

6.14.8

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

2020/10/31

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
登录时 提示用户不存在的 message box位置异常

**Comment by piexlmax** [comment]
message box 位置在哪里呢 可以发送一下图片吗 方便定位bug原因

**Comment by FlameMida** [comment]
![image](https://user-images.githubusercontent.com/33086993/98387682-ac1ca200-208c-11eb-9f5b-5686ea267690.png)
