### ISSUE TITLE
请问如何关闭滑动导航的手势？

### ISSUE THREAD

**Issue by cjosx64** [flipped-aurora/gin-vue-admin#269]
## 描述：
在 mac 下习惯不使用鼠标，而使用手势。
而在内容比较长的表格中，常常需要滚动到表头或这表尾，而使用较大的滚动，
此时会触发页面的路由返回或前进（即页面左端或右端的大箭头），进入另一个页面，而这并不是预期的。

## 问题
请问如何可关闭该功能？

**Comment by SliverHorn** [comment]
- 请按照issues模板进行提问
- 这边建议你买个鼠标

**Comment by SliverHorn** [comment]
- 请按照issues模板进行提问
