### ISSUE TITLE
项目需求征集

### ISSUE THREAD

**Issue by piexlmax** [flipped-aurora/gin-vue-admin#271]
为了项目的不断完善，特此在issue区域开放项目需求征集，大家可以提出合理的通用性高的需求，描述详细，建议合理更容易采纳加入gva的开发计划中。

示例：
需求：工作流相关功能
描述：提供工作流绘制工具（类似java的active），绘制包含开始节点，批改节点，事件节点，网关，结束节点等功能组件，进行拖拽布局绘制。生成工作流相关图以及节点数据。

将实际项目挂载后可以调用工作流提供的创建，提交，回退，驳回等方法实现个人业务挂载工作流功能。

提供示例：https://github.com/flipped-aurora/gin-vue-admin/tree/gva_workflow  （此为我们gva的workflow分支，目前已完成绘制工具和节点流程存储工作，正在提供创建、提交、回退、驳回、等挂载方法）

此功能较为通用，期望采纳

**Comment by zycdmax** [comment]
**大佬啥时候能加个 ant design pro的 手机自适应的前端**

**Comment by SliverHorn** [comment]
> **大佬啥时候能加个 ant design pro的 手机自适应的前端**

请按照示例进行提出需求

**Comment by EziOooo** [comment]
需求：视频流接入
描述：项目需求接入海康摄像头，包括实施画面（RTSP）和云台功能，画面的延迟需要一定保障。另外，还需要接入经过人工智能处理的RTMP流的画面。对于路数的支持以及延迟都有一定的要求。

**Comment by SliverHorn** [comment]
> 大佬，我们有个需求
> 需求：视频流接入
> 描述：项目需求接入海康摄像头，包括实施画面（RTSP）和云台功能，画面的延迟需要一定保障。另外，还需要接入经过人工智能处理的RTMP流的画面。对于路数的支持以及延迟都有一定的要求。
> 另外我15号下载了master分钟，在主页上面的图表好像不见了，我在前端还是个新手，那里可以找到这些图表的前端代码那？目前，想把之前写的gin框架的代码移到我们的框架上，想自己完成一个后台管理和展示的界面。需要花一些曲线图 饼图等。

你这个需求是业务需求，并不是合理的通用性高的需求，感谢的issues

**Comment by maplepie** [comment]
需求：九宫格锁屏功能
描述：类似手机九宫格锁屏的功能，人员暂时离开点击锁屏功能，画出一个图案后确认锁屏，锁屏信息localstorage保存即可，再输入一次解锁，错误几次后需重新登陆。

**Comment by piexlmax** [comment]
> 需求：九宫格锁屏功能
> 描述：类似手机九宫格锁屏的功能，人员暂时离开点击锁屏功能，画出一个图案后确认锁屏，锁屏信息localstorage保存即可，再输入一次解锁，错误几次后需重新登陆。

前端锁屏功能可以提供，九宫格不太适用于pc端，这边会考虑使用密码的形式，感谢提出issue

**Comment by SliverHorn** [comment]
> 需求: 定时任务
> 描述: 比如我改成博客后台，有时候想定时什么时间段发布博文。还有比如bilibili后台，就有定时发布视频；商城后台，定时开启关闭活动等。(我在在线预览上面，没找到类似的功能，我想这个应该算是比较通用的需求。)

定时任务是一个合理的通用性高的需求，感谢的issues

**Comment by tenyear10** [comment]
自适应手机，这个好期待

**Comment by piexlmax** [comment]
> 自适应手机，这个好期待

目前已经做了部分手机端自适应 正在进行中哦~

**Comment by z790490122** [comment]
可以添加多语言对应吗

**Comment by piexlmax** [comment]
> 可以添加多语言对应吗

多语言对应任务量较为庞大且技术和能量不高，element本身支持i18n的多语言操作，可查看具体相关文档

**Comment by youngsailor** [comment]
可以多应用么？
