### ISSUE TITLE
配置文件设置 zap: show-line: true 没有打印文件及行号

### ISSUE THREAD

**Issue by sakishen** [flipped-aurora/gin-vue-admin#273]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.3 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node -v
v14.2.0
npm -v
6.14.8
cnpm -v
cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.8.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
npminstall@3.20.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local
darwin x64 19.6.0
registry=https://registry.npm.taobao.org

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

是

### 5. 您做了什么 ?

 配置文件设置 zap:show-line: true， 但是日志没有打印文件名及行号。
查看源代码，需要在 core/zap.go 中的将代码
if global.GVA_CONFIG.Zap.ShowLine {
    logger.WithOptions(zap.AddCaller())
}
次改为
if global.GVA_CONFIG.Zap.ShowLine {
    logger = logger.WithOptions(zap.AddCaller())
}
才能正常显示文件名及行号。

### 6. 您期望看到什么 ?

看到文件名及行号

### 7. 您看到了什么 ?

日志没有打印文件名及行号

**Comment by SliverHorn** [comment]
- 收到，感谢issues

**Comment by piexlmax** [comment]
新版本bug已修复，修复版本号，2.3.6，目前主干
