### ISSUE TITLE
切换页面 web 侧会提示 Proxy error: Could not proxy request

### ISSUE THREAD

**Issue by sakishen** [flipped-aurora/gin-vue-admin#274]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.3 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node -v
v14.2.0
npm -v
6.14.8
cnpm -v
cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.8.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
npminstall@3.20.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local
darwin x64 19.6.0
registry=https://registry.npm.taobao.org

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

是

### 5. 您做了什么 ?

 配置好环境后， 分别拉起web 及 server
web> npm run serve
server> go run main.go
在页面频繁点击切换，web 侧会提示类似以下的 proxy 错误：

Proxy error: Could not proxy request /api/getApiList from localhost:9528 to http://localhost:8888.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

### 6. 您期望看到什么 ?

 没有 proxy 错误

### 7. 您看到了什么 ?

web 侧会提示类似以下的 proxy 错误：
Proxy error: Could not proxy request customer/customerList?page=1&pageSize=10 from localhost:9528 to http://127.0.0.1:8888.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).

**Comment by SliverHorn** [comment]
- server后端项目没启动的

**Comment by piexlmax** [comment]
> ### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
> go version go1.15.3 darwin/amd64
> 
> ### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
> node -v
> v14.2.0
> npm -v
> 6.14.8
> cnpm -v
> cnpm@6.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
> npm@6.8.0 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
> node@14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
> npminstall@3.20.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
> prefix=/usr/local
> darwin x64 19.6.0
> registry=https://registry.npm.taobao.org
> 
> ### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
> master
> 
> ### 4. 可以在master版本中复现此问题吗 ?
> 是
> 
> ### 5. 您做了什么 ?
> 配置好环境后， 分别拉起web 及 server
> web> npm run serve
> server> go run main.go
> 在页面频繁点击切换，web 侧会提示类似以下的 proxy 错误：
> 
> Proxy error: Could not proxy request /api/getApiList from localhost:9528 to http://localhost:8888.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> 
> ### 6. 您期望看到什么 ?
> 没有 proxy 错误
> 
> ### 7. 您看到了什么 ?
> web 侧会提示类似以下的 proxy 错误：
> Proxy error: Could not proxy request customer/customerList?page=1&pageSize=10 from localhost:9528 to http://127.0.0.1:8888.
> See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
> 
> ### 8. 错误堆栈或者SQL打印

频繁切换会导致过多请求发起，web同时可以处理的axios请求是有限的，这种情况下会导致web浏览器主动断开链接，从而就会报这个错误。

**Comment by sakishen** [comment]
我在现网的Demo 上频繁切换页面， 也复现了

**Comment by piexlmax** [comment]
> 我在现网的Demo 上频繁切换页面， 也复现了
> 页面报错： Error: Request failed with status code 500

查看我上面的回复，问题是web的同时发起axios能力问题，过多请求，后面的必然超时。

**Comment by sakishen** [comment]
> > 我在现网的Demo 上频繁切换页面， 也复现了
> > 页面报错： Error: Request failed with status code 500
> 
> 查看我上面的回复，问题是web的同时发起axios能力问题，过多请求，后面的必然超时。

了解

**Comment by sakishen** [comment]
> > 我在现网的Demo 上频繁切换页面， 也复现了
> > 页面报错： Error: Request failed with status code 500
> 
> 查看我上面的回复，问题是web的同时发起axios能力问题，过多请求，后面的必然超时。

提个建议，能不能在侧栏点击菜单的时候， 只有第一次刷新页面，而再次点击就不强制刷新页面减少点请求。

**Comment by piexlmax** [comment]
> > > 我在现网的Demo 上频繁切换页面， 也复现了
> > > 页面报错： Error: Request failed with status code 500
> > 
> > 
> > 查看我上面的回复，问题是web的同时发起axios能力问题，过多请求，后面的必然超时。
> 
> 提个建议，能不能在侧栏点击菜单的时候， 只有第一次刷新页面，而再次点击就不强制刷新页面减少点请求。

配置中提供了keepAlive选项 需要不再发起请求的 自己配置keepAlive即可

**Comment by sakishen** [comment]
> > > > 我在现网的Demo 上频繁切换页面， 也复现了
> > > > 页面报错： Error: Request failed with status code 500
> > > 
> > > 
> > > 查看我上面的回复，问题是web的同时发起axios能力问题，过多请求，后面的必然超时。
> > 
> > 
> > 提个建议，能不能在侧栏点击菜单的时候， 只有第一次刷新页面，而再次点击就不强制刷新页面减少点请求。
> 
> 配置中提供了keepAlive选项 需要不再发起请求的 自己配置keepAlive即可

原来 keepAlive 是这个功能， 了解~3Q
