### ISSUE TITLE
前端多次切换菜单后会出现路由地址改变,页面不变的情况

### ISSUE THREAD

**Issue by qq6515255** [flipped-aurora/gin-vue-admin#278]
在线DEMO也会出现这种情况,在 超级管路员中选子菜单切换, 然后再点实例文件或者系统工具下的菜单切换后 重新点到超级管理员下的子菜单有时会出现跳转到的页面和路由地址不匹配的情况.

**Comment by piexlmax** [comment]
> 在线DEMO也会出现这种情况,在 超级管路员中选子菜单切换, 然后再点实例文件或者系统工具下的菜单切换后 重新点到超级管理员下的子菜单有时会出现跳转到的页面和路由地址不匹配的情况.

这种情况主要是因为 keepalive导致 如果跳转到了keepalive页面 容易发生此类现象 已经复现 正在修复

**Comment by qq6515255** [comment]
目前我给src/view/layout/index.vue 下的<router-view>标签加上了:key="$route.fullPath" 后好像没再出现过了

**Comment by piexlmax** [comment]
已根据issue描述修复 感谢
