### ISSUE TITLE
主页面左导航栏多级菜单嵌套，点击三级菜单时，其二级父节点菜单也被选中了。

### ISSUE THREAD

**Issue by dwlegend** [flipped-aurora/gin-vue-admin#279]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.3 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
Node  v14.15.0
npm 6.14.8

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
 v2.3.6`

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
左导航菜单增加三级嵌套菜单。

### 6. 您期望看到什么 ?
点击三级菜单时其二级父节点菜单不应该被选中，通常来说只有菜单的最终节点才能被选中。

### 7. 您看到了什么 ?
点击三级菜单时二级菜单也被选中了。

**Comment by piexlmax** [comment]
感谢，经过测试确实存在此问题，将会修改三级菜单的表现形式

**Comment by dwlegend** [comment]
作者，你好，这个问题我这边暂时解决了。
在view/layout/aside/index.vue文件加入了下方样式控制，判断如果菜单是展开的，强制背景色为默认的黑色背景色，防止点击三级菜单，二级菜单变蓝色。
<style lang="scss"&gt;
.is-opened{              //新增加的内容
  background: #191a23 !important      //新增加的内容
}</style&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flipped-aurora/gin-vue-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 上午10:23
收件人:&nbsp;"flipped-aurora/gin-vue-admin"<gin-vue-admin@noreply.github.com&gt;;
抄送:&nbsp;"964826067"<964826067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [flipped-aurora/gin-vue-admin] 主页面左导航栏多级菜单嵌套，点击三级菜单时，其二级父节点菜单也被选中了。 (#279)





 
感谢，经过测试确实存在此问题，将会修改三级菜单的表现形式

**Comment by piexlmax** [comment]
> 作者，你好，这个问题我这边暂时解决了。 在view/layout/aside/index.vue文件加入了下方样式控制，判断如果菜单是展开的，强制背景色为默认的黑色背景色，防止点击三级菜单，二级菜单变蓝色。 <style lang="scss"&gt; .is-opened{ //新增加的内容 background: #191a23 !important //新增加的内容 }</style&gt;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "flipped-aurora/gin-vue-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月16日(星期一) 上午10:23 收件人:&nbsp;"flipped-aurora/gin-vue-admin"<gin-vue-admin@noreply.github.com&gt;; 抄送:&nbsp;"964826067"<964826067@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [flipped-aurora/gin-vue-admin] 主页面左导航栏多级菜单嵌套，点击三级菜单时，其二级父节点菜单也被选中了。 (#279) 感谢，经过测试确实存在此问题，将会修改三级菜单的表现形式 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢提出建议 这边开发版本分支已经修复 本周末将会提交更新 再次表示感谢
