### ISSUE TITLE
前端路由

### ISSUE THREAD

**Issue by MikelPan** [flipped-aurora/gin-vue-admin#281]
请问前端路由是怎么加载

**Comment by piexlmax** [comment]
如果要添加静态路由  如果是不显示的 可以在 router.index.js的baseRouters中添加 如果是显示在左侧菜单的 store.module.router.js的SetAsyncRouter方法的baseRouter的asyncRouter.push添加

**Comment by MikelPan** [comment]
左侧菜单栏从后台获取菜单，那请问面包屑组件在那里，没看到相关代码
