### ISSUE TITLE
生成数据库时候表不能写入数据

### ISSUE THREAD

**Issue by logoove** [flipped-aurora/gin-vue-admin#294]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go 1.15 x64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
cnpm

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 5. 您做了什么 ?
initdb运行时候报错,生成数据表casbin_rules不能写入数据,v1字段长度40太短,演示数据已经是超过此长度,另外还会生成casbin_rule这样一个表明显是哪里写错了,所有表应该只有带后缀s的;希望修复一下

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
此bug主要是 gorm版本号和casbin驱动器版本号不匹配导致

**Comment by logoove** [comment]
gorm-adapter/v3 v3.0.2 这个版本正常 最新的就会出问题 手动改了就好了 默认会成 3.0.4
