### ISSUE TITLE
前端打包如何将elementui使用cdn资源？

### ISSUE THREAD

**Issue by tenyear10** [flipped-aurora/gin-vue-admin#296]
### 6. 您期望看到什么 ?
elementui打包出来目前有点大，想提升首屏加载速度

### 7. 您看到了什么 ?

发现已经有部分资源，在发布版本使用了cdn

**Comment by piexlmax** [comment]
cdn问题我这边会着重处理下 感谢 issue

**Comment by tenyear10** [comment]
非常感谢前辈的开源贡献精神，我是最近开始学go,感觉受益良多。

**Comment by tenyear10** [comment]
websocket预计什么时候集成呀？

**Comment by piexlmax** [comment]
> websocket预计什么时候集成呀？

不好意思 刚来回复 websocket我们经过商讨 决定开放另外一个插件模式 先放在外部 后续如果外部模式存在问题的话 会把它嵌入项目内部

**Comment by tenyear10** [comment]
作者你好：

预计哪个版本会上优化cdn发布的

**Comment by bypanghu** [comment]
> 作者你好：
> 
> 预计哪个版本会上优化cdn发布的

下个版本将会增加相关cdn配置
