### ISSUE TITLE
关于多个database、多数据源

### ISSUE THREAD

**Issue by mortimer-cra** [flipped-aurora/gin-vue-admin#298]
请问
1. 在一个数据库中怎么配置多个database？让业务和框架的表分开
2. 我想通过jdbc的方式连接impala应该怎么办？

**Comment by piexlmax** [comment]
1.对于多数据库 需要创建新的config ymal和数据库全局变量 在init中对于新的全局变量进行初始化
2. JDBA模式是JAVA语言中的 并不能很好地适用于go
