### ISSUE TITLE
如何删除用不到的功能？

### ISSUE THREAD

**Issue by Key-CN** [flipped-aurora/gin-vue-admin#305]
### 想问一下删除部分用不到的功能，具体有没有文件表？怕删错或少删

**Comment by SliverHorn** [comment]
- 请按照issues模板进行提问
- 你这属于自行修改了原有模块，无法提供帮助

**Comment by piexlmax** [comment]
> ### 想问一下删除部分用不到的功能，具体有没有文件表？怕删错或少删

EXA开头的为示例文件 可以删除

**Comment by piexlmax** [comment]
> ### 想问一下删除部分用不到的功能，具体有没有文件表？怕删错或少删

后续版本会提供一键净化脚本 帮助大家删除

**Comment by logoove** [comment]
隐藏菜单就行了
