### ISSUE TITLE
主分支项目，initdb.bat执行问题。

### ISSUE THREAD

**Issue by WvvvWv** [flipped-aurora/gin-vue-admin#312]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.5 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
node:  v14.15.1
npm:  6.14.8
未安装cnpm

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
2020-12-08 clone下来的主分支，应该是：v2.3.8

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?

初始话数据库

### 6. 您期望看到什么 ?

初始化成功

### 7. 您看到了什么 ?
 
![Snipaste_2020-12-09_14-31-38](https://user-images.githubusercontent.com/40822202/101594236-4d9c6800-3a2c-11eb-945d-784b5d0e23bc.png)

通过添加 DueDate: time.Now()解决，如下图：
![Snipaste_2020-12-09_14-42-00](https://user-images.githubusercontent.com/40822202/101594492-b84da380-3a2c-11eb-8b49-38b887ae82d6.png)

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
- [文档](https://www.gin-vue-admin.com/docs/server#3-%E6%95%B0%E6%8D%AE%E5%BA%93%E5%88%9D%E5%A7%8B%E5%8C%96)
- 
![image](https://user-images.githubusercontent.com/45428434/101594645-0367b680-3a2d-11eb-979d-71b46402d640.png)

**Comment by WvvvWv** [comment]
我刚刚又试了一下，我的mysql版本 8.0.22，新建了数据库编码为utf8-mb4，去掉了DueDate: time.Now()，再次执行初始化还是会报错，看起来像我数据库的问题，我再查一下。谢谢！

**Comment by SliverHorn** [comment]
https://blog.csdn.net/shaock2018/article/details/91347932
