### ISSUE TITLE
初始化遇到： 工作流相关 表的初始数据失败,err: Error 1292: Incorrect datetime value: '0000-00-00' for column 'due_date' at row 1

### ISSUE THREAD

**Issue by rwx------** [flipped-aurora/gin-vue-admin#314]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.14.7 darwin/amd64

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 5. 您做了什么 ?
初始化

### 7. 您看到了什么 ?
![image](https://user-images.githubusercontent.com/9865239/101732784-b8b37080-3af8-11eb-80d2-481cc1f918f2.png)

**Comment by SliverHorn** [comment]
https://github.com/flipped-aurora/gin-vue-admin/issues/312

**Comment by SliverHorn** [comment]
https://blog.csdn.net/shaock2018/article/details/91347932

**Comment by rwx------** [comment]
最后是这样解决的，在MySQL中执行：
show variables like 'sql_mode';

把NO_ZERO_IN_DATE,NO_ZERO_DATE这两个删掉即可：
set global sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

还是直接写到这里，方便查看一些。
