### ISSUE TITLE
是否可以在 .gitignore 中添加  *.log 过滤

### ISSUE THREAD

**Issue by rwx------** [flipped-aurora/gin-vue-admin#320]
发现仓库中有   gin-vue-admin/web/debug.log 文件，该文件应该可以不用入到仓库吧？
建议从git仓库中删除该文件，然后添加  .gitignore 的 *.log 过滤。

**Comment by piexlmax** [comment]
感谢issue 此文件为我们组员操作失误导致 感谢issue
