### ISSUE TITLE
请问一下，为什么登陆成功后，还会请求一次这个captcha接口？

### ISSUE THREAD

**Issue by rwx------** [flipped-aurora/gin-vue-admin#321]
请问一下，为什么登陆成功后，还会请求一次这个captcha接口？
具体请看下图：

![image](https://user-images.githubusercontent.com/9865239/102188905-dade3180-3ef0-11eb-83bd-7326fc5d81b2.png)

感觉这个请求是不必要的。

**Comment by piexlmax** [comment]
此问题已修复 将会在周末己行提交更新 感谢 issue

**Comment by piexlmax** [comment]
已修复
