### ISSUE TITLE
Missing due_date default value in model.WorkflowNode

### ISSUE THREAD

**Issue by ithinco** [flipped-aurora/gin-vue-admin#323]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.2 darwin/amd6

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v12.19.0

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

V2.3.7

### 4. 可以在master版本中复现此问题吗 ?
Yes

### 5. 您做了什么 ?
run `make initdb`

### 6. 您期望看到什么 ?
```
[Mysql]-->初始化数据表成功
authority_menu视图创建成功!
[Mysql]-->初始化数据成功
```

### 7. 您看到了什么 ?
```
[Mysql]-->初始化数据表成功
authority_menu视图创建成功!
[Mysql]-->初始化数据成功
[Mysql]-->工作流相关 表的初始数据失败,err: Error 1292: Incorrect datetime value: '0000-00-00' for column 'due_date' at row 1
```

### 8. 错误堆栈或者SQL打印
```
[Mysql]-->工作流相关 表的初始数据失败,err: Error 1292: Incorrect datetime value: '0000-00-00' for column 'due_date' at row 1
```

https://github.com/flipped-aurora/gin-vue-admin/issues/314 described this issue, but its solution is wrong. The root cause of this issue is `model.WorkflowNode` missing default value of `DueDate`

**Comment by rwx------** [comment]
#314 看这个错误，应该是你mysql版本大于了 5.7， 修改一下  sql_mode

**Comment by piexlmax** [comment]
主干已修复 此问题不再复现 due_date 数据类型从 time.Time --> *time.Time 即可
