### ISSUE TITLE
前台路由二级菜单不显示

### ISSUE THREAD

**Issue by anyetanxi2017** [flipped-aurora/gin-vue-admin#324]
### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
go version go1.15.6 darwin/amd64

v10.15.3

6.4.1

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
v2.3.8

### 5. 您做了什么 ?
创建用户管理一级菜单 
- 路由 Path us_user
- 父节点 根目标
- 文件路径  view/user/index.vue

index.vue内容
```
<template>
    <router-view></router-view>
</template>

<script>
export default {
    name:"us_user",
}
</script>
```

创建用户列表二级菜单
- 路由 Path us_user_list
- 父节点 用户管理
- 文件路径  view/user/userList/userList.vue

合建登录日志二级菜单
- 路由 us_login_log
- 父节点 用户管理
- 文件路径  view/user/loginLog/usLoginLog.vue

权限和api都已配置好了。

### 6. 您期望看到什么 ?
题外（生成的表单输入框中，如果能加个回车快捷搜索就很好。）

### 7. 您看到了什么 ?

现在是，点击用户管理，显示空白页面。左侧也只有用户管理菜单，二级菜单一个都没有展示。直接输入二级菜单地址如`http://localhost:8080/#/layout/us_user/us_user_list`  直接404 ，这是什么情况呢。。。 (T＿T); 

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
没有配置菜单
