### ISSUE TITLE
在布署到域名下 表单创建页面无法加载

### ISSUE THREAD

**Issue by billytoe** [flipped-aurora/gin-vue-admin#325]
文件路径 src\view\systemTools\formCreate\index.vue
文件内容
 <iframe width="100%" height="100%" :src="'http://127.0.0.1:8888/form-generator/#/'" frameborder="0"></iframe>

- 

“http://127.0.0.1:8888” 这个地方地址 在我布署到域名下，导致 在客户端网页访问本机的ip，页面加载失败 ，不知道是否能写成相对地址？

**Comment by piexlmax** [comment]
部署教程中已经说明 此地址需要发版前自行修改
