### ISSUE TITLE
There is a problem with this view:/web/src/view/superAdmin/user/user.vue

### ISSUE THREAD

**Issue by songkang1993** [flipped-aurora/gin-vue-admin#327]
Path:  https://github.com/flipped-aurora/gin-vue-admin/blob/master/web/src/view/superAdmin/user/user.vue
![image](https://user-images.githubusercontent.com/38366752/102569477-84efd080-4120-11eb-8dfc-30fd1c90f856.png)
![image](https://user-images.githubusercontent.com/38366752/102569486-87eac100-4120-11eb-87b9-93e32519ea09.png)

Unresolved variable or type scope

**Comment by piexlmax** [comment]
感谢issue，此问题位bug，将会在本周末修。

**Comment by piexlmax** [comment]
已修复 感谢issue
