### ISSUE TITLE
是否可以支持node v.15.x

### ISSUE THREAD

**Issue by zhang-passerby** [flipped-aurora/gin-vue-admin#328]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.14.1 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
v15.4.0

-->

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 5. 您做了什么 ?
什么都没有做，启动不起来

### 6. 您期望看到什么 ?

是否可以支持node15

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
支持 node15 您需要按照文档操作 安装相关依赖
