### ISSUE TITLE
菜单-"展示名称" 支持在Tab中动态增加扩展

### ISSUE THREAD

**Issue by zeusYi** [flipped-aurora/gin-vue-admin#332]
目前”展示名称“ 在Tab页中不支持动态增加扩展

现有情况：
![record](https://user-images.githubusercontent.com/22519964/102766736-91428a80-43b9-11eb-83c4-b3dc8c5c7239.gif)

希望改成:
![image](https://user-images.githubusercontent.com/22519964/102766965-df578e00-43b9-11eb-896e-6d21baded5c8.png)

**Comment by piexlmax** [comment]
新版本已经提供支持 感谢 issue
