### ISSUE TITLE
[feature]:实现admin数据库和业务数据库的分离

### ISSUE THREAD

**Issue by S3cuRiTy-Er1C** [flipped-aurora/gin-vue-admin#335]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go 1.13

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
latest

### 6. 您期望看到什么 ?
期望实现admin数据库与业务数据库的分离，避免耦合加快新系统的接入速度

### 8. 错误堆栈或者SQL打印

**Comment by S3cuRiTy-Er1C** [comment]
如果有规划，我可以进行开发支持

**Comment by tenyear10** [comment]
通过给表指定比如sys_前缀可以吗

**Comment by piexlmax** [comment]
多个数据库目前是支持的 后端数据库和自己的业务数据库是可以支持的 我会在下个版本提供示例

**Comment by lemontreehuang** [comment]
@piexlmax 请问业务数据库分离的示例更新好了吗,提交历史里好像没看到 ^_^

**Comment by sunblognuke** [comment]
@piexlmax 最新版本出来了，示例有提供了么，可以分享下，感谢

**Comment by daz2yy** [comment]
同问👆

**Comment by webff** [comment]
实例出来了吗？急求👆 @piexlmax

**Comment by WalleDong** [comment]
同求

**Comment by piexlmax** [comment]
增加示例并不是何理的做法，这边会增加新功能，开放业务数据库map配置，可以选择调用。

**Comment by piexlmax** [comment]
#809

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/e3df65f354ecfd82d1292c117bbd83060f4b0049 已提供
