### ISSUE TITLE
前端打包能有单独变量控制是否使用CDN.

### ISSUE THREAD

**Issue by cg831344** [flipped-aurora/gin-vue-admin#345]
### 6. 您期望看到什么 ?
在前端中有额外的配置，控制是否使用CDN.
我是做运维开发的，开发的系统大多数情况下，只能内网访问.
if(process.env.NODE_ENV!=='development')
能把CDN单独使用变量独立出来

### 7. 您看到了什么 ?
部分前端包，使用了CDN

**Comment by tenyear10** [comment]
developmnt这个，应该用来区分dev开发还是build发布
