### ISSUE TITLE
操作历史能关联显示API的简介么？

### ISSUE THREAD

**Issue by jun-time** [flipped-aurora/gin-vue-admin#347]
操作历史能关联显示API的简介么？
只是显示API信息对非开发员来讲，不友好

**Comment by piexlmax** [comment]
操作历史增加API简介会多查一次数据库，可以统计一下建议，目前主要为开发人员查看记录使用。

**Comment by yann0917** [comment]
操作历史，可以记录修改前后的数据吗？
