### ISSUE TITLE
IE浏览器上白屏，Window10 IE版本1909

### ISSUE THREAD

**Issue by TalentBoy** [flipped-aurora/gin-vue-admin#349]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.4 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
Nodejs - v12.16.2

npm - 6.14.4

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 4. 可以在master版本中复现此问题吗 ?
可以

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
有较多的VUE插件 无法做到支持IE10
