### ISSUE TITLE
macOS写入的本地log文件格式异常，日志级别中含有特殊字符

### ISSUE THREAD

**Issue by Suyghur** [flipped-aurora/gin-vue-admin#350]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.6 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
node : v15.5.0

npm : 7.3.0

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
在goland中直接run main.go

### 7. 您看到了什么 ?

![image](https://user-images.githubusercontent.com/16944867/103604047-ff0abc80-4f4a-11eb-8316-973042238b6a.png)

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
这是颜色代码，

**Comment by SliverHorn** [comment]
看 https://www.gin-vue-admin.com/docs/config#description-1 说明

**Comment by Suyghur** [comment]
> 这是颜色代码，

是只能修改encode_level的值才能处理吗？我印象中以前的版本好像是直接记录日志级别，没有把颜色代码也记录下来的

**Comment by SliverHorn** [comment]
> > 这是颜色代码，
> 
> 是只能修改encode_level的值才能处理吗？我印象中以前的版本好像是直接记录日志级别，没有把颜色代码也记录下来的

文档描述很清楚了，两个不一样的东西，一直以来都是这样的
