### ISSUE TITLE
[bug] 媒体库无法正常显示上传成功到本地后端的图片

### ISSUE THREAD

**Issue by SliverHorn** [flipped-aurora/gin-vue-admin#356]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

`go version go1.15.4 darwin/amd64`

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node -v: `v12.14.0`
npm: `7.0.10` 
cnpm: 
```shell
cnpm@6.1.1 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.8 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@12.14.0 (/usr/local/bin/node)
npminstall@3.28.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 19.6.0 
registry=https://r.npm.taobao.org
```

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

gva_gormv2_dev

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?

上传图片到server项目后端

### 6. 您期望看到什么 ?

在新增用户时，可以在媒体库选择自己上传的图片作为用户头像

### 7. 您看到了什么 ?

一、在上传下载可以看到正常上传成功的图片
![image](https://user-images.githubusercontent.com/45428434/104093868-518c0600-52c8-11eb-8bd9-470a377fb78c.png)
加载成功调用图
![image](https://user-images.githubusercontent.com/45428434/104093877-65376c80-52c8-11eb-9189-8ca7f349926b.png)

二、图片在媒体库无法观看图片的预览，没加载出来
![image](https://user-images.githubusercontent.com/45428434/104093838-22759480-52c8-11eb-9d6d-373335994ed0.png)
加载失败调用图
![image](https://user-images.githubusercontent.com/45428434/104093887-7bddc380-52c8-11eb-9765-0936340a4f2b.png)

### 8. 错误堆栈或者SQL打印
![image](https://user-images.githubusercontent.com/45428434/104093921-ad568f00-52c8-11eb-9ec9-f2331737283c.png)

### 9. 问题点分析

- 可能是代理转发错误，请求前链接未带api

**Comment by piexlmax** [comment]
已修复~感谢issue
