### ISSUE TITLE
是否集成了富文本？

### ISSUE THREAD

**Issue by Cristiyi** [flipped-aurora/gin-vue-admin#357]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
1.14.4

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
npm

v14

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 6. 您期望看到什么 ?
是否集成了富文本

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
曾经有版本进行过集成，后来因为舆论原因取消了。
