### ISSUE TITLE
角色资源权限在什么场景下生效？

### ISSUE THREAD

**Issue by aixj1984** [flipped-aurora/gin-vue-admin#358]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.2 windows/amd64

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
V2.3.8

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
通过给不同的角色设定角色资源，尤其是父子角色，比如我给子角色设定了可以编辑，父角色设置的不可编辑，但是我的父角色资源又包括了子角色

### 6. 您期望看到什么 ?
这里的资源没明白指的是什么？勾选了就可以拥有其它角色的权利，感觉也不对？

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
看 `示例文件`->`客户列表(资源示例)`

**Comment by aixj1984** [comment]
测试OK，代码也看明白了
