### ISSUE TITLE
操作历史接口bug

### ISSUE THREAD

**Issue by oukan** [flipped-aurora/gin-vue-admin#359]
使用demo环境，访问 http://demo.gin-vue-admin.com/#/layout/admin/operation 操作历史页面，该页面默认调用接口 http://demo.gin-vue-admin.com/api/sysOperationRecord/getSysOperationRecordList?page=1&pageSize=10
，多次访问该页面会导致数据库数据膨胀

![操作历史.png](http://www.oukan.net/file/1.png)

经过分析是中间件 mddleware/operation 将api的返回数据都写入数据表 sys_operation_records 的 resp 字段，需要对 getSysOperationRecordList 接口返回的数据，在写入 sys_operation_records 时进行处理。

**Comment by piexlmax** [comment]
感谢 issue 我们这边尽快核实修复
