### ISSUE TITLE
数据库初始化错误

### ISSUE THREAD

**Issue by ITwalker** [flipped-aurora/gin-vue-admin#366]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.3 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node v14.15.4
npm  6.14.10

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?

make gva

make initdb

### 6. 您期望看到什么 ?

数据库初始化成功

### 7. 您看到了什么 ?

您当前的数据库版本:  {5.6.41} , 使用的数据库是:  {ginadmin} , 数据库编码是:  {utf8mb4}

[Mysql] --> 初始化数据表失败, err: Error 1071: Specified key was too long; max key length is 767 bytes

### 8. 错误堆栈或者SQL打印

您当前的数据库版本:  {5.6.41} , 使用的数据库是:  {ginadmin} , 数据库编码是:  {utf8mb4}

[Mysql] --> 初始化数据表失败, err: Error 1071: Specified key was too long; max key length is 767 bytes

**Comment by SliverHorn** [comment]
把 `config.yaml` 中 `mysql` -> `log-mod` 的 `false` 改为true，再次执行 `make gva` 与 `make initdb` , 执行前建议把`ginadmin` 数据库删除

**Comment by alenstar** [comment]
建立索引时，数据bai库计算key的长度是累加所du有Index用到的字段的zhichar长度；再按下面dao比例相乘不能超过限定的key长度1000：
    latin1=1 byte=1 character；
    uft8=3 byte=1 character；
    gbk=2 byte=1 character。

    解决方法：

    修改字段长度
    指定ID长度 type:varchar(60);

type WorkflowNode struct {
	ID                string `json:"id" form:"id" gorm:"type:varchar(60);comment:节点id;primaryKey;unique;not null"`
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         gorm.DeletedAt `json:"-" gorm:"index"`
	WorkflowProcessID string         `json:"workflowProcessID" gorm:"comment:流程标识"`
	Clazz             string         `json:"clazz" gorm:"comment:节点类型"`
	Label             string         `json:"label" gorm:"comment:节点名称"`
	Type              string         `json:"type" gorm:"comment:图标类型"`
	Shape             string         `json:"shape" gorm:"comment:形状"`
	Description       string         `json:"description" gorm:"comment:详细介绍"`
	View              string         `json:"view" gorm:"comment:前端视图文件"`
	X                 float64        `json:"y" gorm:"comment:x位置"`
	Y                 float64        `json:"x" gorm:"comment:y位置"`
	WaitState         string         `json:"waitState" gorm:"comment:等待属性"`
	StateValue        string         `json:"stateValue" gorm:"comment:等待值"`
	To                string         `json:"to" gorm:"comment:收件人"`
	Subject           string         `json:"subject" gorm:"comment:标题"`
	Content           string         `json:"content" gorm:"comment:内容"`
	Cycle             string         `json:"cycle" gorm:"comment:循环时间"`
	Duration          string         `json:"duration" gorm:"comment:持续时间"`
	HideIcon          bool           `json:"hideIcon" gorm:"comment:是否隐藏图标"`
	DueDate           *time.Time     `json:"dueDate" gorm:"comment:到期时间"`
	AssignType        string         `json:"assignType" gorm:"comment:审批类型"`
	AssignValue       string         `json:"assignValue" gorm:"comment:审批类型值"`
	Success           bool           `json:"success" gorm:"comment:是否成功"`
}

**Comment by piexlmax** [comment]
uft-8mb4数据库主键字符串长度为191 否则会导致超长报错 其他数据类型请自行查阅相关内容
