### ISSUE TITLE
 server/service/sys_menu.go 中 AddBaseMenu方法BUG

### ISSUE THREAD

**Issue by scuxiatian** [flipped-aurora/gin-vue-admin#367]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go1.14.6 windows/amd64
### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
node v14.2.0
npm 6.14.4
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master
### 4. 可以在master版本中复现此问题吗 ?
是
### 5. 问题描述 
 server/service/sys_menu.go 中 92-98行的AddBaseMenu

func AddBaseMenu(menu model.SysBaseMenu) (err error) {
	if !errors.Is(global.GVA_DB.Where("name = ?", menu.Name).First(&model.SysBaseMenu{}).Error, gorm.ErrRecordNotFound) {
		err = errors.New("存在重复name，请修改name")
	}
	err = global.GVA_DB.Create(&menu).Error
	return err
}

发生存在重复name的情况后感觉应该中止执行后续的数据库create操作并返回错误信息，是不是应该在94行后面加上return err呢

**Comment by SliverHorn** [comment]
应该是这样写才对的
```go
if !errors.Is(global.GVA_DB.Where("name = ?", menu.Name).First(&model.SysBaseMenu{}).Error, gorm.ErrRecordNotFound) {
        err = errors.New("存在重复name，请修改name")
} else {
	err = global.GVA_DB.Create(&menu).Error
}
```

**Comment by SliverHorn** [comment]
感谢issues

**Comment by piexlmax** [comment]
已修复至master
