### ISSUE TITLE
大佬好，可以看下form-generator组件的源码吗？

### ISSUE THREAD

**Issue by xiang0308** [flipped-aurora/gin-vue-admin#369]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.4 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
v11.11.0

cnpm@6.1.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.11.2 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@11.11.0 (/usr/local/Cellar/node/11.11.0/bin/node)
npminstall@3.23.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 19.5.0 
registry=https://r.npm.taobao.org

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
https://www.gin-vue-admin.com/docs/base#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD

**Comment by xiang0308** [comment]
> https://www.gin-vue-admin.com/docs/base#%E4%B8%BB%E8%A6%81%E5%8A%9F%E8%83%BD

I found it. Thank you
