### ISSUE TITLE
make initdb报错Incorrect datetime value: '0000-00-00' for column 'due_date'

### ISSUE THREAD

**Issue by fineday009** [flipped-aurora/gin-vue-admin#371]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
❯ go version
go version go1.14.13 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
❯ npm -v
6.14.9

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
2.3.8

### 5. 您做了什么 ?
make gva
make initdb

### 7. 您看到了什么 ?
❯ make gva
go build -o "gva" cmd/main.go
❯ make initdb
您正在使用func Viper()传递的值,config的路径为./config.yaml
[Mysql]-->初始化数据表成功
authority_menu视图创建成功!
[Mysql]-->初始化数据成功
[Mysql]-->工作流相关 表的初始数据失败,err: Error 1292: Incorrect datetime value: '0000-00-00' for column 'due_date' at row 1

### 8. 错误堆栈或者SQL打印

[Mysql]-->工作流相关 表的初始数据失败,err: Error 1292: Incorrect datetime value: '0000-00-00' for column 'due_date' at row 1

**Comment by SliverHorn** [comment]
`v2.3.9` 修复这个问题了
`2.3.8` 解决方案有两种
- 参考[代码](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/cmd/gva/mysql.go#L292)， 执行的sql
- 修改https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/model/sys_workflow.go#L113

```go
type WorkflowNode struct {
	ID                string `json:"id" form:"id" gorm:"comment:节点id;primaryKey;unique;not null"`
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeletedAt         gorm.DeletedAt `json:"-" gorm:"index"`
	WorkflowProcessID string         `json:"workflowProcessID" gorm:"comment:流程标识"`
	Clazz             string         `json:"clazz" gorm:"comment:节点类型"`
	Label             string         `json:"label" gorm:"comment:节点名称"`
	Type              string         `json:"type" gorm:"comment:图标类型"`
	Shape             string         `json:"shape" gorm:"comment:形状"`
	Description       string         `json:"description" gorm:"comment:详细介绍"`
	View              string         `json:"view" gorm:"comment:前端视图文件"`
	X                 float64        `json:"y" gorm:"comment:x位置"`
	Y                 float64        `json:"x" gorm:"comment:y位置"`
	WaitState         string         `json:"waitState" gorm:"comment:等待属性"`
	StateValue        string         `json:"stateValue" gorm:"comment:等待值"`
	To                string         `json:"to" gorm:"comment:收件人"`
	Subject           string         `json:"subject" gorm:"comment:标题"`
	Content           string         `json:"content" gorm:"comment:内容"`
	Cycle             string         `json:"cycle" gorm:"comment:循环时间"`
	Duration          string         `json:"duration" gorm:"comment:持续时间"`
	HideIcon          bool           `json:"hideIcon" gorm:"comment:是否隐藏图标"`
	DueDate           *time.Time     `json:"dueDate" gorm:"comment:到期时间"`
	AssignType        string         `json:"assignType" gorm:"comment:审批类型"`
	AssignValue       string         `json:"assignValue" gorm:"comment:审批类型值"`
	Success           bool           `json:"success" gorm:"comment:是否成功"`
}
```

**Comment by fineday009** [comment]
> `v2.3.9` 修复这个问题了
> `2.3.8` 解决方案有两种
> 
> * 参考[代码](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/cmd/gva/mysql.go#L292)， 执行的sql
> * 修改https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/model/sys_workflow.go#L113
> 
> ```go
> type WorkflowNode struct {
> 	ID                string `json:"id" form:"id" gorm:"comment:节点id;primaryKey;unique;not null"`
> 	CreatedAt         time.Time
> 	UpdatedAt         time.Time
> 	DeletedAt         gorm.DeletedAt `json:"-" gorm:"index"`
> 	WorkflowProcessID string         `json:"workflowProcessID" gorm:"comment:流程标识"`
> 	Clazz             string         `json:"clazz" gorm:"comment:节点类型"`
> 	Label             string         `json:"label" gorm:"comment:节点名称"`
> 	Type              string         `json:"type" gorm:"comment:图标类型"`
> 	Shape             string         `json:"shape" gorm:"comment:形状"`
> 	Description       string         `json:"description" gorm:"comment:详细介绍"`
> 	View              string         `json:"view" gorm:"comment:前端视图文件"`
> 	X                 float64        `json:"y" gorm:"comment:x位置"`
> 	Y                 float64        `json:"x" gorm:"comment:y位置"`
> 	WaitState         string         `json:"waitState" gorm:"comment:等待属性"`
> 	StateValue        string         `json:"stateValue" gorm:"comment:等待值"`
> 	To                string         `json:"to" gorm:"comment:收件人"`
> 	Subject           string         `json:"subject" gorm:"comment:标题"`
> 	Content           string         `json:"content" gorm:"comment:内容"`
> 	Cycle             string         `json:"cycle" gorm:"comment:循环时间"`
> 	Duration          string         `json:"duration" gorm:"comment:持续时间"`
> 	HideIcon          bool           `json:"hideIcon" gorm:"comment:是否隐藏图标"`
> 	DueDate           *time.Time     `json:"dueDate" gorm:"comment:到期时间"`
> 	AssignType        string         `json:"assignType" gorm:"comment:审批类型"`
> 	AssignValue       string         `json:"assignValue" gorm:"comment:审批类型值"`
> 	Success           bool           `json:"success" gorm:"comment:是否成功"`
> }
> ```

按方式2已经解决，感谢！
