### ISSUE TITLE
左侧菜单栏头部的logo和标题，进行前端注释，然后给个路径引用或者提供后台管理界面的直接修改操作。

### ISSUE THREAD

**Issue by tushuaidianzi** [flipped-aurora/gin-vue-admin#373]
### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
issue已收录，将会提供注释和配置文件的模式进行设置

**Comment by bypanghu** [comment]
最新版本已在core/config目录下新增配置文件，目前只设置了appName和appLogo，日后会增加相应配置，全局关键词为$GIN_VUE_ADMIN
