### ISSUE TITLE
有没有考虑OSS添加aws s3云储存

### ISSUE THREAD

**Issue by z790490122** [flipped-aurora/gin-vue-admin#379]
看了你们写的这个框架,我觉得非常适合我公司开发.我现在有两个问题想要咨询下

### 第一个
我这边大多是国外项目, 经常用aws s3储存.有没有计划集成进去.

### 第二个
我看项目中大多数云储存是用的apikey .但是在国外项目一般不用apikey这种方式去访问,储存桶信息,不太安全很容易被遭到攻击.咱这个框架有没有考虑过如果没有apikey设置,自动默认为role去访问.

**Comment by SliverHorn** [comment]
不考虑的

**Comment by piexlmax** [comment]
> 看了你们写的这个框架,我觉得非常适合我公司开发.我现在有两个问题想要咨询下
> 
> ### 第一个
> 我这边大多是国外项目, 经常用aws s3储存.有没有计划集成进去.
> 
> ### 第二个
> 我看项目中大多数云储存是用的apikey .但是在国外项目一般不用apikey这种方式去访问,储存桶信息,不太安全很容易被遭到攻击.咱这个框架有没有考虑过如果没有apikey设置,自动默认为role去访问.

目前项目已经提供了一处可以自定义选择使用存储模式的实现，因为需求太多，所以就没有去做适配，具体方案还需要自行开发，感谢Issue
