### ISSUE TITLE
执行make gva报错

### ISSUE THREAD

**Issue by xzhaha123** [flipped-aurora/gin-vue-admin#382]
/go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:67:51: cannot use stat.Mntfromname[:] (type []byte) as type []int8 in argument to common.IntToString
/go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:68:49: cannot use stat.Mntonname[:] (type []byte) as type []int8 in argument to common.IntToString
/go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:69:50: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString
/go/pkg/mod/github.com/shirou/gopsutil@v2.20.8+incompatible/disk/disk_darwin.go:85:43: cannot use stat.Fstypename[:] (type []byte) as type []int8 in argument to common.IntToString

**Comment by SliverHorn** [comment]
`server/go.mod`
github.com/shirou/gopsutil v2.20.8+incompatible改为github.com/shirou/gopsutil v3.21.1

**Comment by piexlmax** [comment]
此问题已master修复
