### ISSUE TITLE
工作流绘制功能BUG报告

### ISSUE THREAD

**Issue by scuxiatian** [flipped-aurora/gin-vue-admin#383]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go1.14.6 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node v14.2.0
npm 6.14.4

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

是

### 5. 问题描述

又来提Issue了，真心喜欢这个仓库，希望能越来越好！

#### 问题一
使用工作流绘制功能时，新增任意节点并选中，勾选隐藏图标选项，再点击撤销后，发现被隐藏的图标不会再显示出来。
分析原因为，节点初始化时，hideIcon属性为undefined，导致update指令执行过程中，存储的originModel 中也没有hideIcon属性，之后进行撤销操作执行语句`graph.update(item, this.originModel)`时，就不会对hideIcon属性进行更新。
```
cmdPlugin.registerCommand('update', {
  enable: function() {
    return this.itemId && this.updateModel;
  },
  execute: function(graph) {
    const item = graph.findById(this.itemId);
    if(item) {
      if(this.executeTimes === 1)
        this.originModel = mix({}, item.getModel());
      graph.update(item, this.updateModel);
    }
  },
  back: function(graph) {
    const item = graph.findById(this.itemId);
    graph.update(item, this.originModel);
  },
});
```
建议在执行新增节点操作时，对hideIcon属性进行初始化赋值 （src\components\gva-wfd\behavior\dragPanelItemAddNode 122行-124行）
```
addModel.type = getShapeName(clazz);
addModel.shape = getShapeName(clazz);
addModel.hideIcon = false;

```

#### 问题二
使用工作流绘制功能时，在选中任意节点 / 边，在右侧DetailPanel中进行编辑后再执行撤销 / 重做命令时，selectedModel的数据不会进行相应的变化，导致图与表单中数据不一致。
![微信截图_20210224150011](https://user-images.githubusercontent.com/19620676/108960614-265f4980-76b1-11eb-9d5c-ed75490587e9.png)
建议对aftercommandexecute事件进行监听，对selectedModel的数据进行更新（src\components\gva-wfd\components\Wfd.vue 
 141行）
```
initEvents(){
  this.graph.on('afteritemselected',(items)=>{
    if(items && items.length > 0) {
      let item = this.graph.findById(items[0]);
      if(!item){
        item = this.getNodeInSubProcess(items[0])
      }
      this.selectedModel = {...item.getModel()};
    } else {
      this.selectedModel = this.processModel;
    }
  });
 this.graph.on('aftercommandexecute',(command)=>{
    if (command.name !== 'undo' && command.name !== 'redo') return;
    // 更新selectedModel
  });
  ...
}
```

**Comment by piexlmax** [comment]
非常感谢issue 经过测试确实存在上述问题 将会尽快修复！
