### ISSUE TITLE
能登录，getmenue报错（mysql用户名密码不对）

### ISSUE THREAD

**Issue by yuntiantec** [flipped-aurora/gin-vue-admin#391]
IN-VUE-ADMIN]2021/03/04 - 14:01:16.151	error	/home/gopath/src/micro_plat_admin/server/api/v1/sys_menu.go:23	获取失败!	{"err": "Error 1045: Access denied for user 'zhongchou'@'localhost' (using password: YES)"}
gin-vue-admin/api/v1.GetMenu
	/home/gopath/src/micro_plat_admin/server/api/v1/sys_menu.go:23
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
gin-vue-admin/middleware.OperationRecord.func1
	/home/gopath/src/micro_plat_admin/server/middleware/operation.go:60
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
gin-vue-admin/middleware.CasbinHandler.func1
	/home/gopath/src/micro_plat_admin/server/middleware/casbin_rbac.go:23
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
gin-vue-admin/middleware.JWTAuth.func1
	/home/gopath/src/micro_plat_admin/server/middleware/jwt.go:67
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
gin-vue-admin/middleware.Cors.func1
	/home/gopath/src/micro_plat_admin/server/middleware/cors.go:24
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.RecoveryWithWriter.func1
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241
github.com/gin-gonic/gin.(*Context).Next
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/gopath/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/gopath/pkg/mod/github.com/gin-gon

**Comment by piexlmax** [comment]
查看自己配置文件是否跟服务器上mysql 用户名密码匹配 或者对照文档查看是否有所遗漏
