### ISSUE TITLE
新版本初始化数据库的时候出现BUG

### ISSUE THREAD

**Issue by 204065248** [flipped-aurora/gin-vue-admin#394]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.6 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
Nodejs v14.15.4

cnpm@6.1.1 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@6.14.11 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@14.15.4 (D:\IDE\nodejs\node.exe)
npminstall@3.28.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 x64 10.0.18362
registry=https://r.npm.taobao.org
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
v2.4.0

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
清空数据库，启动web服务端 启动go服务端，进入数据库初始化页面，填写数据库信息，进行初始化结果提示
{"err": "Error 1050: Table 'authority_menu' already exists"}

### 6. 您期望看到什么 ?
我希望能够尽快解决，谢谢

### 8. 错误堆栈或者SQL打印
![错误日志](https://pan.ltools.vip/api/v3/file/get/252/QQ%E5%9B%BE%E7%89%8720210308141519.png?sign=fpTUyP4SveHo7VjBXi30M5phDwRMBboHOaJTKK2X3xQ%3D%3A0)

**Comment by piexlmax** [comment]
请先确定自己本地数据库表是否清理干净

**Comment by 204065248** [comment]
解决了，是因为视图没删干净。谢谢
