### ISSUE TITLE
feat: 自动生成代码时迁移数据库不便

### ISSUE THREAD

**Issue by wangerzi** [flipped-aurora/gin-vue-admin#398]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.7 windows/amd64
### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v12.16.1

6.13.4

cnpm@6.0.0 (C:\Users\94468\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@6.8.0 (C:\Users\94468\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@12.16.1 (C:\Program Files\nodejs\node.exe)
npminstall@3.20.2 (C:\Users\94468\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\94468\AppData\Roaming\npm
win32 x64 10.0.18363
registry=https://registry.npm.taobao.org
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?

比如我在电脑A 使用代码生成器自动生成了页面、菜单配置、API权限配置，但这些是不能直接随着代码的提交而带走的，另一台**电脑B 并没有办法方便快速的初始化去使用**。

看了下代码，主要原因估计是 `go run cmd/main.go initdb` 执行的自动插入菜单、API是写死在代码里边的，如果不用 AST 的话不方便注入代码，在考虑是否可以把 menu/api 以 JSON/SQL 的形式固定下来，执行 `initdb` 的时候去 JSON 获取需要初始化的数据/SQL 去执行；然后每次做完代码自动生成后，除了直接插入数据库，还要改一下对应的 menu/api 配置JSON/SQL 文件。

这样就可以把数据抽象出来，避免修改原有代码，还能达到动态维护的目的。

> PS: 我觉着路由也是这个理，每次代码生成完毕还需要手动去做路由初始化和 Model 的 `getTables`

**Comment by SliverHorn** [comment]
1. 数据迁移，与本项目无关，你可通过Navicat，DataGrip 等工具进行导出sql，然后导入服务器的数据库，这是技术常识问题！
2. 也可以通过gva工具，你可以把数据复制到cmd对应的文件中去，这不是我们gin-vue-admin所能做的事， 需要自己手动去copy数据到对应的表，无法替用户做定制化需求！

**Comment by wangerzi** [comment]
> 1. 数据迁移，与本项目无关，你可通过Navicat，DataGrip 等工具进行导出sql，然后导入服务器的数据库，这是技术常识问题！
> 2. 也可以通过gva工具，你可以把数据复制到cmd对应的文件中去，这不是我们gin-vue-admin所能做的事， 需要自己手动去copy数据到对应的表，无法替用户做定制化需求！

大哥你好，数据迁移我理解的，可能我措辞不太妥当，只是想在使用自动生成代码后，由 **代码生成器自己插入数据库** 的 `菜单、API` 能记录在 Git 里边（或者能 导入导出菜单/API 配置存放到 Git 里边），方便协作开发者使用；

**Comment by piexlmax** [comment]
> > 1. 数据迁移，与本项目无关，你可通过Navicat，DataGrip 等工具进行导出sql，然后导入服务器的数据库，这是技术常识问题！
> > 2. 也可以通过gva工具，你可以把数据复制到cmd对应的文件中去，这不是我们gin-vue-admin所能做的事， 需要自己手动去copy数据到对应的表，无法替用户做定制化需求！
> 
> 大哥你好，数据迁移我理解的，可能我措辞不太妥当，只是想在使用自动生成代码后，由 **代码生成器自己插入数据库** 的 `菜单、API` 能记录在 Git 里边（或者能 导入导出菜单/API 配置存放到 Git 里边），方便协作开发者使用；

您好，感谢您的issue，自动化代码生成后的信息是否可用是否为有效数据，程序是不可判定的，从程序设计角度确实可以生成一个xxx.db来跟随代码一起提交到仓库，但是这边会涉及太多人为因素，我们组内也经过了考虑和讨论。只能提出相应建议

1.使用协同数据库进行操作（组内成员公用同一个数据库表）
2.自行导出db.sql创建db文件来保证db的有效性，利用git等工具来进行数据合并

如果您有更好的方案 那是最棒的 协作问题确实是需要考虑的

**Comment by wangerzi** [comment]
@piexlmax 你好，我这边目前能想到的较为通用的实现是将 菜单、API 导出为 JSON 然后手动放到 git 中保管，如果多人协作出现冲突可以手动合并，每次导入的时候清理掉老数据，用 JSON 中的数据重新刷一遍。

但这个方案细想其实也是有问题的，会导致菜单和权限部分设计复杂，菜单数量多的时候还容易的导致性能问题，所以我这边权衡了下还是打算维护初始化 SQL 文件了。
