### ISSUE TITLE
更改首页后无法进入新的首页

### ISSUE THREAD

**Issue by TDL3** [flipped-aurora/gin-vue-admin#399]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16 linux/amd64
### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

node v15.10.0

npm 7.6.0

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
更改了首页

### 6. 您期望看到什么 ?

更改首页后，进入新设置的首页

### 7. 您看到了什么 ?
空白页面
Console 日志：
[vue-router] Route with name 'dashboard' does not exist
![Screenshot from 2021-03-10 14-33-52](https://user-images.githubusercontent.com/29535697/110587185-495c2400-81ae-11eb-972e-7898eeaf9aea.png)

### 8. 错误堆栈或者SQL打印

  | warn | @ | vue-router.esm.js?8c4f:16
-- | -- | -- | --
  | match | @ | vue-router.esm.js?8c4f:1592
  | match | @ | vue-router.esm.js?8c4f:2924
  | transitionTo | @ | vue-router.esm.js?8c4f:2251
  | replace | @ | vue-router.esm.js?8c4f:2720
  | eval | @ | vue-router.esm.js?8c4f:2373
  | _callee$ | @ | permission.js?223d:29
  | tryCatch | @ | runtime.js?96cf:62
  | invoke | @ | runtime.js?96cf:296
  | prototype.<computed> | @ | runtime.js?96cf:114
  | asyncGeneratorStep | @ | asyncToGenerator.js?1da1:3
  | _next | @ | asyncToGenerator.js?1da1:25
  | Promise.then (async) |   |  
  | asyncGeneratorStep | @ | asyncToGenerator.js?1da1:13
  | _next | @ | asyncToGenerator.js?1da1:25
  | eval | @ | asyncToGenerator.js?1da1:32
  | eval | @ | asyncToGenerator.js?1da1:21
  | eval | @ | permission.js?223d:8
  | iterator | @ | vue-router.esm.js?8c4f:2357
  | step | @ | vue-router.esm.js?8c4f:2004
  | runQueue | @ | vue-router.esm.js?8c4f:2012
  | confirmTransition | @ | vue-router.esm.js?8c4f:2387
  | transitionTo | @ | vue-router.esm.js?8c4f:2260
  | push | @ | vue-router.esm.js?8c4f:2704
  | eval | @ | vue-router.esm.js?8c4f:2375
  | _callee$ | @ | permission.js?223d:15
  | tryCatch | @ | runtime.js?96cf:62
  | invoke | @ | runtime.js?96cf:296
  | prototype.<computed> | @ | runtime.js?96cf:114
  | asyncGeneratorStep | @ | asyncToGenerator.js?1da1:3
  | _next | @ | asyncToGenerator.js?1da1:25
  | eval | @ | asyncToGenerator.js?1da1:32
  | eval | @ | asyncToGenerator.js?1da1:21
  | eval | @ | permission.js?223d:8
  | iterator | @ | vue-router.esm.js?8c4f:2357
  | step | @ | vue-router.esm.js?8c4f:2004
  | runQueue | @ | vue-router.esm.js?8c4f:2012
  | confirmTransition | @ | vue-router.esm.js?8c4f:2387
  | transitionTo | @ | vue-router.esm.js?8c4f:2260
  | init | @ | vue-router.esm.js?8c4f:2980
  | beforeCreate | @ | vue-router.esm.js?8c4f:1298
  | invokeWithErrorHandling | @ | vue.runtime.esm.js?2b0e:1854
  | callHook | @ | vue.runtime.esm.js?2b0e:4219
  | Vue._init | @ | vue.runtime.esm.js?2b0e:5004
  | Vue | @ | vue.runtime.esm.js?2b0e:5085
  | eval | @ | main.js?56d7:38
  | ./src/main.js | @ | app.js:1195
  | __webpack_require__ | @ | app.js:854
  | fn | @ | app.js:151
  | 1 | @ | app.js:1339
  | __webpack_require__ | @ | app.js:854
  | checkDeferredModules | @ | app.js:46
  | (anonymous) | @ | app.js:994
  | (anonymous) | @ | app.js:997

**Comment by SliverHorn** [comment]
感觉是没有权限

**Comment by TDL3** [comment]
感谢大佬指点，经过我一番折腾，居然可以了。在绝望尽头看到了曙光！！！

**Comment by TDL3** [comment]
貌似不是没权限，我后来发现只要开一个隐身模式窗口就可以正常进入了，于是我尝试清除浏览器缓存，之后就可以正常进入了！

**Comment by TDL3** [comment]
这是个 bug 吗？

**Comment by piexlmax** [comment]
> 这是个 bug 吗？

详细描述一下复现过程 dashboard 是前端定死的页面路由 可能存在name不匹配的情况 有可能是bug

**Comment by TDL3** [comment]
用代码生器生成一个表 -> 后端注册组件 -> 重启后端 -> 前端添加根菜单并将新加入的菜单设置为首页 -> 重启前端 -> 退出登录 -> 本issuse描述的问题出现 -> 清除浏览器数据 -> 问题解决，成功进入登录界面

**Comment by TDL3** [comment]
> > 这是个 bug 吗？
> 
> 详细描述一下复现过程 dashboard 是前端定死的页面路由 可能存在name不匹配的情况 有可能是bug

用代码生器生成一个表 -> 后端注册组件 -> 重启后端 -> 前端添加根菜单并将新加入的菜单设置为首页 -> 重启前端 -> 退出登录 -> 本issuse描述的问题出现 -> 清除浏览器数据 -> 问题解决，成功进入登录界面

**Comment by piexlmax** [comment]
> > > 这是个 bug 吗？
> > 
> > 
> > 详细描述一下复现过程 dashboard 是前端定死的页面路由 可能存在name不匹配的情况 有可能是bug
> 
> 用代码生器生成一个表 -> 后端注册组件 -> 重启后端 -> 前端添加根菜单并将新加入的菜单设置为首页 -> 重启前端 -> 退出登录 -> 本issuse描述的问题出现 -> 清除浏览器数据 -> 问题解决，成功进入登录界面

感谢 我们会尽快测试复现后修改

**Comment by piexlmax** [comment]
已修复
