### ISSUE TITLE
Mac 前端启动后，后端卡在gorm  getInstance 方法

### ISSUE THREAD

**Issue by cnfox** [flipped-aurora/gin-vue-admin#402]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.5 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
nodejs：v15.3.0 
cnpm@6.1.1 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.11 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@15.3.0 (/usr/local/Cellar/node/15.3.0/bin/node)
npminstall@3.28.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 19.6.0 
registry=https://r.npm.taobao.org

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
 Gin-Vue-Admin :V2.4.0

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?
正常启动后端代码 正常启动启动前端代码 前端请求 /init/checkdb接口
后端卡在了gorm  if db.clone > 0 { fatal error
```go
func (db *DB) getInstance() *DB {
	if db.clone > 0 {
		tx := &DB{Config: db.Config}
```

### 6. 您期望看到什么 ?

前端正常进入初始化数据库页面

### 7. 您看到了什么 ?

后端fatal error

### 8. 错误堆栈或者SQL打印
无

**Comment by piexlmax** [comment]
您好 请问现在能跑通了吗 这个问题在开发时候没有发现 如果可以 可添加我微信

**Comment by cnfox** [comment]
现在已经可以了 mysql的问题  重装了一下就好了
估计是权限问题
