### ISSUE TITLE
创建文件时没有过滤特殊字符

### ISSUE THREAD

**Issue by liangyinchuan** [flipped-aurora/gin-vue-admin#409]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
最新 master

go version go1.15.8 linux/amd64
### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

6.14.10

cnpm@6.1.1 (/usr/local/src/node-v14.15.4-linux-x64/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.11 (/usr/local/src/node-v14.15.4-linux-x64/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@14.15.4 (/usr/local/src/node-v14.15.4-linux-x64/bin/node)
npminstall@3.28.0 (/usr/local/src/node-v14.15.4-linux-x64/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local/src/node-v14.15.4-linux-x64
linux x64 3.10.0-862.11.6.el7.x86_64
registry=https://r.npm.taobao.org
### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?
phper

### 6. 您期望看到什么 ?
修复

### 8. 错误堆栈或者SQL打印

生成逻辑代码时没有过滤输入框输入的内容，导致创建的文件名称前后带有空格，导致加载文件失败

**Comment by piexlmax** [comment]
将会在下个版本修复
