### ISSUE TITLE
字典详情问题

### ISSUE THREAD

**Issue by G-Akiraka** [flipped-aurora/gin-vue-admin#414]
列如字典列表有 ，测试1:数据库id1、测试2:数据库id2，
测试1详情有：aaa:绑定列表id1，bbb:绑定列表id1
测试2详情有：ccc：绑定列表id2，ddd：绑定列表id2
点开测试1、或者测试2、刷新页面或者搜索aaa，然后编辑，变成成功，aaa，SysDictionaryID会变成0，二不是继续对应列表id

**Comment by piexlmax** [comment]
> 列如字典列表有 ，测试1:数据库id1、测试2:数据库id2，
> 测试1详情有：aaa:绑定列表id1，bbb:绑定列表id1
> 测试2详情有：ccc：绑定列表id2，ddd：绑定列表id2
> 点开测试1、或者测试2、刷新页面或者搜索aaa，然后编辑，变成成功，aaa，SysDictionaryID会变成0，二不是继续对应列表id

感谢issue，问题有点不太清楚，可以添加我的微信 shouzi_1994 详细描述 应该属于系统缺陷

**Comment by piexlmax** [comment]
未能复现
