### ISSUE TITLE
初始化数据库失败

### ISSUE THREAD

**Issue by akkuge** [flipped-aurora/gin-vue-admin#415]
mysql 5.7.14
select @@sql_mode;     

----------------------------------------+
| PIPES_AS_CONCAT,ANSI_QUOTES,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+

Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"角色ID",`authority_name` varchar(191) COMMENT "角色名",`parent_id` varchar' at line 1
[1.177ms] [rows:0] CREATE TABLE `sys_authorities` (`created_at` datetime NULL,`updated_at` datetime NULL,`deleted_at` datetime NULL,`authority_id` varchar(90) NOT NULL UNIQUE COMMENT "角色ID",`authority_name` varchar(191) COMMENT "角色名",`parent_id` varchar(191) COMMENT "父角色ID",`default_router` varchar(191) DEFAULT "dashOMMENT "默认菜单",PRIMARY KEY (`authority_id`))

**Comment by akkuge** [comment]
2.4.0

**Comment by SliverHorn** [comment]
- I'm sorry we can't see the error log from your error. Please follow the issues template to ask questions.
- The sql log is incomplete. Please send out the sql of the newly created table.

**Comment by akkuge** [comment]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.2 darwin/amd6

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

Nodejs v15.12.0
npm 7.7.5

cnpm -v
cnpm@6.1.1 (/usr/local/Cellar/node/15.12.0/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.11 (/usr/local/Cellar/node/15.12.0/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@15.12.0 (/usr/local/Cellar/node/15.12.0/bin/node)
npminstall@3.28.0 (/usr/local/Cellar/node/15.12.0/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local/Cellar/node/15.12.0 
darwin x64 19.6.0 
registry=https://r.npm.taobao.org

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master v2.4.0

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?
mysql  5.7.29
mysql> select @@sql_mode;                                                       +-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| PIPES_AS_CONCAT,ANSI_QUOTES,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+


### 6. 您期望看到什么 ?



### 7. 您看到了什么 ?
Go build 
￼

![Uploading Pasted Graphic.png…]()

### 8. 错误堆栈或者SQL打印

**Comment by akkuge** [comment]
GOROOT=/usr/local/Cellar/go/1.16.2/libexec #gosetup
GOPATH=/Users/robine/go #gosetup
/usr/local/Cellar/go/1.16.2/libexec/bin/go build -o /private/var/folders/j9/7vwjwbvd4cg23gvnp22jdznh0000gn/T/___go_build_main_go /Users/robine/Documents/golang/gin-vue-admin/server/main.go #gosetup
/private/var/folders/j9/7vwjwbvd4cg23gvnp22jdznh0000gn/T/___go_build_main_go
您正在使用config的默认值,config的路径为config.yaml
[GIN-VUE-ADMIN]2021/03/30 - 18:19:05.717        error   register table failed   {"err": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\"角色ID\",`authority_name` varchar(191) COMMENT \"角色名\",`parent_id` varchar' at line 1"}

Process finished with the exit code 0

**Comment by yafengstark** [comment]
用Mysql 5.7版本，并没有复现错误

**Comment by SliverHorn** [comment]
- output sql printing, please put it out.
- Is the database code `utf8mb4` ?

**Comment by akkuge** [comment]
已经解决！
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"角色ID",authority_name varchar(191) COMMENT "角色名",parent_id varchar' at line 1
[1.177ms] [rows:0] CREATE TABLE sys_authorities (created_at datetime NULL,updated_at datetime NULL,deleted_at datetime NULL,authority_id varchar(90) NOT NULL UNIQUE COMMENT "角色ID",authority_name varchar(191) COMMENT "角色名",parent_id varchar(191) COMMENT "父角色ID",default_router varchar(191) DEFAULT "dashOMMENT "默认菜单",PRIMARY KEY (authority_id))

SQL语句中不能有""
MYSQL 5.7 在SQL_MODE中去掉ANSI_QUOTES；
