### ISSUE TITLE
数据库连接泄漏，导致最后数据库无法响应新连接。

### ISSUE THREAD

**Issue by tazeng** [flipped-aurora/gin-vue-admin#417]
### 7. 您看到了什么 ?
确定和middleware.CasbinHandler()有关。
修复如下可以解决：
a, _ := gormadapter.NewAdapter(global.GVA_CONFIG.System.DbType, admin.Username+":"+admin.Password+"@("+admin.Path+")/"+admin.Dbname, true)
改为
a,_ :=gormadapter.NewAdapterByDB(global.GVA_DB)

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
In general, this situation occurs only when connecting to a remote database.

**Comment by tazeng** [comment]
What's your mean for "remote" database, the bug code depends on the GC to release the connection to database.
And for "local" databases, i think it uses "open file" system call to open the connection, that will consume the OS file handler, it is also unacceptable in some cases.

**Comment by piexlmax** [comment]
> What's your mean for "remote" database, the bug code depends on the GC to release the connection to database.
> And for "local" databases, i think it uses "open file" system call to open the connection, that will consume the OS file handler, it is also unacceptable in some cases.

感谢您的issue 经过排查 确实存在连接泄露问题 已采用 a,_ :=gormadapter.NewAdapterByDB(global.GVA_DB) 再次表示感谢！
