### ISSUE TITLE
页码高亮样式被覆盖

### ISSUE THREAD

**Issue by fang1998** [flipped-aurora/gin-vue-admin#419]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.15.2 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
nodev  14.16.0   npm  6.14.11

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
V2.3.8

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
本地项目运行之后页码能高亮
![image](https://user-images.githubusercontent.com/39109499/113268638-2b479680-930a-11eb-93f1-cd15abe82c05.png)
项目打包放服务器上后页码不能高亮
![image](https://user-images.githubusercontent.com/39109499/113268830-68ac2400-930a-11eb-8652-696ed5db5488.png)
然后我在官方提供的在线测试文档中发现同样的问题
![image](https://user-images.githubusercontent.com/39109499/113269001-98f3c280-930a-11eb-9577-dac3c9c55945.png)

### 6. 您期望看到什么 ?
当前页的页码高亮

### 7. 您看到了什么 ?
当前页码无高亮

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
已收到反馈 将会进行调整

**Comment by piexlmax** [comment]
已修复
