### ISSUE TITLE
不是 Vue 就更好了

### ISSUE THREAD

**Issue by w4-hanggi** [flipped-aurora/gin-vue-admin#42]
有没有计划出 Angular 或者 React 版本计划呢。

**Comment by piexlmax** [comment]
> 有没有计划出 Angular 或者 React 版本计划呢。

有react版本计划

**Comment by Ruio9244** [comment]
> 有没有计划出 Angular 或者 React 版本计划呢。

请问你更倾向于哪个版本？Angular or React

**Comment by w4-hanggi** [comment]
@Ruio9244 确实不好说，Angular 的 Typescript 的支持和生态更好，React 用的人更多社区更活跃。
