### ISSUE TITLE
master分支或者release 2021/03/07版本 缺少数据库初始化脚本

### ISSUE THREAD

**Issue by StinkyPeach** [flipped-aurora/gin-vue-admin#427]
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

克隆的master
release 2021/03/07版本 

### 4. 可以在master版本中复现此问题吗 ?

可以

### 7. 您看到了什么 ?

整个项目从头部署时，master 和 2021/03/07版本 代码里缺少initdb.bat和对应的源码文件 

### 8. 错误堆栈或者SQL打印

**Comment by SliverHorn** [comment]
Please take a look at the [document](https://www.gin-vue-admin.com)

**Comment by StinkyPeach** [comment]
> Please take a look at the [document](https://www.gin-vue-admin.com)

oh, thanks!
