### ISSUE TITLE
数据库表偶尔出现未创建，但是毫无异常和报错

### ISSUE THREAD

**Issue by neo-6** [flipped-aurora/gin-vue-admin#428]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.2 windows/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v12.14.1

6.13.4

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

当前版本:V2.4.0

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?
通过代码生成器创建了一个表good
// 自动生成模板Good
package model

import (
	"gin-vue-admin/global"
)

// 如果含有time.Time 请自行import time包
type Good struct {
      global.GVA_MODEL
      Name  string `json:"name" form:"name" gorm:"column:name;comment:商品名称;type:varchar(100);size:100;"`
}

func (Good) TableName() string {
  return "cms_good"
}

### 6. 您期望看到什么 ?
在数据库中生成了good表。

### 7. 您看到了什么 ?
实际没有表。

### 8. 错误堆栈或者SQL打印
完全没有错误提示。
通过比对[gorm文档](http://books.studygolang.com/gorm/models.html#md)中的说明，感觉是自动生成的model/good.go有错误，将Name修改后，
`      Name  string `json:"name" form:"name" gorm:"column:name;type:varchar(100);comment:商品名称"``
重新运行，数据库中生成good表。

**Comment by neo-6** [comment]
顺带在修改该表的时候，增加新字段，修改老字段，都会遇到无响应的错误，同时，对应的server中的api\v1，initialize\gorm.go,router.go、model\request\、model\、router\，service\，对应web中的src\api，src\view中的数据模型从cms_good命名方式变成了cmsGood的驼峰式

**Comment by yourenit** [comment]
同样创建不了数据表

**Comment by piexlmax** [comment]
此问题已排查 为自动化模板中 varchar长度和size冲突导致
