### ISSUE TITLE
怎么修改后台响应报panic 的时间上限，表的数据量过大，运用gorm查询时时间较长，容易panic 

### ISSUE THREAD

**Issue by Hujh-work** [flipped-aurora/gin-vue-admin#435]
怎么修改后台响应报panic 的时间上限，表的数据量过大，运用gorm查询时时间较长，容易panic

**Comment by piexlmax** [comment]
再 core下的serve找到对应的系统修改参数即可

**Comment by Hujh-work** [comment]
收到，谢谢



在 2021-04-14 23:27:23，"奇淼（piexlmax" ***@***.***> 写道：

在 core下的serve找到对应的系统修改参数即可
