### ISSUE TITLE
生成代码 request.js报needInit TypeError

### ISSUE THREAD

**Issue by itMuYou** [flipped-aurora/gin-vue-admin#436]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go1.16

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
v14.16.1

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
v2.4

### 5. 您做了什么 ?

生成代码并下载代码

### 7. 您看到了什么 ?
![image](https://user-images.githubusercontent.com/37922559/114976973-79879880-9eb9-11eb-89db-4a547893577d.png)

### 8. 解决办法
在src\utils\request.js文件的69行response.data.data.needInit改为response.data.data?.needInit

**Comment by piexlmax** [comment]
主干已修复
