### ISSUE TITLE
操作记录数据定期清理建议

### ISSUE THREAD

**Issue by bingoIsCoder** [flipped-aurora/gin-vue-admin#437]
数据表sys_operation_records，是用来记录api访问记录的，但是随着日期的增加，这个表会越来越大，能否设计一个定时任务定期去清理下这个表的数据呢

**Comment by piexlmax** [comment]
正在制作定时任务功能和专门针对日志的删除协程

**Comment by piexlmax** [comment]
已添加定时任务功能
