### ISSUE TITLE
能否加上session中间件的操作

### ISSUE THREAD

**Issue by fengyikang88** [flipped-aurora/gin-vue-admin#439]
github.com/gin-contrib/sessions v0.0.3
能否加上这个session包的中间件操作 方便刚使用这个框架的小伙伴

**Comment by piexlmax** [comment]
> github.com/gin-contrib/sessions v0.0.3
> 能否加上这个session包的中间件操作 方便刚使用这个框架的小伙伴

可以提交pr作为备用中间件
