### ISSUE TITLE
请问是否可以增加在线用户和用户的token拉黑功能呢?

### ISSUE THREAD

**Issue by zycdmax** [flipped-aurora/gin-vue-admin#441]
希望增加一个这样的功能  谢谢

**Comment by piexlmax** [comment]
目前有拉黑jwt功能 查看api即可

**Comment by zycdmax** [comment]
现在如果用户多点登录之后 那么是无法查看到用户使用的那个token  则无法做到踢下线用户 或者拉黑用户token
拉黑jwt只有用户主动点击退出登录的  没有管理员强制踢出某个用户

**Comment by piexlmax** [comment]
> 现在如果用户多点登录之后 那么是无法查看到用户使用的那个token 则无法做到踢下线用户 或者拉黑用户token
> 拉黑jwt只有用户主动点击退出登录的 没有管理员强制踢出某个用户

因此多点登录共功能依赖redis，记录活跃的jwt，下一个用户登录会把活跃的jwt拉黑
