### ISSUE TITLE
Mac打包后找不到配置文件config.yaml，得设置绝对路径才行

### ISSUE THREAD

**Issue by xzhaha123** [flipped-aurora/gin-vue-admin#443]
成功启动后也会报错，不知道是不是casbin配置文件找不到的原因

2021/04/22 15:01:32 [Recovery] 2021/04/22 - 15:01:32 panic recovered:
POST /menu/getMenu HTTP/1.1
Host: 127.0.0.1:8888
Connection: close
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close
Content-Length: 0
Cookie: Phpstorm-6562555d=227c4427-9847-4bbf-aea0-d7f74ee002dd; Hm_lvt_1d2d61263f13e4b288c8da19ad3ff56d=1612161710,1612162600; Goland-2d624380=5389cbcb-7ba5-4f04-abb3-6db5d25d7e24; JSESSIONID=FE428B86610993E6F77961F76DBC4C16
Origin: http://localhost:8080
Referer: http://localhost:8080/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: localhost:8080
X-Forwarded-Port: 8080
X-Forwarded-Proto: http
X-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVVUlEIjoiOTkyOTc1OWMtZTE0NS00ZTA0LWIyOTctNGE0MDcwNzRiODlhIiwiSUQiOjEsIlVzZXJuYW1lIjoiYWRtaW4iLCJOaWNrTmFtZSI6Iui2hee6p-euoeeQhuWRmCIsIkF1dGhvcml0eUlkIjoiODg4IiwiQnVmZmVyVGltZSI6ODY0MDAsImV4cCI6MTYxOTY2ODMyNiwiaXNzIjoicW1QbHVzIiwibmJmIjoxNjE5MDYyNTI2fQ.jbdjjxBvTk2vGfd7hQSGuMaa_5x8JLySnwsqNGfuP1A
X-User-Id: 1

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x404ddd2)
	panicmem: panic(memoryError)
/usr/local/go/src/runtime/signal_unix.go:742 (0x404dc52)
	sigpanic: panicmem()

**Comment by piexlmax** [comment]
设置绝对路径可以解决此问题吗 目前确实有用户出现了此问题
