### ISSUE TITLE
更多框架支持，如 echo, iris, chi 等

### ISSUE THREAD

**Issue by runner-mei** [flipped-aurora/gin-vue-admin#448]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go 1.16
echo

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
v12.16.1

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
还未使用

希望可以支持更多框架，如 echo, iris, chi 等， 这些框架，其实大同小异，可以参考一下 https://github.com/runner-mei/gogen 的做法

**Comment by SliverHorn** [comment]
Hello, we don't have much energy to maintain the web framework except gin and gf. Please understand.
