### ISSUE TITLE
Nested categories / real world use case: password manager

### ISSUE THREAD

**Issue by lucmichalski** [flipped-aurora/gin-vue-admin#450]
Hi guys,

Hope you are all well !

I would like to use **gin-vue-admin** for creating a password manager with advanced RBAC functionalities.
Do you think that it is worth to use gin-vue-admin as the core boilerplate of the admin interface for doing so ?

One of them is to create nested category tree to organize passwords in collections, groups like that https://github.com/griffinqiu/go-nested-set, is it something we could integrate into gin-vue-admin ?

Example of interface:
![171575](https://user-images.githubusercontent.com/1963546/115979956-4a43ec00-a589-11eb-84d2-c8b196ccc2ab.png)

That would be awesome as it could trigger a popular usecase based on gin-vue-admin.

Thanks for any insights or inputs on that.

Cheers,
Luc Michalski

**Comment by piexlmax** [comment]
Thank you for your issue
Gin-vue-admin can be used to make password manager. It only designs the most basic functions and provides business automation code, which can facilitate business expansion and make the specific business implementation more convenient.
Thank you very much for trying to develop with gin-vue-admin.
