### ISSUE TITLE
打扰了，咨询一下，不让用视图的情况下，对authority_menu这个视图有啥替代方法吗？

### ISSUE THREAD

**Issue by xuzhenhai** [flipped-aurora/gin-vue-admin#453]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.14.4 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v12.16.1

6.13.4

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

v2.3.0

### 4. 可以在master版本中复现此问题吗 ?
可以

### 5. 您做了什么 ?

authority_menu是一个视图，可公司这边的规范是不给用视图，不知道有啥好的替代方案吗？
谢谢。

### 6. 您期望看到什么 ?
期望看看是否有比较方便成本低的替代方案。在此先谢谢了！

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
用关系表联查即可 视图就是关系表的提前联查映射

**Comment by xuzhenhai** [comment]
嗯嗯 感谢回复。 已经用联查的方式做了改造。
