### ISSUE TITLE
How can i listen Unix sock addr instead of IP:port

### ISSUE THREAD

**Issue by jyxjjj** [flipped-aurora/gin-vue-admin#456]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.3 linux/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

>Null

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

v2.4.1

### 4. 可以在master版本中复现此问题吗 ?

y

### 5. 您做了什么 ?

system.addr: /tmp/ocr.sock

### 6. 您期望看到什么 ?

listening unix sock on /tmp/ocr.sock

### 7. 您看到了什么 ?

* cannot parse 'system.addr' as int: strconv.ParseInt: parsing "/tmp/ocr.sock": invalid syntax

### 8. 错误堆栈或者SQL打印

* cannot parse 'system.addr' as int: strconv.ParseInt: parsing "/tmp/ocr.sock": invalid syntax

**Comment by SliverHorn** [comment]
5. What have you done
Please explain in detail！

**Comment by jyxjjj** [comment]
I just edit the config.yaml to set system.addr as /tmp/ocr.sock then i run it without any change.
After i submit this issue, I searched and checked the codes of this frame, i think it will not support unix socket if I don't change the full frame.
