### ISSUE TITLE
支持 -d 参数后台运行

### ISSUE THREAD

**Issue by jiashiwen** [flipped-aurora/gin-vue-admin#458]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.15.10 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
node -v
v14.16.1

6.14.12

### 6. 您期望看到什么 ?
希望支持 -d 参数 使得程序启动在后台运行

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
问题不明确

**Comment by jiashiwen** [comment]
我提pr了，其实就是启动的时候和NGINX一样支持后台模式，不需要 nohup xxxxxx & 来后台启动

**Comment by YLQZ** [comment]
windows 只需要在编译的时候使用一下go build - ldflags="-H windows"

Linux  在运行程序的尾部加入&，或者nohup ./example &

**Comment by llmgo** [comment]
can use pm2

**Comment by sycki** [comment]
@jiashiwen 进程本身并不能决定自己的父进程是谁，因此通过参数来让进程后台执行的方法并不可取，虽然我们可以通过比较hack的方式达到此目的，但这破坏了程序设计原则。

在Linux系统中，你通常可以使用以下方式启动你的程序，该方法保证程序在启动后，其父进程为1，即使当你关闭当前bash，程序也会继续运行：
```
(./service &> service.log &)
```

在Linux系统中，最好的做法将程序编写为`systemd unit`文件，然后使用`systemctl start my-bin`的方式启动它，系统将保证它会一直运行，且程序产生的日志由系统统一处理。

请Owner @jiashiwen 或管理员@piexlmax 考虑关闭此问题，感谢。
