### ISSUE TITLE
token过期缓冲期内如果出现并发访问的情况会不会导致token覆盖？

### ISSUE THREAD

**Issue by youngsailor** [flipped-aurora/gin-vue-admin#473]
开启单点登录时，在token过期缓冲期内如果出现并发访问，这时携带了相同的token，会不会导致新生成的token被后面并发生成的token覆盖了，或者后面的并发访问直接进入黑名单检查被过滤掉了而无法进行后续业务逻辑了？

**Comment by piexlmax** [comment]
不会的 前端会存储后续来的token 永远以最后的那个为标准进行存储 并且前者没有进入jwt 而是等待其自动过期
