### ISSUE TITLE
数据库初始化逻辑错误

### ISSUE THREAD

**Issue by zskylark** [flipped-aurora/gin-vue-admin#474]
xxxx/server/api/v1/sys_initdb.go
第20行：if global.GVA_DB ！= nil {
应该为：if global.GVA_DB == nil {
不然会导致数据库记录初始化不成功。

**Comment by SliverHorn** [comment]
没错啊

**Comment by SliverHorn** [comment]
/init/checkdb 判断 global.GVA_DB是否为空

**Comment by zskylark** [comment]
我用的是tag：v2.4.1。
我手动在Mysql里建了库以及帐号但未建表。
在程序第一次启动时，main.go:19已经让GVA_DB!=nil，这时会执行接着的initialize.MysqlTables(global.GVA_DB) // 初始化表。
但是initialize.MysqlTables方法只是初始化了表结构，没有写入默认数据。
然后，我调用swagger里的/init/initdb接口想写入默认数据记录，此时会触发之前我描述的问题，总是报错提示：非法访问。
是我操作方法或者顺序有问题吗？

**Comment by SliverHorn** [comment]
gin-vue-admin.com
