### ISSUE TITLE
前端多个路由指向同一模板页时，打开标签页不刷新

### ISSUE THREAD

**Issue by poorboss3** [flipped-aurora/gin-vue-admin#485]
当多个前端路由指向同一vue模板页面，从菜单访问进去打开标签页，直接时第一个开打的页面，后面打开的新标签页不会渲染。

**Comment by piexlmax** [comment]
提供以下代码示例或者图文示例

**Comment by poorboss3** [comment]
搞清楚了 是vue Router push不会刷新页面导致
