### ISSUE TITLE
数据库表前缀不统一，命名也不统一，想和其他系统整合难度好大，希望能优化

### ISSUE THREAD

**Issue by mlsjla** [flipped-aurora/gin-vue-admin#498]
因为gva属于后台系统，用于管理数据生成表单很方便。
但是需要和其他系统整合，方便前台的接口调用。
就需要对表和数据进行共享管理。
本来很容易写自动增删改查， 结果表不统一，存在以下问题，希望能优化。

## 整理以下问题
1. 表前缀不统一， 如有的是sys_  有的是没有前缀， 有的是exa_
2. 无法统一自定义表前缀，而修改gorm的配置增加表前缀， 但是不少表的创建脚本都是写死的要每一处去改，且gorm.open有两处，参数还不一样
3. 表名格式配置也不统一。  有的是后面带s的，有的不带写死的table名称。 建议起码系统自带的表统一下
4. 最好增加表前缀的配置

## 增加表前缀配置，由于历史原因可能引发问题
需要做数据迁移处理。

**Comment by fzqk9** [comment]
确实是个问题 ，希望帮主优化下 表命名

**Comment by piexlmax** [comment]
1.表前缀 exa_ sys_ 为了区分是系统表或者是示例文件表  casbin_rule表名称需要跟casbin官方一致 exa 部分可删除
2.gorm.open 一处用于初始化以部建表 另一处用域正式使用 初始化建表那边只需要使用一次 系统部署完成后可删除
3.表名称带s的为数据表，不带s的为关联表（中间表）这点直接沿用 gorm的默认约定
4.表前缀配置可增加

**Comment by mlsjla** [comment]
@piexlmax   

感谢大佬哦~
可配置表前缀太重要了。

**Comment by mlsjla** [comment]
表名称带s的为数据表，不带s的为关联表问题， 希望这个也可以配置。  

本身orm也支持配置的。
```
默认 NamingStrategy 也提供了几个选项，如：

db, err := gorm.Open(sqlite.Open("gorm.db"), &gorm.Config{
  NamingStrategy: schema.NamingStrategy{
    TablePrefix: "t_",   // 表名前缀，`User`表为`t_users`
    SingularTable: true, // 使用单数表名，启用该选项后，`User` 表将是`user`
    NameReplacer: strings.NewReplacer("CID", "Cid"), // 在转为数据库名称之前，使用NameReplacer更改结构/字段名称。
  },
})
```

**Comment by SliverHorn** [comment]
model里面的模型 实现Tabler接口就可以自定义表名了呀，全局的TablePrefix，基本不能实现你的需求

**Comment by mlsjla** [comment]
sys的表， 不能实现自定义前缀 ？
这样对接其他开源程序太难了。
