### ISSUE TITLE
mac node 16版本上，会报错，默认的 "node-sass": "^4.12.0" 版本不支持node 15 16

### ISSUE THREAD

**Issue by zhipingch** [flipped-aurora/gin-vue-admin#506]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
go version go1.16.4 darwin/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
v16.2.0

7.14.0

`
cnpm@6.2.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.13 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@16.2.0 (/usr/local/Cellar/node/16.2.0/bin/node)
npminstall@3.28.0 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 19.6.0 
registry=https://registry.nlark.com
` 
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?
可以。
mac node 16版本上，会报错，默认的 "node-sass": "^4.12.0" 版本不支持node 15 16；

升级node-sass到6.0.0的话，其他依赖node-sass ^4.0.0的就会报错。目前看用户只能回退node到14

### 5. 您做了什么 ?
1、回退node到14版本，固定版本

### 6. 您期望看到什么 ?
1、期望升级一下，换成 dart-sass。
感谢支持

### 8. 错误堆栈或者SQL打印

**Comment by yann0917** [comment]
我也遇到了，node 16.3 版本的需要 node-sass 6.0，
node-sass 升级之后，还要固定 sass-loader 版本到 10.1.1，要不然不兼容，
运行的时候又报 `Node Sass version 6.0.0 is incompatible with ^4.0.0 || ^5.0.0.`

只能退回到14版本，卸载最新版，安装固定版本 `brew install node@14`

**Comment by piexlmax** [comment]
已修改为dart-sass 遇即2021/06/11下午6：00前上master

**Comment by bypanghu** [comment]
或者直接采用yarn 可以修复此bug
