### ISSUE TITLE
代码生成器功能chrome使用，但是360浏览器用起来丝般顺滑

### ISSUE THREAD

**Issue by ztcx2019** [flipped-aurora/gin-vue-admin#537]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?
 go1.16.4 windows/amd6    

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?
      v14.17.0   ；
     7.12.1；
     cnpm@6.2.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\lib\parse_argv.js)
npm@6.14.13 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\lib\npm.js)
node@14.17.0 (D:\Program Files (x86)\nodejs\node.exe)
npminstall@3.28.0 (C:\Users\Administrator\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\index.js)
prefix=C:\Users\Administrator\AppData\Roaming\npm
win32 ia32 10.0.17134
registry=https://registry.nlark.com

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
Gin-Vue-Admin V2.4.1

### 5. 您做了什么 ?
       gva自动的autocode功能无法使用，只是用Chrome浏览器使用autocode功能页面空白，控制台也未报错，无任何响应，但是360浏览器是可以正常使用autocode 功能的。

### 6. 您期望看到什么 ?
       进入gva后台，使用autocode功能快速生成模块框架，快速进行业务开发和学些。

### 7. 您看到了什么 ?
      360浏览器可以正常使用autocode功能，但是chrome浏览器打开页面空白，控制台及后台程序均无任何输出供参考，完全不知原因以及如何修复。

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
请使用master版本测试
