### ISSUE TITLE
关于SysBaseMenu表的一些疑问

### ISSUE THREAD

**Issue by dybxin** [flipped-aurora/gin-vue-admin#543]
MenuLevel 保留字段的设计考虑的原因？我没看并没有使用到该字段

**Comment by dybxin** [comment]
另外关于角色的设计的疑问: 角色1下新建了子角色2，默认情况下子角色2的权限是不能超出父角色的权限的，但是现在在修改时子角色的权限是可以超出父角色的。

**Comment by piexlmax** [comment]
MenuLevel 是保留字段 
第二个问题可以参考前面的issue https://github.com/flipped-aurora/gin-vue-admin/issues/24

**Comment by dybxin** [comment]
@piexlmax 谢谢
