### ISSUE TITLE
请求添加设置默认角色,添加用户的时候可以不填角色,方便给用户使用的时候权限管理

### ISSUE THREAD

**Issue by godLei6** [flipped-aurora/gin-vue-admin#590]
请求添加设置默认角色,添加用户的时候可以不填角色,方便给用户使用的时候权限管理

**Comment by piexlmax** [comment]
目前已调整为多角色模式 可能并不适用此方式了

**Comment by godLei6** [comment]
那么是否可以控制新增用户的时候控制展示的角色,比如超管可以看到所有角色,但是普通管理员就看不到超管这个角色了
