### ISSUE TITLE
启动gva后为空白

### ISSUE THREAD

**Issue by XiBuYuanMa** [flipped-aurora/gin-vue-admin#596]
如题：启动gva后为空白页，但是8888端口的swagger可以正常访问，并且访问路由记录也可以在控制台正常输出，访问gva就是空白，控制台也没输出访问路由记录。
使用的目前最新版本的master，最新版的npm、nodejs。苹果和Windows都试了。出现同样的问题

**Comment by piexlmax** [comment]
使用的谷歌浏览器吗？前端是否启动？

**Comment by XiBuYuanMa** [comment]
> 使用的谷歌浏览器吗？前端是否启动？

对，用的谷歌浏览器。前端正常启动无报错信息。刚刚查看浏览器控制台看到有报错信息：Uncaught ReferenceError: __VUE_HMR_RUNTIME__ is not defined    
![image](https://user-images.githubusercontent.com/49113945/126898393-5a0e7ae8-3bc0-41d7-b4ca-679137bf5761.png)

**Comment by XiBuYuanMa** [comment]
> 使用的谷歌浏览器吗？前端是否启动？

nodejs 12、14、16版本都试过了，也不行

**Comment by piexlmax** [comment]
是否是npm 安装 不要使用cnpm

**Comment by XiBuYuanMa** [comment]
> 是否是npm 安装 不要使用cnpm

确实是这个问题，之前用的都是cnpm安装。现在解决了
