### ISSUE TITLE
无网络或者内网环境下无法使用表单生成器

### ISSUE THREAD

**Issue by wangyitao** [flipped-aurora/gin-vue-admin#598]
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

最新版本的master分支

### 4. 可以在master版本中复现此问题吗 ?
可以
### 5. 您做了什么 ?
断网，清空浏览器缓存，离线环境开发的时候发现表单生成器无法使用
![test2](https://user-images.githubusercontent.com/12211038/127175132-3e1e4044-7783-4e6f-89fc-76039955dc03.png)

### 6. 您期望看到什么 ?
在没有联网的环境使用，记得很早以前的版本是可以在没有联网的环境下使用表单生成器的。
请教下怎样修改能让表单生成器在没有网络的时候使用？

### 7. 您看到了什么 ?
断网情况下无法使用表单生成器

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
表单生成器来自于你的gin服务，只要是可以连接到你自身的gin服务就可以使用表单生成器。

**Comment by wangyitao** [comment]
> 表单生成器来自于你的gin服务，只要是可以连接到你自身的gin服务就可以使用表单生成器。

感谢回复，亲测表单生成器是依赖网络的，没有网络使用不了，gin服务是开着的，代码生成器可以离线使用。是否可以把表单生成器的依赖资源改成静态的

**Comment by wangyitao** [comment]
> 表单生成器来自于你的gin服务，只要是可以连接到你自身的gin服务就可以使用表单生成器。

感谢回复，亲测表单生成器是依赖网络的，没有网络使用不了，gin服务是开着的，代码生成器可以离线使用。是否可以把表单生成器的依赖资源改成静态的

**Comment by piexlmax** [comment]
本身依赖就是静态的 文档有写需要手动修改为你本身服务所在地址的ip或者内网ip 这种问题应该是你没有修改ip导致使用了我们demo环境的表单生成器
