### ISSUE TITLE
mysql数据表没有一行注释

### ISSUE THREAD

**Issue by MasterJoyHunan** [flipped-aurora/gin-vue-admin#60]
![image](https://user-images.githubusercontent.com/25575041/79535854-34b40080-80b1-11ea-9034-fa19e03ba30b.png)
![image](https://user-images.githubusercontent.com/25575041/79535883-409fc280-80b1-11ea-83c3-7e0dbcf74a93.png)
这是正常的吗？如果正常，为什么这么做呢？

**Comment by piexlmax** [comment]
> ![image](https://user-images.githubusercontent.com/25575041/79535854-34b40080-80b1-11ea-9034-fa19e03ba30b.png)
> ![image](https://user-images.githubusercontent.com/25575041/79535883-409fc280-80b1-11ea-83c3-7e0dbcf74a93.png)
> 这是正常的吗？如果正常，为什么这么做呢？
本项目使用了gorm 对数据库的操作已经抽象为结构体操作，所以数据库中的注释可以转移为代码的结构体注释。不过建议很好，可以考虑添加数据库描述

**Comment by MasterJoyHunan** [comment]
我觉得数据库还是需要加注释的，毕竟项目大多时候是多人开发、其次，若和他人对接，加上注释会省掉大部分沟通成本，
