### ISSUE TITLE
关于SysAuthority表的疑问

### ISSUE THREAD

**Issue by dybxin** [flipped-aurora/gin-vue-admin#601]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.6 linux/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v14.17.0

6.14.13

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

```
type SysAuthority struct {
	CreatedAt       time.Time      // 创建时间
	UpdatedAt       time.Time      // 更新时间
	DeletedAt       *time.Time     `sql:"index"`
	AuthorityId     string         `json:"authorityId" gorm:"not null;unique;primary_key;comment:角色ID;size:90"` // 角色ID
	AuthorityName   string         `json:"authorityName" gorm:"comment:角色名"`                                    // 角色名
	ParentId        string         `json:"parentId" gorm:"comment:父角色ID"`                                       // 父角色ID
	DataAuthorityId []SysAuthority `json:"dataAuthorityId" gorm:"many2many:sys_data_authority_id"`
	Children        []SysAuthority `json:"children" gorm:"-"`
	SysBaseMenus    []SysBaseMenu  `json:"menus" gorm:"many2many:sys_authority_menus;"`
	DefaultRouter   string         `json:"defaultRouter" gorm:"comment:默认菜单;default:dashboard"` // 默认菜单(默认dashboard)
}
```

模型中的Children和DataAuthorityId是否重复？， 另外
![Screenshot from 2021-07-28 17-33-57](https://user-images.githubusercontent.com/14888437/127299965-4c3082e7-2e7a-4486-a43a-7171306da1fd.png)

![Screenshot from 2021-07-28 17-35-51](https://user-images.githubusercontent.com/14888437/127300081-eb1d6b09-4b4d-4691-880a-1ecc6a52422e.png)

为什么 9528 这个 的DataAuthorityId 里面 会包含 8881这个角色？这里的DataAuthorityId作用是什么？

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
DataAuthorityId是资源权限 详细功能可以看 示例文件最后的客户列表 用域控制A角色是否可以查看B的客户之类的功能

**Comment by dybxin** [comment]
@piexlmax  另外 我还注意到 

```
type SysUser struct {
	global.GVA_MODEL
	UUID        uuid.UUID      `json:"uuid" gorm:"comment:用户UUID"`                                                    // 用户UUID
	Username    string         `json:"userName" gorm:"comment:用户登录名"`                                                 // 用户登录名
	Password    string         `json:"-"  gorm:"comment:用户登录密码"`                                                      // 用户登录密码
	NickName    string         `json:"nickName" gorm:"default:系统用户;comment:用户昵称"`                                     // 用户昵称
	HeaderImg   string         `json:"headerImg" gorm:"default:http://qmplusimg.henrongyi.top/head.png;comment:用户头像"` // 用户头像
	Authority   SysAuthority   `json:"authority" gorm:"foreignKey:AuthorityId;references:AuthorityId;comment:用户角色"`
	AuthorityId string         `json:"authorityId" gorm:"default:888;comment:用户角色ID"`     // 用户角色ID
	SideMode    string         `json:"sideMode" gorm:"default:dark;comment:用户角色ID"`       // 用户侧边主题
	ActiveColor string         `json:"activeColor" gorm:"default:#1890ff;comment:用户角色ID"` // 活跃颜色
	BaseColor   string         `json:"baseColor" gorm:"default:#fff;comment:用户角色ID"`      // 基础颜色
	Authorities []SysAuthority `json:"authorities" gorm:"many2many:sys_user_authority;"`
}
```

中新增了 一个用户可以对应多个角色， 并且还保留了  原来的 一个用户只能对应一个角色的设计，并且 代码中  也保留了

```
Preload("Authorities").Preload("Authority")
```
如上的代码，来兼容两种需求。是这样的吗？

**Comment by dybxin** [comment]
> DataAuthorityId是资源权限 详细功能可以看 示例文件最后的客户列表 用域控制A角色是否可以查看B的客户之类的功能

谢谢， 另外，关于这点我还有一个问题，是关于模型中一对多(即 SysAuthority 对应多个Children 并且 类型还都是SysAuthority ), gorm可以通过Preload的方式把SysAuthority 对应的children 查询出来吗？

```
type SysAuthority struct {
	CreatedAt       time.Time      // 创建时间
	UpdatedAt       time.Time      // 更新时间
	DeletedAt       *time.Time     `sql:"index"`
	AuthorityId     string         `json:"authorityId" gorm:"not null;unique;primary_key;comment:角色ID;size:90"` // 角色ID
	AuthorityName   string         `json:"authorityName" gorm:"comment:角色名"`                                    // 角色名
	ParentId        string         `json:"parentId" gorm:"comment:父角色ID"`                                       // 父角色ID
	Children        []SysAuthority `json:"children" gorm:"-"`
	DefaultRouter   string         `json:"defaultRouter" gorm:"comment:默认菜单;default:dashboard"` // 默认菜单(默认dashboard)
}
```

**Comment by dybxin** [comment]
> > DataAuthorityId是资源权限 详细功能可以看 示例文件最后的客户列表 用域控制A角色是否可以查看B的客户之类的功能
> 
> 谢谢， 另外，关于这点我还有一个问题，是关于模型中一对多(即 SysAuthority 对应多个Children 并且 类型还都是SysAuthority ), gorm可以通过Preload的方式把SysAuthority 对应的children 查询出来吗？
> 
> ```
> type SysAuthority struct {
> 	CreatedAt       time.Time      // 创建时间
> 	UpdatedAt       time.Time      // 更新时间
> 	DeletedAt       *time.Time     `sql:"index"`
> 	AuthorityId     string         `json:"authorityId" gorm:"not null;unique;primary_key;comment:角色ID;size:90"` // 角色ID
> 	AuthorityName   string         `json:"authorityName" gorm:"comment:角色名"`                                    // 角色名
> 	ParentId        string         `json:"parentId" gorm:"comment:父角色ID"`                                       // 父角色ID
> 	Children        []SysAuthority `json:"children" gorm:"-"`
> 	DefaultRouter   string         `json:"defaultRouter" gorm:"comment:默认菜单;default:dashboard"` // 默认菜单(默认dashboard)
> }
> ```

@piexlmax 关于这这问题我在官方文档找到了相关的示例，并做了相关的验证，我觉得使用官方的模式 会省掉我们现有通过for...range的查询方式.

现在代码中的通过递归查询方式
```
func (authorityService *AuthorityService) findChildrenAuthority(authority *system.SysAuthority) (err error) {
	err = global.GVA_DB.Preload("DataAuthorityId").Where("parent_id = ?", authority.AuthorityId).Find(&authority.Children).Error
	if len(authority.Children) > 0 {
		for k := range authority.Children {
			err = authorityService.findChildrenAuthority(&authority.Children[k])
		}
	}
	return err
}
```

更改后的方式,使用如下方式可以删除掉字段ParentId        
```
type SysAuthority struct {
	CreatedAt       time.Time      // 创建时间
	UpdatedAt       time.Time      // 更新时间
	DeletedAt       *time.Time     `sql:"index"`
	AuthorityId     string         `json:"authorityId" gorm:"not null;unique;primary_key;comment:角色ID;size:90"` // 角色ID
	AuthorityName   string         `json:"authorityName" gorm:"comment:角色名"`                                    // 角色名
	Children        []SysAuthority `json:"children" gorm:"many2many:sys_authority_children"`
}

db.Model(&model.Authority{}).Preload("Children")).Find(&authority).Error
```

我的粗浅的想法，不知道合适不？还是说您当时这样设计有其他层面的考虑？

**Comment by piexlmax** [comment]
只有一层是完全可以使用预加载的 但是 角色父子关系为树形结构 子角色一样可以拥有子角色 这时候 预加载一层Children就已经不够了

**Comment by pnck** [comment]
> @piexlmax 另外 我还注意到
> 
> ```
> type SysUser struct {
> 	global.GVA_MODEL
> 	UUID        uuid.UUID      `json:"uuid" gorm:"comment:用户UUID"`                                                    // 用户UUID
> 	Username    string         `json:"userName" gorm:"comment:用户登录名"`                                                 // 用户登录名
> 	Password    string         `json:"-"  gorm:"comment:用户登录密码"`                                                      // 用户登录密码
> 	NickName    string         `json:"nickName" gorm:"default:系统用户;comment:用户昵称"`                                     // 用户昵称
> 	HeaderImg   string         `json:"headerImg" gorm:"default:http://qmplusimg.henrongyi.top/head.png;comment:用户头像"` // 用户头像
> 	Authority   SysAuthority   `json:"authority" gorm:"foreignKey:AuthorityId;references:AuthorityId;comment:用户角色"`
> 	AuthorityId string         `json:"authorityId" gorm:"default:888;comment:用户角色ID"`     // 用户角色ID
> 	SideMode    string         `json:"sideMode" gorm:"default:dark;comment:用户角色ID"`       // 用户侧边主题
> 	ActiveColor string         `json:"activeColor" gorm:"default:#1890ff;comment:用户角色ID"` // 活跃颜色
> 	BaseColor   string         `json:"baseColor" gorm:"default:#fff;comment:用户角色ID"`      // 基础颜色
> 	Authorities []SysAuthority `json:"authorities" gorm:"many2many:sys_user_authority;"`
> }
> ```
> 
> 中新增了 一个用户可以对应多个角色， 并且还保留了 原来的 一个用户只能对应一个角色的设计，并且 代码中 也保留了
> 
> ```
> Preload("Authorities").Preload("Authority")
> ```
> 
> 如上的代码，来兼容两种需求。是这样的吗？

给后来的人说一下，这个坑我踩了俩小时最后改前端的时候才发现：
`SysUser` Model里的 `Authority`和 `AuthorityID` 是「当前登录/下次登录角色」，是个跟 `Authorites[]` （用户可选角色）彼此独立的关系，并不是为了「兼容性」保留的。

希望我多留的这句话能节省你俩小时 ☕
