### ISSUE TITLE
关于casbin 中间件的疑问

### ISSUE THREAD

**Issue by dybxin** [flipped-aurora/gin-vue-admin#602]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.6 linux/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

v14.17.0

6.14.13

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

```
func CasbinHandler() gin.HandlerFunc {
	return func(c *gin.Context) {
		claims, _ := c.Get("claims")
		waitUse := claims.(*request.CustomClaims)
		// 获取请求的URI
		obj := c.Request.URL.RequestURI()
		// 获取请求方法
		act := c.Request.Method
		// 获取用户的角色
		sub := waitUse.AuthorityId
		e := casbinService.Casbin()
		// 判断策略中是否存在
		success, _ := e.Enforce(sub, obj, act)
		if global.GVA_CONFIG.System.Env == "develop" || success {
			c.Next()
		} else {
			response.FailWithDetailed(gin.H{}, "权限不足", c)
			c.Abort()
			return
		}
	}
}
```
在casbin 中间件中，通过jwt中的CustomClaims获取到当前用户的AuthorityId, 根据现在的设计一个用可以绑定多个Authority(角色),但是在casbin 拦截器中确是 `sub := waitUse.AuthoritId`   ， 这里是否应该匹配到用户的所有权限id?

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
不应该去匹配所有用户权限 目前为单角色权限模式 用户可以根据切换角色来选择自己当前身份 如果使用角色组的概念 则菜单等都需要引入例如岗位 组织的概念 从而加大配置和开发难度

**Comment by dybxin** [comment]
> 不应该去匹配所有用户权限 目前为单角色权限模式 用户可以根据切换角色来选择自己当前身份 如果使用角色组的概念 则菜单等都需要引入例如岗位 组织的概念 从而加大配置和开发难度

@piexlmax  谢谢，那这里是我理解的有问题吗？
![Screenshot from 2021-08-02 11-51-20](https://user-images.githubusercontent.com/14888437/127802148-905c6236-0bb2-44e1-b7ad-167125240392.png)

demo示例中 确实是一个用户可以绑定多个角色的。
