### ISSUE TITLE
数据库初始化后，出现登陆错误

### ISSUE THREAD

**Issue by srdgame** [flipped-aurora/gin-vue-admin#609]
使用的是master分支

![image](https://user-images.githubusercontent.com/54447/127855923-80193233-ff8c-4240-86ea-aab17d008d46.png)

**Comment by srdgame** [comment]
This issue can be fixed by change mysql global settings:

```
set global table_definition_cache = 4096;
```

**Comment by srdgame** [comment]
![image](https://user-images.githubusercontent.com/54447/127859098-2a64209a-9805-4f9a-bcf7-30a85bad8fd7.png)

**Comment by piexlmax** [comment]
数据库版本是多少

**Comment by srdgame** [comment]
@piexlmax 

Server version: 10.5.11-MariaDB-1 Debian 11

**Comment by piexlmax** [comment]
MariaDB 可能存在一定问题 建议使用mysql 并没有针对MariaDB做专门的测试和适配
