### ISSUE TITLE
关于数据字典的相关问题

### ISSUE THREAD

**Issue by tlerbao** [flipped-aurora/gin-vue-admin#618]
应该是在V2ex看到的

先感谢开源。

### 相关问题

我同样有字典管理这个需求，我看您是用一个infoList混入，然后相关页面直接 定义一个data  xxx + Options，然后created周期里调用 getDict(dictCode) 获得字典数据，然后自己组织表单结构来循环，最后filterDict这个方法应该是用在表格数据行列中的回显具体字典名称的方法。

这么做吧，假设我有个客户管理，客户画像N个字段都是字典数据，我就要在created周期里写N次getDict(xxx)，一两个感觉还好，多了就感觉不那么优雅，不知道这里您考虑过更好的方法没有。

我在另一个仓库（没有完全开源的），看见另一个思路，他定义了一个自定义组件，比如<DictSelect>然后prop过去字典code等，在表单里随便调用DictSelect就行，然后直接生成下拉菜单select，或者单选radio，但是还是菜啊，这种我倒是感觉好一点，但是又不知道在表格里怎么回显了，感觉再get一次后台又不优雅了。

### 结尾

并不使用您的项目，我后端是php，纯属是初学vue的我通过您的代码学习借鉴，如果问题打扰到您，不喜欢可以直接close，不过还是期待您的解答。

纯粹是来请教的哈！

**Comment by piexlmax** [comment]
前端如果获取字典 只能拿字典的key去后端获取 我们项目中的get实际上是做了本地缓存的 所有字典只需要请求一次 别的地方再没刷新之前都不需要去后端请求 多次get并不会影响什么性能代码层面可能会多一点 可以自行吧字典功能再封装一个自用组件就好了
