### ISSUE TITLE
设置权限:在tabPane修改权限对应的菜单切换tabpane没有自动保存

### ISSUE THREAD

**Issue by dybxin** [flipped-aurora/gin-vue-admin#628]
### 1. 您使用的是哪个版本的`Go`和系统类型/架构 ?

go version go1.16.6 linux/amd64

### 2. 您使用的是哪个版本的 `Nodejs` 和 `npm` 或 `cnpm` ?

6.14.13

v14.17.0

### 3. 您使用的是哪个版本的 `gin-vue-admin` ?

master

### 4. 可以在master版本中复现此问题吗 ?

可以

### 5. 您做了什么 ?

代码中有相关的保存机制，但是没有生效

```
const autoEnter = (activeName, oldActiveName) => {
      console.log('save', oldActiveName)
      const paneArr = ["menus", "apis", "datas"];
      if (oldActiveName) {
        // 存疑
        if (ctx.$refs[paneArr[oldActiveName]].needConfirm) {
          ctx.$refs[paneArr[oldActiveName]].enterAndNext();
          ctx.$refs[paneArr[oldActiveName]].needConfirm = false;
        }
      }
    };
```

### 6. 您期望看到什么 ?

切换自动保存

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
可以复现 这边会尽快修改

**Comment by dybxin** [comment]
> 可以复现 这边会尽快修改

@piexlmax 您好，这个问题在刚刚发布的版本已经修复了吗？
