### ISSUE TITLE
master自动生成代码错误

### ISSUE THREAD

**Issue by zhaorx** [flipped-aurora/gin-vue-admin#648]
### 3. 您使用的是哪个版本的 `gin-vue-admin` ?
master

### 5. 您做了什么 ?
按照视频说明 建立student struct 生成对应的代码

### 6. 您期望看到什么 ?
生成8个文件 迁移至对应位置

### 7. 您看到了什么 ?
前端工程的3个文件生成并迁移成功；后端的5个文件只生成了.go无名文件，并且目录都是autocode，看起来是没有完成。
![image](https://user-images.githubusercontent.com/13824730/131317628-d9f89c70-e999-4e9e-bac8-b3e2e2251ddd.png)

### 8. 错误堆栈或者SQL打印

**Comment by piexlmax** [comment]
我测试一下 目前master是vue3的测试版 感谢测试bug

**Comment by piexlmax** [comment]
![image](https://user-images.githubusercontent.com/29840023/131367885-fc3ac784-0567-4664-bf79-9596d4b46b0e.png)
未能复现

**Comment by piexlmax** [comment]
如能复现 还请提供一下入参 感谢

**Comment by zhaorx** [comment]
好吧 你们gitee和github的版本不一样 我下的是gitee上的 不好意思
看了下gitee上的GVA中vue版本还是2.6
我试了下github版的master，结果和你一致。
但是我有个疑问，比如后端model中生成的代码都在autocode下，为什么要这么设计？这个位置，肯定不是代码的最终位置吧？
没有别的问题了，issue可以close了

**Comment by zhaorx** [comment]
举个例子，教学视频中的student.go是生成至model目录下的，但是在最新的这版中，生成到了model下的autocode下
