### ISSUE TITLE
用户管理界面点击创建用户有bug

### ISSUE THREAD

**Issue by LRboyz** [flipped-aurora/gin-vue-admin#660]
点击创建之后弹出的modal框一直无法消失，这种重量级bug都没有发现吗

**Comment by piexlmax** [comment]
> 点击创建之后弹出的modal框一直无法消失，这种重量级bug都没有发现吗

master版本为A测版本 稳定版请查看tag 感谢提出bug

**Comment by piexlmax** [comment]
> 点击创建之后弹出的modal框一直无法消失，这种重量级bug都没有发现吗

请问一下 目前版本创建无法关闭的bug是自动化代码的还是其他的模块的

**Comment by piexlmax** [comment]
用户创建 已修复
