### ISSUE TITLE
在线预览502

### ISSUE THREAD

**Issue by ChasteSui** [flipped-aurora/gin-vue-admin#68]
http://qmplus.henrongyi.top/#/login    预览地址
时间：2020年04月24日11:02:50

**Comment by Ruio9244** [comment]
> http://qmplus.henrongyi.top/#/login 预览地址
> 时间：2020年04月24日11:02:50

请问你遇到了什么问题？

**Comment by ChasteSui** [comment]
刚才预览地址报502  现在没问题了 打扰啦
