### ISSUE TITLE
[Feature]: 权限力度控制到CURD

### ISSUE THREAD

**Issue by chenjpu** [flipped-aurora/gin-vue-admin#693]
### 功能描述以及必要性描述

1.满足更细分的权限控制

**Comment by piexlmax** [comment]
请详细描述，需要具体控制到什么层次，如果是按钮层次的话，可以自行使用v-auth标签来控制，已经开发过此功能，文档有所描述。如果需要后端某些字段控制，可以自行开发接口，按钮太多会影响请求效率。

**Comment by piexlmax** [comment]
内部也会讨论更合适的方案来解决此问题

**Comment by halberd-zhao** [comment]
> 请详细描述，需要具体控制到什么层次，如果是按钮层次的话，可以自行使用v-auth标签来控制，已经开发过此功能，文档有所描述。如果需要后端某些字段控制，可以自行开发接口，按钮太多会影响请求效率。

举个例子：

**Comment by shunhua** [comment]
现在好多需求 都是需要用户自定义配置菜单下的按钮使用权限。希望有更好的解决方案。最好能让用户跟配置菜单一样 。

**Comment by Gooooodman** [comment]
是的。没有权限的按钮，不要用户看到。用户会点，没权限又会问。

**Comment by bypanghu** [comment]
此方案已被解决，详情请看 B站视频教学
https://www.bilibili.com/video/BV1kv4y1g7nT?p=11&vd_source=f2640257c21e3b547a790461ed94875e
