### ISSUE TITLE
[Bug]: autocode生成文件并配置菜单成功后，切换不同tab页时空白问题

### ISSUE THREAD

**Issue by longit123** [flipped-aurora/gin-vue-admin#698]
### gin-vue-admin 版本

2.4.5beta

### Node 版本

v14.14.0

### Golang 版本

go.1.16

### 是否依旧存在

可以

### bug描述

用autocode生成文件，在前端网站新增菜单，菜单keepalive设置为“否“，配置权限和api成功后，点开不同的非keepalive菜单后，再点回来，会变成空白页，再点非keepalive菜单也会变成空白页；

试了2.4.4，没有问题

**Comment by piexlmax** [comment]
已收到 测试复现后尽快修复

**Comment by piexlmax** [comment]
无法复现 请联系微信 shouzi_1994 排查
