### ISSUE TITLE
[Bug]: docker-compose up -d报错缺少gcc 安装完并不能解决问题

### ISSUE THREAD

**Issue by xxmt** [flipped-aurora/gin-vue-admin#699]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v12.15.0

### Golang 版本

go1.14.2

### 是否依旧存在

可以

### bug描述

代码克隆下来 直接up就能出现的问题
docker-compose up -d
Building server
[+] Building 25.1s (15/16)
 => [internal] load build definition from Dockerfile                                            0.0s
 => => transferring dockerfile: 544B                                                            0.0s
 => [internal] load .dockerignore                                                               0.0s
 => => transferring context: 2B                                                                 0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                3.9s
 => [internal] load metadata for docker.io/library/golang:alpine                                3.9s
 => [stage-1 1/3] FROM docker.io/library/alpine:latest@sha256:e1c082e3d3c45cccac829840a25941e6  0.0s
 => [stage-0 1/8] FROM docker.io/library/golang:alpine@sha256:13919fb9091f6667cb375d5fdf016ecd  0.0s
 => [internal] load build context                                                               0.2s
 => => transferring context: 27.50kB                                                            0.2s
 => CACHED [stage-1 2/3] WORKDIR /go/src/github.com/flipped-aurora/gin-vue-admin/server         0.0s
 => CACHED [stage-0 2/8] WORKDIR /go/src/github.com/flipped-aurora/gin-vue-admin/server         0.0s
 => CACHED [stage-0 3/8] COPY . .                                                               0.0s
 => CACHED [stage-0 4/8] RUN go env -w GO111MODULE=on                                           0.0s
 => CACHED [stage-0 5/8] RUN go env -w GOPROXY=https://goproxy.cn,direct                        0.0s
 => CACHED [stage-0 6/8] RUN go env                                                             0.0s
 => CACHED [stage-0 7/8] RUN go mod tidy                                                        0.0s
 => ERROR [stage-0 8/8] RUN go build -o server .                                               20.9s
------
 > [stage-0 8/8] RUN go build -o server .:
#15 20.56 # github.com/flipped-aurora/gin-vue-admin/server
#15 20.56 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exec: "gcc": executable file n
ot found in $PATH
#15 20.56
------
executor failed running [/bin/sh -c go build -o server .]: exit code: 2
ERROR: Service 'server' failed to build : Build failed

**Comment by songzhibin97** [comment]
go1.14.2？要求1.16版本

**Comment by xxmt** [comment]
那我试试更新go版本

**Comment by xxmt** [comment]
更新go到1.17.1还是同样的问题

**Comment by SliverHorn** [comment]
> 更新go到1.17.1还是同样的问题

看go env输出内容

**Comment by xxmt** [comment]
$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xmt\AppData\Local\go-build
set GOENV=C:\Users\xmt\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xmt\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xmt\go
set GOPRIVATE=
set GOPROXY=https://mirrors.aliyun.com/goproxy/
set GOROOT=D:\soft\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\soft\go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.17.1
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=NUL
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\xmt\AppData\Local\Temp\go-build2362347061=/tmp/go-build -gno-record-gcc-switches

**Comment by SliverHorn** [comment]
```dockerfile
go env -w GOPROXY=https://goproxy.cn,direct
go env -w CGO_ENABLED=0 # 加下这个
```
