### ISSUE TITLE
数据库发生这种错误

### ISSUE THREAD

**Issue by zhuqiyun** [flipped-aurora/gin-vue-admin#71]
[2020-04-25 15:06:54]  sql: Scan error on column index 7, name "data_authority_id": unsupported Scan, storing driver.Value type []uint8 into type *[]model.SysAuthority

**Comment by granty1** [comment]
> [2020-04-25 15:06:54] sql: Scan error on column index 7, name "data_authority_id": unsupported Scan, storing driver.Value type []uint8 into type *[]model.SysAuthority

Which API did you call triggered the error?

**Comment by piexlmax** [comment]
> [2020-04-25 15:06:54] sql: Scan error on column index 7, name "data_authority_id": unsupported Scan, storing driver.Value type []uint8 into type *[]model.SysAuthority

详细描述复现步骤，或者提交完整后台报错记录，亦可添加微信群发送bug复现过程

**Comment by stanleylfc** [comment]
这个错误我复现了使用Table 方法替代Model的时候
