### ISSUE TITLE
[Bug]: 设置登录状态失败

### ISSUE THREAD

**Issue by green-chives** [flipped-aurora/gin-vue-admin#711]
### gin-vue-admin 版本

2

### Node 版本

14

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

开启 redis 登录之后，偶尔出现 设置登录状态失败

**Comment by songzhibin97** [comment]
请截图失败的前后端Terminal

**Comment by green-chives** [comment]
应该是我这边的问题，go redis引的包不是v8的
