### ISSUE TITLE
[Bug]: 2.4.5Beta npm run serve报错

### ISSUE THREAD

**Issue by WalleDong** [flipped-aurora/gin-vue-admin#714]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

不可以

### bug描述

> gin-vue-admin@2.3.5 serve /root/gin-vue/web
> node openDocument.js && vite --host --mode development

linux

  vite v2.5.3 dev server running at:

  > Local:    http://localhost:8080/
  > Network:  http://192.196.166.180:8080/
  > Network:  http://10.121.216.255:8080/

  ready in 488ms.

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:8080/' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gin-vue-admin@2.3.5 serve: `node openDocument.js && vite --host --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gin-vue-admin@2.3.5 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-16T07_14_10_928Z-debug.log

root@go-env-pod:~/gin-vue/web# cat /root/.npm/_logs/2021-09-16T07_14_10_928Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/node-v14.17.6-linux-x64/bin/node',
1 verbose cli   '/root/node-v14.17.6-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle gin-vue-admin@2.3.5~preserve: gin-vue-admin@2.3.5
6 info lifecycle gin-vue-admin@2.3.5~serve: gin-vue-admin@2.3.5
7 verbose lifecycle gin-vue-admin@2.3.5~serve: unsafe-perm in lifecycle true
8 verbose lifecycle gin-vue-admin@2.3.5~serve: PATH: /root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/gin-vue/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/protoc/bin:/usr/local/go/bin:/root/golib/bin:/root/node-v14.17.6-linux-x64/bin
9 verbose lifecycle gin-vue-admin@2.3.5~serve: CWD: /root/gin-vue/web
10 silly lifecycle gin-vue-admin@2.3.5~serve: Args: [ '-c', 'node openDocument.js && vite --host --mode development' ]
11 silly lifecycle gin-vue-admin@2.3.5~serve: Returned: code: 1  signal: null
12 info lifecycle gin-vue-admin@2.3.5~serve: Failed to exec serve script
13 verbose stack Error: gin-vue-admin@2.3.5 serve: `node openDocument.js && vite --host --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid gin-vue-admin@2.3.5
15 verbose cwd /root/gin-vue/web
16 verbose Linux 5.3.0-45-generic
17 verbose argv "/root/node-v14.17.6-linux-x64/bin/node" "/root/node-v14.17.6-linux-x64/bin/npm" "run" "serve"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error gin-vue-admin@2.3.5 serve: `node openDocument.js && vite --host --mode development`
22 error Exit status 1
23 error Failed at the gin-vue-admin@2.3.5 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by piexlmax** [comment]
请简述复现过程

**Comment by WalleDong** [comment]
按照readme的操作步骤
# 进入web文件夹
cd web

# 安装依赖也是正常的
npm install

# 启动web项目出现上面的报错
npm run serve

后来用了V2.4.4版本，正常使用

**Comment by WalleDong** [comment]
按照readme的操作步骤

1、进入web文件夹
cd web
2、安装依赖也是正常的
npm install
3、启动web项目出现上面的报错
npm run serve

后来用了V2.4.4版本，正常使用

**Comment by piexlmax** [comment]
node openDocument.js && vite --host --mode development 这句话改成 vite --host --mode development 即可 方便说一下你的计算机系统吗  这是打开文档的指令在你的系统上运行不正常导致的

**Comment by WalleDong** [comment]
系统：
Linux 10-143-110-221 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
node:
v14.17.6
npm:
6.14.15

更改了后，还是有问题
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/node-v14.17.6-linux-x64/bin/node',
1 verbose cli   '/root/node-v14.17.6-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle gin-vue-admin@2.3.5~preserve: gin-vue-admin@2.3.5
6 info lifecycle gin-vue-admin@2.3.5~serve: gin-vue-admin@2.3.5
7 verbose lifecycle gin-vue-admin@2.3.5~serve: unsafe-perm in lifecycle true
8 verbose lifecycle gin-vue-admin@2.3.5~serve: PATH: /root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/gin-vue-admin-2.4.5Beta/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/protoc/bin:/usr/local/go/bin:/root/golib/bin:/root/node-v14.17.6-linux-x64/bin
9 verbose lifecycle gin-vue-admin@2.3.5~serve: CWD: /root/gin-vue-admin-2.4.5Beta/web
10 silly lifecycle gin-vue-admin@2.3.5~serve: Args: [ '-c', 'vite --host --mode development' ]
11 silly lifecycle gin-vue-admin@2.3.5~serve: Returned: code: 1  signal: null
12 info lifecycle gin-vue-admin@2.3.5~serve: Failed to exec serve script
13 verbose stack Error: gin-vue-admin@2.3.5 serve: `vite --host --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid gin-vue-admin@2.3.5
15 verbose cwd /root/gin-vue-admin-2.4.5Beta/web
16 verbose Linux 5.3.0-45-generic
17 verbose argv "/root/node-v14.17.6-linux-x64/bin/node" "/root/node-v14.17.6-linux-x64/bin/npm" "run" "serve"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error gin-vue-admin@2.3.5 serve: `vite --host --mode development`
22 error Exit status 1
23 error Failed at the gin-vue-admin@2.3.5 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by WalleDong** [comment]
系统：
Linux 10-xxx-xxx-xxx 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
node:
v14.17.6
npm:
6.14.15

更改了后，还是有问题
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli '/root/node-v14.17.6-linux-x64/bin/node',
1 verbose cli '/root/node-v14.17.6-linux-x64/bin/npm',
1 verbose cli 'run',
1 verbose cli 'serve'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle gin-vue-admin@2.3.5preserve: gin-vue-admin@2.3.5
6 info lifecycle gin-vue-admin@2.3.5serve: gin-vue-admin@2.3.5
7 verbose lifecycle gin-vue-admin@2.3.5serve: unsafe-perm in lifecycle true
8 verbose lifecycle gin-vue-admin@2.3.5serve: PATH: /root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/gin-vue-admin-2.4.5Beta/web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/protoc/bin:/usr/local/go/bin:/root/golib/bin:/root/node-v14.17.6-linux-x64/bin
9 verbose lifecycle gin-vue-admin@2.3.5serve: CWD: /root/gin-vue-admin-2.4.5Beta/web
10 silly lifecycle gin-vue-admin@2.3.5serve: Args: [ '-c', 'vite --host --mode development' ]
11 silly lifecycle gin-vue-admin@2.3.5serve: Returned: code: 1 signal: null
12 info lifecycle gin-vue-admin@2.3.5serve: Failed to exec serve script
13 verbose stack Error: gin-vue-admin@2.3.5 serve: vite --host --mode development
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:400:28)
13 verbose stack at ChildProcess. (/root/node-v14.17.6-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:400:28)
13 verbose stack at maybeClose (internal/child_process.js:1055:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid gin-vue-admin@2.3.5
15 verbose cwd /root/gin-vue-admin-2.4.5Beta/web
16 verbose Linux 5.3.0-45-generic
17 verbose argv "/root/node-v14.17.6-linux-x64/bin/node" "/root/node-v14.17.6-linux-x64/bin/npm" "run" "serve"
18 verbose node v14.17.6
19 verbose npm v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error gin-vue-admin@2.3.5 serve: vite --host --mode development
22 error Exit status 1
23 error Failed at the gin-vue-admin@2.3.5 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by WalleDong** [comment]
用另一套环境问题没出现上面的问题
两套环境的linux内核是区别：
可用环境：**4.15.0-45-generic**
不可用环境：**5.3.0-45-generic**
我不太相信是因为内核不同导致的^^

**Comment by piexlmax** [comment]
> 用另一套环境，没出现上面的问题 两套环境的linux内核是区别： 可用环境：**4.15.0-45-generic** 不可用环境：**5.3.0-45-generic** 我不太相信是因为内核不同导致的^^

 系统执行下 `xdg-open` 命令 这是vite内置会调用的一个命令 如果缺少就会出现此问题

**Comment by sunnnnnner** [comment]
解决办法 在Linux上安装   xdg-open；安装指令： yum install xdg-utils

**Comment by linexjlin** [comment]
还可以 `touch /usr/bin/xdg-open && chmod +x /usr/bin/xdg-open`

**Comment by yifeng01** [comment]
centos 7 系统下  #docker-compose  -f ./docker-compose-dev.yaml  up    一样报 Error: spawn xdg-open ENOENT

**Comment by sharpenHolic** [comment]
### 问题描述

出现同样的问题，按照上方几种办法依然没有解决，执行顺序

```
sudo npm install cnpm@7.1.0 -g --registry=https://registry.npm.taobao.org
cnpm i
npm run serve
```

### system
Linux ubuntu 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### node 
v10.19.0

### golang
go1.20 linux/amd64



### 报错信息

```
12 info lifecycle gin-vue-admin@2.5.5~serve: Failed to exec serve script
13 verbose stack Error: gin-vue-admin@2.5.5 serve: `vite --host --mode development`
```

**Comment by bypanghu** [comment]
说过，不要用淘宝镜像。

**Comment by sharpenHolic** [comment]
解决：  按照https://npmmirror.com/ 修改镜像
谢谢
