### ISSUE TITLE
[Bug]: favicon.ico 更换失败

### ISSUE THREAD

**Issue by walt-white-zhou** [flipped-aurora/gin-vue-admin#715]
### gin-vue-admin 版本

2.3.5

### Node 版本

12.16.1

### Golang 版本

go 1.16.2

### 是否依旧存在

不可以

### bug描述

1.在public目录下更换favicon.ico文件，实际运行并没有更换。
2.有两个文件引入了favicon.ico文件。

### 修改建议

删除public目录，把favicon.ico复制到根目录，保留根目录index.html。

**Comment by piexlmax** [comment]
删除public目录，把favicon.ico复制到根目录，保留根目录index.html。
