### ISSUE TITLE
希望之后 Merge PR时采用 Rebase 或者 Squash

### ISSUE THREAD

**Issue by RainshawGao** [flipped-aurora/gin-vue-admin#717]
### 功能描述以及必要性描述

目前Merge PR时都采用的是 新增一个commit，这样导致 commit 树很杂乱，其他知名的开源项目大多采用 squash/rebase merge 并且每个 commit 只做一件事，这样使得代码历史可读性更好。

现在：
![image](https://user-images.githubusercontent.com/23495403/133868293-e92cd540-2214-4059-a955-76d0d7feca03.png)

其他知名开源项目
Gin:
![image](https://user-images.githubusercontent.com/23495403/133868363-4e727c40-a05c-4385-9a23-7fddb9732f8a.png)

**Comment by piexlmax** [comment]
感谢建议 以后会修改pr合并方式

**Comment by piexlmax** [comment]
以后会尽量采用 Squash 方式 减少无效commit
