### ISSUE TITLE
[Bug]: 使用global.GVA_DB和gorm.open返回的db在复杂where条件下不一样的问题

### ISSUE THREAD

**Issue by longit123** [flipped-aurora/gin-vue-admin#732]
### gin-vue-admin 版本

2.4.5beta

### Node 版本

v14.14.0

### Golang 版本

go.1.16

### 是否依旧存在

可以

### bug描述

第一步：参考gorm官方文档，对于复杂的where条件查询：
[https://gorm.io/zh_CN/docs/advanced_query.html#group_conditions](https://gorm.io/zh_CN/docs/advanced_query.html#group_conditions)

第二步：根据gorm文档，在gva中生成对应的模型和api请求；

第三步：在处理请求的方法中，

一，使用global.GVA_DB的方式：
// 创建db
db := global.GVA_DB.Model(&autocode.Pizza{})
db.Where(
		db.Where("pizza = ?", "pepperoni").Where(db.Where("size = ?", "small").Or("size = ?", "medium")),
	).Or(
		db.Where("pizza = ?", "hawaiian").Where("size = ?", "xlarge"),
	).Find(&autocode.Pizza{})

期望SQL为：
SELECT * FROM `pizzas` WHERE (pizza = "pepperoni" AND (size = "small" OR size = "medium")) OR (pizza = "hawaiian" AND size = "xlarge")

实际SQL为：
```sql
SELECT * FROM `pizzas` WHERE (pizza = "pepperoni" AND size = "small" OR size = "medium" AND (pizza = "pepperoni" AND size = "small" OR size = "medium") AND (pizza = "pepperoni" AND size = "small" OR size = "medium" AND (pizza = "pepperoni" AND size = "small" OR size = "medium")) AND pizza = "hawaiian" AND size = "xlarge" OR (pizza = "pepperoni" AND size = "small" OR size = "medium" AND (pizza = "pepperoni" AND size = "small" OR size = "medium") AND (pizza = "pepperoni" AND size = "small" OR size = "medium" AND (pizza = "pepperoni" AND size = "small" OR size = "medium")) AND pizza = "hawaiian" AND size = "xlarge")) 
```

二，使用gorm.open方式（才是正常结果）

```sql
dsn := "root:123456@tcp(localhost:3306)/gva?charset=utf8&parseTime=True&loc=Local"
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})

db.Where(
		db.Where("pizza = ?", "pepperoni").Where(db.Where("size = ?", "small").Or("size = ?", "medium")),
	).Or(
		db.Where("pizza = ?", "hawaiian").Where("size = ?", "xlarge"),
	).Find(&autocode.Pizza{})
```
这种方式才会生成正常期望的SQL

**Comment by SliverHorn** [comment]
```go
改成这样试下
global.GVA_DB.Where(
db.Where("pizza = ?", "pepperoni").Where(db.Where("size = ?", "small").Or("size = ?", "medium")),
).Or(
db.Where("pizza = ?", "hawaiian").Where("size = ?", "xlarge"),
).Find(&autocode.Pizza{})
```

**Comment by longit123** [comment]
```sql
SELECT * 
FROM
	`pizzas` 
WHERE
	(
		( pizza = "pepperoni" AND size = "small" OR size = "medium" AND ( pizza = "pepperoni" AND size = "small" OR size = "medium" ) ) 
		OR (
			pizza = "pepperoni" 
			AND size = "small" 
			OR size = "medium" 
			AND ( pizza = "pepperoni" AND size = "small" OR size = "medium" ) 
			AND pizza = "hawaiian" 
			AND size = "xlarge" 
		) 
	)
```

> ```go
> 改成这样试下
> global.GVA_DB.Where(
> db.Where("pizza = ?", "pepperoni").Where(db.Where("size = ?", "small").Or("size = ?", "medium")),
> ).Or(
> db.Where("pizza = ?", "hawaiian").Where("size = ?", "xlarge"),
> ).Find(&autocode.Pizza{})
> ```

**Comment by piexlmax** [comment]
db := global.GVA_DB.Model(&autocode.Pizza{})  不要多创建一次 Model
