### ISSUE TITLE
[Bug]: 菜单管理中添加或编辑后点击确定按钮无反应

### ISSUE THREAD

**Issue by lyd0** [flipped-aurora/gin-vue-admin#733]
### gin-vue-admin 版本

 v2.4.5Beta  3183f55

### Node 版本

v14.17.5

### Golang 版本

go1.17 

### 是否依旧存在

未测试

### bug描述

- 尝试添加菜单的时候,  点击确定没有任何反应，应该是elementUI表单验证的问题
- 位于 web/src/view/superAdmin/menu/menu.vue 文件中的enterDialog 方法 ，代码没有进入this.$refs['menuForm'].validate函数。
- 删除验证可以正常添加 

![image](https://user-images.githubusercontent.com/29918052/134617158-c11cef54-148d-47d5-a9bc-e8d88f05b515.png)

![image](https://user-images.githubusercontent.com/29918052/134617130-e6c6390f-baa7-4cb4-a13d-4fc05b931c2f.png)

**Comment by piexlmax** [comment]
新增 检测结果
![image](https://user-images.githubusercontent.com/29840023/134628920-472dabea-9ee6-4c67-a81f-538e6f704633.png)
编辑 检测结果
![image](https://user-images.githubusercontent.com/29840023/134628956-b303513a-d232-4b08-843f-701a461d1ed1.png)
新增 保存结果
![image](https://user-images.githubusercontent.com/29840023/134629285-308909cd-4170-43db-92c8-ef5e41508ecf.png)

编辑 保存结果
![image](https://user-images.githubusercontent.com/29840023/134629258-ca610ab7-7a8b-4ebf-bd39-7f0fc1fadb0d.png)

结论：无法复现
