### ISSUE TITLE
[Bug]:自动生成代码的时候无法移动vue文件 

### ISSUE THREAD

**Issue by xsyzer** [flipped-aurora/gin-vue-admin#735]
### gin-vue-admin 版本

V2.4.5 beta.1

### Node 版本

v14.16.0

### Golang 版本

go 1.15.7

### 是否依旧存在

可以

### bug描述

自动生成代码的时候，显示移动了文件，实际上前端项目里并没有相应的文件
![Snipaste_2021-09-24_13-37-30](https://user-images.githubusercontent.com/53068487/134623714-047eb1d3-1678-41f8-810b-21e5662760bd.png)
后端是有相应的文件
![Snipaste_2021-09-24_13-38-27](https://user-images.githubusercontent.com/53068487/134623798-928f7e24-1e90-4831-9343-aa7c5e936ada.png)

**Comment by xsyzer** [comment]
大意了，前后端文件没在一个文件夹里

**Comment by piexlmax** [comment]
> 大意了，前后端文件没在一个文件夹里

好尴尬 我正在复现 你给关了
