### ISSUE TITLE
[Feature]: 希望在表单生成器里增加图表组件

### ISSUE THREAD

**Issue by bingLAN** [flipped-aurora/gin-vue-admin#741]
### 功能描述以及必要性描述

1.图表组件也是常用组件，会使自动化组件功能更加丰富。

**Comment by piexlmax** [comment]
图表是指的echart？

**Comment by bingLAN** [comment]
> 图表是指的echart？

是的，饼状图，柱状图，折线图，这些也是常用的

**Comment by piexlmax** [comment]
这个功能表单生成器无法满足 需要自己引入外部三方工具配置参数
