### ISSUE TITLE
[Bug]: 登录成功后，点击栏目没有任何反应

### ISSUE THREAD

**Issue by lowmanisbusy** [flipped-aurora/gin-vue-admin#748]
### gin-vue-admin 版本

V2.4.5 beta.1 （master 分支最新代码）

### Node 版本

v16.10.0 

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述
首先：后端和前端项目已经运行起来，也完成了数据库初始化
然后：登录后，点击左边栏目没有任何反应，后端项目及前端项目的运行没有抛出任何异常。后端有请求菜单栏数据的日志，说明正常情况下，前端的请求可以达到后端
但是：通过 f12 查看，发现如下异常。是我哪里配置没对，还是什么原因，请大佬指教，感谢！

runtime-core.esm-bundler.js:6731 Uncaught TypeError: Cannot read property 'parameters' of undefined
    at Proxy.selectMenuItem (index.vue:69)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6668)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6677)
    at emit$1 (runtime-core.esm-bundler.js:252)
    at runtime-core.esm-bundler.js:6453
    at Proxy.handleMenuItemClick (index.js:526)
    at Proxy.handleClick (index.js:714)
    at createElementBlock.onClick._cache.<computed>._cache.<computed> (index.js:761)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6668)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6677)

**Comment by chimojiacai** [comment]
同问,遇到了一样的问题.
maker一下

**Comment by piexlmax** [comment]
已收到问题 本地无法复现 根据代码分析 问题出在 菜单的routerInfo 如果方便请添加我weixin shouzi_1994 方便 排查原因

**Comment by piexlmax** [comment]
已根据描述做出调整

修改方案
/web/src/view/layout/aside/index.vue文件下的selectMenuItem 添加 `?.`  用于短路避险
```javascript


   selectMenuItem(index, _, ele) {
      const query = {}
      const params = {}
      ele?.route?.parameters &&
      ele.route.parameters.forEach(item => {
        if (item.type === 'query') {
          query[item.key] = item.value
        } else {
          params[item.key] = item.value
        }
      })
      if (index === this.$route.name) return
      if (index.indexOf('http://') > -1 || index.indexOf('https://') > -1) {
        window.open(index)
      } else {
        this.$router.push({ name: index, query, params })
      }
    }

```

**Comment by lowmanisbusy** [comment]
> 已根据描述做出调整
> 
> 修改方案 /web/src/view/layout/aside/index.vue文件下的selectMenuItem 添加 `?.` 用于短路避险
> 
> ```js
>    selectMenuItem(index, _, ele) {
>       const query = {}
>       const params = {}
>       ele?.route?.parameters &&
>       ele.route.parameters.forEach(item => {
>         if (item.type === 'query') {
>           query[item.key] = item.value
>         } else {
>           params[item.key] = item.value
>         }
>       })
>       if (index === this.$route.name) return
>       if (index.indexOf('http://') > -1 || index.indexOf('https://') > -1) {
>         window.open(index)
>       } else {
>         this.$router.push({ name: index, query, params })
>       }
>     }
> ```

拉取 master 代码 #752 后没有再复现该问题，左侧栏目可以正常点击并打开
