### ISSUE TITLE
[Bug]: 登陆后台时遇到问题

### ISSUE THREAD

**Issue by WalleDong** [flipped-aurora/gin-vue-admin#755]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16.0

### Golang 版本

1.16

### 是否依旧存在

可以

### bug描述

本地调试可以正常登录
部署在阿里云的docker后，登陆遇到问题
2021/10/02 08:55:28 [Recovery] 2021/10/02 - 08:55:28 panic recovered:
POST /base/login HTTP/1.0
Host: 121.xxx.xxx.xxx:8080
Connection: close
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Connection: close
Content-Length: 94
Content-Type: application/json
Origin: http://121.xxx.xxx.xxx:8080
Referer: http://121.xxx.xxx.xxx:8080/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
X-Forwarded-For: 180.xxx.xxx.xxx
X-Forwarded-Proto: http
X-Real-Ip: 180.xxx.xxx.xxx
X-Token: 
X-User-Id: undefined

runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0x4493e6)
/usr/local/go/src/runtime/signal_unix.go:735 (0x4493b6)
/go/pkg/mod/gorm.io/gorm@v1.20.7/gorm.go:285 (0x8eadf8)
/go/pkg/mod/gorm.io/gorm@v1.20.7/chainable_api.go:145 (0x8e2efb)
/go/src/github.com/flipped-aurora/gin-vue-admin/server/service/system/sys_user.go:44 (0xc2dcd0)
        (*UserService).Login: err = global.GVA_DB.Where("username = ? AND password = ?", u.Username, u.Password).Preload("Authorities").Preload("Authority").First(&user).Error
/go/src/github.com/flipped-aurora/gin-vue-admin/server/api/v1/system/sys_user.go:36 (0xd591fd)
        (*BaseApi).Login: if err, user := userService.Login(u); err != nil {
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa8b9da)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xa8b9c6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa8ace6)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xa8acc9)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xa8a224)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0xa89e59)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xa89993)
/usr/local/go/src/net/http/server.go:2878 (0x6f4f3a)
/usr/local/go/src/net/http/server.go:1929 (0x6f05e7)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x4640c0)

[GIN] 2021/10/02 - 08:55:28 | 500 |     461.475µs | 180.171.187.196 | POST     "/base/login"
[GIN] 2021/10/02 - 08:55:28 | 200 |    3.014869ms | 180.171.187.196 | POST     "/base/captcha"

**Comment by WalleDong** [comment]
数据库白名单没有配置

**Comment by xxmt** [comment]
如何配置的呢 我也是遇到了这个问题

**Comment by xxmt** [comment]
我本地都遇到这个问题
