### ISSUE TITLE
[Bug]: server/initialize/router.go

### ISSUE THREAD

**Issue by SliverHorn** [flipped-aurora/gin-vue-admin#768]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16.0

### Golang 版本

go version go1.16 darwin/amd64

### 是否依旧存在

可以

### bug描述

1. web项目打包 npm run build 得到的是dist文件夹
```
dist
└── assets
└── index.html

```
2. [server/initialize/router.go](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/initialize/router.go#L26) 中的 static 文件夹是不存在的

### 修改建议

- [server/initialize/router.go](https://github.com/flipped-aurora/gin-vue-admin/blob/master/server/initialize/router.go#L26) 中的 static 修改为assets

**Comment by Jexbat** [comment]
``` go
 Router.Static("/static", "./dist/assets")   // dist里面的静态资源
```
需要修改成：
``` go
Router.Static("/assets", "./dist/assets")   // dist里面的静态资源
```
否则前端无法加载
