### ISSUE TITLE
关于Api的疑惑

### ISSUE THREAD

**Issue by kessil** [flipped-aurora/gin-vue-admin#78]
**首先感谢团队的开源项目！**
体验自动生成代码功能过程中发现： 更新记录时提示“没有权限”，查看API，前端使用“PUT”更新方法，后端添加的更新方法是“POST”，这里应该是一个bug。

另外想问所有API都带有谓语 (*貌似RESTful不提倡*)，出于何种考虑采用带谓语的API而不是如下形式
```
POST /posts
GET /posts
GET /posts/:id
POST /posts/:id
PUT /posts/:id
DELETE /posts/:id
```
初学者一枚，望作者指点迷津

**Comment by granty1** [comment]
1. 在代码生成器的模板：[router.go.tpl](https://github.com/flipped-aurora/gin-vue-admin/blob/303532aff253d007e649feae11693d1663a94fd9/server/resource/template/te/router.go.tpl#L14)中Update对应的方法为PUT，你的代码是否为最新的呢？
2. 对于RESTful只是一种编码风格，在[exp_customer.go](https://github.com/flipped-aurora/gin-vue-admin/blob/303532aff253d007e649feae11693d1663a94fd9/server/router/exp_customer.go#L9)中我们提供了示例代码。

**Comment by kessil** [comment]
api/v1/autocode.go的加入数据库的更新方法是POST，应改为PUT吧

**Comment by piexlmax** [comment]
> api/v1/autocode.go的加入数据库的更新方法是POST，应改为PUT吧。还有获取列表的分组为什么和其他的不一样呢？

当前项目底层并不是按照restful进行开发的 主要考虑的是开发效率问题 但是本框架支持restful模式 具体还看个人选择和喜好
