### ISSUE TITLE
[Feature]: 表单生成器增强: 支持从结构体的字段中拖入设计区域

### ISSUE THREAD

**Issue by Hi-Alan** [flipped-aurora/gin-vue-admin#789]
### 功能描述以及必要性描述

1. 表单生成器支持从结构体的字段中拖入设计区域.
1.1 自动带入如下属性: 标签, 字段名, 控件类型
1.2 自动生成如下代码: 字典数据的获取
2. 表单属性可设置(设计模式下)默认控件的栅格大小, 用户只调整个别特殊控件

**Comment by piexlmax** [comment]
表单生成器采用其他开源产品 https://github.com/JakHuang/form-generator
