### ISSUE TITLE
admin2  视频中演示的 sex 表单 前端不展示男女， 

### ISSUE THREAD

**Issue by tx991020** [flipped-aurora/gin-vue-admin#79]
![image](https://user-images.githubusercontent.com/12123206/81034139-ba64e800-8ec8-11ea-8447-7d66daa2fe54.png)

**Comment by piexlmax** [comment]
由于性别是属于字典型 所以需要自己进行scope.row字典匹配 例如如下写法

`
<el-table-column label="性别" prop="sex" width="120">
       <template slot-scope="scope">
         <div>
           {{scope.row.sex}}
         </div>
       </template>
     </el-table-column>
`
