### ISSUE TITLE
[Bug]: 字典型下拉列表自动生成代码时默认值为0，应为 undefined

### ISSUE THREAD

**Issue by YCF** [flipped-aurora/gin-vue-admin#792]
### gin-vue-admin 版本

2.34.5

### Node 版本

v13.14

### Golang 版本

go 1.17.2

### 是否依旧存在

可以

### bug描述

1.使用代码自动生成器，设置一个字典型的下拉列表。使用自动生成代码时，对应下拉列表会始终以0为默认值。

快速复现：
1.使用代码生成器，设置临时设置一个下拉列表为字典类型，点“预览代码”，查看"web-form"和"web-table"代码，查看 vue 中 data 部分的 `formData`，对应下拉列表的值为0。

### 修改建议

未能找到自动生成器这部分的代码，建议修改该默认值为 `undefined`

**Comment by piexlmax** [comment]
字典为int类型 此处自动化生成无法规定为int外类型 建议字典值从0开始设置 感谢提交issue

**Comment by YCF** [comment]
@piexlmax 可以按以下方法修正：

1. /server/resource/template/web/form.vue.tpl#L66

from

```
{{.FieldJson}}: 0,
```
to
```
 {{.FieldJson}}: {{- if .DictType }} undefined {{ else }} 0 {{- end }},
```

2./server/resource/template/web/table.vue.tpl#L161

同样方法。

**Comment by piexlmax** [comment]
感谢提出解决方案测试通过后将会采纳
