### ISSUE TITLE
[Bug]: 登陆界面验证码长度验证 hard code 与后端可配置项矛盾

### ISSUE THREAD

**Issue by YCF** [flipped-aurora/gin-vue-admin#794]
### gin-vue-admin 版本

2.4.5

### Node 版本

v13.14

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

1.在系统配置中将验证码长度设置为5位或6位以上（不含）
2.重启应用
3.登陆界面显示“验证码格式不正确”。

经代码确认，在 https://github.com/flipped-aurora/gin-vue-admin/blob/master/web/src/view/login/index.vue#L127 中存在hard code。

修改后，用4位验证码成功登陆。

### 修改建议

清楚前端验证码长度验证规则或放宽长度到4位以上。

**Comment by piexlmax** [comment]
可调整为4位以上的配置 此处涉及到部分定制化内容 不是很容易把控用户的设置范围

**Comment by piexlmax** [comment]
fixed
