### ISSUE TITLE
[Feature]希望新增 对 postgreSQL数据库的支持

### ISSUE THREAD

**Issue by kotlin2018** [flipped-aurora/gin-vue-admin#797]
### 功能描述以及必要性描述

1、支持 postgreSQL数据库

### 建议和方案

* 1、基于 postgreSQL 数据库的自动代码生成，建议参考 beego/orm 和 xorm/gen

**Comment by piexlmax** [comment]
正在做

**Comment by piexlmax** [comment]
已支持
