### ISSUE TITLE
[Bug]: 在“自动化代码(复用)” 页面中编辑现有字段，数据库字段类型候选列表丢失

### ISSUE THREAD

**Issue by JorinChi** [flipped-aurora/gin-vue-admin#798]
### gin-vue-admin 版本

2.4.6 Apache

### Node 版本

v14.16.0

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

1. 在“自动化代码管理”中回滚一个结构体
2. 点击“复用”，打开“自动化代码(复用)”页面
3. 点击现有字段后的“编辑”
4. 在不更改 Field数据类型 的情况下，数据库字段类型下拉菜单中显示“无数据”。
5. 更改一次Field数据类型 然后再改回原来的，下拉菜单中的内容就又回来了。

**Comment by piexlmax** [comment]
感谢issue 复现后修复

**Comment by piexlmax** [comment]
已修复 测试成功后劳烦关闭issue

**Comment by JorinChi** [comment]
已测试，感谢修复。
