### ISSUE TITLE
[Bug]: Mac版的360极速浏览器 前端页面全部无法显示

### ISSUE THREAD

**Issue by godzeo** [flipped-aurora/gin-vue-admin#799]
### gin-vue-admin 版本

2.4.5

### Node 版本

14.16

### Golang 版本

1.17

### 是否依旧存在

可以

### bug描述

Mac版的 360极速浏览器 12.2.1652.0 前端页面全部无法显示，全部是灰色的。其他浏览器没有问题

Mac版的 360极速浏览器 12.2.1652.0 

![image](https://user-images.githubusercontent.com/64398024/141676850-912411b8-38bf-4a51-a4ce-8ee0adfae036.png)

**Comment by piexlmax** [comment]
vue3 不支持
