### ISSUE TITLE
[Bug]: m1 mac 下IOMasterPort用不了

### ISSUE THREAD

**Issue by hkshawn** [flipped-aurora/gin-vue-admin#803]
### gin-vue-admin 版本

2.4.6

### Node 版本

17.0.1

### Golang 版本

1..17.2

### 是否依旧存在

可以

### bug描述

# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here

**Comment by piexlmax** [comment]
请提供详细复现步骤

**Comment by hkshawn** [comment]
得到群主大佬指点,我这是cgo没打开导致的

**Comment by jiangzhikele** [comment]
大佬，这个是怎么解决的啊？

**Comment by denghuachengle** [comment]
您好 能协助看下吗，我的CGO是打开的 但是还是跟你一样的错误 求助！ @hkshawn

**Comment by denghuachengle** [comment]
qq: 3067244185

**Comment by zinwalin** [comment]
> 得到群主大佬指点,我这是cgo没打开导致的

能分享下怎么解决这个warning的吗？

**Comment by zealyong** [comment]
> 您好 能协助看下吗，我的CGO是打开的 但是还是跟你一样的错误 求助！ @hkshawn

go env -w CGO_ENABLED="0"
