### ISSUE TITLE
[Feature]: 首次登陆不需要填写验证码

### ISSUE THREAD

**Issue by YCF** [flipped-aurora/gin-vue-admin#807]
### 功能描述以及必要性描述

毕竟验证码是用于防密码穷举爆破的，首次登陆就要输入体验较差。

### 建议和方案

根据来源ip，一段时间内没有密码重试错误日志就不用验证码。

**Comment by loveplxf** [comment]
同样需求

**Comment by supine-win** [comment]
这种自己改一下不就行了...

**Comment by piexlmax** [comment]
可做

**Comment by snans** [comment]
> 可做

按照目前全国的网络安全防护要求，肯定是每次打开都需要有验证码，否则等保通不过，如果要新增这个功能，只能拜托肥宅给个开通或不开通的选项啊。

**Comment by ismdeep** [comment]
可以这样做：通过配置项表示默认是否启用“首次登陆不需要填写验证码”功能，当有等保要求的情况下，修改一下配置即可。

**Comment by piexlmax** [comment]
已可配置，且可自行控制是否启用，另外我不胖，假肥宅。新年快乐！
