### ISSUE TITLE
[Bug]: closeTab不起作用

### ISSUE THREAD

**Issue by zinwalin** [flipped-aurora/gin-vue-admin#810]
### gin-vue-admin 版本

master 182bb75

### Node 版本

v17.0.1

### Golang 版本

go1.17.2

### 是否依旧存在

可以

### bug描述

为某些菜单开启clostTab功能后，按浏览器的返回按钮， 标签没有自动关闭。

**Comment by piexlmax** [comment]
已可复现

**Comment by piexlmax** [comment]
fixed:https://github.com/flipped-aurora/gin-vue-admin/commit/a3cb0a530e810b7f620bb3e5a483538bf9f08242
