### ISSUE TITLE
[Bug]: API设置问题

### ISSUE THREAD

**Issue by 204065248** [flipped-aurora/gin-vue-admin#812]
### gin-vue-admin 版本

V2.4.0

### Node 版本

v14.16.1

### Golang 版本

go1.17.3 windows/amd64

### 是否依旧存在

未测试

### bug描述

图一：

![BT7DJ6 JBRKWT`18PP5D)Y7](https://user-images.githubusercontent.com/17307843/142985213-b878d71f-586c-4e1f-b1b1-d72f5d399ceb.png)

图二：

![image](https://user-images.githubusercontent.com/17307843/142985354-c460fcb0-50fa-4fbc-b958-2b9a52673a30.png)

赋予角色上图三个权限 也提示成功了。图一的问题是两个API一个设置成功了一个没成功，但是不管成没成功实际都没权限。
图二设置也提示成功，但是显示没权限，但是实际上是有权限。

**Comment by SliverHorn** [comment]
是不是设置错角色了？

**Comment by 204065248** [comment]
> 是不是设置错角色了？

我解决了，我自己的原因
