### ISSUE TITLE
[Bug]: Security Issues

### ISSUE THREAD

**Issue by Tom4t0** [flipped-aurora/gin-vue-admin#813]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16.0

### Golang 版本

go1.16

### 是否依旧存在

可以

### bug描述

发现了一个安全漏洞，已经通过邮箱联系你。

### 修改建议

很好修复

**Comment by piexlmax** [comment]
感谢提交安全漏洞 已在#811修复
