### ISSUE TITLE
[Bug]: 自动生成文件名带下划线，编译不通过

### ISSUE THREAD

**Issue by yxhlcl** [flipped-aurora/gin-vue-admin#824]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.17.4

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

自动生成代码表单中，文件名s使用驼峰命名，实际生成的文件名是下划线，导致编译不通过，改成驼峰命名，可以通过

**Comment by piexlmax** [comment]
不要使用大写开头
