### ISSUE TITLE
[Bug]: 后端请求时间有点长后前端报错Error: socket hang up

### ISSUE THREAD

**Issue by RaymondNY** [flipped-aurora/gin-vue-admin#828]
### gin-vue-admin 版本

master

### Node 版本

v14.16

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

1.后端如果有接口处理时间大于20S。
![image](https://user-images.githubusercontent.com/18241498/144781773-6567b518-37c8-4a26-b74a-c85aa5fac4e1.png)
2.前端就无法处理，可是后端的接口已经返回了。
![image](https://user-images.githubusercontent.com/18241498/144781835-2ad48833-bfd2-479e-b3a5-4665e74cd3fd.png)
![image](https://user-images.githubusercontent.com/18241498/144781877-8953d416-12a7-42cb-86ff-004efd008e11.png)

### 修改建议

希望大佬查看下

**Comment by songzhibin97** [comment]
修改前端超时时间

**Comment by RaymondNY** [comment]
> 修改前端超时时间

axios.create里默认是timeout: 999999。20秒的接口在999秒范围呢，可依旧没有生效

**Comment by RaymondNY** [comment]
是我理解错了

**Comment by RaymondNY** [comment]
后端21秒处理完了，也成功返回。可请求还一直pending

**Comment by piexlmax** [comment]
后端默认超时时间为20S

**Comment by sx-zyf-123** [comment]
请问解决了么，我也遇到了这个问题，服务端日志显示返回200，但是接口返回的是500

**Comment by reliejiayou** [comment]
> 请问解决了么，我也遇到了这个问题，服务端日志显示返回200，但是接口返回的是500

怀疑是node的问题，不用node启动前端，改为构建前端后由nginx代理，则无该报错。
