### ISSUE TITLE
[Bug]: 代码生成器：文件名首字母限定小写 然后 前后trim不能传入空格

### ISSUE THREAD

**Issue by liu2015** [flipped-aurora/gin-vue-admin#838]
### gin-vue-admin 版本

2.4.6

### Node 版本

node-v16.13.1-x64

### Golang 版本

1.74

### 是否依旧存在

可以

### bug描述

功能描述以及必要性描述
代码生成器 文件名首字母限定小写 然后 前后trim不能传入空，
使用从数据库创建代码，选择数据库，选择表名，自动带出的 简称：不能与结构体名字重复。还有文件名应该是小写开头。
![03df7e3020ba6e06ebfc4b3cf173004](https://user-images.githubusercontent.com/11133364/145764950-17948cae-7f00-45ec-b339-3fbd5b1dacaa.png)

建议和方案
既然是自动带出的内容，应该是符合定义并且正确的建议。
懒人模式，既然是你的建议，我自动生成，就不打算做任何改动，遵从默认最合适。

**Comment by piexlmax** [comment]
#839
