### ISSUE TITLE
BreakpointContinue

### ISSUE THREAD

**Issue by shanhuijie** [flipped-aurora/gin-vue-admin#84]
文件断点续传是不是还没有做完整，是不是要判断文件整个上传完成之后把文件切片删除。

**Comment by piexlmax** [comment]
> 文件断点续传是不是还没有做完整，是不是要判断文件整个上传完成之后把文件切片删除。

当前是判断了切片数量以后才会清除切片的，V2版本是完善的 前端每次要上传文件之前是有md5的 然后 后端这边保存了现有切片和总文件的md5对应挂钩 前端会获取到后端的切片数量 然后判断切片位置 进行续传 这个功能把压力放在前端进行 为了减少服务器压力 是鉴于当前项目环境是小水管的一个偏门解决方案
