### ISSUE TITLE
[Bug]: docker运行出现问题

### ISSUE THREAD

**Issue by cicada-cn** [flipped-aurora/gin-vue-admin#843]
### gin-vue-admin 版本

2.4.5

### Node 版本

12.16.1

### Golang 版本

golang:alpine

### 是否依旧存在

可以

### bug描述

docker compose up
![image](https://user-images.githubusercontent.com/49928866/146299350-fe455eb2-b088-4a91-b5ce-efa61c9d8218.png)

**Comment by cicada-cn** [comment]
可以啦~ 谢谢 :)

**Comment by piexlmax** [comment]
目前依赖已经锁死，vite最新版本出了较多坑。
