### ISSUE TITLE
[Feature]: 不知道是否会增加工作流内容

### ISSUE THREAD

**Issue by loveplxf** [flipped-aurora/gin-vue-admin#844]
### 功能描述以及必要性描述

扩充系统功能，成为豪华跑车

**Comment by piexlmax** [comment]
工作流在旧版本中提供过，由于维护成本太大所以选择的取消，如果有兴趣可以从旧版本进行移植，可以查看分支https://github.com/flipped-aurora/gin-vue-admin/tree/gva_workflow
