### ISSUE TITLE
[Bug]: 代码生成器创建field，数据库字段类型问题

### ISSUE THREAD

**Issue by admi2u** [flipped-aurora/gin-vue-admin#847]
### gin-vue-admin 版本

v2.4.5

### Node 版本

v14.18.2

### Golang 版本

go1.17.5

### 是否依旧存在

可以

### bug描述

使用代码生成器创建field时，是否支持数据库的text类型和foreign key类型？并无“数据库字段类型”选项可以选择。
![image](https://user-images.githubusercontent.com/36391186/146715015-9b343c0a-c165-4da2-af97-d1a3c47af92b.png)

**Comment by piexlmax** [comment]
由于数据库类型定义会产生一些未知bug导致整体项目崩溃 因此暂时选择取消 如果需要配置可以参考gorm文档为gorm的tag设置type属性

**Comment by admi2u** [comment]
好的，谢谢
