### ISSUE TITLE
[Feature]: 请教一个问题

### ISSUE THREAD

**Issue by xzhaha123** [flipped-aurora/gin-vue-admin#851]
### 功能描述以及必要性描述

通过循环去根据不同的条件查询数据时，前面循环中的查询条件也会带上，请问如何解决

**Comment by piexlmax** [comment]
每次循环都是用新的model而不是使用之前返回的model

**Comment by xzhaha123** [comment]
> 每次循环都是用新的model而不是使用之前返回的model

是的，但是有一些公用的前置条件，就得全部再写一遍了。
