### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by insomniasary** [flipped-aurora/gin-vue-admin#852]
### gin-vue-admin 版本

V2.4.6 Beta

### Node 版本

v14.16.0

### Golang 版本

go 1.1.7

### 是否依旧存在

可以

### bug描述

# #
server/source/system/casbin.go 的adapter.CasbinRule初始化Ptype写成PType
> 

### 修改建议

更新一下呗~

**Comment by piexlmax** [comment]
server/source/system/casbin.go 的adapter.CasbinRule初始化Ptype写成PType  此bug是由于自行更改了casbin-adapter版本导致 项目中已经锁定了casbin版本不做调整
