### ISSUE TITLE
[Bug]: 所有页面下拉选择框显示异常

### ISSUE THREAD

**Issue by sycki** [flipped-aurora/gin-vue-admin#853]
### gin-vue-admin 版本

v2.4.6Beta

### Node 版本

v12.18.3

### Golang 版本

go1.17

### 是否依旧存在

可以

### bug描述

- 该问题一直存在，且可以在任意包含 选择框（el-select组件） 的页面复现，下图以[api管理页面](https://demo.gin-vue-admin.com/#/layout/admin/api)为例。
- 每个选择框末尾的箭头按钮，显示位置偏上，但该[el-select组件](https://element-plus.gitee.io/zh-CN/component/select.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95)在ElementPlus官方文档中是正常的，所以我认为这是个问题，一定程度上影响了使用体验，望前端同学给予评估和修复，感谢！

    ![image](https://user-images.githubusercontent.com/18598448/147387858-d9ac5bae-e4d9-467d-836b-1b659ea26c67.png)

**Comment by piexlmax** [comment]
已复现

**Comment by piexlmax** [comment]
已修复
