### ISSUE TITLE
[Bug]: 所有页面日期范围选择框显示异常

### ISSUE THREAD

**Issue by sycki** [flipped-aurora/gin-vue-admin#854]
### gin-vue-admin 版本

2.4.6Beta

### Node 版本

v12.18.3

### Golang 版本

go1.17

### 是否依旧存在

可以

### bug描述

- 该问题一直存在，且可以在任意包含 日期范围选择框（el-date-picker组件） 的页面复现
- 为方便前端同学复现该问题，我在api管理页面（在其它页面都可以）手动增加一个 日期范围选择框，代码如下：
在该项目的前端文件中增加如下代码`src/view/superAdmin/api/api.vue`
```
<template>
  <div>
    <div class="gva-search-box">
      <el-form ref="searchForm" :inline="true" :model="searchInfo">
        <!-- 此处插入一个el-date-picker组件 -->
        <el-form-item label="日期范围:">
          <el-date-picker
            style="width: 300px;"
            v-model="dateRange"
            type="daterange"
            size="large"
            range-separator="至"
            start-placeholder="开始日期"
            end-placeholder="结束日期">
          </el-date-picker>
        </el-form-item>
        <el-form-item label="路径">
          <el-input v-model="searchInfo.path" placeholder="路径" />
        </el-form-item>
...后面省略...
```
- 此时，页面显示如下图，选择框中间的 `至` 字，显示位置偏下，但该[el-date-picker组件](https://element-plus.gitee.io/zh-CN/component/date-picker.html#%E9%80%89%E6%8B%A9%E6%9C%88%E4%BB%BD%E8%8C%83%E5%9B%B4)在ElementPlus官方文档中是正常的，该问题比较影响用户体验，望前端同学给予评估和修复，感谢！

![image](https://user-images.githubusercontent.com/18598448/147388320-2673626e-e58b-4b74-ba21-430aba4659e4.png)

**Comment by piexlmax** [comment]
已复现

**Comment by piexlmax** [comment]
已修复
