### ISSUE TITLE
[Bug]: 页面左侧菜单底部显示异常

### ISSUE THREAD

**Issue by sycki** [flipped-aurora/gin-vue-admin#855]
### gin-vue-admin 版本

2.4.6Beta

### Node 版本

v12.18.3

### Golang 版本

go1.17

### 是否依旧存在

可以

### bug描述

该问题在最近的版本中出现，在之前的V2.4.5Beta版本中没有此问题，我的使用浏览器版本为`Chrome 96.0.4664.110`，复现步骤如下：
1. 登录V2.4.6Beta版本的GVA，点击并展开左侧的超级管理员菜单。
2. 将左侧的菜单滚到到底部，即可看到菜单尾部出现空白。

![image](https://user-images.githubusercontent.com/18598448/147388443-753962f5-ce23-42cc-8450-ddc401a79cea.png)

**Comment by piexlmax** [comment]
已复现

**Comment by piexlmax** [comment]
已修复
