### ISSUE TITLE
[Bug]: api管理根据id排序，会出现报错

### ISSUE THREAD

**Issue by georgezhangjiacheng** [flipped-aurora/gin-vue-admin#859]
### gin-vue-admin 版本

2.4.6

### Node 版本

v12.18.2

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

https://demo.gin-vue-admin.com/api/api/getApiList
该接口在使用的时候如果前端页面”api管理“ 点击以id排序，那么传入的参数orderKey: "ID"，会导致后端查询错误
报错的sql为：SELECT * FROM `sys_apis` WHERE `sys_apis`.`deleted_at` IS NULL ORDER BY  LIMIT 10
![image](https://user-images.githubusercontent.com/49780609/147622264-f9d33bbc-7eec-4541-be96-ed3eec2372c2.png)
![image](https://user-images.githubusercontent.com/49780609/147622275-2dcac455-da45-4cd1-a022-e94ebcbca681.png)

### 修改建议

后端判断的方案为小写的”id“，应该修改前端body传入参数为orderKey: "id"
![image](https://user-images.githubusercontent.com/49780609/147622290-3d294896-5f1f-470d-99a9-cafc609a4851.png)

**Comment by piexlmax** [comment]
感谢提交issue，我们复现后会尽快修复。
