### ISSUE TITLE
希望提供 Validator 校验器功能

### ISSUE THREAD

**Issue by MuRongXiaoDouBi** [flipped-aurora/gin-vue-admin#86]
希望提供 Validator 校验器功能，此功能在参数校验时比较有用，此功能可以在参数与规则不匹配时，直接抛出错误信息

**Comment by granty1** [comment]
在 [verify](https://github.com/flipped-aurora/gin-vue-admin/tree/verify)  分支已经在完善该动能，你可以切换查看一下代码，并且欢迎提出任何建议！

**Comment by MuRongXiaoDouBi** [comment]
看了源码后，是不是不支持自定义检验规则，比如我想判断两次的密码是否相等

**Comment by granty1** [comment]
目前该分支还在开发中，你的想法或建议可以描述的具体一点，我们在开发时会考虑的。

**Comment by MuRongXiaoDouBi** [comment]
好的，我整理一下具体想法，在此issue直接回复

**Comment by piexlmax** [comment]
> 好的，我整理一下具体想法，在此issue直接回复

自定义校验功能这里可以提供方法，当前是提供很多简单组合可以自行拼接，后期会增加例如电话校验 邮件校验等 具体可自行组合

**Comment by MuRongXiaoDouBi** [comment]
#### 检验规则可否复用
例如 `gin-vue-admin/server/api/v1/sys_api.go/` 文件下 `CreateApi` 方法中的 `ApiVerify` 内的所有校验规则可否提取出来复用。如果可以复用，Rules的key可否自定义别名，比如：一个校验规则下有 `id` 字段，另一个需要校验的参数里有个 `uid` 字段，`uid` 与 `id` 字段的校验规则完全一样，可否将 `uid` 设置别名为 `id` ，并使用 `id` 的校验规则

**Comment by piexlmax** [comment]
> #### 检验规则可否复用
> 例如 `gin-vue-admin/server/api/v1/sys_api.go/` 文件下 `CreateApi` 方法中的 `ApiVerify` 内的所有校验规则可否提取出来复用。如果可以复用，Rules的key可否自定义别名，比如：一个校验规则下有 `id` 字段，另一个需要校验的参数里有个 `uid` 字段，`uid` 与 `id` 字段的校验规则完全一样，可否将 `uid` 设置别名为 `id` ，并使用 `id` 的校验规则

提议很棒 可以研究
