### ISSUE TITLE
[Bug]:前端vue获取图片路径错误

### ISSUE THREAD

**Issue by banana1024** [flipped-aurora/gin-vue-admin#863]
### gin-vue-admin 版本

2.4.6

### Node 版本

v14.18.2

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

想修改头像
![image](https://user-images.githubusercontent.com/47801606/147826153-394a7378-8b38-4c12-a386-bd5355fa7ae9.png)
自己上传图片后
![image](https://user-images.githubusercontent.com/47801606/147827957-c1de8e17-7830-4bc7-9eca-27ad7a581fe8.png)
媒体库显示如下：
![image](https://user-images.githubusercontent.com/47801606/147825997-2f0d9e1b-0d08-4a73-a81a-6c45212dcc0c.png)

浏览器F12后控制台报错如下：

GET http://xxx.xxx.xxx.xxx:8080/undefineduploads/file/96d6f2e7e1f705ab5e59c84a6dc009b2_20211231152344.png 404 (Not Found)

问题出在web/components/chooselmg/index.vue

第八行 :src="(item.url && item.url.slice(0, 4) !== 'http')?path+item.url:item.url"

**Comment by piexlmax** [comment]
已修复
