### ISSUE TITLE
建议加一个增删改查的例子，比如文章的例子，以供更多的小白可以用起来

### ISSUE THREAD

**Issue by lujscn** [flipped-aurora/gin-vue-admin#87]
本人是做后端的，对VUE语法只是略懂皮毛，打开了gin-vue-admin感觉打开了新世纪，但是折腾了很久都没有用起来，希望这么好的项目能让小白也用起来，而不仅仅是大神的专利。

其实也不用做什么改动，就增加一个文章的例子就行了。

**Comment by piexlmax** [comment]
> 本人是做后端的，对VUE语法只是略懂皮毛，打开了gin-vue-admin感觉打开了新世纪，但是折腾了很久都没有用起来，希望这么好的项目能让小白也用起来，而不仅仅是大神的专利。
> 
> 其实也不用做什么改动，就增加一个文章的例子就行了。

有增删改查的例子的 代码示例里面最后的客户功能就是增删改查的例子~然后可以加我的微信或者进群 我个人在群内是非常活跃的~

**Comment by lujscn** [comment]
好的谢谢大佬
