### ISSUE TITLE
[Bug]: GetApiById API get error:'cannot convert 12 to Int8' when use postgresql

### ISSUE THREAD

**Issue by jianmaikj** [flipped-aurora/gin-vue-admin#873]
### gin-vue-admin 版本

2.4.6

### Node 版本

v16.13.1

### Golang 版本

go 1.17.0

### 是否依旧存在

可以

### bug描述

GetApiById API get error:'cannot convert 12 to Int8' when use postgresql

**Comment by piexlmax** [comment]
我们会尝试开始复现并且在复现后修复

**Comment by TrumanH** [comment]
@jianmaikj Can you help to verify the PR 928?

**Comment by piexlmax** [comment]
> @jianmaikj Can you help to verify the PR 928? I think it fixed this issue.

thx!PR has been adopted!
