### ISSUE TITLE
[Bug]: 重置用户密码时显示权限不足。

### ISSUE THREAD

**Issue by promende** [flipped-aurora/gin-vue-admin#878]
### gin-vue-admin 版本

2.4.4（一个月前的版本）

### Node 版本

12.18.3

### Golang 版本

1.17.5

### 是否依旧存在

可以

### bug描述

重置用户密码时显示权限不足。

### 修改建议

前端页面：api 管理中将重置用户密码（api 简介）的api 路径改为/user/resetPassword
后端代码：https://github.com/flipped-aurora/gin-vue-admin/blob/main/server/api/v1/system/sys_user.go 中第 336 行以后改为
if err := userService.ResetPassword(utils.GetUserID(c)); err != nil {
    global.GVA_LOG.Error("重置失败!", zap.Error(err))
    response.FailWithMessage("重置失败"+err.Error(), c)
} else {
    response.OkWithMessage("重置成功", c)
}

**Comment by piexlmax** [comment]
初始化数据丢失了重置密码的配置 现在已经修复了 感谢提交issue 2.4.x分支也同步修复了 一个月前的应该可以和2.4.x分支保持同步
