### ISSUE TITLE
部署后部分电脑上不能访问

### ISSUE THREAD

**Issue by as564335sa** [flipped-aurora/gin-vue-admin#880]
### gin-vue-admin 版本

master

### Node 版本

最新

### Golang 版本

最新

### 是否依旧存在

可以

### bug描述

第一次用，出现个奇怪的问题，测试环境运行正常，编译好后部署到生产环境，访问主页会报这个错误；
![QQ图片20220109210824](https://user-images.githubusercontent.com/35949162/148685895-d467f6db-055a-484f-b414-0ed70c5db600.png)
用两台电脑测试过，一台运行后，两个电脑访问都会报这个错误；在另一台上运行之后，两台电脑又都能正常访问，前端小白不知道这是什么问题

**Comment by piexlmax** [comment]
nginx对静态的拦截导致
