### ISSUE TITLE
[Bug]: 用户密码重置成功后没有生效

### ISSUE THREAD

**Issue by thereyou** [flipped-aurora/gin-vue-admin#882]
### gin-vue-admin 版本

2.4.6

### Node 版本

v 16.13.1

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

用户密码重置成功后为什么没有生效

**Comment by thereyou** [comment]
建议：重置的时候可以指定密码，另外可增加用户密码预设强度策略

**Comment by songzhibin97** [comment]
`用户密码重置成功后为什么没有生效`是指什么？
在个人中心里面可以正确修改
