### ISSUE TITLE
[Bug]: ws插件添加开放权限启动失败，提示空指针

### ISSUE THREAD

**Issue by AzraelJi** [flipped-aurora/gin-vue-admin#884]
### gin-vue-admin 版本

最新master分支

### Node 版本

v14.16.1

### Golang 版本

go 1.16

### 是否依旧存在

不可以

### bug描述

ws.go类：添加
var WsPlugin = new(wsPlugin)
路由里加载插件：
PluginInit(PublicGroup, ws.WsPlugin)
报错信息：
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49de0a3]

goroutine 1 [running]:
github.com/flipped-aurora/gin-vue-admin/server/plugin/ws.(*wsPlugin).Register(0xc0000ae300, 0xc00047bac0)
	/Users/sunji/local/vscode/gin-vue-admin/server/plugin/ws/ws.go:59 +0x43
github.com/flipped-aurora/gin-vue-admin/server/initialize.PluginInit(0xc00047afc0, 0xc000811d38, 0x1, 0x1)
	/Users/sunji/local/vscode/gin-vue-admin/server/initialize/plugin.go:16 +0x91
github.com/flipped-aurora/gin-vue-admin/server/initialize.InstallPlugin(0xc00047afc0, 0xc00047b080)
	/Users/sunji/local/vscode/gin-vue-admin/server/initialize/plugin.go:23 +0xb5
github.com/flipped-aurora/gin-vue-admin/server/initialize.Routers(0x0)
	/Users/sunji/local/vscode/gin-vue-admin/server/initialize/router.go:80 +0x685
github.com/flipped-aurora/gin-vue-admin/server/core.RunWindowsServer()
	/Users/sunji/local/vscode/gin-vue-admin/server/core/server.go:28 +0x52
main.main()
	/Users/sunji/local/vscode/gin-vue-admin/server/main.go:33 +0xbf

### 修改建议

希望老大解惑

**Comment by songzhibin97** [comment]
请正常调用 GenerateWs

**Comment by songzhibin97** [comment]
目前没有，有计划补

**Comment by AzraelJi** [comment]
太棒了，期待直播，😄
