### ISSUE TITLE
[Bug]: 代码自动生成后访问时权限不足

### ISSUE THREAD

**Issue by dxl3811051** [flipped-aurora/gin-vue-admin#898]
### gin-vue-admin 版本

v2.5.0

### Node 版本

16.13.2

### Golang 版本

1.17

### 是否依旧存在

可以

### bug描述

照着视频 用自动生成代码功能后，建立菜单 然后访问显示权限不足，经过检查是自动代码没有在casbin_rule表创建相应的路径 导致报错！

### 修改建议

什么时候方便修复下这个问题么 还是我操作上有什么问题？

**Comment by piexlmax** [comment]
需要在角色管理界面添加api权限

**Comment by dxl3811051** [comment]
谢谢 是我没搞清楚界面功能就在瞎折腾了  不好意思 ！！
