### ISSUE TITLE
[Feature]: i18n 分支添加切换语言入口

### ISSUE THREAD

**Issue by jh235** [flipped-aurora/gin-vue-admin#899]
### 功能描述以及必要性描述

目前i18n分支有多语言相关代码，但是没有看到切换功能，只能通过修改配置文件来显示不同语言

### 建议和方案

在首页添加语言切换功能

**Comment by MohamedHassanNasr** [comment]
Dear @jh235 
If you talk about the fronend i18n feature, then you can use the newer branch i18n-dev-new, i already added language switching option to the login screen.
Regards,
Mohamed Hassan
