### ISSUE TITLE
功能增强及建议

### ISSUE THREAD

**Issue by jimmy201602** [flipped-aurora/gin-vue-admin#90]
1：目前查询部分没有实现表所有字段模糊匹配功能
2：加载动画部分可以加在右侧的列表部分，只局部动画即可，现在全页面loading。。。觉得不太好
![image](https://user-images.githubusercontent.com/17548183/81779720-e0713480-9527-11ea-9a6b-e17c80c8719f.png)
3：时间日期部分自动生成代码model部分没有引入time
4：生成model部分建议可以自定义表名，那么在生成架构体时灵活性更大了
类似这样
//get real table name
func (Example *Example) TableName() string {
	return "example_table"
}
5:自动生成代码部分如果是布尔值时，那么前端部分需要自己实现布尔值的render功能
6:日期的处理，在前端建议给一个提示，或者在视频教学中说明（然并卵，建议生成模板时加提示吧）

无论如何，以上只是个人愚见，望采纳

**Comment by piexlmax** [comment]
> 1：目前查询部分没有实现表所有字段模糊匹配功能
> 2：加载动画部分可以加在右侧的列表部分，只局部动画即可，现在全页面loading。。。觉得不太好
> ![image](https://user-images.githubusercontent.com/17548183/81779720-e0713480-9527-11ea-9a6b-e17c80c8719f.png)
> 3：时间日期部分自动生成代码model部分没有引入time
> 4：生成model部分建议可以自定义表名，那么在生成架构体时灵活性更大了
> 类似这样
> //get real table name
> func (Example *Example) TableName() string {
> return "example_table"
> }
> 5:自动生成代码部分如果是布尔值时，那么前端部分需要自己实现布尔值的render功能
> 6:日期的处理，在前端建议给一个提示，或者在视频教学中说明（然并卵，建议生成模板时加提示吧）
> 
> 无论如何，以上只是个人愚见，望采纳

1 3 4 6可采纳 2考虑到loading时候跳转路由可能会产生不可预知的bug，5 可提供示例

**Comment by jimmy201602** [comment]
vue filter里新增以下方法即可，类似formatDate的用法
            formatBoolean: function (value) {
                if (value) {
                    return '?'
                }else {
                    return '?'
                }
            }

**Comment by piexlmax** [comment]
> vue filter里新增以下方法即可，类似formatDate的用法
> formatBoolean: function (value) {
> if (value) {
> return '?'
> }else {
> return '?'
> }
> }

这个 需要用户自己配置字典 使用filter不能达到通用效果 最好的办法是 {{scope.row.key?"":""}}
