### ISSUE TITLE
[Bug]: 主视区loading存在不生效情况

### ISSUE THREAD

**Issue by l-moondream** [flipped-aurora/gin-vue-admin#900]
### gin-vue-admin 版本

2.4.3

### Node 版本

v14.17.6

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

1.以项目中的服务器状态模块为例
2.打开服务器状态页面，停留1,2分钟，此时接口已发送十来次
3.打开api管理页面，设置浏览器network为slow 3G
4.点击api管理查询，接口请求为pending状态
5.主视区设置的loading没有生效
![image](https://user-images.githubusercontent.com/53330236/151143903-06e40df4-6dc3-4329-9a53-7987b8f20475.png)

### 修改建议

require.js的closeLoading函数未对donNotShowLoading为true时进行限制。可以对closeLoading函数中的acitveAxios--添加判断条件。 
![image](https://user-images.githubusercontent.com/53330236/151147614-3dbd4d41-8e73-477e-9673-7136234c6895.png)

**Comment by piexlmax** [comment]
我们会尽快复现并且修复
