### ISSUE TITLE
[Bug]: 编辑菜单里的“keepalive”功能不生效

### ISSUE THREAD

**Issue by thereyou** [flipped-aurora/gin-vue-admin#903]
### gin-vue-admin 版本

2.4.6

### Node 版本

v 16.13.1

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

操作历史-启用“keepalive”，从其它页面返回操作历史页面后还会跳转到第一页

**Comment by piexlmax** [comment]
请尝试v2.4.x分支是否已修复，此问题已经在某个版本进行过修复。

**Comment by piexlmax** [comment]
> ### gin-vue-admin 版本
> 2.4.6
> 
> ### Node 版本
> v 16.13.1
> 
> ### Golang 版本
> go 1.16
> 
> ### 是否依旧存在
> 可以
> 
> ### bug描述
> 操作历史-启用“keepalive”，从其它页面返回操作历史页面后还会跳转到第一页
> 
> ### 修改建议
> _No response_

如果要简单修复 只需要删除 views/layout/index.vue 下 
![image](https://user-images.githubusercontent.com/29840023/156106158-2f80699d-c918-47cc-8001-aa3132d450f9.png)

的 v-if 即可
