### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by myahuang** [flipped-aurora/gin-vue-admin#907]
### gin-vue-admin 版本

2.4.3

### Node 版本

v14.15.0

### Golang 版本

go 1.16.9

### 是否依旧存在

未测试

### bug描述

大佬，你好！我发现批量删除操作记录，会让goland后端系统崩溃，terminal不停的输出/及一些字符，好像陷入死循环.
发生情况是批量删除操作记录并确认，有的时候选择每页50或100项时也会崩溃

**Comment by piexlmax** [comment]
开启连接池就可以了
