### ISSUE TITLE
[Feature]: 大佬我想问下在哪里配置 路由是否需要token验证

### ISSUE THREAD

**Issue by xian896668** [flipped-aurora/gin-vue-admin#908]
### 功能描述以及必要性描述

比如我有一个路由 不要登录就能获取到数据     是自动生成的路由代码   应该怎么配置才能不用进行登录的token验证

就像获取验证码一样 不需要登录就能获取到

**Comment by derekcdq** [comment]
在router/system/sys_base.go里面添加就行了
