### ISSUE TITLE
pgsql速度慢，并且部分功能报错

### ISSUE THREAD

**Issue by myahuang** [flipped-aurora/gin-vue-admin#909]
### gin-vue-admin 版本

2.4.6

### Node 版本

v14.15.0

### Golang 版本

go 1.16.9

### 是否依旧存在

未测试

### bug描述

大佬你好，我初始化的时候选择pgsql后，重启前端和前端，可以登录进入系统，但是会提示大大于200ms报警，另外菜单管理和用户管理点击“编辑”按钮会报错，后端服务器会报error": "cannot convert 1 to Int8", "errorVerbose": "cannot convert 1 to Int8”之类的错误，信息中的1可以换成其他数字，视前端点击的“编辑”按钮位置而定。不知道能否改善一下，本人萌新一枚，感谢大佬这个项目!

**Comment by myahuang** [comment]
我是本地的连接，我用python的sqlalchemy读取速度几百条记录速度快的很，基本不会等待，go不是比python更快吗？

**Comment by piexlmax** [comment]
请到配置文件中配置连接池和最大连接数
pgsql:
    max-idle-conns: 10
    max-open-conns: 100

**Comment by myahuang** [comment]
修改配置后不会报大于200ms报警了，但是“”菜单管理和用户管理点击“编辑”按钮会报错，后端服务器会报error": "cannot convert 1 to Int8", "errorVerbose": "cannot convert 1 to Int8”之类的错误依然存在，感觉是数据类型不兼容造成的。
