### ISSUE TITLE
[Bug]: postgresql初始化数据库异常

### ISSUE THREAD

**Issue by ccfish86** [flipped-aurora/gin-vue-admin#910]
### gin-vue-admin 版本

V2.5.0 beta.2

### Node 版本

v14.17.4

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

初始化时，选pgsql，
如果userName使用普通用户的时候，可能无法正常创建数据库。
用户，chemen/，配置login/create database权限，然后按照以下输入
![image](https://user-images.githubusercontent.com/15622514/153797615-7acb570e-7b6e-4b8b-9824-30ab2c604a83.png)

如果db=chemen不提前创建时：`自动创建数据库失败!     {"error": "failed to connect to `host=192.168.124.13 user=chemen database=`: server error (FATAL: database \"chemen\" does not exist (SQLSTATE 3D000))"}`
如果提前创建时：`自动创建数据库失败!     {"error": "ERROR: database \"chemen\" already exists (SQLSTATE 42P04)"}`

### 修改建议

看下是否支持
`SELECT 'CREATE DATABASE $database'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$database')`

**Comment by piexlmax** [comment]
chemen 有建库权限吗

**Comment by ccfish86** [comment]
> chemen 有建库权限吗

有权限，可能需要先通过 `SELECT FROM pg_database WHERE datname = '$database'`判断库存不存在，然后再执行`CREATE DATABASE $database`。合成一句的那种做法，是psql工具里用的（SELECT 'CREATE DATABASE $database' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$database')\gexec）。

**Comment by AuroraTea** [comment]
啊所以大佬怎么解决，现在还是有这个问题SELECT 'CREATE DATABASE $database' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$database')是要改动Gin-Vue-Admin的源代码吗

**Comment by trojansun** [comment]
我修改了源码，先查询下数据库是否存在，当数据库不存在的时候，再创建数据库。
`sys_initdb.go` 增加check方法
`sys_initdb_pgsql.go` 57行 调用 `sys_initdb.go` 的check方法，当查询数据库不存在的时候，走
```shell
                createSql := fmt.Sprintf("CREATE DATABASE %s;", c.Dbname)
		if err = createDatabase(dsn, "pgx", createSql); err != nil {
			return nil, err
		} // 创建数据库
```
逻辑，可初始化成功。
