### ISSUE TITLE
[Bug]: 清理0016eab39cd2e0687be4653ad263cfb12e3406a5误带的gin-vue-admin二进制吧

### ISSUE THREAD

**Issue by daqingshu** [flipped-aurora/gin-vue-admin#911]
### gin-vue-admin 版本

main

### Node 版本

v14.16.0

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

1、0016eab39cd2e0687be4653ad263cfb12e3406a5误带进来gin-vue-admin二进制，虽然删除，但是git历史记录里面还有，导致仓库很大，国内访问github本来就慢，希望清理历史记录，让仓库变小。

### 修改建议

本机安装 https://github.com/newren/git-filter-repo/
然后执行 git filter-repo --path server/gin-vue-admin --invert-paths
再 git push --force，就可以将仓库大小变小
不过会改变所有的历史commit id，请视情况修复吧。

**Comment by piexlmax** [comment]
非常感谢您提出的建议和解决方案，我们也注意到了这个问题，但是担心会影响到现有用户的更新，因此不敢做变动。

**Comment by daqingshu** [comment]
> 非常感谢您提出的建议和解决方案，我们也注意到了这个问题，但是担心会影响到现有用户的更新，因此不敢做变动。

在从master变为main的时候，其实可以这么搞一下，或者什么时候再搞个新版本作默认分支，比如v2?

**Comment by piexlmax** [comment]
> > 非常感谢您提出的建议和解决方案，我们也注意到了这个问题，但是担心会影响到现有用户的更新，因此不敢做变动。
> 
> 在从master变为main的时候，其实可以这么搞一下，或者什么时候再搞个新版本作默认分支，比如v2?

发布大版本（不兼容）时候 可以搞一下
