### ISSUE TITLE
每个包都有enter.go文件，虽然方便了包管理，但是不是会存在一些冗余

### ISSUE THREAD

**Issue by caipeishen** [flipped-aurora/gin-vue-admin#913]
### 功能描述以及必要性描述

1.每个包都有enter.go文件，虽然方便了包管理，但是不是会存在一些代码繁琐
2.自己是java转go，对go的理解可能还是不到位，希望能解答一下

**Comment by piexlmax** [comment]
enter非必要文件 这里是为了方便对每一个叶子，也就是 go里面引用的那些结构体再其他包内使用的时候，可以统一 new 一下即可，如果不想加入enter 也可以单独引用叶子节点的结构体new。 这样的设计就是为了大家可以枝条注册，也可以叶子注册。自行选择的一种模式。

**Comment by caipeishen** [comment]
感谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月15日(星期二) 上午10:55
收件人: ***@***.***&gt;; 
抄送: "Cai ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [flipped-aurora/gin-vue-admin] 每个包都有enter.go文件，虽然方便了包管理，但是不是会存在一些冗余 (Issue #913)





 
enter非必要文件 这里是为了方便对每一个叶子，也就是 go里面引用的那些结构体再其他包内使用的时候，可以统一 new 一下即可，如果不想加入enter 也可以单独引用叶子节点的结构体new。 这样的设计就是为了大家可以枝条注册，也可以叶子注册。自行选择的一种模式。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenhd** [comment]
我遇到一种情况就是A包下有B，B包下有C、D，这时候同层级的C想访问D的数据然后进行import A就会报import cycle，场景就是某个service接口想调用另一个service接口，因为已经有一整个树的注册，我再自行注册D不清楚会不会产生泄露，想请问下有没有好的方法
