### ISSUE TITLE
[Bug]: 一个用户登录时,没有清空session的history,造成另一个用户登录时tab页面出错!

### ISSUE THREAD

**Issue by weiyunxiao** [flipped-aurora/gin-vue-admin#917]
### gin-vue-admin 版本

2.4.5Beta

### Node 版本

v16

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

1.用户登录打开一些tab,登出后前端session的history仍然保存中.
2.使用另一个用户登录,没有上一个用户的菜单,会读取上一个用户的history,造成tab打开错误

### 修改建议

登出时,添加清空前端session功能.

**Comment by piexlmax** [comment]
本次版本更新修复，感谢您提交issue
