### ISSUE TITLE
[Feature]: 验证码配置重复

### ISSUE THREAD

**Issue by myahuang** [flipped-aurora/gin-vue-admin#918]
### 功能描述以及必要性描述

系统配置菜单的验证码配置菜单重复，里面内容一模一样。
![image](https://user-images.githubusercontent.com/57703532/154428242-625378d2-1f0a-4197-bac8-e36dd0faf0eb.png)

### 建议和方案

删掉一个

**Comment by tscuite** [comment]
尝试清除一下缓存，在main分支没有发现异常
![image](https://user-images.githubusercontent.com/64051240/154429401-fdc693aa-dd13-4666-b15c-5bee843585d9.png)

**Comment by myahuang** [comment]
我清除缓存了，甚至把项目文件夹删除，原来的zip包重新解压，运行，还是这样的，edge和chrome都一样。2.4.6版本，2.11日下载的zip包

**Comment by tscuite** [comment]
后续版本中已修复，可尝试修改web/src/view/systemTools/system/system.vue文件
