### ISSUE TITLE
vue 线上打包配置问题

### ISSUE THREAD

**Issue by EverCurse** [flipped-aurora/gin-vue-admin#93]
前端我看到有个配置是vue.config.js  配置的是开发环境的一些参数。现在我想上线 在生产环境 我怎么新建一个生产配置和npm run build联系起来打包呢？ 对前端不是很熟悉 希望解答下

**Comment by piexlmax** [comment]
这里只需要关注前端目录下的.env.development  .env.production两个文件中的 VUE_APP_BASE_API 即可 这是发送ajax的主要相对路径前缀 开发环境用 webpack进行了代理 线上环境会产生v1前缀 建议自行修改v1或者nginx代理  如果还有疑问 可以添加 作者微信 感谢使用本框架
