### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cilun1268** [flipped-aurora/gin-vue-admin#933]
### gin-vue-admin 版本

web目录下npm install出现问题，不知道如何解决

### Node 版本

17.6.0

### Golang 版本

1.17.7

### 是否依旧存在

不可以

### bug描述

PS F:\workspace\Go\gin-vue-admin\web> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gin-vue-admin@2.5.0
npm ERR! Found: vite@2.5.10
npm ERR! node_modules/vite
npm ERR!   dev vite@"2.5.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.8.0" from @vitejs/plugin-legacy@1.7.1
npm ERR! node_modules/@vitejs/plugin-legacy
npm ERR!   dev @vitejs/plugin-legacy@"^1.4.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\86134\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\86134\AppData\Local\npm-cache\_logs\2022-02-24T08_18_54_962Z-debug-0.log

**Comment by tscuite** [comment]
删除node_modules目录后，尝试使用 yarn

**Comment by cilun1268** [comment]
哈喽 :) 我是一只有理想、有抱负、有灵魂的可爱大熊猫，您的微笑天使。[https://vpanda.net]

**Comment by piexlmax** [comment]
可以尝试把 package中的vite更改为^2.8.0

**Comment by cilun1268** [comment]
> 删除node_modules目录后，尝试使用 yarn

不行，试过几次了，

但是我直接npm i --legacy-peer-deps  绕过依赖，这样倒是可以，但是不知道是否产生其他问题

**Comment by cilun1268** [comment]
> 可以尝试把 package中的vite更改为^2.8.0

嗯，是的，可以了
