### ISSUE TITLE
[Bug]: keepalive选项无效

### ISSUE THREAD

**Issue by ZhuoxueQAQ** [flipped-aurora/gin-vue-admin#934]
### gin-vue-admin 版本

v2.5.0 beta

### Node 版本

v16.13.1

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

按照视频教程修改keepalive选项后无法修改，目前为2.5.0 bata版本（看到一个类似的issue说2.4.x已经修复过了QAQ还是不行）。复现步骤：clone当前项目主版本（2.5.0 bata 2 组合式api版本 ），初始化以后，修改超级管理员->操作历史页面为keep-alive之后无效。（和b站视频：https://www.bilibili.com/video/BV1Rg411u7xH?p=9 里面的操作流程完全一致）。

**Comment by piexlmax** [comment]
请提供复现步骤

**Comment by ZhuoxueQAQ** [comment]
> 

复现步骤：clone当前项目主版本（2.5.0 bata 2 组合式api版本 ），初始化以后，修改超级管理员->操作历史页面为keep-alive之后无效。（和b站视频：https://www.bilibili.com/video/BV1Rg411u7xH?p=9 里面的操作流程完全一致）。

**Comment by ZhuoxueQAQ** [comment]
> ### gin-vue-admin 版本
> v2.5.0 beta
> 
> ### Node 版本
> v16.13.1
> 
> ### Golang 版本
> go 1.17
> 
> ### 是否依旧存在
> 可以
> 
> ### bug描述
> 按照视频教程修改keepalive选项后无法修改，目前为2.5.0 bata版本（看到一个类似的issue说2.4.x已经修复过了QAQ还是不行）。复现步骤：clone当前项目主版本（2.5.0 bata 2 组合式api版本 ），初始化以后，修改超级管理员->操作历史页面为keep-alive之后无效。（和b站视频：https://www.bilibili.com/video/BV1Rg411u7xH?p=9 里面的操作流程完全一致）。
> 
> ### 修改建议
> _No response_

**Comment by ZhuoxueQAQ** [comment]
> 请提供复现步骤

查看当前页面的路由，keep-alive为true，但是还是无效。复现步骤如上
