### ISSUE TITLE
Api管理表格无法根据id进行排序，会报错[Bug]: 

### ISSUE THREAD

**Issue by myahuang** [flipped-aurora/gin-vue-admin#936]
### gin-vue-admin 版本

2.4.6

### Node 版本

v14.15.0

### Golang 版本

go 1.16.9

### 是否依旧存在

未测试

### bug描述

Api管理菜单点进去后发现那个表格除了id外都可以进行排序操作，就id列会报错

### 修改建议

萌新无法给出建议

**Comment by piexlmax** [comment]
会在复现后尽快修复。

**Comment by piexlmax** [comment]
2.5.0
![image](https://user-images.githubusercontent.com/29840023/156101626-533ce945-a20b-4fc1-a0a4-84a636c6e322.png)
无法复现

**Comment by piexlmax** [comment]
> 我的是2.11日下载的zip包，版本2.4.6，的确会存在。 ![image](https://user-images.githubusercontent.com/57703532/156193986-ef7f4b33-7843-41be-8f8d-3ef10270ffc7.png)
> 
> 后台信息如下：
> 
> > 2022/03/01 23:05:00 E:/gin-vue-admin-2.4.6/server/service/system/sys_api.go:94 Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your M
> > ySQL server version for the right syntax to use near 'LIMIT 10' at line 1
> > [1.081ms] [rows:1] SELECT * FROM `sys_apis` WHERE `sys_apis`.`deleted_at` IS NULL ORDER BY  LIMIT 10
> > [github.com/flipped-aurora/gin-vue-admin/server]2022/03/01 - 23:05:00.573       error   E:/gin-vue-admin-2.4.6/server/api/v1/system/sys_api.go:80       获取失败!       {"er
> > ror": "Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 10' at line
> > 1"}
> > 而且这个问题很严重的，因为我发现点id排序错误后，1 2 3 4哪些分页按钮都失效，点击都会错误
> > 我的mysql版本是8.0.11

加一下我的微信 shouzi_1994 我远程看下

**Comment by TrumanH** [comment]
@piexlmax 看了一眼这个函数：`func (apiService *ApiService) GetAPIInfoList`,目测当参数`order`不为以下["id","path","api_group","description","method"]之一时 ,比如`order=="ID"`即可复现。后端提了个PR: https://github.com/flipped-aurora/gin-vue-admin/pull/950
同时注意检查前端此接口`/api/getApiList`对应入参`orderKey`的传值。

**Comment by TrumanH** [comment]
@myahuang 是否可贴出复现时`/api/getApiList`对应请求体，验证是否由非法的`orderKey`参数导致？其值不为以下`["id","path","api_group","description","method"]`之一 ？

**Comment by piexlmax** [comment]
此处后端限制是为了防止sql注入，已采纳对非法数据提示的pr
