### ISSUE TITLE
[Feature]: 自动化代码增加模块选择功能

### ISSUE THREAD

**Issue by piexlmax** [flipped-aurora/gin-vue-admin#937]
### 功能描述以及必要性描述

1.目前的自动化代码都会被分配到autocode下，这样对于业务分区用户还需要手动拖拽或者修改代码内容。
2.增加自动创建模块的功能点，或者前置的一个创建模块的功能页面，让用户在用自动化代码的时候，一步到位，代码直接进入自己要写入的业务模块中。进一步提升开发速度。

### 建议和方案

增加自动创建模块的功能点，或者前置的一个创建模块的功能页面，让用户在用自动化代码的时候，一步到位，代码直接进入自己要写入的业务模块中。进一步提升开发速度。

**Comment by songzhibin97** [comment]
@songzhibin97

**Comment by songzhibin97** [comment]
排期
