### ISSUE TITLE
[Feature]: 和go_gin_api功能打通的问题

### ISSUE THREAD

**Issue by iakirago** [flipped-aurora/gin-vue-admin#938]
### 功能描述以及必要性描述

在使用中遇到个问题，接口开发使用的是go_gin_api,管理后台使用的是gin-vue-admin,
1、发现公用的字段
DeletedAtint32 // 是否删除 1:是 -1:否
CreatedAt time.Time gorm:"time" // 创建时间
UpdatedAt time.Time gorm:"time" // 更新时间
上述三个字段中，在go_gin_api中IsDeleted对应的gin-vue-admin的DeletedAt，字段没有打通，无法一起使用

### 建议和方案

如果可以，能否实现用户选择使用DeletedAt或者IsDeleted(gon_gin_api使用该字段标记删除)来标记数据删除，这个样一个做接口开发，一个可以用来做后台数据管理

**Comment by piexlmax** [comment]
gorm默认使用的CreatedAt 来记录删除 如果有特殊需求可以尝试冗余一个字段进行记录即可
