### ISSUE TITLE
[Feature]: 面包屑导航

### ISSUE THREAD

**Issue by pddzl** [flipped-aurora/gin-vue-admin#940]
### 功能描述以及必要性描述

你好gva，以后会加上面包屑导航吗

**Comment by piexlmax** [comment]
会加的，这个是因为处理keepalive重复生命周期不小心弄没了，会尽快修复！

**Comment by piexlmax** [comment]
https://github.com/flipped-aurora/gin-vue-admin/commit/8bf33f107983dc78d2de58d5e0a53e4bbae4b6f1
