### ISSUE TITLE
[Bug]: api地址命名混淆

### ISSUE THREAD

**Issue by 768446472** [flipped-aurora/gin-vue-admin#942]
### gin-vue-admin 版本

2.5.0

### Node 版本

v16.14.0

### Golang 版本

go 1.17.8

### 是否依旧存在

可以

### bug描述

文件：/server/router/system/sys_user.go

16		userRouter.POST("register", baseApi.Register)                     // 用户注册账号

此处对应的功能实际为管理员手动新增账号，与预期用户自己注册账号功能不符。
register地址的经过鉴权处理，无法实现用户注册。

### 修改建议

建议将api地址及相关服务修改为更为准确的描述， 如 ’createUser‘。
以避免开发者在开发开放注册功能时出现混淆。

**Comment by piexlmax** [comment]
已收到，将会在下个版本调整
