### ISSUE TITLE
管理后台 不停的刷新页面 [Bug]: 

### ISSUE THREAD

**Issue by lovemintblue** [flipped-aurora/gin-vue-admin#958]
### gin-vue-admin 版本

2.4.5

### Node 版本

v16

### Golang 版本

go1.17

### 是否依旧存在

可以

### bug描述

管理后台 不停的刷新页面 请求 /menu/getMenu 和 /user/getUserInfo 接口

**Comment by songzhibin97** [comment]
不停刷新是指？请截图详细内容

**Comment by lovemintblue** [comment]
> 
我在初始化数据的时候 都在不停刷新了 链接在下面
http://www.zcylovezhx.com/#/init

**Comment by lovemintblue** [comment]
> 请截图是内容刷新吗？

老哥 初始化的时候 页面都已经在刷新了 链接 http://www.zcylovezhx.com/#/init 麻烦看一下

**Comment by songzhibin97** [comment]
![image](https://user-images.githubusercontent.com/49082129/158548511-9ff8f730-0fff-46f1-b32d-c2ab5c54e7f6.png)

**Comment by songzhibin97** [comment]
没太看懂

**Comment by songzhibin97** [comment]
@bypanghu

**Comment by bypanghu** [comment]
请问你加群了嘛？加一下群 在群里艾特我一下，在微信说话比较方便

**Comment by bypanghu** [comment]
还有需要你确认一点就是，你是不是在服务器上run 的，而不是build的？

**Comment by lovemintblue** [comment]
> build

我是run 的  应该build吗

**Comment by bypanghu** [comment]
> > build
> 
> 我是run 的 应该build吗

额，麻烦看一下vue build。你的那个是vite 服务器在查找你有么有改代码，重新画页面，打包之后就会被删除，你直接开发环境，肯定有问题了

**Comment by lovemintblue** [comment]
> > > build
> > 
> > 
> > 我是run 的 应该build吗
> 
> 额，麻烦看一下vue build。你的那个是vite 服务器在查找你有么有改代码，重新画页面，打包之后就会被删除，你直接开发环境，肯定有问题了

感谢感谢 我不是前端 有点不太了解了 再次感谢！
