### ISSUE TITLE
[Bug]: keep-alive 无效

### ISSUE THREAD

**Issue by azurachen** [flipped-aurora/gin-vue-admin#961]
### gin-vue-admin 版本

2.5.0

### Node 版本

v16.14.0

### Golang 版本

go 1.17.7

### 是否依旧存在

可以

### bug描述

1. 按照B站 《手把手教你使用gin-vue-admin(分P合集)》P4操作，无法实现嵌套效果。
2. 在 @/view/superAdmin/index.vue 添加如下内容：
<template>
  <div>下面是内容
    <router-view v-slot="{ Component }">下面是内容
      <transition mode="out-in" name="el-fade-in-linear">
        <keep-alive :include="routerStore.keepAliveRouters">
          <component :is="Component" />
        </keep-alive>
      </transition>
    </router-view>
    上面是内容
  </div>
</template>
3.在后台的 超级管理员子菜单也无法显示  ”下面是内容“”上面是内容“ 等字样

**Comment by piexlmax** [comment]
已微信联系解决
