### ISSUE TITLE
请教一下utils.Verify的作用是？

### ISSUE THREAD

**Issue by jialeo** [flipped-aurora/gin-vue-admin#966]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14

### Golang 版本

1.17

### 是否依旧存在

可以

### bug描述

即用用到了gin的bind，为什么还要自定义一个utils.Verify()函数呢？这个有详细文档吗？

**Comment by songzhibin97** [comment]
手写的验证器，可以用gin的bind，具体使用看代码
