### ISSUE TITLE
[Bug]: 用户列表在编辑界面修改权限会多出来同名角

### ISSUE THREAD

**Issue by erlangzhang** [flipped-aurora/gin-vue-admin#967]
### gin-vue-admin 版本

2.4.5

### Node 版本

v14.16

### Golang 版本

go 1.18

### 是否依旧存在

可以

### bug描述

1.首先在列表上修改某个用户角色, 如1变2或2变1
2.在编辑界面也去修改下用户角色，这里候就会有一个角色会被新增，同时列表修改的角色被改回去了，与列表展示不一致

**Comment by pnck** [comment]
（随手补充）这个bug在 #957  修掉之前是由于userService.SetUserInfo接受了一个空的Authority struct导致自动创建了一个authority id为空字符串的角色造成的，不清楚现在还能否复现

**Comment by piexlmax** [comment]
> （随手补充）这个bug在 #957 修掉之前是由于userService.SetUserInfo接受了一个空的Authority struct导致自动创建了一个authority id为空字符串的角色造成的，不清楚现在还能否复现

非常感谢您之前的pr，此功能已经修复，用户版本为2.4.5的声明式api版本。
