### ISSUE TITLE
重构CreateTemp

### ISSUE THREAD

**Issue by WangLeonard** [flipped-aurora/gin-vue-admin#97]
初步想法是遍历`resource/template`文件夹下所有`.tpl`文件  
根据该文件路径信息，实现当前功能（应该只需要很少的额外辅助信息 ）  
减少当前的重复代码，后续增加`tpl`文件也更方便   

如果有需要我会进行这部分代码的重构，后续提交pr

**Comment by piexlmax** [comment]
是的 这里重复代码有点多 实现功能后忘记了优化 感谢

**Comment by piexlmax** [comment]
已采纳PR万分感谢
