### ISSUE TITLE
[Bug]:基于postgreSQL代码生成后新增菜单bug

### ISSUE THREAD

**Issue by sniperZj** [flipped-aurora/gin-vue-admin#973]
### gin-vue-admin 版本

 V2.5.0b

### Node 版本

v14.17.2

### Golang 版本

go 1.16.5

### 是否依旧存在

可以

### bug描述

1、基于postgreSQL代码生成后新增菜单
2、报唯一约束错误（唯一的约束）

### 修改建议

菜单初始化sql的自增序列未递增，调整即可

**Comment by pnck** [comment]
append : 初始化PG里的数据会有不能正确 set 主键sequence的现象，我目前也是workaround手动 select setval，不知道有没有更好的办法
