### ISSUE TITLE
[Bug]: Open Form Builder

### ISSUE THREAD

**Issue by israebe** [flipped-aurora/gin-vue-admin#975]
### gin-vue-admin 版本

V2.5.0

### Node 版本

v17.5.0

### Golang 版本

go 1.17.6

### 是否依旧存在

可以

### bug描述

when Open Form Builder , I found it Loading and I get this in console:

Uncaught TypeError: s.chunk is not a function
    at index.94d8e405.js:1:3359
    at index.94d8e405.js:1:3443

**Comment by piexlmax** [comment]
请问是部署过后的吗

**Comment by israebe** [comment]
run it on local pc  localhost

**Comment by piexlmax** [comment]
Please provide the detailed generation process of the bug

**Comment by israebe** [comment]
Hi piexlmax,
detailed generation process :

*in Frontend in browser console :
index.94d8e405.js:1 Uncaught TypeError: s.chunk is not a function
    at index.94d8e405.js:1:3359
    at index.94d8e405.js:1:3443
(anonymous) @ index.94d8e405.js:1
(anonymous) @ index.94d8e405.js:1

*in Backend server:
[GIN] 2022/03/28 - 11:19:50 | 200 |    2.925403ms |       127.0.0.1 | GET      "/form-generator/css/index.f05c41c6.css"
[GIN] 2022/03/28 - 11:19:50 | 200 |    3.082242ms |       127.0.0.1 | GET      "/form-generator/js/chunk-vendors.9ae0d8fb.js"
[GIN] 2022/03/28 - 11:19:50 | 200 |    2.992449ms |       127.0.0.1 | GET      "/form-generator/js/index.94d8e405.js"
[GIN] 2022/03/28 - 11:19:51 | 200 |     142.796µs |       127.0.0.1 | GET      "/form-generator/js/parser-example.c1051310.js"

[GIN] 2022/03/28 - 11:19:51 | 304 |       63.35µs |       127.0.0.1 | GET      "/form-generator/css/parser-example.69e16e51.css"
[GIN] 2022/03/28 - 11:19:51 | 304 |      62.347µs |       127.0.0.1 | GET      "/form-generator/js/tinymce-example.5a756246.js"

**Comment by piexlmax** [comment]
Sorry, I didn't reply to you for a long time. You can try to use the main branch code to see if this problem still exists.

**Comment by songzhibin97** [comment]
Temporarily closed
