### ISSUE TITLE
[Chore]:  config结构中tag不一致导致序列化/反序列化config文件的问题

### ISSUE THREAD

**Issue by pnck** [flipped-aurora/gin-vue-admin#977]
### 功能描述以及必要性描述

- viper使用`mapstructure` tag来反序列化配置文件，但它不提供序列化回去的方法
- 可以用 `yaml.marshall` 来直接把配置序列化回文件，但用的是 `yaml` tag
- 注意到大多数配置结构里的 `mapstructure` 和 `yaml` tag都是一样的 kebab-case写法，但存在例外，如 `Zap.ShowLine`

于是为了避免踩到改了配置写出去读不回来的坑，我自己新加的配置结构也只好用了 _「官方」_ 的写法（指转一遍map再循环让viper set一遍kv再writeconfig）来持久化配置。但其实如果 `yaml`和`mapstructure`的值能保证一样的话，一次性序列化操作就够了

这个 `StructToMap()` 的轮子也本可以去掉的

**Comment by piexlmax** [comment]
@songzhibin97 cc
