### ISSUE TITLE
[Feature]: 代码生成器部分，添加设置自动生成的表单出现的方式

### ISSUE THREAD

**Issue by iakirago** [flipped-aurora/gin-vue-admin#979]
### 功能描述以及必要性描述

1、自动生成代码器的部分，希望添加一个选项，自动生成的表单可以是弹窗或者新的页面方式出现

**Comment by piexlmax** [comment]
自动表单已经存在了，自动产生的xxxxForm.vue即表单页面 书写路由跳转代码即可
