### ISSUE TITLE
[Bug]: 自动化填充数据后新增菜单和字典告知主键重复

### ISSUE THREAD

**Issue by wuyushuai** [flipped-aurora/gin-vue-admin#983]
### gin-vue-admin 版本

V2.5.1 beta

### Node 版本

V2.5.1 beta

### Golang 版本

1.7

### 是否依旧存在

可以

### bug描述

postgresql 14  添加菜单错误

`2022/03/27 09:29:32 D:/code/gin-vue-admin/server/service/system/sys_menu.go:114 record not found
[1.651ms] [rows:0] SELECT * FROM "sys_base_menus" WHERE name = 'testtwo' AND "sys_base_menus"."deleted_at" IS 
NULL ORDER BY "sys_base_menus"."id" LIMIT 1

2022/03/27 09:29:32 D:/code/gin-vue-admin/server/service/system/sys_menu.go:117 ERROR: duplicate key value violates 
unique constraint "sys_base_menus_pkey" (SQLSTATE 23505)
[4.891ms] [rows:0] INSERT INTO "sys_base_menus" ("created_at","updated_at","deleted_at","menu_level","parent_i
d","path","name","hidden","component","sort","keep_alive","default_menu","title","icon","close_tab") VALUES ('2022-03-27 09:29:32.186','2022-03-27 09:29:32.186',NULL,0,'0','testtwo','testtwo',false,'view/testStruct/testStruct.vue',0,false,false,'啊啊','aim',false) RETURNING "id"
[github.com/flipped-aurora/gin-vue-admin/server]2022/03/27 - 09:29:32.190       error  D:/code/gin-vue-admin/server/api/v
1/system/sys_menu.go:119        添加失败!       {"error": "ERROR: duplicate key value violates unique constraint \"sys_base_menus_pkey\" (SQLSTATE 23505)"}
[GIN] 2022/03/27 - 09:29:32 | 200 |     30.8095ms |       127.0.0.1 | POST     "/menu/addBaseMenu"`

**Comment by songzhibin97** [comment]
sys_base_menus_pkey 是什么表？

**Comment by piexlmax** [comment]
sys_base_menus_pkey 参数key重复了 但是这个key是哪个表里的。。

**Comment by piexlmax** [comment]
已复现，初始数据导致新增key无法开始自增，正在调整。

**Comment by wuyushuai** [comment]
> 




> 已复现，最初自增数据导致无法新增关键，正在调整。


字典添加我记得也是有问题  忘记说了  好像是相同问题

**Comment by pnck** [comment]
> 已复现，初始数据导致新增key无法开始自增，正在调整。

https://github.com/go-gorm/gorm/issues/5105 

大概是 gorm 的 bug

**Comment by pnck** [comment]
> > 已复现，初始数据导致新增key无法开始自增，正在调整。
> 
> [go-gorm/gorm#5105](https://github.com/go-gorm/gorm/issues/5105)
> 
> 大概是 gorm 的 bug

今天又调了一下，原来跟gorm也没关系，是 `source/system/menu.go`里初始化把menu的id写死了，pg  insert 的的时候如果给出了覆盖serial/sequence生成器的值则不会使用序列生成器……
要么不填 ID 要么填充完初始数据把sequence重置一下

**Comment by wuyushuai** [comment]
> > > 已复现，最初自增数据导致无法新增关键，正在调整。
> > 
> > 
> > [go-gorm/gorm#5105](https://github.com/go-gorm/gorm/issues/5105)
> > 大概是gorm的虫子
> 
> 今天又调了一下关系，原来跟gorm没有关系，是里初始化`source/system/menu.go`把menu的id写死了，pg insert的时候如果已经使用了serial/sequence覆盖生成器的则不会生成生成器…… 或者最初未填写完数据把序列重新整理一下ID
> 
> @piexlmax

确实是这样子的  修改默认的global.GVA_MODEL{ID: 1}  id去掉后就可了

**Comment by piexlmax** [comment]
这里主要是担心关联会出现问题，会采用sequence重置的方式解决
