### ISSUE TITLE
[Bug]: 前端项目在登录页面中账密错误code == 7 时loading似乎没有关掉

### ISSUE THREAD

**Issue by tianketianke** [flipped-aurora/gin-vue-admin#988]
### gin-vue-admin 版本

main

### Node 版本

16

### Golang 版本

1.17

### 是否依旧存在

未测试

### bug描述

1. 输入一个错帐密
2. loading未关闭

**Comment by bypanghu** [comment]
你好，我在demo上测试 并未复现 在login页面输入错误密码导致的弹窗

**Comment by piexlmax** [comment]
> 你好，我在demo上测试 并未复现 在login页面输入错误密码导致的弹窗

可以复现，马上修复，demo不是main代码

**Comment by piexlmax** [comment]
已修复 https://github.com/flipped-aurora/gin-vue-admin/commit/3fecdbe5d98dbe1bf9cea642d767e87449e53de6
