### ISSUE TITLE
[Bug]: vue启动问题描述

### ISSUE THREAD

**Issue by JarvisHsu** [flipped-aurora/gin-vue-admin#990]
### gin-vue-admin 版本

2.5.0

### Node 版本

v16.14.2

### Golang 版本

go 1.16

### 是否依旧存在

未测试

### bug描述

![image](https://user-images.githubusercontent.com/42184646/160607977-afc0243c-28b5-46fe-83ec-b8caafd9fefd.png)

**Comment by bypanghu** [comment]
如果在云端安装这个项目，请先确保环境中存在 `xdg-open` 命令.如果没有，请先安装这个
