### ISSUE TITLE
[Bug]: 启动404错误

### ISSUE THREAD

**Issue by gonboy** [flipped-aurora/gin-vue-admin#991]
### gin-vue-admin 版本

V2.5.1 beta

### Node 版本

16.14.2 (包含 npm 8.5.0)

### Golang 版本

go1.17.7 windows/amd64

### 是否依旧存在

可以

### bug描述
Win10 X64

git最新版本，启动报错

http://localhost:8080/#/login
---------------------------------------
接口报错
检测到接口错误Error: Request failed with status code 404
错误码 404 ：此类错误多为接口未注册（或未重启）或者请求路径（方法）与api路径（方法）不符--如果为自动化代码请检查是否存在空格
--------------------------------server	
	欢迎使用 github.com/flipped-aurora/gin-vue-admin/server
	当前版本:V2.5.1 beta
    加群方式:微信号：shouzi_1994 QQ群：622360840
	GVA讨论社区:https://support.qq.com/products/371961
	默认自动化文档地址:http://127.0.0.1:8888/swagger/index.html
	默认前端文件运行地址:http://127.0.0.1:8080

--------------------------------web
vite v2.8.6 dev server running at:
>network: http://192.168.30.209:8080
>network: http://192.168.227.1:8080
>network: http://192.168.193.1/209:8080
>local: http://localhost:8080/
>network: http://172.19.16.1:8080
ready in 1634ms

### 修改建议

什么原因？

**Comment by bypanghu** [comment]
报错404 要么是后端没启动，要么就是你改了后端的端口，需要自己是修改前端代理的路径

**Comment by gonboy** [comment]
下载代码后，没有进行任何更改啊！（我的Mysql 不是3306端口）
确定server和web都启动了

奇怪了

**Comment by bypanghu** [comment]
那你初始化了？初始化mysql 的时候改端口了吗？

**Comment by gonboy** [comment]
找到原因了。
和 seafile 端口冲突了。
