### ISSUE TITLE
[Feature]: 增加server启动，端口占用检测功能。 否则端口被占用，都不报错。

### ISSUE THREAD

**Issue by gonboy** [flipped-aurora/gin-vue-admin#992]
### 功能描述以及必要性描述

建议：增加server启动，端口占用检测功能。 
否则端口被占用，server 启动都不报错。

**Comment by piexlmax** [comment]
开搞

**Comment by piexlmax** [comment]
[github.com/flipped-aurora/gin-vue-admin/server]2022/03/31 - 21:54:03.402       error   E:/gin-vue-admin/server/core/server.go:47       listen tcp :8888: b
ind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
测试结果 本issue关闭
