### ISSUE TITLE
[Bug]: 前端模块无法独立运行

### ISSUE THREAD

**Issue by junbin-yang** [flipped-aurora/gin-vue-admin#994]
### gin-vue-admin 版本

2.5.0

### Node 版本

v16.13.1

### Golang 版本

go 1.17

### 是否依旧存在

可以

### bug描述

我没有先启动go项目。先用vscode打开前端项目时失败，前端项目是否无法单独启动吗？
如图vscode下启动成功。但是浏览器一直无法响应
![image](https://user-images.githubusercontent.com/22806800/160818525-85ab57e7-18d0-4bb5-8ec4-153dc5e3afa9.png)

**Comment by bypanghu** [comment]
前端独立运行需要自己制作mock数据，gva的前端的数据都依赖于后端数据库返回，更适合用户
