### ISSUE TITLE
[Bug]:  operation record middleware 不能正确处理文件上传下载

### ISSUE THREAD

**Issue by pnck** [flipped-aurora/gin-vue-admin#995]
### gin-vue-admin 版本

2.5（main主线）

### Node 版本

v17.7.0

### Golang 版本

go 1.17.8

### 是否依旧存在

未测试

### bug描述

- 目前的「操作记录」中间件默认请求响应body中都是正常string，而且会全量保存
- 在一些业务中，可能会认为「上传」是相对有风险的操作，想要记录，那这样会保存下大量无意义的二进制数据，而且无法入库（`string()只能处理utf8字节流`，可以存成blob之类的？）
- 观察到这个中间件还留了个2020年的 TODO 在那……

### 修改建议

1.  处理`content-disposition`和`content-type`，忽略上传下载文件的body
2. 限制记录body的最大大小，只记录开头一部分

**Comment by piexlmax** [comment]
下载依然存在问题，响应头获取无简便方法，暂时搁置。

**Comment by songzhibin97** [comment]
可以针对接口加一个白名单去过滤

**Comment by pnck** [comment]
#1037
