### ISSUE TITLE
[Feature]: 自动化生成代码建议参考fastadmin的关联表功能

### ISSUE THREAD

**Issue by Jessppp** [flipped-aurora/gin-vue-admin#998]
### 功能描述以及必要性描述

fastadmin的关联表功能很好用，正常的业务场景中关联表的情况100%会出现的，让gva更强大懒人一些吧
![image](https://user-images.githubusercontent.com/16432902/161119330-a0d29568-c392-4593-b196-653f5e15b1d0.png)

### 建议和方案

1. 增加表关联一对一、一对多功能，可选关联表显示某些字段和查询条件配置
2. 对应生成CRUD页面列表显示和新增修改关联

**Comment by piexlmax** [comment]
会纳入开发计划

**Comment by Jessppp** [comment]
> 会纳入开发计划

期待gva越来越强大！

**Comment by oxeyaa** [comment]
关联表如果能直接支持原生sql就更美丽了..

**Comment by Kevin-Ben** [comment]
已经开发好了吗？

**Comment by jerevive** [comment]
为什么关闭掉了，真的需要这个
